import Mathlib

/-!
# Experimental abstract root-chart terminality

Let a finite centre be generated by `g i`.  In a chart with pivot `k`, assume
that every transformed generator factors as one exceptional element times a
controlled root and that the pivot controlled root is `1`.  Then the same
factorization holds for all `q`-th powers and the transformed full root packet
is the unit ideal.

This theorem contains no coordinate-polynomial assumption.  It isolates the
minimal algebraic chart interface needed for terminality.  A geometric blowup
implementation still has to construct the chart, exceptional factor and
controlled roots, and prove their overlap and saturation laws.
-/

namespace PCRLean
namespace Experimental
namespace AbstractRootChartTerminality

noncomputable section

universe u v w

variable {A : Type u} {B : Type v}
variable [CommRing A] [CommRing B]
variable {ι : Type w} [Fintype ι]

/-- Minimal pivot-chart factorization data for a finite centre generator
family. -/
structure RootChart (generator : ι → A) (pivot : ι) where
  chartMap : A →+* B
  exceptional : B
  controlledRoot : ι → B
  factorization : ∀ i,
    chartMap (generator i) = exceptional * controlledRoot i
  pivot_controlledRoot : controlledRoot pivot = 1

namespace RootChart

variable {generator : ι → A} {pivot : ι}
    (C : RootChart generator pivot)

/-- Exact factorization of every powered centre generator. -/
theorem pow_factorization (i : ι) (q : Nat) :
    C.chartMap ((generator i) ^ q) =
      C.exceptional ^ q * (C.controlledRoot i) ^ q := by
  rw [map_pow, C.factorization i, mul_pow]

/-- Controlled full root ideal in the pivot chart. -/
def transformedRootIdeal (q : Nat) : Ideal B :=
  Ideal.span (Set.range fun i : ι => (C.controlledRoot i) ^ q)

/-- The pivot controlled root contributes the unit. -/
theorem one_mem_transformedRootIdeal (q : Nat) :
    (1 : B) ∈ C.transformedRootIdeal q := by
  apply Ideal.subset_span
  refine ⟨pivot, ?_⟩
  simp [C.pivot_controlledRoot]

/-- Every full controlled root packet is terminal in its pivot chart. -/
theorem transformedRootIdeal_eq_top (q : Nat) :
    C.transformedRootIdeal q = ⊤ := by
  apply top_unique
  intro b hb
  have h1 := C.one_mem_transformedRootIdeal q
  simpa using (C.transformedRootIdeal q).mul_mem_left b h1

/-- Controlled ideals in any two charts are equal once both contain their pivot
root, because both are the unit ideal. -/
theorem transformedRootIdeal_eq
    {pivot' : ι} (D : RootChart generator pivot') (q : Nat) :
    C.transformedRootIdeal q = D.transformedRootIdeal q := by
  rw [C.transformedRootIdeal_eq_top, D.transformedRootIdeal_eq_top]

/-- Controlled root ideal of a selected finite owner support. -/
def transformedOwnerIdeal [DecidableEq ι]
    (support : Finset ι) (q : Nat) : Ideal B :=
  Ideal.span (Set.range fun i : support => (C.controlledRoot i.1) ^ q)

/-- An owner support containing the pivot is terminal in that pivot chart. -/
theorem transformedOwnerIdeal_eq_top_of_mem [DecidableEq ι]
    (support : Finset ι) (q : Nat) (hpivot : pivot ∈ support) :
    C.transformedOwnerIdeal support q = ⊤ := by
  apply top_unique
  intro b hb
  have h1 : (1 : B) ∈ C.transformedOwnerIdeal support q := by
    apply Ideal.subset_span
    refine ⟨⟨pivot, hpivot⟩, ?_⟩
    simp [C.pivot_controlledRoot]
  simpa using (C.transformedOwnerIdeal support q).mul_mem_left b h1

end RootChart

end

end AbstractRootChartTerminality
end Experimental
end PCRLean
