import Mathlib
import PCRLean.Experimental.CoordinateSubspaceOrderHeredity

/-!
# Affine positive-dimensional centre heredity

Keep the passive coordinates fixed and translate only the coordinates normal to
the centre.  The affine regular subspace

`z_i = b_i`

has actual ideal generated by `z_i - b_i`.  Normal translation carries this
ideal exactly to the coordinate-centre ideal `(z_i)`, and carries every ideal
power to the corresponding power.

Consequently the centre-order predicate after normal translation gives actual
marked-power containment along a positive-dimensional affine centre.  Prime-
power Frobenius root compression preserves this condition after scaling the
mark.

This is an affine split-linear chamber.  Arbitrary regular local centres,
nonlinear embeddings, passive Tor safety, boundary SNC and hereditary blowup
transport remain separate.
-/

namespace PCRLean
namespace Experimental
namespace AffineCoordinateSubspaceHeredity

noncomputable section

universe u v w

variable {K : Type u} [Field K]
variable {α : Type v} {ι : Type w}
variable [Fintype ι] [DecidableEq ι]

abbrev P := CoordinateBlowupChart.P (R := K) (α := α) (ι := ι)

open CoordinateSubspaceOrderHeredity

/-- Translate only the normal coordinates by `b`. -/
def normalTranslate (b : ι → K) :
    P (K := K) (α := α) (ι := ι) →ₐ[K]
      P (K := K) (α := α) (ι := ι) :=
  MvPolynomial.aeval fun s =>
    match s with
    | Sum.inl a => MvPolynomial.X (Sum.inl a)
    | Sum.inr i => MvPolynomial.X (Sum.inr i) + MvPolynomial.C (b i)

@[simp] theorem normalTranslate_passive
    (b : ι → K) (a : α) :
    normalTranslate (α := α) b
        (CoordinateBlowupChart.passiveVar
          (R := K) (α := α) (ι := ι) a) =
      CoordinateBlowupChart.passiveVar
        (R := K) (α := α) (ι := ι) a := by
  simp [normalTranslate, CoordinateBlowupChart.passiveVar]

@[simp] theorem normalTranslate_centre
    (b : ι → K) (i : ι) :
    normalTranslate (α := α) b
        (CoordinateBlowupChart.centreVar
          (R := K) (α := α) (ι := ι) i) =
      CoordinateBlowupChart.centreVar
        (R := K) (α := α) (ι := ι) i + MvPolynomial.C (b i) := by
  simp [normalTranslate, CoordinateBlowupChart.centreVar]

/-- Translation by `b` followed by translation by `-b` is the identity. -/
theorem normalTranslate_comp_neg (b : ι → K) :
    (normalTranslate (α := α) b).comp
        (normalTranslate (α := α) (-b)) =
      AlgHom.id K (P (K := K) (α := α) (ι := ι)) := by
  apply MvPolynomial.algHom_ext
  intro s
  cases s <;> simp [normalTranslate]

/-- Translation by `-b` followed by translation by `b` is the identity. -/
theorem normalTranslate_neg_comp (b : ι → K) :
    (normalTranslate (α := α) (-b)).comp
        (normalTranslate (α := α) b) =
      AlgHom.id K (P (K := K) (α := α) (ι := ι)) := by
  apply MvPolynomial.algHom_ext
  intro s
  cases s <;> simp [normalTranslate]

/-- Normal translation as a polynomial algebra automorphism. -/
noncomputable def normalTranslateEquiv (b : ι → K) :
    P (K := K) (α := α) (ι := ι) ≃ₐ[K]
      P (K := K) (α := α) (ι := ι) :=
  AlgEquiv.ofAlgHom
    (normalTranslate (α := α) b)
    (normalTranslate (α := α) (-b))
    (normalTranslate_comp_neg (α := α) b)
    (normalTranslate_neg_comp (α := α) b)

/-- Equation of the affine centre in one normal direction. -/
def affineCentreGenerator (b : ι → K) (i : ι) :
    P (K := K) (α := α) (ι := ι) :=
  CoordinateBlowupChart.centreVar
    (R := K) (α := α) (ι := ι) i - MvPolynomial.C (b i)

/-- Actual coherent ideal of the affine positive-dimensional centre. -/
def affineCentreIdeal (b : ι → K) :
    Ideal (P (K := K) (α := α) (ι := ι)) :=
  Ideal.span (Set.range (affineCentreGenerator (α := α) b))

/-- Each affine centre equation belongs to the actual centre ideal. -/
theorem affineCentreGenerator_mem (b : ι → K) (i : ι) :
    affineCentreGenerator (α := α) b i ∈
      affineCentreIdeal (α := α) b :=
  Ideal.subset_span ⟨i, rfl⟩

/-- Normal translation sends the affine centre ideal exactly to the coordinate
centre ideal. -/
theorem map_affineCentreIdeal_eq_centreIdeal (b : ι → K) :
    Ideal.map (normalTranslate (α := α) b)
        (affineCentreIdeal (α := α) b) =
      CoordinateBlowupChart.centreIdeal
        (R := K) (α := α) (ι := ι) := by
  apply le_antisymm
  · rw [affineCentreIdeal, CoordinateBlowupChart.centreIdeal,
      Ideal.map_le_iff_le_comap, Ideal.span_le]
    rintro x ⟨i, rfl⟩
    rw [Ideal.mem_comap]
    simp [affineCentreGenerator, normalTranslate]
    exact CoordinateSubspaceOrderHeredity.centreVar_mem
      (K := K) (α := α) i
  · rw [CoordinateBlowupChart.centreIdeal, Ideal.span_le]
    rintro x ⟨i, rfl⟩
    have hm := Ideal.mem_map_of_mem (normalTranslate (α := α) b)
      (affineCentreGenerator_mem (α := α) b i)
    simpa [affineCentreGenerator, normalTranslate] using hm

/-- Inverse normal translation sends the coordinate centre ideal to the affine
centre ideal. -/
theorem map_centreIdeal_eq_affineCentreIdeal (b : ι → K) :
    Ideal.map (normalTranslate (α := α) (-b))
        (CoordinateBlowupChart.centreIdeal
          (R := K) (α := α) (ι := ι)) =
      affineCentreIdeal (α := α) b := by
  apply le_antisymm
  · rw [CoordinateBlowupChart.centreIdeal, affineCentreIdeal,
      Ideal.map_le_iff_le_comap, Ideal.span_le]
    rintro x ⟨i, rfl⟩
    rw [Ideal.mem_comap]
    simp [affineCentreGenerator, normalTranslate]
    exact affineCentreGenerator_mem (α := α) b i
  · rw [affineCentreIdeal, Ideal.span_le]
    rintro x ⟨i, rfl⟩
    have hm := Ideal.mem_map_of_mem (normalTranslate (α := α) (-b))
      (CoordinateSubspaceOrderHeredity.centreVar_mem
        (K := K) (α := α) i)
    simpa [affineCentreGenerator, normalTranslate] using hm

/-- Normal translation carries every affine-centre power to the matching
coordinate-centre power. -/
theorem map_affineCentreIdeal_pow_eq_centreIdeal_pow
    (b : ι → K) (mark : Nat) :
    Ideal.map (normalTranslate (α := α) b)
        ((affineCentreIdeal (α := α) b) ^ mark) =
      (CoordinateBlowupChart.centreIdeal
        (R := K) (α := α) (ι := ι)) ^ mark := by
  rw [Ideal.map_pow, map_affineCentreIdeal_eq_centreIdeal]

/-- Inverse translation carries every coordinate-centre power to the matching
affine-centre power. -/
theorem map_centreIdeal_pow_eq_affineCentreIdeal_pow
    (b : ι → K) (mark : Nat) :
    Ideal.map (normalTranslate (α := α) (-b))
        ((CoordinateBlowupChart.centreIdeal
          (R := K) (α := α) (ι := ι)) ^ mark) =
      (affineCentreIdeal (α := α) b) ^ mark := by
  rw [Ideal.map_pow, map_centreIdeal_eq_affineCentreIdeal]

/-- Exact membership transport between affine and coordinate centre powers. -/
theorem mem_affineCentreIdeal_pow_iff
    (b : ι → K) (f : P (K := K) (α := α) (ι := ι))
    (mark : Nat) :
    f ∈ (affineCentreIdeal (α := α) b) ^ mark ↔
      normalTranslate (α := α) b f ∈
        (CoordinateBlowupChart.centreIdeal
          (R := K) (α := α) (ι := ι)) ^ mark := by
  constructor
  · intro hf
    have hm := Ideal.mem_map_of_mem (normalTranslate (α := α) b) hf
    rw [map_affineCentreIdeal_pow_eq_centreIdeal_pow] at hm
    exact hm
  · intro hf
    have hm := Ideal.mem_map_of_mem (normalTranslate (α := α) (-b)) hf
    rw [map_centreIdeal_pow_eq_affineCentreIdeal_pow] at hm
    have hcomp := congrArg
      (fun H : P (K := K) (α := α) (ι := ι) →ₐ[K]
          P (K := K) (α := α) (ι := ι) => H f)
      (normalTranslate_neg_comp (α := α) b)
    simpa [AlgHom.comp_apply] using hcomp ▸ hm

/-- Normal-order condition along the affine centre. -/
def AffineCentreOrderGE
    (b : ι → K) (f : P (K := K) (α := α) (ι := ι))
    (mark : Nat) : Prop :=
  CoordinateSubspaceOrderHeredity.CentreOrderGE
    (normalTranslate (α := α) b f) mark

/-- Affine centre order gives actual marked-power containment. -/
theorem mem_affineCentreIdeal_pow_of_orderGE
    (b : ι → K) (f : P (K := K) (α := α) (ι := ι))
    (mark : Nat)
    (horder : AffineCentreOrderGE (α := α) b f mark) :
    f ∈ (affineCentreIdeal (α := α) b) ^ mark := by
  apply (mem_affineCentreIdeal_pow_iff b f mark).mpr
  exact CoordinateSubspaceOrderHeredity.mem_centreIdeal_pow_of_centreOrderGE
    (normalTranslate (α := α) b f) mark horder

/-- Frobenius mark compression preserves affine centre order exactly. -/
theorem affineCentreOrderGE_power_iff
    (p : Nat) [Fact p.Prime] [CharP K p]
    (e mark : Nat) (b : ι → K)
    (g : P (K := K) (α := α) (ι := ι)) :
    AffineCentreOrderGE (α := α) b (g ^ (p ^ e))
        ((p ^ e) * mark) ↔
      AffineCentreOrderGE (α := α) b g mark := by
  unfold AffineCentreOrderGE
  rw [map_pow]
  exact CoordinateSubspaceOrderHeredity.centreOrderGE_power_iff
    p e mark (normalTranslate (α := α) b g)

/-- A root affine-centre order certificate gives marked permissibility for the
prime-power equation along the same positive-dimensional affine centre. -/
theorem frobeniusPower_mem_affineCentreIdeal_pow
    (p : Nat) [Fact p.Prime] [CharP K p]
    (e mark : Nat) (b : ι → K)
    (g : P (K := K) (α := α) (ι := ι))
    (hrootOrder : AffineCentreOrderGE (α := α) b g mark) :
    g ^ (p ^ e) ∈
      (affineCentreIdeal (α := α) b) ^ ((p ^ e) * mark) := by
  apply mem_affineCentreIdeal_pow_of_orderGE
  exact (affineCentreOrderGE_power_iff p e mark b g).mpr hrootOrder

end

end AffineCoordinateSubspaceHeredity
end Experimental
end PCRLean
