import Mathlib
import Mathlib.LinearAlgebra.SymmetricAlgebra.Basic

/-!
# Intrinsic affine conormal ideals

Let `D` be a source module, let

`pair : D → T∨`, `value : D → R`

be linear, and regard an element `d : D` as the affine conormal equation

`ι(pair d) - value d = 0`

inside `Sym_R(T∨)`.

The assignment

`d ↦ ι(pair d) - algebraMap(value d)`

is itself linear.  Hence an ideal generated by finitely many affine equations
depends only on the submodule spanned by their source elements, not on the
chosen finite generating packet.

This is the intrinsic ideal-level counterpart of Noetherian affine orbit
packet canonicity.  It combines the covector row and right-hand side before any
coordinate choice and therefore avoids a presentation-dependent graph tuple.
-/

namespace PCRLean
namespace Experimental
namespace AffineConormalIdeal

noncomputable section

universe u v w x

variable {R : Type u} [CommRing R]
variable {D : Type v} [AddCommGroup D] [Module R D]
variable {T : Type w} [AddCommGroup T] [Module R T]
variable {κ : Type x} [Fintype κ]

abbrev Cotangent := Module.Dual R T
abbrev Sym := SymmetricAlgebra R (Cotangent (R := R) (T := T))

/-- Linear affine-equation map into the cotangent symmetric algebra. -/
def equationMap
    (pair : D →ₗ[R] Cotangent (R := R) (T := T))
    (value : D →ₗ[R] R) :
    D →ₗ[R] Sym (R := R) (T := T) :=
  (SymmetricAlgebra.ι R (Cotangent (R := R) (T := T))).comp pair -
    (Algebra.linearMap R (Sym (R := R) (T := T))).comp value

@[simp] theorem equationMap_apply
    (pair : D →ₗ[R] Cotangent (R := R) (T := T))
    (value : D →ₗ[R] R) (d : D) :
    equationMap pair value d =
      SymmetricAlgebra.ι R (Cotangent (R := R) (T := T)) (pair d) -
        algebraMap R (Sym (R := R) (T := T)) (value d) :=
  rfl

/-- Actual intrinsic ideal generated by a finite source packet. -/
def packetIdeal
    (pair : D →ₗ[R] Cotangent (R := R) (T := T))
    (value : D →ₗ[R] R)
    (s : Finset D) : Ideal (Sym (R := R) (T := T)) :=
  Ideal.span (Set.range fun d : s => equationMap pair value d.1)

/-- Every named finite packet equation belongs to the intrinsic ideal. -/
theorem generator_mem_packetIdeal
    (pair : D →ₗ[R] Cotangent (R := R) (T := T))
    (value : D →ₗ[R] R)
    (s : Finset D) (d : s) :
    equationMap pair value d.1 ∈ packetIdeal pair value s :=
  Ideal.subset_span ⟨d, rfl⟩

/-- Every source element in the linear span of the packet has its affine
equation in the same actual ideal. -/
theorem equationMap_mem_of_mem_span
    (pair : D →ₗ[R] Cotangent (R := R) (T := T))
    (value : D →ₗ[R] R)
    (s : Finset D)
    {d : D}
    (hd : d ∈ Submodule.span R (s : Set D)) :
    equationMap pair value d ∈ packetIdeal pair value s := by
  induction hd using Submodule.span_induction with
  | mem d hd =>
      exact generator_mem_packetIdeal pair value s ⟨d, hd⟩
  | zero =>
      simp [packetIdeal]
  | add d e hd he ihd ihe =>
      rw [map_add]
      exact (packetIdeal pair value s).add_mem ihd ihe
  | smul a d hd ih =>
      rw [map_smul]
      change algebraMap R (Sym (R := R) (T := T)) a *
          equationMap pair value d ∈ packetIdeal pair value s
      exact (packetIdeal pair value s).mul_mem_left _ ih

/-- Equal source packet spans produce exactly the same intrinsic affine ideal. -/
theorem packetIdeal_eq_of_span_eq
    {λ : Type*} [Fintype λ]
    (pair : D →ₗ[R] Cotangent (R := R) (T := T))
    (value : D →ₗ[R] R)
    (s : Finset D) (t : Finset D)
    (hspan : Submodule.span R (s : Set D) =
      Submodule.span R (t : Set D)) :
    packetIdeal pair value s = packetIdeal pair value t := by
  apply le_antisymm
  · rw [packetIdeal, Ideal.span_le]
    rintro x ⟨d, rfl⟩
    apply equationMap_mem_of_mem_span pair value t
    rw [← hspan]
    exact Submodule.subset_span d.2
  · rw [packetIdeal, Ideal.span_le]
    rintro x ⟨d, rfl⟩
    apply equationMap_mem_of_mem_span pair value s
    rw [hspan]
    exact Submodule.subset_span d.2

/-- Equivalent formulation using arbitrary finite indexed source families. -/
def indexedIdeal
    (pair : D →ₗ[R] Cotangent (R := R) (T := T))
    (value : D →ₗ[R] R)
    (source : κ → D) : Ideal (Sym (R := R) (T := T)) :=
  Ideal.span (Set.range fun i : κ => equationMap pair value (source i))

/-- An indexed affine ideal contains every equation whose source lies in the
span of the indexed family. -/
theorem equationMap_mem_indexedIdeal_of_mem_span
    (pair : D →ₗ[R] Cotangent (R := R) (T := T))
    (value : D →ₗ[R] R)
    (source : κ → D)
    {d : D}
    (hd : d ∈ Submodule.span R (Set.range source)) :
    equationMap pair value d ∈ indexedIdeal pair value source := by
  induction hd using Submodule.span_induction with
  | mem d hd =>
      rcases hd with ⟨i, rfl⟩
      exact Ideal.subset_span ⟨i, rfl⟩
  | zero => simp [indexedIdeal]
  | add d e hd he ihd ihe =>
      rw [map_add]
      exact (indexedIdeal pair value source).add_mem ihd ihe
  | smul a d hd ih =>
      rw [map_smul]
      change algebraMap R (Sym (R := R) (T := T)) a *
          equationMap pair value d ∈ indexedIdeal pair value source
      exact (indexedIdeal pair value source).mul_mem_left _ ih

end

end AffineConormalIdeal
end Experimental
end PCRLean
