import Mathlib
import PCRLean.Experimental.MaximalMinorEquationIdeal
import PCRLean.Experimental.PolynomialGraphCentreHeredity

/-!
# Relative affine-packet effectivity and graph-hybrid centres

Let `M Z = b` be a finite affine packet over `R`.  For a proposed graph tuple
`h`, write the residual rows as

`ρ_r = (M h)_r - b_r`.

If every `ρ_r` lies in a coefficient ideal `J ⊂ R`, then every affine packet
equation belongs to the actual hybrid ideal

`(Z_i-h_i) + J R[Z]`.

Consequently the ideal generated by the `q`-th powers of the packet rows lies
in the `q`-th power of the hybrid ideal.  Exact determinantal effectivity is the
special case `J=0`; a nonzero cokernel order ideal supplies the canonical
coefficient defect component.
-/

namespace PCRLean
namespace Experimental
namespace AffinePacketHybridEffectivity

noncomputable section

universe u v w

variable {R : Type u} [CommRing R]
variable {κ : Type v} [Fintype κ]
variable {ι : Type w} [Fintype ι] [DecidableEq ι]

open MaximalMinorEquationIdeal
open PolynomialGraphCentreHeredity

abbrev P := MvPolynomial ι R

/-- Extension of a coefficient ideal to the normal polynomial ring. -/
def extendedIdeal (J : Ideal R) : Ideal (P (R := R) (ι := ι)) :=
  Ideal.map MvPolynomial.C J

/-- Hybrid of a graph centre and a coefficient defect component. -/
def hybridIdeal (J : Ideal R) (h : ι → R) :
    Ideal (P (R := R) (ι := ι)) :=
  graphIdeal h ⊔ extendedIdeal J

/-- One equation is a graph-linear combination plus its coefficient residual. -/
theorem equation_eq_graphCombination_add_residual
    (M : Matrix κ ι R) (b : κ → R) (h : ι → R) (r : κ) :
    equation M b r =
      (∑ j : ι, MvPolynomial.C (M r j) * graphGenerator h j) +
        MvPolynomial.C ((M.mulVec h) r - b r) := by
  simp [MaximalMinorEquationIdeal.equation,
    graphGenerator, Matrix.mulVec, dotProduct]
  ring

/-- Relative solvability modulo `J` puts every equation in the hybrid ideal. -/
theorem equation_mem_hybridIdeal
    (M : Matrix κ ι R) (b : κ → R) (h : ι → R)
    (J : Ideal R)
    (Hres : ∀ r : κ, (M.mulVec h) r - b r ∈ J)
    (r : κ) :
    equation M b r ∈ hybridIdeal J h := by
  rw [equation_eq_graphCombination_add_residual]
  apply (hybridIdeal J h).add_mem
  · apply (hybridIdeal J h).sum_mem
    intro j hj
    exact (show graphIdeal h ≤ hybridIdeal J h from le_sup_left)
      ((graphIdeal h).mul_mem_left _ (graphGenerator_mem h j))
  · have hmap :
        MvPolynomial.C ((M.mulVec h) r - b r) ∈ extendedIdeal J :=
      Ideal.mem_map_of_mem MvPolynomial.C (Hres r)
    exact (show extendedIdeal J ≤ hybridIdeal J h from le_sup_right) hmap

/-- The complete original affine packet ideal is contained in the hybrid
centre. -/
theorem equationIdeal_le_hybridIdeal
    (M : Matrix κ ι R) (b : κ → R) (h : ι → R)
    (J : Ideal R)
    (Hres : ∀ r : κ, (M.mulVec h) r - b r ∈ J) :
    equationIdeal M b ≤ hybridIdeal J h := by
  rw [equationIdeal, ActualIdealGluing.generatedIdeal, Ideal.span_le]
  rintro x ⟨r, rfl⟩
  exact equation_mem_hybridIdeal M b h J Hres r

/-- Source ideal generated by `q`-th powers of all affine packet rows. -/
def poweredEquationIdeal
    (M : Matrix κ ι R) (b : κ → R) (q : Nat) :
    Ideal (P (R := R) (ι := ι)) :=
  Ideal.span (Set.range fun r : κ => (equation M b r) ^ q)

/-- Relative graph effectivity gives exact marked-power containment at every
power. -/
theorem poweredEquationIdeal_le_hybridIdeal_pow
    (M : Matrix κ ι R) (b : κ → R) (h : ι → R)
    (J : Ideal R)
    (Hres : ∀ r : κ, (M.mulVec h) r - b r ∈ J)
    (q : Nat) :
    poweredEquationIdeal M b q ≤ (hybridIdeal J h) ^ q := by
  rw [poweredEquationIdeal, Ideal.span_le]
  rintro x ⟨r, rfl⟩
  exact Ideal.pow_mem_pow
    (equation_mem_hybridIdeal M b h J Hres r) q

/-- If the coefficient defect ideal is zero and the tuple is an exact solution,
the hybrid ideal reduces to the pure graph centre. -/
theorem hybridIdeal_bot
    (h : ι → R) : hybridIdeal (⊥ : Ideal R) h = graphIdeal h := by
  simp [hybridIdeal, extendedIdeal]

end

end AffinePacketHybridEffectivity
end Experimental
end PCRLean
