import Mathlib
import Mathlib.LinearAlgebra.SymmetricAlgebra.Basic
import PCRLean.Experimental.AffineConormalIdeal
import PCRLean.Experimental.ConormalAffinePacketCoordinates
import PCRLean.Experimental.DualPacketAffineLinearRealization
import PCRLean.Experimental.MaximalMinorEquationIdeal

/-!
# Coordinate realization of intrinsic affine conormal ideals

Let

`pair : D → T∨`, `value : D → K`

be linear and let `source : κ → D` be a finite source family.  The intrinsic
actual ideal in `Sym_K(T∨)` is generated by

`ι(pair(source r)) - value(source r)`.

A finite linear frame `E : T ≃ K^σ` induces:

1. a linear equivalence `T∨ ≃ (K^σ)∨`;
2. an algebra equivalence
   `Sym_K(T∨) ≃ K[X_σ]`; and
3. the coordinate rectangular packet matrix
   `M_{ri} = pair(source r)(E⁻¹ e_i)`.

This file proves that the algebra equivalence sends the intrinsic affine ideal
*exactly* to the ideal generated by all coordinate equations

`Σ_i M_{ri} X_i - value(source r)`.

Combining this with the maximal-minor theorem shows that, under the two finite
determinantal conditions, the intrinsic conormal ideal is the coordinate-free
form of the canonical polynomial graph centre.
-/

namespace PCRLean
namespace Experimental
namespace AffineConormalIdealCoordinates

noncomputable section

universe u v w x y

variable {K : Type u} [Field K]
variable {D : Type v} [AddCommGroup D] [Module K D]
variable {T : Type w} [AddCommGroup T] [Module K T]
variable {κ : Type x} [Fintype κ]
variable {σ : Type y} [Fintype σ] [DecidableEq σ] [Nonempty σ]

abbrev Coord := σ → K
abbrev CotangentT := Module.Dual K T
abbrev CotangentCoord := Module.Dual K (Coord (K := K) (σ := σ))
abbrev SymT := SymmetricAlgebra K (CotangentT (K := K) (T := T))
abbrev SymCoord := SymmetricAlgebra K (CotangentCoord (K := K) (σ := σ))

variable (E : T ≃ₗ[K] Coord (K := K) (σ := σ))

/-- Dual coordinate equivalence. -/
def dualCoordinateEquiv :
    CotangentT (K := K) (T := T) ≃ₗ[K]
      CotangentCoord (K := K) (σ := σ) where
  toFun f := f.comp E.symm.toLinearMap
  invFun g := g.comp E.toLinearMap
  left_inv := by
    intro f
    ext t
    simp
  right_inv := by
    intro g
    ext z
    simp
  map_add' := by
    intro f g
    ext z
    rfl
  map_smul' := by
    intro a f
    ext z
    rfl

/-- Symmetric-algebra map induced by the dual coordinate equivalence. -/
def symForward :
    SymT (K := K) (T := T) →ₐ[K]
      SymCoord (K := K) (σ := σ) :=
  SymmetricAlgebra.lift
    ((SymmetricAlgebra.ι K
      (CotangentCoord (K := K) (σ := σ))).comp
      (dualCoordinateEquiv E).toLinearMap)

/-- Inverse symmetric-algebra map. -/
def symBackward :
    SymCoord (K := K) (σ := σ) →ₐ[K]
      SymT (K := K) (T := T) :=
  SymmetricAlgebra.lift
    ((SymmetricAlgebra.ι K
      (CotangentT (K := K) (T := T))).comp
      (dualCoordinateEquiv E).symm.toLinearMap)

@[simp] theorem symForward_ι
    (f : CotangentT (K := K) (T := T)) :
    symForward E
        (SymmetricAlgebra.ι K
          (CotangentT (K := K) (T := T)) f) =
      SymmetricAlgebra.ι K
        (CotangentCoord (K := K) (σ := σ))
        (dualCoordinateEquiv E f) := by
  simp [symForward]

@[simp] theorem symBackward_ι
    (g : CotangentCoord (K := K) (σ := σ)) :
    symBackward E
        (SymmetricAlgebra.ι K
          (CotangentCoord (K := K) (σ := σ)) g) =
      SymmetricAlgebra.ι K
        (CotangentT (K := K) (T := T))
        ((dualCoordinateEquiv E).symm g) := by
  simp [symBackward]

/-- The two symmetric-algebra substitutions are inverse. -/
theorem symBackward_comp_symForward :
    (symBackward E).comp (symForward E) =
      AlgHom.id K (SymT (K := K) (T := T)) := by
  apply SymmetricAlgebra.algHom_ext
  ext f
  simp

/-- Inverse identity in the other direction. -/
theorem symForward_comp_symBackward :
    (symForward E).comp (symBackward E) =
      AlgHom.id K (SymCoord (K := K) (σ := σ)) := by
  apply SymmetricAlgebra.algHom_ext
  ext g
  simp

/-- Symmetric-algebra equivalence induced by the frame. -/
noncomputable def symmetricEquiv :
    SymT (K := K) (T := T) ≃ₐ[K]
      SymCoord (K := K) (σ := σ) where
  toAlgHom := symForward E
  invFun := symBackward E
  left_inv := by
    intro x
    have h := congrArg
      (fun F : SymT (K := K) (T := T) →ₐ[K]
        SymT (K := K) (T := T) => F x)
      (symBackward_comp_symForward E)
    simpa using h
  right_inv := by
    intro x
    have h := congrArg
      (fun F : SymCoord (K := K) (σ := σ) →ₐ[K]
        SymCoord (K := K) (σ := σ) => F x)
      (symForward_comp_symBackward E)
    simpa using h

/-- Full coordinate algebra equivalence to the affine polynomial ring. -/
noncomputable def coordinateAlgEquiv :
    SymT (K := K) (T := T) ≃ₐ[K]
      MvPolynomial σ K :=
  (symmetricEquiv E).trans
    (DualPacketAffineLinearRealization.algebraEquiv
      (K := K) (σ := σ))

/-- Finite affine packet obtained from one indexed source family. -/
def coordinatePacket
    (pair : D →ₗ[K] CotangentT (K := K) (T := T))
    (value : D →ₗ[K] K)
    (source : κ → D) :
    ConormalAffinePacketCoordinates.Packet
      (K := K) (V := T) (κ := κ) where
  row := fun r => pair (source r)
  rhs := fun r => value (source r)

/-- The coordinate algebra equivalence sends a cotangent generator to its
actual coordinate linear polynomial. -/
theorem coordinateAlgEquiv_ι
    (f : CotangentT (K := K) (T := T)) :
    coordinateAlgEquiv E
        (SymmetricAlgebra.ι K
          (CotangentT (K := K) (T := T)) f) =
      FunctionalPacketIdeal.functionalPolynomial
        (dualCoordinateEquiv E f) := by
  simp [coordinateAlgEquiv]

/-- One intrinsic affine conormal equation maps to the corresponding original
coordinate packet equation. -/
theorem coordinateAlgEquiv_equationMap
    (pair : D →ₗ[K] CotangentT (K := K) (T := T))
    (value : D →ₗ[K] K)
    (source : κ → D) (r : κ) :
    coordinateAlgEquiv E
        (AffineConormalIdeal.equationMap pair value (source r)) =
      MaximalMinorEquationIdeal.equation
        ((coordinatePacket pair value source).matrix E)
        (coordinatePacket pair value source).rhs r := by
  rw [AffineConormalIdeal.equationMap_apply]
  simp only [map_sub, map_algebraMap, coordinateAlgEquiv_ι]
  rw [MaximalMinorEquationIdeal.equation]
  congr 1
  rw [FunctionalPacketIdeal.functionalPolynomial,
    LinearPacketIdeal.linearPolynomial]
  rfl

/-- Main ideal-level semantic alignment theorem. -/
theorem map_intrinsicIdeal_eq_coordinateEquationIdeal
    (pair : D →ₗ[K] CotangentT (K := K) (T := T))
    (value : D →ₗ[K] K)
    (source : κ → D) :
    Ideal.map (coordinateAlgEquiv E)
        (AffineConormalIdeal.indexedIdeal pair value source) =
      MaximalMinorEquationIdeal.equationIdeal
        ((coordinatePacket pair value source).matrix E)
        (coordinatePacket pair value source).rhs := by
  apply le_antisymm
  · rw [Ideal.map_le_iff_le_comap,
      AffineConormalIdeal.indexedIdeal, Ideal.span_le]
    rintro x ⟨r, rfl⟩
    rw [Ideal.mem_comap, coordinateAlgEquiv_equationMap]
    exact ActualIdealGluing.generator_mem
      (MaximalMinorEquationIdeal.equation
        ((coordinatePacket pair value source).matrix E)
        (coordinatePacket pair value source).rhs) r
  · rw [MaximalMinorEquationIdeal.equationIdeal,
      ActualIdealGluing.generatedIdeal, Ideal.span_le]
    rintro x ⟨r, rfl⟩
    rw [← coordinateAlgEquiv_equationMap E pair value source r]
    exact Ideal.mem_map_of_mem _
      (Ideal.subset_span ⟨r, rfl⟩)

variable [IsNoetherianRing K] [IsRegularRing K]

/-- Under the two finite determinantal conditions, the intrinsic affine
conormal ideal maps exactly to the canonical graph centre. -/
theorem map_intrinsicIdeal_eq_graphIdeal
    (pair : D →ₗ[K] CotangentT (K := K) (T := T))
    (value : D →ₗ[K] K)
    (source : κ → D)
    (Hrank : MaximalMinorAtlas.FullRankCover
      ((coordinatePacket pair value source).matrix E))
    (Haug : MaximalMinorAugmentedPacket.AugmentedRankCondition
      ((coordinatePacket pair value source).matrix E)
      (coordinatePacket pair value source).rhs) :
    Ideal.map (coordinateAlgEquiv E)
        (AffineConormalIdeal.indexedIdeal pair value source) =
      PolynomialGraphCentreHeredity.graphIdeal
        (Haug.globalGraph Hrank) := by
  rw [map_intrinsicIdeal_eq_coordinateEquationIdeal E pair value source]
  exact MaximalMinorEquationIdeal.equationIdeal_eq_graphIdeal
    ((coordinatePacket pair value source).matrix E)
    (coordinatePacket pair value source).rhs
    (Haug.globalGraph Hrank)
    (Haug.globalGraph_solves Hrank) Hrank

end

end AffineConormalIdealCoordinates
end Experimental
end PCRLean
