import PCRLean.Experimental.AffineCoordinateSubspaceHeredity

#print axioms PCRLean.Experimental.AffineCoordinateSubspaceHeredity.normalTranslate_comp_neg
#print axioms PCRLean.Experimental.AffineCoordinateSubspaceHeredity.normalTranslate_neg_comp
#print axioms PCRLean.Experimental.AffineCoordinateSubspaceHeredity.map_affineCentreIdeal_eq_centreIdeal
#print axioms PCRLean.Experimental.AffineCoordinateSubspaceHeredity.map_centreIdeal_eq_affineCentreIdeal
#print axioms PCRLean.Experimental.AffineCoordinateSubspaceHeredity.mem_affineCentreIdeal_pow_iff
#print axioms PCRLean.Experimental.AffineCoordinateSubspaceHeredity.mem_affineCentreIdeal_pow_of_orderGE
#print axioms PCRLean.Experimental.AffineCoordinateSubspaceHeredity.affineCentreOrderGE_power_iff
#print axioms PCRLean.Experimental.AffineCoordinateSubspaceHeredity.frobeniusPower_mem_affineCentreIdeal_pow
