import PCRLean.Experimental.AffineConormalIdealCoordinates

#print axioms PCRLean.Experimental.AffineConormalIdealCoordinates.dualCoordinateEquiv
#print axioms PCRLean.Experimental.AffineConormalIdealCoordinates.symBackward_comp_symForward
#print axioms PCRLean.Experimental.AffineConormalIdealCoordinates.symForward_comp_symBackward
#print axioms PCRLean.Experimental.AffineConormalIdealCoordinates.coordinateAlgEquiv_ι
#print axioms PCRLean.Experimental.AffineConormalIdealCoordinates.coordinateAlgEquiv_equationMap
#print axioms PCRLean.Experimental.AffineConormalIdealCoordinates.map_intrinsicIdeal_eq_coordinateEquationIdeal
#print axioms PCRLean.Experimental.AffineConormalIdealCoordinates.map_intrinsicIdeal_eq_graphIdeal
