import PCRLean.Experimental.AffineLinearFrameExactFrobeniusHeredity

#print axioms PCRLean.Experimental.AffineLinearFrameExactFrobeniusHeredity.frobeniusPower_mem_affineCentreIdeal_pow_iff
#print axioms PCRLean.Experimental.AffineLinearFrameExactFrobeniusHeredity.affineCentreIdeal_ne_top
#print axioms PCRLean.Experimental.AffineLinearFrameExactFrobeniusHeredity.frobeniusPower_mem_frameCentreIdeal_pow_iff
#print axioms PCRLean.Experimental.AffineLinearFrameExactFrobeniusHeredity.map_affineCentreIdeal_eq_affineFrameCentreIdeal
#print axioms PCRLean.Experimental.AffineLinearFrameExactFrobeniusHeredity.map_affineFrameCentreIdeal_eq_affineCentreIdeal
#print axioms PCRLean.Experimental.AffineLinearFrameExactFrobeniusHeredity.mem_affineFrameCentreIdeal_pow_iff
#print axioms PCRLean.Experimental.AffineLinearFrameExactFrobeniusHeredity.affineFrameCentreIdeal_fg
#print axioms PCRLean.Experimental.AffineLinearFrameExactFrobeniusHeredity.affineFrameCentreIdeal_ne_top
#print axioms PCRLean.Experimental.AffineLinearFrameExactFrobeniusHeredity.frobeniusPower_mem_affineFrameCentreIdeal_pow_iff
