import PCRLean.Experimental.ArbitraryFiniteLinearPacketRegularCentre

#print axioms PCRLean.Experimental.ArbitraryFiniteLinearPacketRegularCentre.rangeProjection_surjective
#print axioms PCRLean.Experimental.ArbitraryFiniteLinearPacketRegularCentre.rangeProjection_ker_eq
#print axioms PCRLean.Experimental.ArbitraryFiniteLinearPacketRegularCentre.centreIdeal_eq_rangeCentreIdeal
#print axioms PCRLean.Experimental.ArbitraryFiniteLinearPacketRegularCentre.quotientEquiv
#print axioms PCRLean.Experimental.ArbitraryFiniteLinearPacketRegularCentre.centreIdeal_ne_top
#print axioms PCRLean.Experimental.ArbitraryFiniteLinearPacketRegularCentre.centreIdeal_fg
#print axioms PCRLean.Experimental.ArbitraryFiniteLinearPacketRegularCentre.quotient_isRegularRing
#print axioms PCRLean.Experimental.ArbitraryFiniteLinearPacketRegularCentre.certificate
