import Mathlib
import Mathlib.LinearAlgebra.SymmetricAlgebra.Basis
import Mathlib.RingTheory.RegularLocalRing.Polynomial
import PCRLean.BiorthogonalSplitFrame
import PCRLean.Experimental.SurjectiveFreeRegularCentre
import PCRLean.Experimental.FiniteFreeSymmetricAlgebraRegular

/-!
# Experimental regular centre from a biorthogonal packet

A finite packet of linear functionals with biorthogonal transverse vectors is
the local algebraic certificate supplied by an invertible Jacobian minor. The
explicit transverse section makes packet evaluation surjective. Therefore the
intrinsic ideal generated by the common linear kernel has an exact symmetric-
algebra quotient.

The construction works over every nontrivial regular commutative ring, not only
over a field. Because the finite coefficient space `ι → K` has its standard
basis, its symmetric algebra is a finite-variable polynomial ring over `K` and
is regular. If the source direction module is finite free, its symmetric
algebra is also Noetherian. Hence a finite biorthogonal packet over a regular
chart supplies an actual proper finite-type regular centre.

This is the direct Fitting-chart-to-centre bridge. It does not prove that every
Frobenius/Fitting core has a nonempty constant-rank chart, that the local ideals
glue after localization, or that their transforms reenter hereditarily after
blowup.
-/

namespace PCRLean
namespace Experimental
namespace BiorthogonalRegularCentre

noncomputable section

universe u v w

variable {K : Type u} [CommRing K] [Nontrivial K] [IsRegularRing K]
variable {V : Type v} [AddCommGroup V] [Module K V]
variable {ι : Type w} [Fintype ι] [DecidableEq ι]

open BiorthogonalSplitFrame
open SurjectiveLinearMapSymmetricQuotient
open SurjectiveFreeRegularCentre

variable (F : BiorthogonalSplitFrame.Frame
  (K := K) (V := V) (ι := ι))

/-- Packet evaluation is surjective, with the biorthogonal transverse section
as an explicit preimage operation. -/
theorem eval_surjective : Function.Surjective F.eval := by
  intro a
  exact ⟨F.section a, F.eval_section a⟩

/-- Membership in the evaluation kernel is simultaneous annihilation by all
packet rows. -/
theorem mem_eval_ker_iff (x : V) :
    x ∈ LinearMap.ker F.eval ↔ ∀ i : ι, F.packet i x = 0 := by
  constructor
  · intro hx i
    have hzero : F.eval x = 0 := LinearMap.mem_ker.mp hx
    have hi := congrFun hzero i
    simpa [BiorthogonalSplitFrame.Frame.eval] using hi
  · intro h
    apply LinearMap.mem_ker.mpr
    funext i
    exact h i

/-- Intrinsic actual ideal attached to the common kernel of the packet. -/
def centreIdeal : Ideal (SymmetricAlgebra K V) :=
  SurjectiveLinearMapSymmetricQuotient.kernelIdeal F.eval

/-- The ideal is generated by degree-one vectors annihilated by every packet
functional. -/
theorem centreIdeal_eq_span_commonKernel :
    F.centreIdeal =
      Ideal.span (Set.range fun x : LinearMap.ker F.eval =>
        SymmetricAlgebra.ι K V x.1) := by
  rfl

/-- Exact quotient theorem for the intrinsic packet centre. -/
noncomputable def quotientEquiv :
    (SymmetricAlgebra K V ⧸ F.centreIdeal) ≃+*
      SymmetricAlgebra K (ι → K) :=
  SurjectiveLinearMapSymmetricQuotient.quotientEquiv
    F.eval F.eval_surjective

/-- The packet centre is proper. -/
theorem centreIdeal_ne_top : F.centreIdeal ≠ ⊤ := by
  exact SurjectiveLinearMapSymmetricQuotient.kernelIdeal_ne_top
    F.eval F.eval_surjective

/-- The packet centre is finite type whenever the ambient symmetric algebra is
Noetherian. -/
theorem centreIdeal_fg
    [IsNoetherianRing (SymmetricAlgebra K V)] :
    F.centreIdeal.FG := by
  exact IsNoetherian.noetherian _

/-- The symmetric algebra of the finite coefficient space is regular, with no
extra target hypothesis. -/
theorem coefficientSymmetricAlgebra_isRegularRing :
    IsRegularRing (SymmetricAlgebra K (ι → K)) := by
  let e : MvPolynomial ι K ≃+* SymmetricAlgebra K (ι → K) :=
    (SymmetricAlgebra.equivMvPolynomial (Pi.basisFun K ι)).symm.toRingEquiv
  exact IsRegularRing.of_ringEquiv e

/-- Regularity of the actual centre quotient follows automatically from the
finite packet and regularity of the base ring. -/
theorem quotient_isRegularRing :
    IsRegularRing (SymmetricAlgebra K V ⧸ F.centreIdeal) := by
  letI : IsRegularRing (SymmetricAlgebra K (ι → K)) :=
    coefficientSymmetricAlgebra_isRegularRing (K := K) (ι := ι)
  exact IsRegularRing.of_ringEquiv F.quotientEquiv.symm

/-- Assemble the actual proper finite-type regular centre directly from the
biorthogonal packet. -/
noncomputable def certificate
    [IsNoetherianRing (SymmetricAlgebra K V)] :
    SurjectiveFreeRegularCentre.Certificate F.eval := by
  letI : IsRegularRing (SymmetricAlgebra K (ι → K)) :=
    coefficientSymmetricAlgebra_isRegularRing (K := K) (ι := ι)
  exact SurjectiveFreeRegularCentre.certificate F.eval F.eval_surjective

/-- If the source module is finite free, Noetherianity of its symmetric algebra
is automatic over the regular base ring. -/
noncomputable def finiteFreeCertificate
    [Module.Free K V] [Module.Finite K V] :
    SurjectiveFreeRegularCentre.Certificate F.eval := by
  letI : IsNoetherianRing (SymmetricAlgebra K V) :=
    FiniteFreeSymmetricAlgebraRegular.isNoetherianRing
      (K := K) (M := V)
  exact F.certificate

end

end BiorthogonalRegularCentre
end Experimental
end PCRLean
