import Mathlib
import PCRLean.Experimental.MarkedClosureArrangement

/-!
# Canonical active-legal completion of a finite minimizer family

A cardinal-minimal acceptable family need not be unique.  Instead of choosing
one minimizer, retain the finite family of all minimizers and close upward under
adding correction components.  Scheme-theoretically, adding components adds
ideal generators and therefore passes to a smaller intersection stratum.

The upper completion is deliberately larger than the exact semilattice of
unions of minimizers.  Its advantage is that it is canonical, finite, closed
under unions, and every member is automatically active-owner acceptable as
soon as every minimizer is acceptable.  Later geometric gates may select a
smaller regular building set inside this finite envelope.
-/

namespace PCRLean
namespace Experimental
namespace CanonicalIntersectionCompletion

noncomputable section

universe u v w

open MarkedClosureArrangement
open OrderIdealMarkedClosureCompiler

variable {R : Type u} [CommRing R]
variable {Component : Type v} [Fintype Component] [DecidableEq Component]
variable {Owner : Type w} [Fintype Owner]

/-- Canonical finite upper envelope generated by a family of selected
correction sets. -/
def upperCompletion (minimizers : Finset (Finset Component)) :
    Finset (Finset Component) :=
  Finset.univ.filter fun selected =>
    ∃ minimal ∈ minimizers, minimal ⊆ selected

@[simp] theorem mem_upperCompletion_iff
    {minimizers : Finset (Finset Component)}
    {selected : Finset Component} :
    selected ∈ upperCompletion minimizers ↔
      ∃ minimal ∈ minimizers, minimal ⊆ selected := by
  simp [upperCompletion]

/-- Every generating minimizer belongs to the upper completion. -/
theorem minimizer_mem_upperCompletion
    {minimizers : Finset (Finset Component)}
    {minimal : Finset Component}
    (hminimal : minimal ∈ minimizers) :
    minimal ∈ upperCompletion minimizers := by
  exact mem_upperCompletion_iff.mpr
    ⟨minimal, hminimal, Finset.Subset.rfl⟩

/-- The upper completion is closed under finite binary unions. -/
theorem union_mem_upperCompletion
    {minimizers : Finset (Finset Component)}
    {A B : Finset Component}
    (hA : A ∈ upperCompletion minimizers)
    (hB : B ∈ upperCompletion minimizers) :
    A ∪ B ∈ upperCompletion minimizers := by
  rcases mem_upperCompletion_iff.mp hA with ⟨minimal, hminimal, hsub⟩
  apply mem_upperCompletion_iff.mpr
  exact ⟨minimal, hminimal,
    hsub.trans Finset.subset_union_left⟩

/-- Every upper-completion stratum remains active-owner acceptable. -/
theorem acceptable_of_mem_upperCompletion
    (J : Ideal R) (component : Component → Ideal R)
    (Q : Requirements (R := R) (Owner := Owner))
    (minimizers : Finset (Finset Component))
    (hacceptable : ∀ minimal ∈ minimizers,
      Acceptable J component Q minimal)
    {selected : Finset Component}
    (hselected : selected ∈ upperCompletion minimizers) :
    Acceptable J component Q selected := by
  rcases mem_upperCompletion_iff.mp hselected with
    ⟨minimal, hminimal, hsub⟩
  exact acceptable_mono J component Q hsub
    (hacceptable minimal hminimal)

/-- Intersecting two closure centres is represented by union of their selected
component sets. -/
theorem closure_intersection_union
    (J : Ideal R) (component : Component → Ideal R)
    (A B : Finset Component) :
    closure J component (A ∪ B) =
      closure J component A ⊔ closure J component B :=
  intersectionClosure_eq_sup J component A B

/-- Adding components can only shrink the corresponding closed centre.  In
ideal order, the closure ideal increases. -/
theorem closure_mono_of_subset
    (J : Ideal R) (component : Component → Ideal R)
    {A B : Finset Component} (hAB : A ⊆ B) :
    closure J component A ≤ closure J component B :=
  closure_mono J component hAB

/-- If the full correction family is itself among the minimizers, the upper
completion contains only that full family.  This records the unique terminal
boundary of the completion construction. -/
theorem upperCompletion_eq_single_univ
    (minimizers : Finset (Finset Component))
    (hmins : minimizers = {Finset.univ}) :
    upperCompletion minimizers = {Finset.univ} := by
  subst hmins
  ext selected
  simp [upperCompletion, Finset.Subset.antisymm_iff]

end

end CanonicalIntersectionCompletion
end Experimental
end PCRLean
