import Mathlib
import PCRLean.Experimental.DeterminantalCokernelObstruction
import PCRLean.Experimental.ProjectiveMoritaDescent
import PCRLean.Experimental.ProjectiveSectionOrderIdeal

/-!
# The intrinsic order ideal of a cokernel obstruction

For a packet map `φ : N → E` and target `b : E`, the exact obstruction is
`ω = [b] ∈ coker φ`. If the cokernel is finite projective and is supplied with
a finite dual frame, the order ideal of `ω` is an intrinsic finite ideal.

It is zero exactly when the packet is effective, and the obstruction lies in
its own scalar extension. Therefore the packet becomes effective after
quotienting by the order ideal. This ideal is the canonical defect component
predicted by hybrid centre synthesis.
-/

namespace PCRLean
namespace Experimental
namespace CokernelOrderIdeal

noncomputable section

universe u v w x

variable {R : Type u} [CommRing R]
variable {N : Type v} {E : Type w}
variable [AddCommGroup N] [Module R N]
variable [AddCommGroup E] [Module R E]
variable {ι : Type x} [Fintype ι] [DecidableEq ι]

open DeterminantalCokernelObstruction
open ProjectiveMoritaDescent
open ProjectiveSectionOrderIdeal

abbrev Q (φ : N →ₗ[R] E) := E ⧸ LinearMap.range φ

/-- Canonical order ideal of the cokernel obstruction class. -/
def obstructionIdeal
    (φ : N →ₗ[R] E) (b : E) : Ideal R :=
  orderIdeal (obstruction φ b)

/-- The obstruction class is generated by its own order ideal. -/
theorem obstruction_mem_orderIdeal_smul_top
    (φ : N →ₗ[R] E) (b : E)
    (F : DualFrame (R := R) (P := Q φ) (ι := ι)) :
    obstruction φ b ∈
      obstructionIdeal φ b • (⊤ : Submodule R (Q φ)) := by
  exact section_mem_orderIdeal_smul_top F (obstruction φ b)

/-- The canonical defect ideal vanishes exactly when the packet has an actual
solution. -/
theorem obstructionIdeal_eq_bot_iff_exists
    (φ : N →ₗ[R] E) (b : E)
    (F : DualFrame (R := R) (P := Q φ) (ι := ι)) :
    obstructionIdeal φ b = ⊥ ↔ ∃ x : N, φ x = b := by
  rw [obstructionIdeal,
    ProjectiveSectionOrderIdeal.orderIdeal_eq_bot_iff F,
    DeterminantalCokernelObstruction.obstruction_eq_zero_iff_exists]

/-- Over a Noetherian base the canonical obstruction component is finite type. -/
theorem obstructionIdeal_fg
    [IsNoetherianRing R]
    (φ : N →ₗ[R] E) (b : E) :
    (obstructionIdeal φ b).FG :=
  ProjectiveSectionOrderIdeal.orderIdeal_fg _

end

end CokernelOrderIdeal
end Experimental
end PCRLean
