import PCRLean.Experimental.CokernelOrderIdealBaseChange

#print axioms PCRLean.Experimental.CokernelOrderIdealBaseChange.CompatibleObstructions.toCompatibleFrames
#print axioms PCRLean.Experimental.CokernelOrderIdealBaseChange.CompatibleObstructions.map_obstructionIdeal_eq
#print axioms PCRLean.Experimental.CokernelOrderIdealBaseChange.CompatibleObstructions.target_eq_bot_of_source_eq_bot
#print axioms PCRLean.Experimental.CokernelOrderIdealBaseChange.CompatibleObstructions.source_eq_bot_of_target_eq_bot
#print axioms PCRLean.Experimental.CokernelOrderIdealBaseChange.CompatibleObstructions.obstructionIdeal_eq_bot_iff
