import Mathlib
import Mathlib.Algebra.MvPolynomial.Equiv
import Mathlib.RingTheory.Ideal.Quotient.Operations
import PCRLean.CoordinateBlowupChart

/-!
# Experimental exact coordinate-centre quotient bridge

This module constructs the actual elimination morphism which keeps all passive
coordinates and kills all centre coordinates.  It proves that its kernel is
exactly the ideal generated by the centre coordinates.  Consequently the
quotient by the actual centre ideal is the smaller passive polynomial ring.

The theorem is affine and coordinate-split.  It is an experimental U2 bridge,
not a universal regular-centre theorem and not a resolution theorem.
-/

namespace PCRLean
namespace Experimental
namespace CoordinateCentreQuotient

noncomputable section

universe u v w

variable {K : Type u} [CommRing K]
variable {α : Type v} {ι : Type w}

abbrev A := CoordinateBlowupChart.P (R := K) (α := α) (ι := ι)

/-- Keep passive variables and kill all centre variables. -/
def passiveEval : A (K := K) (α := α) (ι := ι) →+* MvPolynomial α K :=
  MvPolynomial.eval₂Hom (RingHom.id K)
    (fun s => match s with
      | Sum.inl a => MvPolynomial.X a
      | Sum.inr _ => 0)

@[simp] theorem passiveEval_C (a : K) :
    passiveEval (K := K) (α := α) (ι := ι) (MvPolynomial.C a) =
      MvPolynomial.C a := by
  simp [passiveEval]

@[simp] theorem passiveEval_passiveVar (a : α) :
    passiveEval (K := K) (α := α) (ι := ι)
        (MvPolynomial.X (Sum.inl a)) = MvPolynomial.X a := by
  simp [passiveEval]

@[simp] theorem passiveEval_centreVar (i : ι) :
    passiveEval (K := K) (α := α) (ι := ι)
        (CoordinateBlowupChart.centreVar
          (R := K) (α := α) (ι := ι) i) = 0 := by
  simp [passiveEval, CoordinateBlowupChart.centreVar]

/-- Re-embed the passive part after elimination. -/
def passiveProjection : A (K := K) (α := α) (ι := ι) →+*
    A (K := K) (α := α) (ι := ι) :=
  (MvPolynomial.rename (fun a : α => (Sum.inl a : α ⊕ ι))).toRingHom.comp
    (passiveEval (K := K) (α := α) (ι := ι))

@[simp] theorem passiveProjection_C (a : K) :
    passiveProjection (K := K) (α := α) (ι := ι) (MvPolynomial.C a) =
      MvPolynomial.C a := by
  simp [passiveProjection]

@[simp] theorem passiveProjection_passiveVar (a : α) :
    passiveProjection (K := K) (α := α) (ι := ι)
        (MvPolynomial.X (Sum.inl a)) = MvPolynomial.X (Sum.inl a) := by
  simp [passiveProjection]

@[simp] theorem passiveProjection_centreVar (i : ι) :
    passiveProjection (K := K) (α := α) (ι := ι)
        (CoordinateBlowupChart.centreVar
          (R := K) (α := α) (ι := ι) i) = 0 := by
  simp [passiveProjection, CoordinateBlowupChart.centreVar]

/-- Every centre coordinate belongs to the actual coordinate-centre ideal. -/
theorem centreVar_mem (i : ι) :
    CoordinateBlowupChart.centreVar (R := K) (α := α) (ι := ι) i ∈
      CoordinateBlowupChart.centreIdeal
        (R := K) (α := α) (ι := ι) := by
  rw [CoordinateBlowupChart.centreIdeal]
  exact Ideal.subset_span ⟨i, rfl⟩

/-- Every polynomial differs from its passive projection by an element of the
actual centre ideal. -/
theorem sub_passiveProjection_mem (p : A (K := K) (α := α) (ι := ι)) :
    p - passiveProjection (K := K) (α := α) (ι := ι) p ∈
      CoordinateBlowupChart.centreIdeal
        (R := K) (α := α) (ι := ι) := by
  induction p using MvPolynomial.induction_on with
  | C a => simp
  | add p q hp hq =>
      have hadd :=
        (CoordinateBlowupChart.centreIdeal
          (R := K) (α := α) (ι := ι)).add_mem hp hq
      simpa [map_add, add_sub_add_comm] using hadd
  | mul_X p s hp =>
      cases s with
      | inl a =>
          rw [map_mul, passiveProjection_passiveVar, ← sub_mul]
          rw [mul_comm]
          exact (CoordinateBlowupChart.centreIdeal
            (R := K) (α := α) (ι := ι)).mul_mem_left _ hp
      | inr i =>
          rw [map_mul, passiveProjection_centreVar]
          simp only [mul_zero, sub_zero]
          exact (CoordinateBlowupChart.centreIdeal
            (R := K) (α := α) (ι := ι)).mul_mem_left p
              (centreVar_mem (K := K) (α := α) i)

/-- The actual coordinate-centre ideal is contained in the elimination kernel. -/
theorem centreIdeal_le_ker :
    CoordinateBlowupChart.centreIdeal
        (R := K) (α := α) (ι := ι) ≤
      RingHom.ker (passiveEval (K := K) (α := α) (ι := ι)) := by
  rw [CoordinateBlowupChart.centreIdeal, Ideal.span_le]
  rintro x ⟨i, rfl⟩
  apply RingHom.mem_ker.mpr
  exact passiveEval_centreVar (K := K) (α := α) i

/-- The elimination kernel contains no additional equations: it is exactly the
actual coordinate-centre ideal. -/
theorem ker_passiveEval_eq_centreIdeal :
    RingHom.ker (passiveEval (K := K) (α := α) (ι := ι)) =
      CoordinateBlowupChart.centreIdeal
        (R := K) (α := α) (ι := ι) := by
  apply le_antisymm
  · intro p hp
    have hzero :
        passiveEval (K := K) (α := α) (ι := ι) p = 0 :=
      RingHom.mem_ker.mp hp
    have hmem := sub_passiveProjection_mem
      (K := K) (α := α) (ι := ι) p
    simpa [passiveProjection, hzero] using hmem
  · exact centreIdeal_le_ker (K := K) (α := α) (ι := ι)

/-- Passive evaluation is surjective, with section given by variable renaming. -/
theorem passiveEval_surjective :
    Function.Surjective
      (passiveEval (K := K) (α := α) (ι := ι)) := by
  intro p
  refine ⟨MvPolynomial.rename
      (fun a : α => (Sum.inl a : α ⊕ ι)) p, ?_⟩
  induction p using MvPolynomial.induction_on with
  | C a => simp
  | add p q hp hq => simp [hp, hq]
  | mul_X p a hp => simp [hp]

/-- Exact quotient theorem for the actual coordinate centre. -/
noncomputable def quotientEquiv :
    (A (K := K) (α := α) (ι := ι) ⧸
        CoordinateBlowupChart.centreIdeal
          (R := K) (α := α) (ι := ι)) ≃+*
      MvPolynomial α K :=
  (Ideal.quotEquivOfEq
      (ker_passiveEval_eq_centreIdeal
        (K := K) (α := α) (ι := ι)).symm).trans
    (RingHom.quotientKerEquivOfSurjective
      (passiveEval (K := K) (α := α) (ι := ι))
      (passiveEval_surjective (K := K) (α := α) (ι := ι)))

/-- The quotient equivalence evaluates representatives by killing centre
coordinates. -/
@[simp] theorem quotientEquiv_mk
    (p : A (K := K) (α := α) (ι := ι)) :
    quotientEquiv (K := K) (α := α) (ι := ι)
        (Ideal.Quotient.mk
          (CoordinateBlowupChart.centreIdeal
            (R := K) (α := α) (ι := ι)) p) =
      passiveEval (K := K) (α := α) (ι := ι) p := by
  rfl

end

end CoordinateCentreQuotient
end Experimental
end PCRLean