import PCRLean.Experimental.CoordinateCentreExactFrobeniusHeredity

#print axioms PCRLean.Experimental.CoordinateCentreExactFrobeniusHeredity.normalPolynomialEquiv_centreVar
#print axioms PCRLean.Experimental.CoordinateCentreExactFrobeniusHeredity.map_centreIdeal_eq_normalIdeal
#print axioms PCRLean.Experimental.CoordinateCentreExactFrobeniusHeredity.map_normalIdeal_eq_centreIdeal
#print axioms PCRLean.Experimental.CoordinateCentreExactFrobeniusHeredity.mem_centreIdeal_pow_iff_normalIdeal_pow
#print axioms PCRLean.Experimental.CoordinateCentreExactFrobeniusHeredity.mem_centreIdeal_pow_iff_normalOrderGE
#print axioms PCRLean.Experimental.CoordinateCentreExactFrobeniusHeredity.normalOrderGE_power_iff
#print axioms PCRLean.Experimental.CoordinateCentreExactFrobeniusHeredity.frobeniusPower_mem_centreIdeal_pow_iff
