import PCRLean.Experimental.DerivativeZeroFinitePresentation

#print axioms PCRLean.Experimental.DerivativeZeroFinitePresentation.rootRow_pow
#print axioms PCRLean.Experimental.DerivativeZeroFinitePresentation.presentationIdeal_eq_rootPowerIdeal
#print axioms PCRLean.Experimental.DerivativeZeroFinitePresentation.presentationIdeal_le_rootIdeal_pow
#print axioms PCRLean.Experimental.DerivativeZeroFinitePresentation.markedPresentation_permissible
#print axioms PCRLean.Experimental.DerivativeZeroFinitePresentation.rootRow_totalDegree_le
#print axioms PCRLean.Experimental.DerivativeZeroFinitePresentation.degreeMass_rootPacket_lt
#print axioms PCRLean.Experimental.DerivativeZeroFinitePresentation.no_infinite_rootPacket_chain
