import Mathlib
import PCRLean.MarkedIdeal
import PCRLean.Experimental.PDerivFrobeniusDescent

/-!
# Finite derivative-zero presentations

A finite family of polynomials over a perfect field is called derivative-zero
when every first partial derivative of every row vanishes.  Apply the explicit
perfect-field Frobenius root row by row.  The original presentation ideal is
then exactly the ideal generated by the `p`-th powers of the root rows, and is
contained in the `p`-th power of the actual root ideal.  Thus a mark-`p` packet
is permissible for this finite actual root ideal.

The total-degree mass of the finite presentation strictly decreases whenever at
least one row is nonconstant.  This gives a genuine finite-packet termination
rank for repeated rank-zero Frobenius extraction.  The root ideal need not be a
regular centre; regularization or hybrid synthesis remains a separate geometric
step.
-/

namespace PCRLean
namespace Experimental
namespace DerivativeZeroFinitePresentation

noncomputable section

universe u v w

variable {K : Type u} [Field K]
variable {σ : Type v} [Fintype σ] [DecidableEq σ]
variable {κ : Type w} [Fintype κ]
variable (p : Nat) [Fact p.Prime] [CharP K p] [PerfectField K p]

open PDerivFrobeniusDescent

/-- All first partial derivatives vanish on every row. -/
def AllPDerivZero (equation : κ → MvPolynomial σ K) : Prop :=
  ∀ j i, MvPolynomial.pderiv i (equation j) = 0

/-- Canonical finite packet of perfect-field Frobenius roots. -/
def rootPacket (equation : κ → MvPolynomial σ K) :
    κ → MvPolynomial σ K :=
  fun j => derivativeRoot p (equation j)

/-- Ideal generated by the original finite presentation. -/
def presentationIdeal (equation : κ → MvPolynomial σ K) :
    Ideal (MvPolynomial σ K) :=
  Ideal.span (Set.range equation)

/-- Actual ideal generated by the canonical roots. -/
def rootIdeal (equation : κ → MvPolynomial σ K) :
    Ideal (MvPolynomial σ K) :=
  Ideal.span (Set.range (rootPacket p equation))

/-- Finite ideal generated by the `p`-th powers of the canonical roots. -/
def rootPowerIdeal (equation : κ → MvPolynomial σ K) :
    Ideal (MvPolynomial σ K) :=
  Ideal.span (Set.range fun j : κ => (rootPacket p equation j) ^ p)

/-- Each recovered root raises back to its named equation. -/
theorem rootRow_pow
    (equation : κ → MvPolynomial σ K)
    (hzero : AllPDerivZero equation) (j : κ) :
    (rootPacket p equation j) ^ p = equation j := by
  exact derivativeRoot_pow p (equation j) (hzero j)

/-- The original presentation ideal is exactly the finite ideal of root
powers. -/
theorem presentationIdeal_eq_rootPowerIdeal
    (equation : κ → MvPolynomial σ K)
    (hzero : AllPDerivZero equation) :
    presentationIdeal equation = rootPowerIdeal p equation := by
  apply le_antisymm
  · rw [presentationIdeal, Ideal.span_le]
    rintro z ⟨j, rfl⟩
    rw [← rootRow_pow p equation hzero j]
    exact Ideal.subset_span ⟨j, rfl⟩
  · rw [rootPowerIdeal, Ideal.span_le]
    rintro z ⟨j, rfl⟩
    rw [rootRow_pow p equation hzero j]
    exact Ideal.subset_span ⟨j, rfl⟩

/-- Every root row belongs to the actual root ideal. -/
theorem rootRow_mem_rootIdeal
    (equation : κ → MvPolynomial σ K) (j : κ) :
    rootPacket p equation j ∈ rootIdeal p equation :=
  Ideal.subset_span ⟨j, rfl⟩

/-- The derivative-zero presentation belongs to the `p`-th power of the actual
root ideal. -/
theorem presentationIdeal_le_rootIdeal_pow
    (equation : κ → MvPolynomial σ K)
    (hzero : AllPDerivZero equation) :
    presentationIdeal equation ≤ (rootIdeal p equation) ^ p := by
  rw [presentationIdeal, Ideal.span_le]
  rintro z ⟨j, rfl⟩
  rw [← rootRow_pow p equation hzero j]
  exact Ideal.pow_mem_pow (rootRow_mem_rootIdeal p equation j) p

/-- The mark-`p` finite presentation is permissible for its canonical actual
root ideal. -/
theorem markedPresentation_permissible
    (equation : κ → MvPolynomial σ K)
    (hzero : AllPDerivZero equation) :
    MarkedIdeal.Permissible
      (R := MvPolynomial σ K)
      ⟨presentationIdeal equation, p, Fact.out.pos⟩
      (rootIdeal p equation) :=
  presentationIdeal_le_rootIdeal_pow p equation hzero

/-- Total-degree mass of a finite presentation. -/
def degreeMass (equation : κ → MvPolynomial σ K) : Nat :=
  ∑ j : κ, (equation j).totalDegree

/-- Root extraction never increases the degree of an individual row. -/
theorem rootRow_totalDegree_le
    (equation : κ → MvPolynomial σ K)
    (hzero : AllPDerivZero equation) (j : κ) :
    (rootPacket p equation j).totalDegree ≤ (equation j).totalDegree := by
  by_cases hpos : 0 < (equation j).totalDegree
  · exact (derivativeRoot_totalDegree_lt p (equation j) (hzero j) hpos).le
  · have hz : (equation j).totalDegree = 0 := Nat.eq_zero_of_not_pos hpos
    have hpow := rootRow_pow p equation hzero j
    rw [← hpow, MvPolynomial.totalDegree_pow] at hz
    have hp : 0 < p := Fact.out.pos
    have hroot : (rootPacket p equation j).totalDegree = 0 := by omega
    simp [hroot]

/-- If at least one row is nonconstant, rowwise root extraction strictly lowers
the total-degree mass. -/
theorem degreeMass_rootPacket_lt
    (equation : κ → MvPolynomial σ K)
    (hzero : AllPDerivZero equation)
    (hnonconstant : ∃ j : κ, 0 < (equation j).totalDegree) :
    degreeMass (rootPacket p equation) < degreeMass equation := by
  rcases hnonconstant with ⟨j, hj⟩
  apply Finset.sum_lt_sum
  · intro i hi
    exact rootRow_totalDegree_le p equation hzero i
  · exact ⟨j, Finset.mem_univ j,
      derivativeRoot_totalDegree_lt p (equation j) (hzero j) hj⟩

/-- There is no infinite chain of finite derivative-zero presentations in which
all rows are replaced by their canonical roots and at least one row remains
nonconstant at every step. -/
theorem no_infinite_rootPacket_chain :
    ¬ ∃ f : Nat → (κ → MvPolynomial σ K),
      ∀ n,
        AllPDerivZero (f n) ∧
        (∃ j : κ, 0 < (f n j).totalDegree) ∧
        f (n + 1) = rootPacket p (f n) := by
  rintro ⟨f, hf⟩
  exact PCRLean.noInfiniteDescending Nat.lt_wfRel.wf
    (fun n => degreeMass (f n))
    (fun n => by
      rcases hf n with ⟨hzero, hnonconstant, hnext⟩
      rw [hnext]
      exact degreeMass_rootPacket_lt p (f n) hzero hnonconstant)

end

end DerivativeZeroFinitePresentation
end Experimental
end PCRLean
