import Mathlib

/-!
# The coordinate-free determinantal obstruction

A finite affine packet is a map `φ : N → E` together with a target section
`b : E`. The exact obstruction to solving `φ x = b` is the class of `b` in

`coker φ = E / range φ`.

This quotient is the coordinate-free object represented by the augmented
maximal minors. Vanishing gives a global solution; nonvanishing is a coherent
finite discrepancy whose support can be sent to a lower Fitting frontier.
-/

namespace PCRLean
namespace Experimental
namespace DeterminantalCokernelObstruction

noncomputable section

universe u v w

variable {R : Type u} [CommRing R]
variable {N : Type v} {E : Type w}
variable [AddCommGroup N] [Module R N]
variable [AddCommGroup E] [Module R E]

/-- Class of the desired target section in the cokernel of the packet map. -/
def obstruction (φ : N →ₗ[R] E) (b : E) :
    E ⧸ LinearMap.range φ :=
  Submodule.Quotient.mk b

/-- Effectivity is exactly vanishing of the cokernel class. -/
theorem obstruction_eq_zero_iff
    (φ : N →ₗ[R] E) (b : E) :
    obstruction φ b = 0 ↔ b ∈ LinearMap.range φ := by
  exact Submodule.Quotient.mk_eq_zero

/-- Membership in the range is the existence of an actual solution. -/
theorem obstruction_eq_zero_iff_exists
    (φ : N →ₗ[R] E) (b : E) :
    obstruction φ b = 0 ↔ ∃ x : N, φ x = b := by
  rw [obstruction_eq_zero_iff]
  exact LinearMap.mem_range

/-- Cyclic coherent discrepancy generated by the obstruction class. -/
def cyclicObstruction (φ : N →ₗ[R] E) (b : E) :
    Submodule R (E ⧸ LinearMap.range φ) :=
  Submodule.span R {obstruction φ b}

/-- The cyclic discrepancy vanishes precisely when the packet is effective. -/
theorem cyclicObstruction_eq_bot_iff
    (φ : N →ₗ[R] E) (b : E) :
    cyclicObstruction φ b = ⊥ ↔ obstruction φ b = 0 := by
  rw [cyclicObstruction, Submodule.span_eq_bot]
  simp

/-- Coordinate-free effectivity criterion. -/
theorem cyclicObstruction_eq_bot_iff_exists
    (φ : N →ₗ[R] E) (b : E) :
    cyclicObstruction φ b = ⊥ ↔ ∃ x : N, φ x = b := by
  rw [cyclicObstruction_eq_bot_iff, obstruction_eq_zero_iff_exists]

end

end DeterminantalCokernelObstruction
end Experimental
end PCRLean
