import Mathlib
import PCRLean.MarkedIdeal
import PCRLean.Experimental.DualPacketRegularCentre
import PCRLean.Experimental.IntrinsicKernelRootPacket

/-!
# Experimental correctly oriented root package of a dual packet

For a finite covector packet on a tangent space, the actual centre ideal is
generated by its cotangent row span.  At mark `q`, the corresponding intrinsic
root package is generated by the `q`-th powers of every row-span element.  It
lies in the `q`-th power of the actual centre and is therefore marked
permissible.

The root package is exactly the generic intrinsic kernel root packet of the
canonical conormal quotient by the row span.  It depends only on the packet
span, so redundant rows and finite changes of presentation do not alter it.
This file does not prove controlled-transform terminality on nonlinear blowup
charts.
-/

namespace PCRLean
namespace Experimental
namespace DualPacketRootPackage

noncomputable section

universe u v w

variable {K : Type u} [Field K]
variable {T : Type v} [AddCommGroup T] [Module K T]
variable {ι : Type w} [Fintype ι]

abbrev Cotangent := Module.Dual K T

open DualPacketRegularCentre

/-- Correctly oriented `q`-th root package generated by the cotangent row span. -/
def rootPowerIdeal
    (packet : ι → Cotangent (K := K) (T := T)) (q : Nat) :
    Ideal (SymmetricAlgebra K (Cotangent (K := K) (T := T))) :=
  Ideal.span (Set.range fun f : packetSpan packet =>
    (SymmetricAlgebra.ι K (Cotangent (K := K) (T := T)) f.1) ^ q)

/-- Every named row-span root power belongs to the package. -/
theorem rootGenerator_mem
    (packet : ι → Cotangent (K := K) (T := T))
    (q : Nat) (f : packetSpan packet) :
    (SymmetricAlgebra.ι K (Cotangent (K := K) (T := T)) f.1) ^ q ∈
      rootPowerIdeal packet q := by
  apply Ideal.subset_span
  exact ⟨f, rfl⟩

/-- The dual-packet root package lies in the corresponding power of the actual
centre ideal. -/
theorem rootPowerIdeal_le_centreIdeal_pow
    (packet : ι → Cotangent (K := K) (T := T)) (q : Nat) :
    rootPowerIdeal packet q ≤ (centreIdeal packet) ^ q := by
  rw [rootPowerIdeal, Ideal.span_le]
  rintro z ⟨f, rfl⟩
  exact Ideal.pow_mem_pow
    (Ideal.subset_span ⟨f, rfl⟩) q

/-- Correctly oriented marked permissibility of the full row-span root package. -/
theorem rootPacket_permissible
    (packet : ι → Cotangent (K := K) (T := T))
    {q : Nat} (hq : 0 < q) :
    MarkedIdeal.Permissible
      (R := SymmetricAlgebra K (Cotangent (K := K) (T := T)))
      ⟨rootPowerIdeal packet q, q, hq⟩
      (centreIdeal packet) :=
  rootPowerIdeal_le_centreIdeal_pow packet q

/-- The row-span root package is exactly the generic intrinsic root packet of
the canonical conormal quotient. -/
theorem rootPowerIdeal_eq_intrinsic
    (packet : ι → Cotangent (K := K) (T := T)) (q : Nat) :
    rootPowerIdeal packet q =
      IntrinsicKernelRootPacket.rootPowerIdeal
        (conormalQuotient packet) q := by
  apply le_antisymm
  · rw [rootPowerIdeal, Ideal.span_le]
    rintro z ⟨f, rfl⟩
    apply Ideal.subset_span
    refine ⟨⟨f.1, ?_⟩, rfl⟩
    rw [ker_conormalQuotient_eq_packetSpan]
    exact f.2
  · rw [IntrinsicKernelRootPacket.rootPowerIdeal, Ideal.span_le]
    rintro z ⟨f, rfl⟩
    apply Ideal.subset_span
    refine ⟨⟨f.1, ?_⟩, rfl⟩
    rw [← ker_conormalQuotient_eq_packetSpan]
    exact f.2

/-- Equal row spans give equal root packages, even for different packet index
types. -/
theorem rootPowerIdeal_eq_of_span_eq
    {κ : Type*} [Fintype κ]
    (p : ι → Cotangent (K := K) (T := T))
    (r : κ → Cotangent (K := K) (T := T))
    (hspan : packetSpan p = packetSpan r)
    (q : Nat) :
    rootPowerIdeal p q = rootPowerIdeal r q := by
  unfold rootPowerIdeal
  rw [hspan]

end

end DualPacketRootPackage
end Experimental
end PCRLean
