import Mathlib
import PCRLean.Experimental.AbstractRootChartTerminality
import PCRLean.Experimental.LeftCoordinateBlowupChart
import PCRLean.Experimental.DualPacketCoordinateNormalization
import PCRLean.Experimental.DualPacketAffineQuotient
import PCRLean.Experimental.FrobeniusFiniteRootGeneration

/-!
# Experimental blowup charts for arbitrary dual-packet linear centres

Choose a basis of the packet row span, extend it to cotangent coordinates, and
conjugate the standard coordinate-centre blowup chart back to the original
affine polynomial ring.  Every centre-basis linear form factors as the pivot
exceptional form times a controlled root, with pivot controlled root equal to
`1`.

In characteristic `p`, the full row-span `p^e`-root package equals the finite
ideal generated by the powers of the centre-basis forms.  Hence every standard
pivot chart makes the controlled full root packet terminal.  A positive-rank
centre supplies at least one pivot chart.  The rank-zero chamber is not hidden
in this theorem and remains a separate geometric obligation.
-/

namespace PCRLean
namespace Experimental
namespace DualPacketBlowupChart

noncomputable section

universe u v w

variable {K : Type u} [Field K]
variable {σ : Type v} [Fintype σ] [DecidableEq σ]
variable {κ : Type w} [Fintype κ]

abbrev Direction := σ → K
abbrev Dual := Module.Dual K (Direction (K := K) (σ := σ))

open DualPacketCoordinateNormalization
open DualPacketAffineLinearRealization
open DualPacketRegularCentre

/-- Actual linear form attached to one basis vector of the packet row span. -/
def basisGenerator
    (packet : κ → Dual (K := K) (σ := σ))
    (i : CentreIndex packet) : MvPolynomial σ K :=
  FunctionalPacketIdeal.functionalPolynomial (centreCovector packet i)

/-- The normalizing coordinate equivalence sends a basis generator to its
standard centre coordinate. -/
@[simp] theorem actualCoordinateEquiv_basisGenerator
    (packet : κ → Dual (K := K) (σ := σ))
    (i : CentreIndex packet) :
    actualCoordinateEquiv packet (basisGenerator packet i) =
      LeftCoordinateBlowupChart.centreVar
        (R := K) (α := PassiveIndex packet) i := by
  rw [basisGenerator]
  change
    symmetricCoordinateEquiv packet
      (polyToSym (K := K) (σ := σ)
        (FunctionalPacketIdeal.functionalPolynomial
          (centreCovector packet i))) = _
  rw [← symToPoly_ι]
  rw [DualPacketAffineQuotient.polyToSym_symToPoly]
  rw [← fullBasis_inl packet i]
  simp [symmetricCoordinateEquiv,
    LeftCoordinateBlowupChart.centreVar]

/-- Conjugated standard blowup chart on the original affine polynomial ring. -/
def chartMap
    (packet : κ → Dual (K := K) (σ := σ))
    (k : CentreIndex packet) :
    MvPolynomial σ K →+* MvPolynomial σ K :=
  (actualCoordinateEquiv packet).symm.toAlgHom.toRingHom.comp
    ((LeftCoordinateBlowupChart.chartMap
      (R := K) (α := PassiveIndex packet) k).comp
      (actualCoordinateEquiv packet).toAlgHom.toRingHom)

/-- Exceptional basis form in the conjugated chart. -/
def exceptional
    (packet : κ → Dual (K := K) (σ := σ))
    (k : CentreIndex packet) : MvPolynomial σ K :=
  (actualCoordinateEquiv packet).symm
    (LeftCoordinateBlowupChart.centreVar
      (R := K) (α := PassiveIndex packet) k)

/-- Controlled root in the conjugated chart. -/
def controlledRoot
    (packet : κ → Dual (K := K) (σ := σ))
    (k i : CentreIndex packet) : MvPolynomial σ K :=
  (actualCoordinateEquiv packet).symm
    (LeftCoordinateBlowupChart.controlledRoot
      (R := K) (α := PassiveIndex packet) k i)

/-- Exact factorization of every centre-basis generator in every pivot chart. -/
theorem basisGenerator_factorization
    (packet : κ → Dual (K := K) (σ := σ))
    (k i : CentreIndex packet) :
    chartMap packet k (basisGenerator packet i) =
      exceptional packet k * controlledRoot packet k i := by
  change
    (actualCoordinateEquiv packet).symm
      (LeftCoordinateBlowupChart.chartMap
        (R := K) (α := PassiveIndex packet) k
        (actualCoordinateEquiv packet (basisGenerator packet i))) = _
  rw [actualCoordinateEquiv_basisGenerator]
  rw [LeftCoordinateBlowupChart.centreVar_factorization]
  simp [exceptional, controlledRoot]

/-- The pivot controlled root is the unit. -/
@[simp] theorem controlledRoot_pivot
    (packet : κ → Dual (K := K) (σ := σ))
    (k : CentreIndex packet) :
    controlledRoot packet k k = 1 := by
  simp [controlledRoot, LeftCoordinateBlowupChart.controlledRoot]

/-- The conjugated packet chart satisfies the abstract terminality interface. -/
def rootChart
    (packet : κ → Dual (K := K) (σ := σ))
    (k : CentreIndex packet) :
    AbstractRootChartTerminality.RootChart
      (basisGenerator packet) k where
  chartMap := chartMap packet k
  exceptional := exceptional packet k
  controlledRoot := controlledRoot packet k
  factorization := basisGenerator_factorization packet k
  pivot_controlledRoot := controlledRoot_pivot packet k

/-- The centre-basis covectors span exactly the original packet row span. -/
theorem centreCovector_packetSpan_eq
    (packet : κ → Dual (K := K) (σ := σ)) :
    packetSpan (centreCovector packet) = packetSpan packet := by
  apply le_antisymm
  · rw [packetSpan, Submodule.span_le]
    rintro f ⟨i, rfl⟩
    exact (centreBasis packet i).2
  · intro f hf
    let fs : packetSpan packet := ⟨f, hf⟩
    have hrepr :
        (∑ i : CentreIndex packet,
          ((centreBasis packet).repr fs) i • centreBasis packet i) = fs :=
      (centreBasis packet).sum_repr fs
    have hsum :
        f = ∑ i : CentreIndex packet,
          ((centreBasis packet).repr fs) i • centreCovector packet i := by
      have hval := congrArg Subtype.val hrepr
      simpa [fs, centreCovector] using hval.symm
    rw [hsum]
    exact (packetSpan (centreCovector packet)).sum_mem fun i hi =>
      (packetSpan (centreCovector packet)).smul_mem _
        (Submodule.subset_span ⟨i, rfl⟩)

section Frobenius

variable (p : Nat) [Fact p.Prime] [CharP K p]

/-- The full packet root package equals the finite ideal generated by powers of
the chosen centre-basis forms. -/
theorem actualRootPowerIdeal_eq_basisPowerIdeal
    (packet : κ → Dual (K := K) (σ := σ)) (e : Nat) :
    DualPacketAffineRootPackage.actualRootPowerIdeal packet (p ^ e) =
      FrobeniusFiniteRootGeneration.packetPowerIdeal p
        (centreCovector packet) e := by
  calc
    DualPacketAffineRootPackage.actualRootPowerIdeal packet (p ^ e) =
        DualPacketAffineRootPackage.actualRootPowerIdeal
          (centreCovector packet) (p ^ e) :=
      DualPacketAffineRootPackage.actualRootPowerIdeal_eq_of_span_eq
        packet (centreCovector packet)
        (centreCovector_packetSpan_eq packet).symm (p ^ e)
    _ = FrobeniusFiniteRootGeneration.packetPowerIdeal p
          (centreCovector packet) e :=
      FrobeniusFiniteRootGeneration.actualRootPowerIdeal_eq_packetPowerIdeal
        p (centreCovector packet) e

/-- Exact powered factorization of every centre-basis source generator. -/
theorem basisGenerator_pow_factorization
    (packet : κ → Dual (K := K) (σ := σ))
    (k i : CentreIndex packet) (e : Nat) :
    chartMap packet k ((basisGenerator packet i) ^ (p ^ e)) =
      (exceptional packet k) ^ (p ^ e) *
        (controlledRoot packet k i) ^ (p ^ e) := by
  rw [map_pow, basisGenerator_factorization, mul_pow]

/-- Every standard pivot chart terminalizes the controlled full Frobenius root
packet of an arbitrary positive-rank linear packet centre. -/
theorem transformedRootIdeal_eq_top
    (packet : κ → Dual (K := K) (σ := σ))
    (k : CentreIndex packet) (e : Nat) :
    (rootChart packet k).transformedRootIdeal (p ^ e) = ⊤ :=
  (rootChart packet k).transformedRootIdeal_eq_top (p ^ e)

/-- Positive row-span rank supplies at least one pivot chart. -/
theorem nonempty_centreIndex_of_positive_finrank
    (packet : κ → Dual (K := K) (σ := σ))
    (hpos : 0 < FiniteDimensional.finrank K (packetSpan packet)) :
    Nonempty (CentreIndex packet) := by
  exact Fin.nonempty_iff.mpr hpos

end Frobenius

end

end DualPacketBlowupChart
end Experimental
end PCRLean
