import Mathlib
import PCRLean.FunctionalPacketIdeal
import PCRLean.LinearPacketIdeal
import PCRLean.Experimental.DualPacketRegularCentre

/-!
# Experimental affine realization of dual-packet centres

For a finite coordinate tangent space `K^σ`, the symmetric algebra of its dual
is canonically algebra-equivalent to the affine polynomial ring `K[X_σ]`.
The equivalence sends a covector to its actual linear polynomial.  Under this
equivalence, the correctly oriented row-span centre ideal is exactly the ideal
generated by the packet's actual linear polynomials.

This theorem lifts the corrected cotangent-symmetric construction into the
ordinary affine coordinate ring.  It remains a linear chart theorem: arbitrary
regular local rings still require a parameter-lifting and descent argument.
-/

namespace PCRLean
namespace Experimental
namespace DualPacketAffineLinearRealization

noncomputable section

universe u v w

variable {K : Type u} [Field K]
variable {σ : Type v} [Fintype σ] [DecidableEq σ]
variable {κ : Type w} [Fintype κ]

abbrev Direction := σ → K
abbrev Dual := Module.Dual K (Direction (K := K) (σ := σ))

/-- Coordinate projection as a covector. -/
def coordinateFunctional (i : σ) : Dual (K := K) (σ := σ) where
  toFun x := x i
  map_add' := by
    intro x y
    rfl
  map_smul' := by
    intro a x
    rfl

@[simp] theorem coordinateFunctional_apply (i : σ)
    (x : Direction (K := K) (σ := σ)) :
    coordinateFunctional (K := K) i x = x i := rfl

/-- Standard reconstruction of a coordinate vector from basis vectors. -/
theorem direction_eq_sum_basisVector
    (x : Direction (K := K) (σ := σ)) :
    x = ∑ i : σ, x i • FunctionalPacketIdeal.basisVector (K := K) i := by
  classical
  funext j
  simp [FunctionalPacketIdeal.basisVector]

/-- Every covector is the corresponding combination of coordinate
projections. -/
theorem functional_eq_sum_coordinateFunctional
    (f : Dual (K := K) (σ := σ)) :
    f = ∑ i : σ,
      f (FunctionalPacketIdeal.basisVector (K := K) i) •
        coordinateFunctional (K := K) i := by
  ext x
  have hx := congrArg f
    (direction_eq_sum_basisVector (K := K) (σ := σ) x)
  simpa [mul_comm] using hx

/-- The coordinate row of a coordinate projection is the standard coordinate
row. -/
theorem coefficientRow_coordinateFunctional (i : σ) :
    FunctionalPacketIdeal.coefficientRow
        (coordinateFunctional (K := K) i) =
      LinearPacketIdeal.coordinateRow (K := K) i := by
  classical
  funext j
  simp [FunctionalPacketIdeal.coefficientRow,
    FunctionalPacketIdeal.basisVector,
    coordinateFunctional, LinearPacketIdeal.coordinateRow, eq_comm]

/-- A coordinate covector integrates to the corresponding polynomial
coordinate. -/
@[simp] theorem functionalPolynomial_coordinateFunctional (i : σ) :
    FunctionalPacketIdeal.functionalPolynomial
        (coordinateFunctional (K := K) i) =
      MvPolynomial.X i := by
  rw [FunctionalPacketIdeal.functionalPolynomial,
    coefficientRow_coordinateFunctional]
  exact LinearPacketIdeal.linearPolynomial_coordinateRow (K := K) i

/-- Symmetric algebra to the actual affine polynomial ring. -/
def symToPoly :
    SymmetricAlgebra K (Dual (K := K) (σ := σ)) →ₐ[K]
      MvPolynomial σ K :=
  SymmetricAlgebra.lift
    (FunctionalPacketIdeal.integrationMap (K := K) (σ := σ))

/-- Reconstruct the symmetric algebra from affine coordinate variables. -/
def polyToSym :
    MvPolynomial σ K →ₐ[K]
      SymmetricAlgebra K (Dual (K := K) (σ := σ)) :=
  MvPolynomial.aeval fun i =>
    SymmetricAlgebra.ι K (Dual (K := K) (σ := σ))
      (coordinateFunctional (K := K) i)

@[simp] theorem symToPoly_ι
    (f : Dual (K := K) (σ := σ)) :
    symToPoly (K := K) (σ := σ)
        (SymmetricAlgebra.ι K (Dual (K := K) (σ := σ)) f) =
      FunctionalPacketIdeal.functionalPolynomial f := by
  simp [symToPoly]

@[simp] theorem polyToSym_X (i : σ) :
    polyToSym (K := K) (σ := σ) (MvPolynomial.X i) =
      SymmetricAlgebra.ι K (Dual (K := K) (σ := σ))
        (coordinateFunctional (K := K) i) := by
  simp [polyToSym]

/-- The affine-to-symmetric map is a left inverse on symmetric generators. -/
theorem polyToSym_symToPoly_ι
    (f : Dual (K := K) (σ := σ)) :
    polyToSym (K := K) (σ := σ)
        (symToPoly (K := K) (σ := σ)
          (SymmetricAlgebra.ι K (Dual (K := K) (σ := σ)) f)) =
      SymmetricAlgebra.ι K (Dual (K := K) (σ := σ)) f := by
  classical
  rw [symToPoly_ι, FunctionalPacketIdeal.functionalPolynomial,
    LinearPacketIdeal.linearPolynomial]
  simp only [map_sum, map_mul, MvPolynomial.map_C, polyToSym_X]
  change
    (∑ i : σ,
      f (FunctionalPacketIdeal.basisVector (K := K) i) •
        SymmetricAlgebra.ι K (Dual (K := K) (σ := σ))
          (coordinateFunctional (K := K) i)) = _
  rw [← map_sum]
  rw [← functional_eq_sum_coordinateFunctional (K := K) (σ := σ) f]

/-- The symmetric-to-affine map is a left inverse on polynomial variables. -/
theorem symToPoly_polyToSym_X (i : σ) :
    symToPoly (K := K) (σ := σ)
        (polyToSym (K := K) (σ := σ) (MvPolynomial.X i)) =
      MvPolynomial.X i := by
  simp

/-- The two substitutions are inverse algebra homomorphisms. -/
theorem polyToSym_comp_symToPoly :
    (polyToSym (K := K) (σ := σ)).comp
        (symToPoly (K := K) (σ := σ)) =
      AlgHom.id K (SymmetricAlgebra K (Dual (K := K) (σ := σ))) := by
  apply SymmetricAlgebra.algHom_ext
  ext f
  exact polyToSym_symToPoly_ι (K := K) (σ := σ) f

/-- The two substitutions are inverse in the other order. -/
theorem symToPoly_comp_polyToSym :
    (symToPoly (K := K) (σ := σ)).comp
        (polyToSym (K := K) (σ := σ)) =
      AlgHom.id K (MvPolynomial σ K) := by
  ext i
  exact symToPoly_polyToSym_X (K := K) (σ := σ) i

/-- Canonical coordinate algebra equivalence. -/
noncomputable def algebraEquiv :
    SymmetricAlgebra K (Dual (K := K) (σ := σ)) ≃ₐ[K]
      MvPolynomial σ K where
  toAlgHom := symToPoly (K := K) (σ := σ)
  invFun := polyToSym (K := K) (σ := σ)
  left_inv := by
    intro p
    have h := congrArg
      (fun F : SymmetricAlgebra K (Dual (K := K) (σ := σ)) →ₐ[K]
          SymmetricAlgebra K (Dual (K := K) (σ := σ)) => F p)
      (polyToSym_comp_symToPoly (K := K) (σ := σ))
    simpa using h
  right_inv := by
    intro p
    have h := congrArg
      (fun F : MvPolynomial σ K →ₐ[K] MvPolynomial σ K => F p)
      (symToPoly_comp_polyToSym (K := K) (σ := σ))
    simpa using h

/-- Actual affine ideal generated by the packet's linear polynomials. -/
def actualIdeal
    (packet : κ → Dual (K := K) (σ := σ)) :
    Ideal (MvPolynomial σ K) :=
  Ideal.span (Set.range fun i : κ =>
    FunctionalPacketIdeal.functionalPolynomial (packet i))

/-- Every covector in the packet row span integrates into the actual affine
packet ideal. -/
theorem functionalPolynomial_mem_actualIdeal_of_mem_span
    (packet : κ → Dual (K := K) (σ := σ))
    {f : Dual (K := K) (σ := σ)}
    (hf : f ∈ Submodule.span K (Set.range packet)) :
    FunctionalPacketIdeal.functionalPolynomial f ∈ actualIdeal packet := by
  induction hf using Submodule.span_induction with
  | mem f hf =>
      rcases hf with ⟨i, rfl⟩
      exact Ideal.subset_span ⟨i, rfl⟩
  | zero =>
      simp [FunctionalPacketIdeal.functionalPolynomial,
        FunctionalPacketIdeal.coefficientRow,
        LinearPacketIdeal.linearPolynomial, actualIdeal]
  | add f g hf hg hfi hgi =>
      rw [FunctionalPacketIdeal.functionalPolynomial_add]
      exact (actualIdeal packet).add_mem hfi hgi
  | smul a f hf hfi =>
      rw [FunctionalPacketIdeal.functionalPolynomial_smul]
      exact (actualIdeal packet).mul_mem_left _ hfi

/-- The corrected row-span centre maps exactly to the actual affine linear
packet ideal. -/
theorem map_centreIdeal_eq_actualIdeal
    (packet : κ → Dual (K := K) (σ := σ)) :
    Ideal.map (symToPoly (K := K) (σ := σ))
        (DualPacketRegularCentre.centreIdeal packet) =
      actualIdeal packet := by
  apply le_antisymm
  · rw [Ideal.map_le_iff_le_comap,
      DualPacketRegularCentre.centreIdeal, Ideal.span_le]
    rintro z ⟨f, rfl⟩
    rw [Ideal.mem_comap, symToPoly_ι]
    exact functionalPolynomial_mem_actualIdeal_of_mem_span
      packet f.2
  · rw [actualIdeal, Ideal.span_le]
    rintro z ⟨i, rfl⟩
    rw [← symToPoly_ι]
    apply Ideal.mem_map_of_mem
    apply Ideal.subset_span
    refine ⟨⟨packet i, ?_⟩, rfl⟩
    exact Submodule.subset_span ⟨i, rfl⟩

/-- Equal packet spans give the same actual affine ideal. -/
theorem actualIdeal_eq_of_span_eq
    {λ : Type*} [Fintype λ]
    (p : κ → Dual (K := K) (σ := σ))
    (q : λ → Dual (K := K) (σ := σ))
    (hspan : Submodule.span K (Set.range p) =
      Submodule.span K (Set.range q)) :
    actualIdeal p = actualIdeal q := by
  rw [← map_centreIdeal_eq_actualIdeal,
    ← map_centreIdeal_eq_actualIdeal]
  congr 1
  exact DualPacketRegularCentre.centreIdeal_eq_of_span_eq p q hspan

end

end DualPacketAffineLinearRealization
end Experimental
end PCRLean
