import Mathlib
import PCRLean.FinitePacketEvaluation
import PCRLean.Experimental.IntrinsicKernelIdealFunctoriality
import PCRLean.Experimental.SurjectiveFiniteDimensionalRegularCentre

/-!
# Experimental correctly oriented regular centre from a dual packet

Let `T` be a finite-dimensional tangent space and let a finite packet consist of
covectors in `Tᵛ`.  The candidate centre tangent space is their simultaneous
kernel.  Its actual linear ideal belongs to `SymmetricAlgebra K (Tᵛ)` and is
generated by the subspace spanned by the packet rows.

Equivalently, quotient the cotangent space by the packet span.  The kernel of
that quotient is precisely the row span, so the intrinsic kernel-ideal theorem
produces the correct actual centre.  Its quotient is the symmetric algebra of
the cotangent quotient and is regular.

This file corrects the tangent/cotangent orientation: the kernel of the tangent
evaluation map is a tangent subspace, not itself an ideal generator module in
the ambient cotangent symmetric algebra.  Lifting this first-order centre to a
regular centre in a nonlinear local ring and proving marked permissibility and
hereditary transport remain separate geometric obligations.
-/

namespace PCRLean
namespace Experimental
namespace DualPacketRegularCentre

noncomputable section

universe u v w

variable {K : Type u} [Field K]
variable {T : Type v} [AddCommGroup T] [Module K T]
variable {ι : Type w} [Fintype ι]

abbrev Cotangent := Module.Dual K T

open IntrinsicKernelIdealFunctoriality

/-- Cotangent row span of the packet. -/
def packetSpan (packet : ι → Cotangent (K := K) (T := T)) :
    Submodule K (Cotangent (K := K) (T := T)) :=
  Submodule.span K (Set.range packet)

/-- Canonical conormal quotient by the packet row span. -/
def conormalQuotient (packet : ι → Cotangent (K := K) (T := T)) :
    Cotangent (K := K) (T := T) →ₗ[K]
      (Cotangent (K := K) (T := T) ⧸ packetSpan packet) :=
  Submodule.mkQ (packetSpan packet)

/-- The conormal quotient has kernel exactly the packet row span. -/
theorem ker_conormalQuotient_eq_packetSpan
    (packet : ι → Cotangent (K := K) (T := T)) :
    LinearMap.ker (conormalQuotient packet) = packetSpan packet := by
  ext f
  simp [conormalQuotient]

/-- The canonical conormal quotient is surjective. -/
theorem conormalQuotient_surjective
    (packet : ι → Cotangent (K := K) (T := T)) :
    Function.Surjective (conormalQuotient packet) := by
  exact Submodule.mkQ_surjective (packetSpan packet)

/-- Actual linear centre ideal generated by the full packet row span. -/
def centreIdeal (packet : ι → Cotangent (K := K) (T := T)) :
    Ideal (SymmetricAlgebra K (Cotangent (K := K) (T := T))) :=
  Ideal.span (Set.range fun f : packetSpan packet =>
    SymmetricAlgebra.ι K (Cotangent (K := K) (T := T)) f.1)

/-- The row-span ideal is exactly the intrinsic kernel ideal of the conormal
quotient. -/
theorem centreIdeal_eq_kernelIdeal
    (packet : ι → Cotangent (K := K) (T := T)) :
    centreIdeal packet = kernelIdealOf (conormalQuotient packet) := by
  apply le_antisymm
  · rw [centreIdeal, Ideal.span_le]
    rintro z ⟨f, rfl⟩
    apply Ideal.subset_span
    refine ⟨⟨f.1, ?_⟩, rfl⟩
    rw [ker_conormalQuotient_eq_packetSpan]
    exact f.2
  · rw [kernelIdealOf, Ideal.span_le]
    rintro z ⟨f, rfl⟩
    apply Ideal.subset_span
    refine ⟨⟨f.1, ?_⟩, rfl⟩
    rw [← ker_conormalQuotient_eq_packetSpan]
    exact f.2

/-- Every original packet row is an actual degree-one centre equation. -/
theorem packetGenerator_mem
    (packet : ι → Cotangent (K := K) (T := T)) (i : ι) :
    SymmetricAlgebra.ι K (Cotangent (K := K) (T := T)) (packet i) ∈
      centreIdeal packet := by
  apply Ideal.subset_span
  refine ⟨⟨packet i, ?_⟩, rfl⟩
  exact Submodule.subset_span ⟨i, rfl⟩

/-- Simultaneous tangent kernel of the packet. -/
def commonTangentKernel
    (packet : ι → Cotangent (K := K) (T := T)) : Submodule K T :=
  LinearMap.ker (FinitePacketEvaluation.evalMap packet)

/-- Pointwise description of the common tangent kernel. -/
theorem mem_commonTangentKernel_iff
    (packet : ι → Cotangent (K := K) (T := T)) (x : T) :
    x ∈ commonTangentKernel packet ↔ ∀ i, packet i x = 0 := by
  simpa [commonTangentKernel, FinitePacketEvaluation.persistentKernel] using
    (FinitePacketEvaluation.mem_persistentKernel_iff packet x)

/-- The annihilator in `T` of a cotangent submodule. -/
def annihilator (S : Submodule K (Cotangent (K := K) (T := T))) :
    Submodule K T where
  carrier := {x | ∀ f ∈ S, f x = 0}
  zero_mem' := by simp
  add_mem' := by
    intro x y hx hy f hf
    simp [hx f hf, hy f hf]
  smul_mem' := by
    intro a x hx f hf
    simp [hx f hf]

/-- Vanishing on the packet rows is equivalent to vanishing on their entire
linear span. -/
theorem annihilates_packetSpan_iff
    (packet : ι → Cotangent (K := K) (T := T)) (x : T) :
    (∀ f ∈ packetSpan packet, f x = 0) ↔ ∀ i, packet i x = 0 := by
  constructor
  · intro h i
    exact h (packet i) (Submodule.subset_span ⟨i, rfl⟩)
  · intro h f hf
    induction hf using Submodule.span_induction with
    | mem g hg =>
        rcases hg with ⟨i, rfl⟩
        exact h i
    | zero => simp
    | add f g hf hg hfx hgx => simpa using congrArg₂ (· + ·) hfx hgx
    | smul a f hf hfx => simpa using congrArg (fun z : K => a * z) hfx

/-- The candidate centre tangent space is exactly the annihilator of the
cotangent row span defining the actual ideal. -/
theorem commonTangentKernel_eq_annihilator
    (packet : ι → Cotangent (K := K) (T := T)) :
    commonTangentKernel packet = annihilator (packetSpan packet) := by
  ext x
  rw [mem_commonTangentKernel_iff]
  exact (annihilates_packetSpan_iff packet x).symm

/-- Equal cotangent row spans define the same actual centre ideal. -/
theorem centreIdeal_eq_of_span_eq
    {κ : Type*} [Fintype κ]
    (p : ι → Cotangent (K := K) (T := T))
    (q : κ → Cotangent (K := K) (T := T))
    (hspan : packetSpan p = packetSpan q) :
    centreIdeal p = centreIdeal q := by
  unfold centreIdeal
  rw [hspan]

section FiniteDimensional

variable [FiniteDimensional K T]

/-- Exact quotient by the correctly oriented actual packet centre. -/
noncomputable def quotientEquiv
    (packet : ι → Cotangent (K := K) (T := T)) :
    (SymmetricAlgebra K (Cotangent (K := K) (T := T)) ⧸
        centreIdeal packet) ≃+*
      SymmetricAlgebra K
        (Cotangent (K := K) (T := T) ⧸ packetSpan packet) :=
  (Ideal.quotEquivOfEq (centreIdeal_eq_kernelIdeal packet)).trans
    (SurjectiveFiniteDimensionalRegularCentre.quotientEquiv
      (conormalQuotient packet) (conormalQuotient_surjective packet))

/-- The correctly oriented packet centre is proper. -/
theorem centreIdeal_ne_top
    (packet : ι → Cotangent (K := K) (T := T)) :
    centreIdeal packet ≠ ⊤ := by
  rw [centreIdeal_eq_kernelIdeal]
  exact SurjectiveFiniteDimensionalRegularCentre.centreIdeal_ne_top
    (conormalQuotient packet) (conormalQuotient_surjective packet)

/-- The correctly oriented packet centre is finitely generated. -/
theorem centreIdeal_fg
    (packet : ι → Cotangent (K := K) (T := T)) :
    (centreIdeal packet).FG := by
  rw [centreIdeal_eq_kernelIdeal]
  exact SurjectiveFiniteDimensionalRegularCentre.centreIdeal_fg
    (conormalQuotient packet) (conormalQuotient_surjective packet)

/-- The correctly oriented packet-centre quotient is regular. -/
theorem quotient_isRegularRing
    (packet : ι → Cotangent (K := K) (T := T)) :
    IsRegularRing
      (SymmetricAlgebra K (Cotangent (K := K) (T := T)) ⧸
        centreIdeal packet) := by
  rw [centreIdeal_eq_kernelIdeal]
  exact SurjectiveFiniteDimensionalRegularCentre.quotient_isRegularRing
    (conormalQuotient packet) (conormalQuotient_surjective packet)

end FiniteDimensional

end

end DualPacketRegularCentre
end Experimental
end PCRLean
