import PCRLean.Experimental.DualPacketRankZeroNoGo

#print axioms PCRLean.Experimental.DualPacketRankZeroNoGo.packetSpan_eq_bot_of_finrank_eq_zero
#print axioms PCRLean.Experimental.DualPacketRankZeroNoGo.packet_eq_zero_of_finrank_eq_zero
#print axioms PCRLean.Experimental.DualPacketRankZeroNoGo.actualIdeal_eq_bot_of_finrank_eq_zero
#print axioms PCRLean.Experimental.DualPacketRankZeroNoGo.actualRootPowerIdeal_eq_bot_of_finrank_eq_zero
#print axioms PCRLean.Experimental.DualPacketRankZeroNoGo.packetPowerIdeal_eq_bot_of_finrank_eq_zero
#print axioms PCRLean.Experimental.DualPacketRankZeroNoGo.centreIndex_isEmpty_of_finrank_eq_zero
#print axioms PCRLean.Experimental.DualPacketRankZeroNoGo.owner_eq_bot_of_rank_zero_root_realization
