import PCRLean.Experimental.DualPacketAffineLinearRealization

#print axioms PCRLean.Experimental.DualPacketAffineLinearRealization.direction_eq_sum_basisVector
#print axioms PCRLean.Experimental.DualPacketAffineLinearRealization.functional_eq_sum_coordinateFunctional
#print axioms PCRLean.Experimental.DualPacketAffineLinearRealization.functionalPolynomial_coordinateFunctional
#print axioms PCRLean.Experimental.DualPacketAffineLinearRealization.polyToSym_comp_symToPoly
#print axioms PCRLean.Experimental.DualPacketAffineLinearRealization.symToPoly_comp_polyToSym
#print axioms PCRLean.Experimental.DualPacketAffineLinearRealization.algebraEquiv
#print axioms PCRLean.Experimental.DualPacketAffineLinearRealization.functionalPolynomial_mem_actualIdeal_of_mem_span
#print axioms PCRLean.Experimental.DualPacketAffineLinearRealization.map_centreIdeal_eq_actualIdeal
#print axioms PCRLean.Experimental.DualPacketAffineLinearRealization.actualIdeal_eq_of_span_eq
