import Mathlib
import Mathlib.LinearAlgebra.SymmetricAlgebra.Basis
import PCRLean.Experimental.DualPacketAffineLinearRealization
import PCRLean.Experimental.DualPacketRegularCentre

/-!
# Experimental coordinate normalization of dual-packet centres

Choose a basis of the finite-dimensional packet row span and extend it to a
basis of the entire cotangent space.  The induced polynomial coordinates send
the correctly oriented row-span centre ideal exactly to the standard coordinate
ideal generated by the basis vectors of the row span.

Composing with the explicit cotangent-symmetric/affine-polynomial equivalence
normalizes the actual packet ideal in `K[X_σ]` to a coordinate centre.  This is
the linear coordinate-change theorem required to construct standard blowup
charts for every finite linear packet centre.
-/

namespace PCRLean
namespace Experimental
namespace DualPacketCoordinateNormalization

noncomputable section

universe u v w

variable {K : Type u} [Field K]
variable {σ : Type v} [Fintype σ] [DecidableEq σ]
variable {κ : Type w} [Fintype κ]

abbrev Direction := σ → K
abbrev Dual := Module.Dual K (Direction (K := K) (σ := σ))

open DualPacketRegularCentre
open DualPacketAffineLinearRealization

/-- Finite index type of a basis of the packet row span. -/
abbrev CentreIndex
    (packet : κ → Dual (K := K) (σ := σ)) :=
  Fin (FiniteDimensional.finrank K (packetSpan packet))

/-- A basis of the packet row span. -/
noncomputable def centreBasis
    (packet : κ → Dual (K := K) (σ := σ)) :
    Basis (CentreIndex packet) K (packetSpan packet) :=
  FiniteDimensional.finBasis K (packetSpan packet)

/-- The row-span basis viewed as covectors in the whole cotangent space. -/
def centreCovector
    (packet : κ → Dual (K := K) (σ := σ))
    (i : CentreIndex packet) : Dual (K := K) (σ := σ) :=
  (centreBasis packet i).1

/-- The row-span basis remains linearly independent in the ambient cotangent
space. -/
theorem centreCovector_linearIndependent
    (packet : κ → Dual (K := K) (σ := σ)) :
    LinearIndependent K (centreCovector packet) := by
  exact (centreBasis packet).linearIndependent.map'
    (Submodule.subtype (packetSpan packet))
    (Submodule.injective_subtype (packetSpan packet))

/-- Index type added when the centre basis is extended to a full cotangent
basis. -/
abbrev PassiveIndex
    (packet : κ → Dual (K := K) (σ := σ)) :=
  Basis.extendIndex K (centreCovector packet)

/-- Full cotangent basis extending the row-span basis. -/
noncomputable def fullBasis
    (packet : κ → Dual (K := K) (σ := σ)) :
    Basis (CentreIndex packet ⊕ PassiveIndex packet) K
      (Dual (K := K) (σ := σ)) :=
  Basis.extend (centreCovector_linearIndependent packet)

/-- The full basis restricts to the chosen row-span basis on its left summand. -/
@[simp] theorem fullBasis_inl
    (packet : κ → Dual (K := K) (σ := σ))
    (i : CentreIndex packet) :
    fullBasis packet (Sum.inl i) = centreCovector packet i := by
  simp [fullBasis]

/-- Symmetric algebra coordinates supplied by the extended cotangent basis. -/
noncomputable def symmetricCoordinateEquiv
    (packet : κ → Dual (K := K) (σ := σ)) :
    SymmetricAlgebra K (Dual (K := K) (σ := σ)) ≃ₐ[K]
      MvPolynomial (CentreIndex packet ⊕ PassiveIndex packet) K :=
  SymmetricAlgebra.equivMvPolynomial (fullBasis packet)

/-- Standard coordinate ideal generated by the centre-basis variables. -/
def coordinateCentreIdeal
    (packet : κ → Dual (K := K) (σ := σ)) :
    Ideal (MvPolynomial (CentreIndex packet ⊕ PassiveIndex packet) K) :=
  Ideal.span (Set.range fun i : CentreIndex packet =>
    MvPolynomial.X (Sum.inl i : CentreIndex packet ⊕ PassiveIndex packet))

/-- The abstract row-span centre equals the ideal generated by the row-span
basis vectors. -/
theorem centreIdeal_eq_basisIdeal
    (packet : κ → Dual (K := K) (σ := σ)) :
    centreIdeal packet =
      Ideal.span (Set.range fun i : CentreIndex packet =>
        SymmetricAlgebra.ι K (Dual (K := K) (σ := σ))
          (centreCovector packet i)) := by
  apply le_antisymm
  · rw [centreIdeal, Ideal.span_le]
    rintro z ⟨f, rfl⟩
    have hrepr :
        (∑ i : CentreIndex packet,
          ((centreBasis packet).repr f) i • centreBasis packet i) = f :=
      (centreBasis packet).sum_repr f
    have hsum :
        SymmetricAlgebra.ι K (Dual (K := K) (σ := σ)) f =
          ∑ i : CentreIndex packet,
            ((centreBasis packet).repr f) i •
              SymmetricAlgebra.ι K (Dual (K := K) (σ := σ))
                (centreCovector packet i) := by
      rw [← hrepr]
      simp [centreCovector]
    rw [hsum]
    exact (Ideal.span (Set.range fun i : CentreIndex packet =>
      SymmetricAlgebra.ι K (Dual (K := K) (σ := σ))
        (centreCovector packet i))).sum_mem fun i hi =>
      (Ideal.span (Set.range fun i : CentreIndex packet =>
        SymmetricAlgebra.ι K (Dual (K := K) (σ := σ))
          (centreCovector packet i))).smul_mem _
        (Ideal.subset_span ⟨i, rfl⟩)
  · rw [Ideal.span_le]
    rintro z ⟨i, rfl⟩
    apply Ideal.subset_span
    exact ⟨centreBasis packet i, rfl⟩

/-- The extended basis sends the abstract row-span centre exactly to a standard
coordinate centre. -/
theorem map_centreIdeal_eq_coordinateCentreIdeal
    (packet : κ → Dual (K := K) (σ := σ)) :
    Ideal.map (symmetricCoordinateEquiv packet).toAlgHom
        (centreIdeal packet) = coordinateCentreIdeal packet := by
  rw [centreIdeal_eq_basisIdeal]
  apply le_antisymm
  · rw [Ideal.map_le_iff_le_comap, Ideal.span_le]
    rintro z ⟨i, rfl⟩
    rw [Ideal.mem_comap]
    simp [symmetricCoordinateEquiv, coordinateCentreIdeal]
  · rw [coordinateCentreIdeal, Ideal.span_le]
    rintro z ⟨i, rfl⟩
    rw [← fullBasis_inl packet i]
    have hgen :
        SymmetricAlgebra.ι K (Dual (K := K) (σ := σ))
            (fullBasis packet (Sum.inl i)) ∈
          Ideal.span (Set.range fun j : CentreIndex packet =>
            SymmetricAlgebra.ι K (Dual (K := K) (σ := σ))
              (centreCovector packet j)) := by
      rw [fullBasis_inl]
      exact Ideal.subset_span ⟨i, rfl⟩
    exact Ideal.mem_map_of_mem
      (symmetricCoordinateEquiv packet).toAlgHom hgen

/-- Actual affine coordinates which normalize the packet centre. -/
noncomputable def actualCoordinateEquiv
    (packet : κ → Dual (K := K) (σ := σ)) :
    MvPolynomial σ K ≃ₐ[K]
      MvPolynomial (CentreIndex packet ⊕ PassiveIndex packet) K :=
  (algebraEquiv (K := K) (σ := σ)).symm.trans
    (symmetricCoordinateEquiv packet)

/-- The actual affine packet ideal maps exactly to the standard coordinate
centre ideal. -/
theorem map_actualIdeal_eq_coordinateCentreIdeal
    (packet : κ → Dual (K := K) (σ := σ)) :
    Ideal.map (actualCoordinateEquiv packet).toAlgHom
        (actualIdeal packet) = coordinateCentreIdeal packet := by
  rw [← map_centreIdeal_eq_actualIdeal]
  rw [Ideal.map_map]
  have hcomp :
      (actualCoordinateEquiv packet).toAlgHom.comp
          (symToPoly (K := K) (σ := σ)) =
        (symmetricCoordinateEquiv packet).toAlgHom := by
    ext f
    simp [actualCoordinateEquiv, algebraEquiv]
  rw [hcomp]
  exact map_centreIdeal_eq_coordinateCentreIdeal packet

end

end DualPacketCoordinateNormalization
end Experimental
end PCRLean
