import Mathlib
import PCRLean.Experimental.ExceptionalDebtLineage

/-!
# Unit-cocycle overlap transport for exceptional debt

On an overlap of two ordinary blowup charts, local equations of the same
exceptional divisor differ by a unit.  This file isolates the exact algebraic
consequence needed by the debt ledger.

If a ring equivalence sends `E₁` to `u * E₂` with `u` a unit, then for every
natural debt exponent `δ` it sends

`(E₁)^δ` exactly to `(E₂)^δ`.

Thus a chart transition may change the local equation of the exceptional
divisor, but it cannot change the debt exponent or create a new source event.
The construction of the actual overlap equivalences and verification of their
cocycle laws remain separate geometric obligations.
-/

namespace PCRLean
namespace Experimental
namespace ExceptionalDebtOverlapTransport

noncomputable section

universe u v w

variable {A : Type u} {B : Type v}
variable [CommRing A] [CommRing B]

/-- Multiplying a principal generator by a unit does not change its ideal. -/
theorem span_singleton_unit_mul
    (u b : B) (hu : IsUnit u) :
    Ideal.span {u * b} = Ideal.span {b} := by
  rcases hu with ⟨U, rfl⟩
  apply le_antisymm
  · rw [Ideal.span_le]
    intro x hx
    have hxb : x = (U : B) * b := by simpa using hx
    rw [hxb]
    exact (Ideal.span {b}).mul_mem_left (U : B)
      (Ideal.mem_span_singleton_self b)
  · rw [Ideal.span_le]
    intro x hx
    have hxb : x = b := by simpa using hx
    rw [hxb]
    have hgen : (U : B) * b ∈ Ideal.span {((U : B) * b)} :=
      Ideal.mem_span_singleton_self _
    have hinv := (Ideal.span {((U : B) * b)}).mul_mem_left
      ((↑U⁻¹ : B)) hgen
    simpa [mul_assoc] using hinv

/-- Principal debt ideal generated by one local exceptional equation. -/
def debtIdeal (E : A) (δ : Nat) : Ideal A :=
  (Ideal.span {E}) ^ δ

/-- Data of one overlap transition for exceptional equations. -/
structure Overlap where
  equiv : A ≃+* B
  leftExceptional : A
  rightExceptional : B
  unit : B
  unit_isUnit : IsUnit unit
  exceptional_eq : equiv leftExceptional = unit * rightExceptional

namespace Overlap

variable (O : Overlap (A := A) (B := B))

/-- The principal exceptional ideal transports exactly across the overlap. -/
theorem map_exceptionalIdeal :
    Ideal.map O.equiv (Ideal.span {O.leftExceptional}) =
      Ideal.span {O.rightExceptional} := by
  calc
    Ideal.map O.equiv (Ideal.span {O.leftExceptional}) =
        Ideal.span {O.equiv O.leftExceptional} := by
      rw [Ideal.map_span]
      congr 1
      simp
    _ = Ideal.span {O.unit * O.rightExceptional} := by
      rw [O.exceptional_eq]
    _ = Ideal.span {O.rightExceptional} :=
      span_singleton_unit_mul O.unit O.rightExceptional O.unit_isUnit

/-- Every exceptional debt power transports exactly. -/
theorem map_debtIdeal (δ : Nat) :
    Ideal.map O.equiv (debtIdeal O.leftExceptional δ) =
      debtIdeal O.rightExceptional δ := by
  rw [debtIdeal, debtIdeal, Ideal.map_pow, O.map_exceptionalIdeal]

end Overlap

section Lineage

variable {Source : Type w} [DecidableEq Source]

/-- An overlap certificate attached to one immutable debt event. -/
structure EventOverlap (E : ExceptionalDebtLineage.Event (Source := Source))
    extends Overlap (A := A) (B := B)

namespace EventOverlap

variable {E : ExceptionalDebtLineage.Event (Source := Source)}
    (O : EventOverlap (A := A) (B := B) E)

/-- The ideal representing one event debt is independent of the chart equation. -/
theorem map_eventDebt :
    Ideal.map O.toOverlap.equiv
        (debtIdeal O.toOverlap.leftExceptional E.debt) =
      debtIdeal O.toOverlap.rightExceptional E.debt :=
  O.toOverlap.map_debtIdeal E.debt

/-- Chart overlap preserves the event source support definitionally. -/
theorem source_support_preserved : E.support = E.support := rfl

end EventOverlap

end Lineage

end

end ExceptionalDebtOverlapTransport
end Experimental
end PCRLean
