import PCRLean.Experimental.FaithfullyFlatCotangentProjectiveDescent

#print axioms PCRLean.Experimental.FaithfullyFlatCotangentProjectiveDescent.cotangent_flat_of_tensorProduct
#print axioms PCRLean.Experimental.FaithfullyFlatCotangentProjectiveDescent.cotangent_finitePresentation_of_tensorProduct
#print axioms PCRLean.Experimental.FaithfullyFlatCotangentProjectiveDescent.cotangent_projective_of_tensorProduct
