import PCRLean.Experimental.FaithfullyFlatConormalDescentKernelIndex

#print axioms PCRLean.Experimental.FaithfullyFlatCotangentFinitenessDescent.cotangent_finite_of_tensorProduct
#print axioms PCRLean.Experimental.FaithfullyFlatCotangentFinitenessDescent.cotangent_finite_of_baseChange_equiv
#print axioms PCRLean.Experimental.FaithfullyFlatGraphCentreDescent.ideal_ne_top_of_graphModel
#print axioms PCRLean.Experimental.FaithfullyFlatGraphCentreDescent.ideal_fg_of_graphModel
#print axioms PCRLean.Experimental.FaithfullyFlatGraphCentreDescent.quotient_isReduced_of_graphModel
#print axioms PCRLean.Experimental.PolynomialGraphCentreCotangentBasis.cotangentEquivRows
#print axioms PCRLean.Experimental.ReducedRegularGraphCentreCertificate.certificate
#print axioms PCRLean.Experimental.FaithfullyFlatConormalDescentKernelIndex.loaded
