import PCRLean.Experimental.FiniteReesFrobeniusCompression

#print axioms PCRLean.Experimental.FiniteReesFrobeniusCompression.Presentation.rootTerm_isIntegral
#print axioms PCRLean.Experimental.FiniteReesFrobeniusCompression.Presentation.rootAdjoin_isIntegral
#print axioms PCRLean.Experimental.FiniteReesFrobeniusCompression.Presentation.rootSet_finite
#print axioms PCRLean.Experimental.FiniteReesFrobeniusCompression.Presentation.rootAdjoin_moduleFinite
#print axioms PCRLean.Experimental.FiniteReesFrobeniusCompression.Presentation.isIntegral_rootAdjoin_iff
#print axioms PCRLean.Experimental.FiniteReesFrobeniusCompression.Presentation.sourceTerm_mem_sourceAlgebra
#print axioms PCRLean.Experimental.FiniteReesFrobeniusCompression.Presentation.rootAdjoin_over_sourceAlgebra_moduleFinite
#print axioms PCRLean.Experimental.FiniteReesFrobeniusCompression.Presentation.isIntegral_sourceAlgebra_iff_rootAdjoin
