import PCRLean.Experimental.FiniteHasseIntegralCompression

#print axioms PCRLean.Experimental.FiniteHasseIntegralCompression.Packet.rootOperatorSet_finite
#print axioms PCRLean.Experimental.FiniteHasseIntegralCompression.Packet.isIntegral_of_pow_mem
#print axioms PCRLean.Experimental.FiniteHasseIntegralCompression.Packet.rootOperator_isIntegral
#print axioms PCRLean.Experimental.FiniteHasseIntegralCompression.Packet.rootOperatorAdjoin_isIntegral
#print axioms PCRLean.Experimental.FiniteHasseIntegralCompression.Packet.rootOperatorAdjoin_moduleFinite
#print axioms PCRLean.Experimental.FiniteHasseIntegralCompression.Packet.isIntegral_rootOperatorAdjoin_iff
#print axioms PCRLean.Experimental.FiniteHasseIntegralCompression.Packet.sourceOperator_mem
#print axioms PCRLean.Experimental.FiniteHasseIntegralCompression.Packet.rootOperatorAdjoin_over_source_moduleFinite
#print axioms PCRLean.Experimental.FiniteHasseIntegralCompression.Packet.isIntegral_sourceOperator_iff_rootOperatorAdjoin
