import Mathlib

/-!
# Finite Hasse-compatible integral compression

The differential closure of a Frobenius root is controlled by a finite Hasse
packet.  Abstractly, let `root_j^p = source_j`.  For every finite operator index
`d`, suppose a root-level operator and a source-level operator satisfy

`(rootOp d root_j)^p = sourceOp d source_j`.

If the current graded algebra contains every source-level value, then every
root-level value is integral over it.  Adjoining the entire finite root-operator
packet is a finite integral extension and does not change the ambient integral
elements.

For actual Hasse operators the intended compatibility is

`(∂^[β] g)^p = ∂^[pβ] (g^p)`.

This file proves the finite integral compiler from that compatibility.  The
operator identity itself, its weight bookkeeping, and geometric transform
compatibility remain separate local-algebra obligations.
-/

namespace PCRLean
namespace Experimental
namespace FiniteHasseIntegralCompression

noncomputable section

universe u v w x

variable {R : Type u} [CommRing R]
variable {B : Type v} [CommRing B] [Algebra R B]
variable {κ : Type w} [Fintype κ]
variable {δ : Type x} [Fintype δ]
variable (p : Nat) [Fact p.Prime]

/-- A finite Frobenius presentation equipped with compatible finite root- and
source-level operator packets. -/
structure Packet where
  root : κ → B
  source : κ → B
  root_pow : ∀ j, (root j) ^ p = source j
  rootOp : δ → B → B
  sourceOp : δ → B → B
  operator_pow : ∀ d j,
    (rootOp d (root j)) ^ p = sourceOp d (source j)

namespace Packet

variable (P : Packet (B := B) (κ := κ) (δ := δ) p)

/-- Finite set of all root-level operator values. -/
def rootOperatorSet : Set B :=
  Set.range fun z : δ × κ => P.rootOp z.1 (P.root z.2)

/-- The root-operator set is finite. -/
theorem rootOperatorSet_finite : P.rootOperatorSet.Finite :=
  Set.finite_range _

/-- Positive-power membership gives integrality in an arbitrary ambient
commutative algebra. -/
theorem isIntegral_of_pow_mem
    (S : Subalgebra R B) (x : B) (hx : x ^ p ∈ S) :
    IsIntegral S x := by
  have hpow : IsIntegral S (x ^ p) := by
    simpa using
      (isIntegral_algebraMap (R := S) (A := B) (⟨x ^ p, hx⟩ : S))
  exact hpow.of_pow Fact.out.pos

/-- Every root-level operator value is integral if the corresponding source
value belongs to the current algebra. -/
theorem rootOperator_isIntegral
    (S : Subalgebra R B)
    (hsource : ∀ d j, P.sourceOp d (P.source j) ∈ S)
    (d : δ) (j : κ) :
    IsIntegral S (P.rootOp d (P.root j)) := by
  apply P.isIntegral_of_pow_mem p S
  rw [P.operator_pow d j]
  exact hsource d j

/-- Adjoining the full finite root-operator packet is integral. -/
theorem rootOperatorAdjoin_isIntegral
    (S : Subalgebra R B)
    (hsource : ∀ d j, P.sourceOp d (P.source j) ∈ S) :
    Algebra.IsIntegral S (Algebra.adjoin S P.rootOperatorSet) := by
  apply Algebra.IsIntegral.adjoin
  intro x hx
  rcases hx with ⟨⟨d, j⟩, rfl⟩
  exact P.rootOperator_isIntegral p S hsource d j

/-- The full finite Hasse-root packet gives a finite module extension. -/
theorem rootOperatorAdjoin_moduleFinite
    (S : Subalgebra R B)
    (hsource : ∀ d j, P.sourceOp d (P.source j) ∈ S) :
    Module.Finite S (Algebra.adjoin S P.rootOperatorSet) := by
  exact Algebra.finite_adjoin_of_finite_of_isIntegral
    P.rootOperatorSet_finite
    (fun x hx => by
      rcases hx with ⟨⟨d, j⟩, rfl⟩
      exact P.rootOperator_isIntegral p S hsource d j)

/-- Finite Hasse-compatible root adjoining does not change ambient integral
elements. -/
theorem isIntegral_rootOperatorAdjoin_iff
    (S : Subalgebra R B)
    (hsource : ∀ d j, P.sourceOp d (P.source j) ∈ S)
    (y : B) :
    IsIntegral S y ↔ IsIntegral (Algebra.adjoin S P.rootOperatorSet) y := by
  let T := Algebra.adjoin S P.rootOperatorSet
  letI : Algebra.IsIntegral S T :=
    P.rootOperatorAdjoin_isIntegral p S hsource
  constructor
  · intro hy
    exact hy.tower_top
  · intro hy
    exact isIntegral_trans y hy

/-- The finite source-operator algebra. -/
def sourceOperatorAlgebra : Subalgebra R B :=
  Algebra.adjoin R
    (Set.range fun z : δ × κ => P.sourceOp z.1 (P.source z.2))

/-- Every source-operator value belongs to the source-operator algebra. -/
theorem sourceOperator_mem (d : δ) (j : κ) :
    P.sourceOp d (P.source j) ∈ P.sourceOperatorAlgebra :=
  Algebra.subset_adjoin ⟨(d, j), rfl⟩

/-- The root-operator algebra is finite over the algebra generated by the
source-operator packet. -/
theorem rootOperatorAdjoin_over_source_moduleFinite :
    Module.Finite P.sourceOperatorAlgebra
      (Algebra.adjoin P.sourceOperatorAlgebra P.rootOperatorSet) := by
  exact P.rootOperatorAdjoin_moduleFinite p P.sourceOperatorAlgebra
    P.sourceOperator_mem

/-- Source-operator and root-operator algebras have the same ambient integral
elements. -/
theorem isIntegral_sourceOperator_iff_rootOperatorAdjoin
    (y : B) :
    IsIntegral P.sourceOperatorAlgebra y ↔
      IsIntegral
        (Algebra.adjoin P.sourceOperatorAlgebra P.rootOperatorSet) y :=
  P.isIntegral_rootOperatorAdjoin_iff p P.sourceOperatorAlgebra
    P.sourceOperator_mem y

end Packet

end

end FiniteHasseIntegralCompression
end Experimental
end PCRLean
