import Mathlib
import PCRLean.Experimental.FinitePacketAutomaticRegularCentre

/-!
# Experimental antitonicity of finite-packet centres

The submodule spanned by a finite functional packet is the information carried
by that packet.  Enlarging the packet span shrinks the simultaneous kernel.
Since the actual centre ideal is generated by that kernel, packet-span growth
shrinks the centre ideal as well.  Thus the finite-packet centre construction
is order reversing.

This statement permits different finite index types and therefore proves full
presentation independence, including redundant generators and changes in the
number of rows.  It is a linear theorem and does not supply geometric marked
permissibility or nonlinear transform compatibility.
-/

namespace PCRLean
namespace Experimental
namespace FinitePacketCentreAntitone

noncomputable section

universe u v w x

variable {K : Type u} [Field K]
variable {V : Type v} [AddCommGroup V] [Module K V]
variable {ι : Type w} {κ : Type x}
variable [Fintype ι] [Fintype κ]

abbrev Dual := Module.Dual K V

open FinitePacketAutomaticRegularCentre

/-- Packet-span inclusion reverses simultaneous-kernel inclusion. -/
theorem packetKer_antitone
    (p : ι → Dual (K := K) (V := V))
    (q : κ → Dual (K := K) (V := V))
    (hspan : Submodule.span K (Set.range p) ≤
      Submodule.span K (Set.range q)) :
    LinearMap.ker (packetMap q) ≤ LinearMap.ker (packetMap p) := by
  intro x hx
  rw [mem_packetKer_iff] at hx ⊢
  intro i
  have hpi : p i ∈ Submodule.span K (Set.range p) :=
    Submodule.subset_span ⟨i, rfl⟩
  have hpiq : p i ∈ Submodule.span K (Set.range q) := hspan hpi
  induction hpiq using Submodule.span_induction with
  | mem f hf =>
      rcases hf with ⟨j, rfl⟩
      exact hx j
  | zero => simp
  | add f g hf hg hfx hgx => simpa using congrArg₂ (· + ·) hfx hgx
  | smul a f hf hfx => simpa using congrArg (fun z : K => a * z) hfx

/-- Packet-span inclusion reverses actual-centre-ideal inclusion. -/
theorem centreIdeal_antitone
    (p : ι → Dual (K := K) (V := V))
    (q : κ → Dual (K := K) (V := V))
    (hspan : Submodule.span K (Set.range p) ≤
      Submodule.span K (Set.range q)) :
    centreIdeal q ≤ centreIdeal p := by
  unfold centreIdeal ArbitraryFiniteLinearPacketRegularCentre.centreIdeal
  exact IntrinsicKernelIdealMonotonicity.kernelIdealOf_mono
    (packetKer_antitone p q hspan)

/-- Packets with the same span define the same actual centre, even when their
finite index types differ. -/
theorem centreIdeal_eq_of_span_eq
    (p : ι → Dual (K := K) (V := V))
    (q : κ → Dual (K := K) (V := V))
    (hspan : Submodule.span K (Set.range p) =
      Submodule.span K (Set.range q)) :
    centreIdeal p = centreIdeal q := by
  apply le_antisymm
  · exact centreIdeal_antitone q p hspan.symm.le
  · exact centreIdeal_antitone p q hspan.le

/-- Adding rows to a packet cannot enlarge its intrinsic centre ideal. -/
theorem centreIdeal_le_of_each_old_row_in_new_span
    (p : ι → Dual (K := K) (V := V))
    (q : κ → Dual (K := K) (V := V))
    (hrows : ∀ i, p i ∈ Submodule.span K (Set.range q)) :
    centreIdeal q ≤ centreIdeal p := by
  apply centreIdeal_antitone p q
  rw [Submodule.span_le]
  rintro f ⟨i, rfl⟩
  exact hrows i

end

end FinitePacketCentreAntitone
end Experimental
end PCRLean
