import Mathlib
import PCRLean.MarkedIdeal

/-!
# Experimental finite hybrid marked synthesis

A prepared marked equation may split into finitely many components: pure
Frobenius roots, ordinary/Hasse defects, owner contributions, and boundary
corrections.  If every term is controlled at the same mark by its named actual
ideal component, then the finite sum is controlled by the join of all those
components.

This file turns a term-to-component decomposition into marked permissibility.
It generalizes the two-term hybrid mechanism behind `y^p-x^(p+1)`.
Regularity, strictness, singular-locus containment, owner compatibility, and
hereditary transport remain independent gates.
-/

namespace PCRLean
namespace Experimental
namespace FiniteHybridMarkedSynthesis

noncomputable section

universe u v

variable {R : Type u} [CommRing R]
variable {ι : Type v} [Fintype ι] [DecidableEq ι]

/-- Actual hybrid ideal generated by a selected finite family of components. -/
def hybridCentre (component : ι → Ideal R) (selected : Finset ι) : Ideal R :=
  selected.sup component

/-- Every selected component ideal lies below the finite hybrid join. -/
theorem component_le_hybridCentre
    (component : ι → Ideal R) (selected : Finset ι)
    {i : ι} (hi : i ∈ selected) :
    component i ≤ hybridCentre component selected := by
  exact Finset.le_sup hi

/-- The same inclusion persists after taking a fixed marked power. -/
theorem component_pow_le_hybrid_pow
    (component : ι → Ideal R) (selected : Finset ι)
    {i : ι} (hi : i ∈ selected) (m : Nat) :
    component i ^ m ≤ (hybridCentre component selected) ^ m := by
  gcongr
  exact component_le_hybridCentre component selected hi

/-- Finite term synthesis at one common mark. -/
theorem sum_mem_hybrid_pow
    (component : ι → Ideal R)
    (term : ι → R)
    (selected : Finset ι)
    (m : Nat)
    (hterm : ∀ i ∈ selected, term i ∈ component i ^ m) :
    (∑ i ∈ selected, term i) ∈
      (hybridCentre component selected) ^ m := by
  exact ((hybridCentre component selected) ^ m).sum_mem
    (fun i hi => component_pow_le_hybrid_pow
      component selected hi m (hterm i hi))

/-- A finite decomposition certificate for one marked equation. -/
structure EquationDecomposition
    (component : ι → Ideal R) (f : R) (m : Nat) where
  selected : Finset ι
  term : ι → R
  equation_eq : f = ∑ i ∈ selected, term i
  term_controlled : ∀ i ∈ selected, term i ∈ component i ^ m

namespace EquationDecomposition

variable {component : ι → Ideal R} {f : R} {m : Nat}

/-- The decomposed equation lies in the marked power of the finite hybrid. -/
theorem equation_mem_hybrid_pow
    (D : EquationDecomposition component f m) :
    f ∈ (hybridCentre component D.selected) ^ m := by
  rw [D.equation_eq]
  exact sum_mem_hybrid_pow component D.term D.selected m D.term_controlled

/-- A principal marked packet compiled from the decomposition is permissible
for the finite hybrid centre. -/
theorem principalPacket_permissible
    (D : EquationDecomposition component f m)
    (hm : 0 < m) :
    MarkedIdeal.Permissible
      (R := R) ⟨Ideal.span {f}, m, hm⟩
      (hybridCentre component D.selected) := by
  exact MarkedIdeal.permissible_span_singleton hm D.equation_mem_hybrid_pow

end EquationDecomposition

/-- Owner-ideal form: if each selected owner ideal is controlled by its own
component at the same mark, their finite join is controlled by the hybrid
centre. -/
theorem ownerJoin_le_hybrid_pow
    (ownerIdeal component : ι → Ideal R)
    (selected : Finset ι)
    (m : Nat)
    (howner : ∀ i ∈ selected, ownerIdeal i ≤ component i ^ m) :
    selected.sup ownerIdeal ≤ (hybridCentre component selected) ^ m := by
  apply Finset.sup_le
  intro i hi
  exact (howner i hi).trans
    (component_pow_le_hybrid_pow component selected hi m)

/-- The finite join of selected owners is marked-permissible for the hybrid
centre. -/
theorem ownerJoin_permissible
    (ownerIdeal component : ι → Ideal R)
    (selected : Finset ι)
    (m : Nat) (hm : 0 < m)
    (howner : ∀ i ∈ selected, ownerIdeal i ≤ component i ^ m) :
    MarkedIdeal.Permissible
      (R := R)
      ⟨selected.sup ownerIdeal, m, hm⟩
      (hybridCentre component selected) :=
  ownerJoin_le_hybrid_pow ownerIdeal component selected m howner

end

end FiniteHybridMarkedSynthesis
end Experimental
end PCRLean
