import PCRLean.Experimental.FittingAugmentedMinorConsistency

#print axioms PCRLean.Experimental.FittingAugmentedMinorConsistency.graph_eq_selectedSolution
#print axioms PCRLean.Experimental.FittingAugmentedMinorConsistency.AugmentedMinorsVanish.fullEquation
#print axioms PCRLean.Experimental.FittingAugmentedMinorConsistency.AugmentedMinorsVanish.toConsistent
#print axioms PCRLean.Experimental.FittingAugmentedMinorConsistency.AugmentedMinorsVanish.toGraphCompatible
#print axioms PCRLean.Experimental.FittingAugmentedMinorConsistency.AugmentedMinorsVanish.globalGraph
#print axioms PCRLean.Experimental.FittingAugmentedMinorConsistency.AugmentedMinorsVanish.globalGraph_localizes
#print axioms PCRLean.Experimental.FittingAugmentedMinorConsistency.AugmentedMinorsVanish.localEquationIdeal_is_globalCentreBaseChange
