import PCRLean.Experimental.FittingGraphRestrictionCompatibility

#print axioms PCRLean.Experimental.FittingGraphRestrictionCompatibility.overlapOpen_eq_basicOpen_mul
#print axioms PCRLean.Experimental.FittingGraphRestrictionCompatibility.restrictionLeft_algebraMap
#print axioms PCRLean.Experimental.FittingGraphRestrictionCompatibility.overlapSectionEquiv_comp_leftMap
#print axioms PCRLean.Experimental.FittingGraphRestrictionCompatibility.overlapSectionEquiv_comp_rightMap
#print axioms PCRLean.Experimental.FittingGraphRestrictionCompatibility.FittingGraphCentreOverlap.Compatible.toCompatibleSectionData
#print axioms PCRLean.Experimental.FittingGraphRestrictionCompatibility.FittingGraphCentreOverlap.Compatible.globalizationCertificate
#print axioms PCRLean.Experimental.FittingGraphRestrictionCompatibility.FittingGraphCentreOverlap.Compatible.globalGraph_localizes
#print axioms PCRLean.Experimental.FittingGraphRestrictionCompatibility.FittingGraphCentreOverlap.Compatible.local_centre_is_global_baseChange
