import PCRLean.Experimental.FittingLinearSystemRowCompatibility

#print axioms PCRLean.Experimental.FittingLinearSystemRowCompatibility.Compatible.leftSolution_solves_left
#print axioms PCRLean.Experimental.FittingLinearSystemRowCompatibility.Compatible.leftSolution_solves_right
#print axioms PCRLean.Experimental.FittingLinearSystemRowCompatibility.Compatible.rightInverse_mul_rightMatrix
#print axioms PCRLean.Experimental.FittingLinearSystemRowCompatibility.Compatible.rightMatrix_mulVec_injective
#print axioms PCRLean.Experimental.FittingLinearSystemRowCompatibility.Compatible.solution_eq
#print axioms PCRLean.Experimental.FittingLinearSystemRowCompatibility.Compatible.graph_eq
#print axioms PCRLean.Experimental.FittingLinearSystemRowCompatibility.Compatible.toGraphCompatible
#print axioms PCRLean.Experimental.FittingLinearSystemRowCompatibility.Compatible.overlapIdeal_eq
#print axioms PCRLean.Experimental.FittingLinearSystemRowCompatibility.Compatible.globalGraph_localizes
#print axioms PCRLean.Experimental.FittingLinearSystemRowCompatibility.Compatible.localEquationIdeal_is_globalCentreBaseChange
