import Mathlib
import PCRLean.ActualIdealGluing
import PCRLean.Experimental.FittingGraphCentreOverlap
import PCRLean.Experimental.InvertibleMatrixGeneratorGauge

/-!
# Gauge-valued Fitting overlap descent for centre ideals

The equality-valued graph overlap condition is too restrictive for a general
regular immersion: local conormal frames may differ by an invertible matrix.
This module replaces componentwise equality by `GL_r` gauge data.

Each determinant chart carries a finite equation vector.  After mapping two
vectors to the canonical double localization, assume the first is an
invertible-matrix transform of the second.  Then their generated actual ideals
are equal on the overlap.

This is the correct pairwise descent condition for a possibly nontrivial
conormal bundle.  The module does not yet construct the global coherent ideal
sheaf from the gauge atlas; that is the remaining ideal-sheaf effectivity
bridge.
-/

namespace PCRLean
namespace Experimental
namespace FittingGaugeCentreOverlap

noncomputable section

universe u v w

variable {R : Type u} [CommRing R] [IsDomain R]
variable [IsNoetherianRing R] [IsRegularRing R]
variable {Chart : Type v} [Fintype Chart]
variable {ι : Type w} [Fintype ι] [DecidableEq ι]

open FittingGraphCentreAtlas
open FittingGraphCentreOverlap

variable {A : FittingMinorAtlas.Atlas (R := R) (Chart := Chart)}

/-- A finite local equation frame on every determinant chart. -/
structure Data where
  equation : ∀ c : Chart, ι → ChartRing A c

namespace Data

variable (D : Data (ι := ι) A)

/-- Actual ideal generated by one local equation frame. -/
def localIdeal (c : Chart) : Ideal (ChartRing A c) :=
  ActualIdealGluing.generatedIdeal (D.equation c)

/-- Equation vector from the left chart, mapped to the overlap. -/
def leftEquation (c d : Chart) :
    ι → OverlapRing (A := A) c d :=
  fun i => leftMap (A := A) c d (D.equation c i)

/-- Equation vector from the right chart, mapped to the overlap. -/
def rightEquation (c d : Chart) :
    ι → OverlapRing (A := A) c d :=
  fun i => rightMap (A := A) c d (D.equation d i)

end Data

/-- Mapping a finitely generated ideal maps each named generator. -/
theorem map_generatedIdeal
    {S T : Type*} [CommRing S] [CommRing T]
    (f : S →+* T) (g : ι → S) :
    Ideal.map f (ActualIdealGluing.generatedIdeal g) =
      ActualIdealGluing.generatedIdeal (fun i => f (g i)) := by
  apply le_antisymm
  · rw [Ideal.map_le_iff_le_comap,
      ActualIdealGluing.generatedIdeal, Ideal.span_le]
    rintro x ⟨i, rfl⟩
    rw [Ideal.mem_comap]
    exact ActualIdealGluing.generator_mem (fun j => f (g j)) i
  · rw [ActualIdealGluing.generatedIdeal, Ideal.span_le]
    rintro x ⟨i, rfl⟩
    exact Ideal.mem_map_of_mem f
      (ActualIdealGluing.generator_mem g i)

/-- Pairwise gauge transition data. -/
structure Compatible (D : Data (ι := ι) A) where
  gauge : ∀ c d : Chart,
    InvertibleMatrixGeneratorGauge.Gauge
      (R := OverlapRing (A := A) c d) (ι := ι)
  transition : ∀ c d,
    (gauge c d).transform (D.rightEquation c d) =
      D.leftEquation c d

namespace Compatible

variable {D : Data (ι := ι) A}
    (H : Compatible D)

/-- Gauge-related local equation frames define the same overlap ideal. -/
theorem overlapIdeal_eq (c d : Chart) :
    Ideal.map (leftMap (A := A) c d) (D.localIdeal c) =
      Ideal.map (rightMap (A := A) c d) (D.localIdeal d) := by
  rw [map_generatedIdeal, map_generatedIdeal]
  rw [← H.transition c d]
  exact (H.gauge c d).generatedIdeal_transform_eq
    (D.rightEquation c d)

/-- Complete pairwise ideal-sheaf descent datum. -/
structure Certificate where
  overlapEquality : ∀ c d : Chart,
    Ideal.map (leftMap (A := A) c d) (D.localIdeal c) =
      Ideal.map (rightMap (A := A) c d) (D.localIdeal d)

/-- Assemble the pairwise gauge descent certificate. -/
noncomputable def certificate : Certificate H where
  overlapEquality := H.overlapIdeal_eq

end Compatible

end

end FittingGaugeCentreOverlap
end Experimental
end PCRLean
