import PCRLean.Experimental.FittingGraphSectionAtlas

#print axioms PCRLean.Experimental.FittingGraphSectionAtlas.chartSectionEquiv_algebraMap
#print axioms PCRLean.Experimental.FittingGraphSectionAtlas.CompatibleSectionData.toSectionAtlas
#print axioms PCRLean.Experimental.FittingGraphSectionAtlas.CompatibleSectionData.restrict_globalCoefficient_eq_algebraMap
#print axioms PCRLean.Experimental.FittingGraphSectionAtlas.CompatibleSectionData.globalGraph_section_restricts
#print axioms PCRLean.Experimental.FittingGraphSectionAtlas.CompatibleSectionData.globalGraph_localizes
#print axioms PCRLean.Experimental.FittingGraphSectionAtlas.CompatibleSectionData.local_graphIdeal_eq_global_baseChange
#print axioms PCRLean.Experimental.FittingGraphSectionAtlas.CompatibleSectionData.certificate
