import PCRLean.Experimental.FPQCFittingImageCentreRoundIndex

#print axioms PCRLean.Experimental.MarkedPermissibilityFaithfullyFlatDescent.permissible_extend_iff
#print axioms PCRLean.Experimental.FrobeniusNormalBasicOpenDescent.reflectsFrobeniusPowers_of_basicOpenCover
#print axioms PCRLean.Experimental.MarkedPermissibilityBasicOpenDescent.owners_permissible_of_basicOpenCover
#print axioms PCRLean.Experimental.FittingCentreLegalityCompiler.compile
#print axioms PCRLean.Experimental.FlatPassiveTorSafety.owners_torSafe_of_flat
#print axioms PCRLean.Experimental.FittingFlatJointLegalityCompiler.compile
#print axioms PCRLean.Experimental.PolynomialGraphBoundarySNC.certificate
#print axioms PCRLean.Experimental.ExceptionalDebtLineage.enroll_idempotent
#print axioms PCRLean.Experimental.GraphDebtCleanupCompiler.rank_decreases
#print axioms PCRLean.Experimental.ExceptionalDebtOverlapTransport.EventOverlap.map_eventDebt
#print axioms PCRLean.Experimental.ExceptionalDebtOverlapCocycle.map_eventDebt_trans
#print axioms PCRLean.Experimental.PolynomialGraphJointResolutionChamber.certificate
#print axioms PCRLean.Experimental.PolynomialGraphMarkBoundary.sourcePacket_not_permissible_of_block_lt_mark
#print axioms PCRLean.Experimental.InvertibleMatrixGeneratorGauge.Gauge.generatedIdeal_transform_eq
#print axioms PCRLean.Experimental.FittingGaugeCentreOverlap.Compatible.overlapIdeal_eq
#print axioms PCRLean.Experimental.HeterogeneousGeneratorGluing.FrameEquivalence.ideal_eq
#print axioms PCRLean.Experimental.ModuleImageCentre.SpanningFrame.generatedIdeal_eq_imageIdeal
#print axioms PCRLean.Experimental.ModuleImageGraphAtlas.Data.localCentre_eq_map_globalCentre
#print axioms PCRLean.Experimental.OperatorOrbitImageCentre.exists_finite_raw_packet_presentation
#print axioms PCRLean.Experimental.FPQCFittingImageCentreRoundIndex.loaded
