import PCRLean.Experimental.FrobeniusNormalLocalCoordinateModel

#print axioms PCRLean.Experimental.FrobeniusNormalLocalCoordinateModel.reflects_of_model
#print axioms PCRLean.Experimental.FrobeniusNormalLocalCoordinateModel.power_mem_scaled_iff_of_model
#print axioms PCRLean.Experimental.FrobeniusNormalLocalCoordinateModel.reflects_of_coordinateModel
#print axioms PCRLean.Experimental.FrobeniusNormalLocalCoordinateModel.reflects_of_affineFrameModel
#print axioms PCRLean.Experimental.FrobeniusNormalLocalCoordinateModel.power_mem_scaled_iff_of_coordinateModel
