import Mathlib
import PCRLean.Experimental.DualPacketAffineRootPackage

/-!
# Experimental finite generation of row-span roots by Frobenius powers

Let the coefficient field have characteristic `p`, with `p` prime, and put
`q = p^e`.  The `q`-th power map is additive.  Consequently the `q`-th power of
any linear combination of packet rows is a linear combination of the `q`-th
powers of the original finite packet rows.  Hence the full row-span root
package is exactly the ideal generated by the finitely many packet powers.

This is the positive-characteristic finite packetization theorem for the root
package.  It converts the root-realization obligation into a finite ideal
equality.
-/

namespace PCRLean
namespace Experimental
namespace FrobeniusFiniteRootGeneration

noncomputable section

universe u v w

variable {K : Type u} [Field K]
variable {σ : Type v} [Fintype σ] [DecidableEq σ]
variable {κ : Type w} [Fintype κ]
variable (p : Nat) [Fact p.Prime] [CharP K p]

abbrev Direction := σ → K
abbrev Dual := Module.Dual K (Direction (K := K) (σ := σ))

open DualPacketAffineLinearRealization
open DualPacketRegularCentre
open DualPacketAffineRootPackage

/-- Finite ideal generated by the `p^e`-th powers of the named packet rows. -/
def packetPowerIdeal
    (packet : κ → Dual (K := K) (σ := σ)) (e : Nat) :
    Ideal (MvPolynomial σ K) :=
  Ideal.span (Set.range fun i : κ =>
    (FunctionalPacketIdeal.functionalPolynomial (packet i)) ^ (p ^ e))

/-- Every named packet power belongs to the finite packet-power ideal. -/
theorem packetPowerGenerator_mem
    (packet : κ → Dual (K := K) (σ := σ))
    (e : Nat) (i : κ) :
    (FunctionalPacketIdeal.functionalPolynomial (packet i)) ^ (p ^ e) ∈
      packetPowerIdeal p packet e := by
  apply Ideal.subset_span
  exact ⟨i, rfl⟩

/-- The Frobenius power of every covector in the packet span belongs to the
finite ideal generated by packet-row powers. -/
theorem functionalPolynomial_pow_mem_packetPowerIdeal
    (packet : κ → Dual (K := K) (σ := σ))
    (e : Nat)
    {f : Dual (K := K) (σ := σ)}
    (hf : f ∈ Submodule.span K (Set.range packet)) :
    (FunctionalPacketIdeal.functionalPolynomial f) ^ (p ^ e) ∈
      packetPowerIdeal p packet e := by
  induction hf using Submodule.span_induction with
  | mem f hf =>
      rcases hf with ⟨i, rfl⟩
      exact packetPowerGenerator_mem p packet e i
  | zero =>
      have hp : 0 < p := (Fact.out : p.Prime).pos
      have hq : 0 < p ^ e := pow_pos hp e
      simpa [FunctionalPacketIdeal.functionalPolynomial,
        FunctionalPacketIdeal.coefficientRow,
        LinearPacketIdeal.linearPolynomial, hq] using
        (packetPowerIdeal p packet e).zero_mem
  | add f g hf hg hfi hgi =>
      rw [FunctionalPacketIdeal.functionalPolynomial_add,
        add_pow_char_pow]
      exact (packetPowerIdeal p packet e).add_mem hfi hgi
  | smul a f hf hfi =>
      rw [FunctionalPacketIdeal.functionalPolynomial_smul, mul_pow]
      exact (packetPowerIdeal p packet e).mul_mem_left _ hfi

/-- Main finite-generation theorem: the full row-span root package equals the
finite ideal of named packet Frobenius powers. -/
theorem actualRootPowerIdeal_eq_packetPowerIdeal
    (packet : κ → Dual (K := K) (σ := σ)) (e : Nat) :
    actualRootPowerIdeal packet (p ^ e) = packetPowerIdeal p packet e := by
  apply le_antisymm
  · rw [actualRootPowerIdeal, Ideal.span_le]
    rintro z ⟨f, rfl⟩
    exact functionalPolynomial_pow_mem_packetPowerIdeal
      p packet e f.2
  · rw [packetPowerIdeal, Ideal.span_le]
    rintro z ⟨i, rfl⟩
    exact rootGenerator_mem packet (p ^ e)
      ⟨packet i, Submodule.subset_span ⟨i, rfl⟩⟩

/-- The finite packet-power ideal is permissible for the same actual affine
centre. -/
theorem packetPowerIdeal_permissible
    (packet : κ → Dual (K := K) (σ := σ)) (e : Nat) :
    MarkedIdeal.Permissible
      (R := MvPolynomial σ K)
      ⟨packetPowerIdeal p packet e, p ^ e,
        pow_pos (Fact.out : p.Prime).pos e⟩
      (actualIdeal packet) := by
  rw [← actualRootPowerIdeal_eq_packetPowerIdeal p packet e]
  exact actualRootPacket_permissible packet
    (pow_pos (Fact.out : p.Prime).pos e)

end

end FrobeniusFiniteRootGeneration
end Experimental
end PCRLean
