import PCRLean.Experimental.GradedFrobeniusHeredityKernelIndex

#print axioms PCRLean.Experimental.UnivariateFrobeniusOrderHeredity.atPointSingular_pow_iff
#print axioms PCRLean.Experimental.FrobeniusMarkScalingBoundary.unscaled_mark_counterexample
#print axioms PCRLean.Experimental.UniversalMarkedFrobeniusEquivalence.derivativeZero_root_equivalent
#print axioms PCRLean.Experimental.MultivariateFrobeniusOrderHeredity.orderGE_power_iff
#print axioms PCRLean.Experimental.MultivariatePointIdealBridge.mem_pointIdeal_pow_of_atPointOrderGE
#print axioms PCRLean.Experimental.CoordinateSubspaceOrderHeredity.centreOrderGE_power_iff
#print axioms PCRLean.Experimental.AffineCoordinateSubspaceHeredity.affineCentreOrderGE_power_iff
#print axioms PCRLean.Experimental.LinearFrameSubspaceHeredity.frameCentreOrderGE_power_iff
#print axioms PCRLean.Experimental.FrobeniusSupportDomain.orderGE_power_iff
#print axioms PCRLean.Experimental.CoordinateCentreExactFrobeniusHeredity.frobeniusPower_mem_centreIdeal_pow_iff
#print axioms PCRLean.Experimental.AffineLinearFrameExactFrobeniusHeredity.frobeniusPower_mem_affineFrameCentreIdeal_pow_iff
#print axioms PCRLean.Experimental.FrobeniusNormalCentre.affineFrameCentre_reflects
#print axioms PCRLean.Experimental.FrobeniusNormalCentreCounterexample.bottom_not_reflects_twoPowers
#print axioms PCRLean.Experimental.GradedPowerReflection.reflectsFrobeniusPowers_of_frobeniusGradedReduced
#print axioms PCRLean.Experimental.FrobeniusNormalFaithfullyFlatDescent.reflectsFrobeniusPowers_of_extended
#print axioms PCRLean.Experimental.CoordinateControlledTransformHeredity.quotient_unique
#print axioms PCRLean.Experimental.CoordinateControlledTransformHeredity.quotient_primePower_eq
#print axioms PCRLean.Experimental.GradedFrobeniusHeredityKernelIndex.loaded
