import Mathlib
import PCRLean.Experimental.HybridDefectRootCusp

/-!
# Experimental singular-locus containment for the hybrid cusp centre

For `f = y^p - x^(p+1)` in characteristic `p`, the hypersurface singular ideal
is generated by `f` and its two partial derivatives.  The derivative packet is
`(-x^p, 0)`.  The hybrid centre `(x,y)` contains the equation and both partial
derivatives, so its closed subscheme lies inside the hypersurface singular
locus.

This closes the singular-locus gate for the exact toy chamber.  It does not
prove a universal singular-locus containment theorem for arbitrary hybrid
components, nor owner, passive, boundary, or hereditary legality.
-/

namespace PCRLean
namespace Experimental
namespace HybridCuspSingularContainment

noncomputable section

universe u

variable {K : Type u} [Field K]
variable (p : Nat) [Fact p.Prime] [CharP K p]

open HybridDefectRootCusp

abbrev P := MvPolynomial Bool K

/-- Ordinary Jacobian ideal of the cusp. -/
def jacobianIdeal : Ideal (P (K := K)) :=
  Ideal.span (Set.range fun i : Bool =>
    MvPolynomial.pderiv i (cusp (K := K) p))

/-- Scheme-theoretic hypersurface singular ideal `(f, df)`. -/
def singularIdeal : Ideal (P (K := K)) :=
  Ideal.span {cusp (K := K) p} ⊔ jacobianIdeal (K := K) p

/-- Positive powers of the hybrid centre are contained in the centre itself. -/
theorem hybridIdeal_pow_le_hybridIdeal :
    (hybridIdeal (K := K)) ^ p ≤ hybridIdeal (K := K) := by
  obtain ⟨n, rfl⟩ := Nat.exists_eq_succ_of_ne_zero Fact.out.ne_zero
  rw [pow_succ]
  exact Ideal.mul_le_left

/-- The cusp equation belongs to the hybrid centre, not only to its marked
power. -/
theorem cusp_mem_hybridIdeal :
    cusp (K := K) p ∈ hybridIdeal (K := K) :=
  hybridIdeal_pow_le_hybridIdeal (K := K) p
    (HybridDefectRootCusp.cusp_mem_hybridIdeal_pow (K := K) p)

/-- The visible derivative generator `x^p` belongs to the hybrid centre. -/
theorem x_pow_mem_hybridIdeal :
    (x (K := K)) ^ p ∈ hybridIdeal (K := K) :=
  hybridIdeal_pow_le_hybridIdeal (K := K) p
    (Ideal.pow_mem_pow
      (HybridDefectRootCusp.x_mem_hybridIdeal (K := K)) p)

/-- Every ordinary partial derivative of the cusp belongs to the hybrid centre. -/
theorem pderiv_mem_hybridIdeal (i : Bool) :
    MvPolynomial.pderiv i (cusp (K := K) p) ∈
      hybridIdeal (K := K) := by
  cases i with
  | false =>
      rw [HybridDefectRootCusp.pderiv_x_cusp (K := K) p]
      exact (hybridIdeal (K := K)).neg_mem
        (x_pow_mem_hybridIdeal (K := K) p)
  | true =>
      rw [HybridDefectRootCusp.pderiv_y_cusp (K := K) p]
      exact (hybridIdeal (K := K)).zero_mem

/-- The full Jacobian ideal is contained in the hybrid centre. -/
theorem jacobianIdeal_le_hybridIdeal :
    jacobianIdeal (K := K) p ≤ hybridIdeal (K := K) := by
  rw [jacobianIdeal, Ideal.span_le]
  rintro z ⟨i, rfl⟩
  exact pderiv_mem_hybridIdeal (K := K) p i

/-- Main toy-chamber singular-containment theorem.  Algebraically
`singularIdeal ≤ hybridIdeal`; contravariantly this says the closed hybrid
centre is contained in the hypersurface singular locus. -/
theorem singularIdeal_le_hybridIdeal :
    singularIdeal (K := K) p ≤ hybridIdeal (K := K) := by
  apply sup_le
  · rw [Ideal.span_le]
    simpa using cusp_mem_hybridIdeal (K := K) p
  · exact jacobianIdeal_le_hybridIdeal (K := K) p

end

end HybridCuspSingularContainment
end Experimental
end PCRLean
