import PCRLean.Experimental.IntegralEquivalentReesPresentations

#print axioms PCRLean.Experimental.IntegralEquivalentReesPresentations.IntegralEquivalent.refl
#print axioms PCRLean.Experimental.IntegralEquivalentReesPresentations.IntegralEquivalent.symm
#print axioms PCRLean.Experimental.IntegralEquivalentReesPresentations.IntegralEquivalent.trans
#print axioms PCRLean.Experimental.IntegralEquivalentReesPresentations.singleRoot_integralEquivalent
#print axioms PCRLean.Experimental.IntegralEquivalentReesPresentations.finiteRoot_integralEquivalent
#print axioms PCRLean.Experimental.IntegralEquivalentReesPresentations.finiteSourceRoot_integralEquivalent
#print axioms PCRLean.Experimental.IntegralEquivalentReesPresentations.finiteHasse_integralEquivalent
#print axioms PCRLean.Experimental.IntegralEquivalentReesPresentations.finiteHasseSource_integralEquivalent
#print axioms PCRLean.Experimental.IntegralEquivalentReesPresentations.Chain.zero_to
#print axioms PCRLean.Experimental.IntegralEquivalentReesPresentations.Chain.endpoint_integralEquivalent
