import Mathlib
import PCRLean.Experimental.SurjectiveLinearMapSymmetricQuotient

/-!
# Experimental gauge invariance of intrinsic linear centres

The actual centre ideal attached to a linear map is generated by its source
kernel.  Therefore it is invariant under every change of target presentation
which preserves that kernel.  In particular, postcomposition by a linear
equivalence changes coefficient coordinates but leaves the centre ideal
literally equal.

This is the algebraic overlap principle for Fitting/conormal frames.  It does
not yet descend ideals across localization maps or prove existence of a finite
constant-rank atlas.
-/

namespace PCRLean
namespace Experimental
namespace IntrinsicCentreGaugeInvariance

noncomputable section

universe u v w₁ w₂ x

variable {R : Type u} [CommRing R]
variable {V : Type v} [AddCommGroup V] [Module R V]
variable {W₁ : Type w₁} [AddCommGroup W₁] [Module R W₁]
variable {W₂ : Type w₂} [AddCommGroup W₂] [Module R W₂]

open SurjectiveLinearMapSymmetricQuotient

/-- Linear maps with equal source kernels define equal intrinsic actual centre
ideals, even when their target modules differ. -/
theorem kernelIdeal_eq_of_ker_eq
    (p : V →ₗ[R] W₁) (q : V →ₗ[R] W₂)
    (hker : LinearMap.ker p = LinearMap.ker q) :
    kernelIdeal p = kernelIdeal q := by
  rw [kernelIdeal, kernelIdeal]
  apply congrArg Ideal.span
  ext z
  constructor
  · rintro ⟨x, rfl⟩
    refine ⟨⟨x.1, ?_⟩, rfl⟩
    rw [← hker]
    exact x.2
  · rintro ⟨x, rfl⟩
    refine ⟨⟨x.1, ?_⟩, rfl⟩
    rw [hker]
    exact x.2

/-- Postcomposition by a target linear equivalence preserves the source
kernel. -/
theorem ker_equiv_comp_eq
    (e : W₁ ≃ₗ[R] W₂) (p : V →ₗ[R] W₁) :
    LinearMap.ker (e.toLinearMap.comp p) = LinearMap.ker p := by
  ext x
  change e (p x) = 0 ↔ p x = 0
  constructor
  · intro h
    apply e.injective
    simpa using h
  · intro h
    simpa [h]

/-- Target gauge changes leave the intrinsic centre ideal literally equal. -/
theorem kernelIdeal_equiv_comp_eq
    (e : W₁ ≃ₗ[R] W₂) (p : V →ₗ[R] W₁) :
    kernelIdeal (e.toLinearMap.comp p) = kernelIdeal p := by
  exact kernelIdeal_eq_of_ker_eq
    (e.toLinearMap.comp p) p (ker_equiv_comp_eq e p)

/-- A finite family of coefficient presentations related by target gauges. -/
structure GaugeAtlas (Chart : Type x) where
  Target : Chart → Type w₁
  targetAddCommGroup : ∀ c, AddCommGroup (Target c)
  targetModule : ∀ c, Module R (Target c)
  project : ∀ c, V →ₗ[R] Target c
  transition : ∀ c d, Target c ≃ₗ[R] Target d
  compatible : ∀ c d,
    (transition c d).toLinearMap.comp (project c) = project d

attribute [instance] GaugeAtlas.targetAddCommGroup GaugeAtlas.targetModule

namespace GaugeAtlas

variable {Chart : Type x} (A : GaugeAtlas
  (R := R) (V := V) Chart)

/-- Every chart presentation in a gauge atlas defines the same actual centre
ideal. -/
theorem kernelIdeal_eq (c d : Chart) :
    kernelIdeal (A.project c) = kernelIdeal (A.project d) := by
  rw [← A.compatible c d]
  exact (kernelIdeal_equiv_comp_eq (A.transition c d) (A.project c)).symm

end GaugeAtlas

end

end IntrinsicCentreGaugeInvariance
end Experimental
end PCRLean
