import Mathlib
import Mathlib.LinearAlgebra.SymmetricAlgebra.Basic
import PCRLean.Experimental.SurjectiveLinearMapSymmetricQuotient

/-!
# Experimental transport of intrinsic linear centres

A linear equivalence of source modules induces an algebra equivalence of their
symmetric algebras.  If source and target equivalences intertwine two linear
quotient presentations, then the intrinsic ideal generated by the source
kernel is transported exactly to the intrinsic ideal of the second
presentation.

This is the algebraic overlap theorem before localization: it handles changes
of ambient conormal frame and coefficient frame simultaneously.  It does not
yet prove compatibility with scalar extension or localization, nor construct a
finite constant-rank atlas from arbitrary Frobenius/Fitting data.
-/

namespace PCRLean
namespace Experimental
namespace IntrinsicCentreTransport

noncomputable section

universe u v₁ v₂ w₁ w₂

variable {R : Type u} [CommRing R]
variable {V₁ : Type v₁} {V₂ : Type v₂}
variable [AddCommGroup V₁] [Module R V₁]
variable [AddCommGroup V₂] [Module R V₂]
variable {W₁ : Type w₁} {W₂ : Type w₂}
variable [AddCommGroup W₁] [Module R W₁]
variable [AddCommGroup W₂] [Module R W₂]

open SurjectiveLinearMapSymmetricQuotient

/-- Algebra map on symmetric algebras induced by a linear map. -/
def symmetricMap (f : V₁ →ₗ[R] V₂) :
    SymmetricAlgebra R V₁ →ₐ[R] SymmetricAlgebra R V₂ :=
  SymmetricAlgebra.lift ((SymmetricAlgebra.ι R V₂).comp f)

@[simp] theorem symmetricMap_ι (f : V₁ →ₗ[R] V₂) (x : V₁) :
    symmetricMap f (SymmetricAlgebra.ι R V₁ x) =
      SymmetricAlgebra.ι R V₂ (f x) := by
  simp [symmetricMap]

/-- A source linear equivalence induces an algebra equivalence of symmetric
algebras. -/
noncomputable def symmetricEquiv (e : V₁ ≃ₗ[R] V₂) :
    SymmetricAlgebra R V₁ ≃ₐ[R] SymmetricAlgebra R V₂ := by
  refine AlgEquiv.ofAlgHom
    (symmetricMap e.toLinearMap)
    (symmetricMap e.symm.toLinearMap) ?_ ?_
  · apply SymmetricAlgebra.algHom_ext
    ext x
    simp [symmetricMap]
  · apply SymmetricAlgebra.algHom_ext
    ext y
    simp [symmetricMap]

@[simp] theorem symmetricEquiv_ι (e : V₁ ≃ₗ[R] V₂) (x : V₁) :
    symmetricEquiv e (SymmetricAlgebra.ι R V₁ x) =
      SymmetricAlgebra.ι R V₂ (e x) := by
  simp [symmetricEquiv, symmetricMap]

/-- A commutative source-target gauge square transports the intrinsic actual
centre ideal exactly. -/
theorem map_kernelIdeal_eq
    (sourceGauge : V₁ ≃ₗ[R] V₂)
    (targetGauge : W₁ ≃ₗ[R] W₂)
    (p : V₁ →ₗ[R] W₁)
    (q : V₂ →ₗ[R] W₂)
    (hcomm : targetGauge.toLinearMap.comp p =
      q.comp sourceGauge.toLinearMap) :
    Ideal.map (symmetricEquiv sourceGauge).toAlgHom (kernelIdeal p) =
      kernelIdeal q := by
  apply le_antisymm
  · rw [kernelIdeal, Ideal.map_le_iff_le_comap, Ideal.span_le]
    rintro z ⟨x, rfl⟩
    rw [Ideal.mem_comap]
    rw [symmetricEquiv_ι]
    apply Ideal.subset_span
    refine ⟨⟨sourceGauge x.1, ?_⟩, rfl⟩
    apply LinearMap.mem_ker.mpr
    have hx : p x.1 = 0 := LinearMap.mem_ker.mp x.2
    have hc := LinearMap.congr_fun hcomm x.1
    simpa [LinearMap.comp_apply, hx] using hc.symm
  · rw [kernelIdeal, Ideal.span_le]
    rintro z ⟨y, rfl⟩
    have hy : q y.1 = 0 := LinearMap.mem_ker.mp y.2
    have hpre : sourceGauge.symm y.1 ∈ LinearMap.ker p := by
      apply LinearMap.mem_ker.mpr
      apply targetGauge.injective
      have hc := LinearMap.congr_fun hcomm (sourceGauge.symm y.1)
      simpa [LinearMap.comp_apply, hy] using hc
    have hgen :
        SymmetricAlgebra.ι R V₁ (sourceGauge.symm y.1) ∈ kernelIdeal p := by
      apply Ideal.subset_span
      exact ⟨⟨sourceGauge.symm y.1, hpre⟩, rfl⟩
    have hm := Ideal.mem_map_of_mem
      (symmetricEquiv sourceGauge).toAlgHom hgen
    simpa using hm

/-- If only the source frame changes and the target is fixed, the same exact
transport theorem applies. -/
theorem map_kernelIdeal_eq_of_sourceGauge
    (sourceGauge : V₁ ≃ₗ[R] V₂)
    (p : V₁ →ₗ[R] W₁)
    (q : V₂ →ₗ[R] W₁)
    (hcomm : p = q.comp sourceGauge.toLinearMap) :
    Ideal.map (symmetricEquiv sourceGauge).toAlgHom (kernelIdeal p) =
      kernelIdeal q := by
  exact map_kernelIdeal_eq sourceGauge (LinearEquiv.refl R W₁)
    p q (by simpa using hcomm)

end

end IntrinsicCentreTransport
end Experimental
end PCRLean
