import PCRLean.Experimental.MaximalMinorResolutionKernelIndex
import PCRLean.Experimental.ConormalAffinePacketCoordinates
import PCRLean.Experimental.ConormalPacketFrameIndependence
import PCRLean.Experimental.ConormalAffinePacketOverRing
import PCRLean.Experimental.NoetherianAffineOrbitPacket
import PCRLean.Experimental.NoetherianAffineOrbitPacketCanonicity
import PCRLean.Experimental.AffineConormalIdeal
import PCRLean.Experimental.AffineConormalIdealCoordinates
import PCRLean.Experimental.AffineConormalRegularCentre
import PCRLean.Experimental.NoetherianAffineOrbitIdeal
import PCRLean.Experimental.ProjectiveMoritaDescent
import PCRLean.Experimental.DeterminantalCokernelObstruction
import PCRLean.Experimental.ProjectiveSectionOrderIdeal
import PCRLean.Experimental.ProjectiveSectionOrderIdealMinimality
import PCRLean.Experimental.ProjectiveSectionOrderIdealBaseChange
import PCRLean.Experimental.CokernelOrderIdeal
import PCRLean.Experimental.CokernelOrderIdealBaseChange
import PCRLean.Experimental.CokernelOrderIdealCompiler
import PCRLean.Experimental.SplitPacketOrderIdeal
import PCRLean.Experimental.AffinePacketHybridEffectivity
import PCRLean.Experimental.SplitMatrixOrderIdealHybrid
import PCRLean.Experimental.OrderIdealMarkedClosureCompiler
import PCRLean.Experimental.SplitMatrixMarkedHybridCompiler
import PCRLean.Experimental.SplitMatrixMarkedHybridRegularCentre
import PCRLean.Experimental.NestedPolynomialGraphHybrid
import PCRLean.Experimental.NestedPolynomialGraphFlattening

/-!
# Integrated intrinsic order-ideal hybrid index

This experimental index joins the two branches of the current centre synthesis
architecture.

## Zero-obstruction branch

* a finite affine conormal packet is coordinatized without changing its
  intrinsic solution predicate;
* maximal minors generate `1` and augmented maximal minors vanish iff the
  packet has a unique solution;
* the ideal generated by all original packet equations is exactly the graph
  centre ideal;
* the corresponding intrinsic affine conormal ideal has quotient equal to the
  coefficient field and is independent of finite orbit packets and coordinate
  frames.

## Nonzero-obstruction branch

* the cokernel class has an intrinsic finite order ideal;
* this ideal is the least coefficient defect and has an exact
  graph/hybrid/unit trichotomy;
* compatible finite-projective base change transports the ideal exactly and
  faithfully flat maps preserve the full zero/proper-nonzero/unit status;
* a split matrix packet turns the residual order ideal into an actual
  graph-plus-defect hybrid centre;
* a finite cardinal-minimal marked closure selects only essential correction
  components;
* properness and regularity of the hybrid centre reduce exactly to the
  coefficient closure quotient; and
* when the coefficient closure is itself a polynomial graph centre, the nested
  hybrid flattens to one larger graph centre and inherits the complete standard
  all-chart exit.

The index does not construct the intrinsic Frobenius--Hasse packet, prove that
the universal cokernel is finite projective, construct marked correction
components in every chamber, handle a general non-graph coefficient closure,
or prove general resolution.
-/

namespace PCRLean
namespace Experimental
namespace IntrinsicOrderIdealHybridKernelIndex

/-- Marker theorem confirming elaboration of the integrated experimental DAG. -/
theorem loaded : True := True.intro

end IntrinsicOrderIdealHybridKernelIndex
end Experimental
end PCRLean
