import PCRLean.Experimental.IntrinsicOrderIdealMinimalityAtomic

#print axioms PCRLean.Experimental.IntrinsicOrderIdealMinimalityAtomic.functionalsVanishMod_iff_orderIdeal_le
#print axioms PCRLean.Experimental.IntrinsicOrderIdealMinimalityAtomic.orderIdeal_isLeast_intrinsic
#print axioms PCRLean.Experimental.IntrinsicOrderIdealMinimalityAtomic.no_proper_ideal_absorbs_unit_intrinsic
#print axioms PCRLean.Experimental.IntrinsicOrderIdealMinimalityAtomic.orderIdeal_eq_top_iff_no_proper_intrinsic
#print axioms PCRLean.Experimental.IntrinsicOrderIdealMinimalityAtomic.zeroDetection_requires_dual_separation
