import Mathlib
import PCRLean.MarkedIdeal
import PCRLean.Experimental.IntrinsicKernelIdealFunctoriality

/-!
# Experimental intrinsic kernel root packets

For a linear packet map `project`, the intrinsic centre ideal is generated by
degree-one vectors in `ker project`.  At a positive mark `q`, take the ideal
generated by the `q`-th powers of those same degree-one vectors.  This root
packet lies in the `q`-th power of the intrinsic centre ideal, hence is marked
permissible without choosing coordinates or a kernel basis.

The construction depends only on the kernel and is functorial under commuting
linear squares.  It is the coordinate-free analogue of the full coordinate
Frobenius-root packet.  This file does not prove terminality of its controlled
transform on arbitrary nonlinear blowup charts.
-/

namespace PCRLean
namespace Experimental
namespace IntrinsicKernelRootPacket

noncomputable section

universe u v v' w w'

variable {R : Type u} [CommRing R]
variable {V : Type v} {V' : Type v'}
variable {Kmod : Type w} {Kmod' : Type w'}
variable [AddCommGroup V] [Module R V]
variable [AddCommGroup V'] [Module R V']
variable [AddCommGroup Kmod] [Module R Kmod]
variable [AddCommGroup Kmod'] [Module R Kmod']

open IntrinsicKernelIdealFunctoriality

/-- Intrinsic ideal generated by `q`-th powers of all degree-one kernel
vectors. -/
def rootPowerIdeal (project : V →ₗ[R] Kmod) (q : Nat) :
    Ideal (SymmetricAlgebra R V) :=
  Ideal.span (Set.range fun x : project.ker =>
    (SymmetricAlgebra.ι R V x.1) ^ q)

/-- Every named kernel root power belongs to the intrinsic root packet. -/
theorem rootGenerator_mem
    (project : V →ₗ[R] Kmod) (q : Nat) (x : project.ker) :
    (SymmetricAlgebra.ι R V x.1) ^ q ∈ rootPowerIdeal project q := by
  apply Ideal.subset_span
  exact ⟨x, rfl⟩

/-- The intrinsic root packet is contained in the corresponding power of the
actual centre ideal. -/
theorem rootPowerIdeal_le_kernelIdeal_pow
    (project : V →ₗ[R] Kmod) (q : Nat) :
    rootPowerIdeal project q ≤ (kernelIdealOf project) ^ q := by
  rw [rootPowerIdeal, Ideal.span_le]
  rintro z ⟨x, rfl⟩
  exact Ideal.pow_mem_pow
    (Ideal.subset_span ⟨x, rfl⟩) q

/-- Coordinate-free marked permissibility of the full intrinsic root packet. -/
theorem rootPacket_permissible
    (project : V →ₗ[R] Kmod) {q : Nat} (hq : 0 < q) :
    MarkedIdeal.Permissible
      (R := SymmetricAlgebra R V)
      ⟨rootPowerIdeal project q, q, hq⟩
      (kernelIdealOf project) :=
  rootPowerIdeal_le_kernelIdeal_pow project q

/-- The root packet depends only on the linear kernel. -/
theorem rootPowerIdeal_eq_of_ker_eq
    {Kmod₂ : Type*} [AddCommGroup Kmod₂] [Module R Kmod₂]
    (project₁ : V →ₗ[R] Kmod) (project₂ : V →ₗ[R] Kmod₂)
    (hker : project₁.ker = project₂.ker) (q : Nat) :
    rootPowerIdeal project₁ q = rootPowerIdeal project₂ q := by
  apply le_antisymm
  · rw [rootPowerIdeal, Ideal.span_le]
    rintro z ⟨x, rfl⟩
    apply Ideal.subset_span
    refine ⟨⟨x.1, ?_⟩, rfl⟩
    rw [← hker]
    exact x.2
  · rw [rootPowerIdeal, Ideal.span_le]
    rintro z ⟨x, rfl⟩
    apply Ideal.subset_span
    refine ⟨⟨x.1, ?_⟩, rfl⟩
    rw [hker]
    exact x.2

/-- A commuting square transports the intrinsic root packet forward. -/
theorem map_rootPowerIdeal_le
    (project : V →ₗ[R] Kmod)
    (project' : V' →ₗ[R] Kmod')
    (f : V →ₗ[R] V')
    (g : Kmod →ₗ[R] Kmod')
    (hcomm : project'.comp f = g.comp project)
    (q : Nat) :
    Ideal.map (symmetricMap f) (rootPowerIdeal project q) ≤
      rootPowerIdeal project' q := by
  rw [Ideal.map_le_iff_le_comap, rootPowerIdeal, Ideal.span_le]
  rintro z ⟨x, rfl⟩
  rw [Ideal.mem_comap]
  change symmetricMap f ((SymmetricAlgebra.ι R V x.1) ^ q) ∈
    rootPowerIdeal project' q
  rw [map_pow, symmetricMap_ι]
  apply Ideal.subset_span
  refine ⟨⟨f x.1, ?_⟩, rfl⟩
  apply LinearMap.mem_ker.mpr
  have hx : project x.1 = 0 := LinearMap.mem_ker.mp x.2
  have hpoint := LinearMap.congr_fun hcomm x.1
  simpa [LinearMap.comp_apply, hx] using hpoint

end

end IntrinsicKernelRootPacket
end Experimental
end PCRLean
