import Mathlib
import Mathlib.LinearAlgebra.SymmetricAlgebra.Basic
import PCRLean.Experimental.SplitSurjectionSymmetricQuotient

/-!
# Experimental intrinsic kernel-ideal functoriality

For a linear map `project : V →ₗ[R] Kmod`, define the actual ideal of the
symmetric algebra generated by degree-one elements coming from `ker project`.
This ideal is intrinsic: it depends only on the kernel submodule, not on a
chosen complement or target coordinates.

A commuting square of linear maps carries the old intrinsic kernel ideal into
the new one.  This is the elementary hereditary-transport theorem required by
the proposed conormal-quotient centre architecture.  It does not assert that a
geometric blowup supplies the commuting square, nor that the resulting
containment is an equality after saturation or localization.
-/

namespace PCRLean
namespace Experimental
namespace IntrinsicKernelIdealFunctoriality

noncomputable section

universe u v v' w w'

variable {R : Type u} [CommRing R]
variable {V : Type v} {V' : Type v'}
variable {Kmod : Type w} {Kmod' : Type w'}
variable [AddCommGroup V] [Module R V]
variable [AddCommGroup V'] [Module R V']
variable [AddCommGroup Kmod] [Module R Kmod]
variable [AddCommGroup Kmod'] [Module R Kmod']

/-- The symmetric-algebra map induced by a linear map. -/
def symmetricMap (f : V →ₗ[R] V') :
    SymmetricAlgebra R V →ₐ[R] SymmetricAlgebra R V' :=
  SymmetricAlgebra.lift ((SymmetricAlgebra.ι R V').comp f)

@[simp] theorem symmetricMap_ι (f : V →ₗ[R] V') (v : V) :
    symmetricMap f (SymmetricAlgebra.ι R V v) =
      SymmetricAlgebra.ι R V' (f v) := by
  simp [symmetricMap]

/-- The actual degree-one ideal determined by the kernel of a linear map. -/
def kernelIdealOf (project : V →ₗ[R] Kmod) :
    Ideal (SymmetricAlgebra R V) :=
  Ideal.span (Set.range fun x : project.ker =>
    SymmetricAlgebra.ι R V x.1)

/-- The ideal only depends on the kernel submodule.  In particular it is
independent of target coordinates, a basis, and any chosen right inverse. -/
theorem kernelIdealOf_eq_of_ker_eq
    {Kmod₂ : Type*} [AddCommGroup Kmod₂] [Module R Kmod₂]
    (project₁ : V →ₗ[R] Kmod) (project₂ : V →ₗ[R] Kmod₂)
    (hker : project₁.ker = project₂.ker) :
    kernelIdealOf project₁ = kernelIdealOf project₂ := by
  subst hker
  rfl

/-- A commuting linear square transports the intrinsic kernel ideal forward.
This is the exact algebraic containment needed for hereditary centre transport. -/
theorem map_kernelIdealOf_le
    (project : V →ₗ[R] Kmod)
    (project' : V' →ₗ[R] Kmod')
    (f : V →ₗ[R] V')
    (g : Kmod →ₗ[R] Kmod')
    (hcomm : project'.comp f = g.comp project) :
    Ideal.map (symmetricMap f) (kernelIdealOf project) ≤
      kernelIdealOf project' := by
  rw [Ideal.map_le_iff_le_comap, kernelIdealOf, Ideal.span_le]
  rintro x ⟨k, rfl⟩
  rw [Ideal.mem_comap]
  rw [symmetricMap_ι]
  apply Ideal.subset_span
  refine ⟨⟨f k.1, ?_⟩, rfl⟩
  apply LinearMap.mem_ker.mpr
  have hk : project k.1 = 0 := LinearMap.mem_ker.mp k.2
  have hpoint := LinearMap.congr_fun hcomm k.1
  simpa [LinearMap.comp_apply, hk] using hpoint

/-- The intrinsic ideal used by the split-surjection quotient theorem is the
same generic kernel ideal. -/
theorem splitSurjection_kernelIdeal_eq
    (S : SplitSurjectionSymmetricQuotient.SplitSurjection
      (R := R) (V := V) (Kmod := Kmod)) :
    S.kernelIdeal = kernelIdealOf S.project := by
  rfl

/-- Functorial transport specialized to split-surjection centre ideals. -/
theorem map_splitSurjection_kernelIdeal_le
    (S : SplitSurjectionSymmetricQuotient.SplitSurjection
      (R := R) (V := V) (Kmod := Kmod))
    (T : SplitSurjectionSymmetricQuotient.SplitSurjection
      (R := R) (V := V') (Kmod := Kmod'))
    (f : V →ₗ[R] V')
    (g : Kmod →ₗ[R] Kmod')
    (hcomm : T.project.comp f = g.comp S.project) :
    Ideal.map (symmetricMap f) S.kernelIdeal ≤ T.kernelIdeal := by
  rw [splitSurjection_kernelIdeal_eq, splitSurjection_kernelIdeal_eq]
  exact map_kernelIdealOf_le S.project T.project f g hcomm

end

end IntrinsicKernelIdealFunctoriality
end Experimental
end PCRLean
