import Mathlib
import Mathlib.Data.Matrix.Mul
import PCRLean.ActualIdealGluing
import PCRLean.Experimental.PolynomialGraphCentreHeredity

/-!
# Invertible linear systems define exact polynomial graph centres

Let `M` be a square matrix over a commutative ring with a two-sided inverse
`N`, and let `b` be a coefficient vector. In the polynomial ring `R[Z_i]`, the
linear system

`M Z = b`

has the unique solution

`h = N b`.

This file proves that the ideal generated by the system equations is exactly
the polynomial graph ideal

`(Z_i - h_i)`.

The proof is constructive. The matrix `M` writes every system equation as a
linear combination of graph equations, and `N` writes every graph equation as
a linear combination of system equations. Thus an invertible Fitting minor
produces an actual graph centre, not merely an abstract regular quotient.

When `R` is the passive coefficient ring on a determinant localization, this
is the missing algebraic bridge from local Fitting data to the graph-centre
macros and their Čech globalization.
-/

namespace PCRLean
namespace Experimental
namespace InvertibleLinearSystemGraph

noncomputable section

universe u v

variable {R : Type u} [CommRing R]
variable {ι : Type v} [Fintype ι] [DecidableEq ι]

open PolynomialGraphCentreHeredity

abbrev P := MvPolynomial ι R

/-- A square linear system with an explicit two-sided matrix inverse. -/
structure System where
  matrix : Matrix ι ι R
  inverse : Matrix ι ι R
  rhs : ι → R
  leftInverse : matrix * inverse = 1
  rightInverse : inverse * matrix = 1

namespace System

variable (S : System (R := R) (ι := ι))

/-- Unique coefficient-valued solution. -/
def solution : ι → R :=
  S.inverse.mulVec S.rhs

/-- Vector of graph equations. -/
def graphVector : ι → P (R := R) (ι := ι) :=
  fun i => graphGenerator S.solution i

/-- The original linear system, expressed as the matrix applied to the graph
vector. -/
def equationVector : ι → P (R := R) (ι := ι) :=
  (S.matrix.map MvPolynomial.C).mulVec S.graphVector

/-- One system equation. -/
def equation (i : ι) : P (R := R) (ι := ι) :=
  S.equationVector i

/-- Actual ideal generated by the linear-system equations. -/
def equationIdeal : Ideal (P (R := R) (ι := ι)) :=
  ActualIdealGluing.generatedIdeal S.equation

/-- The computed solution satisfies the original system. -/
theorem matrix_mulVec_solution :
    S.matrix.mulVec S.solution = S.rhs := by
  rw [solution, Matrix.mulVec_mulVec, S.leftInverse]
  simp

/-- Pointwise solution identity. -/
theorem matrix_mulVec_solution_apply (i : ι) :
    S.matrix.mulVec S.solution i = S.rhs i := by
  rw [S.matrix_mulVec_solution]

/-- Every system equation is the explicit matrix combination of the graph
equations. -/
theorem equation_reconstruct (i : ι) :
    S.equation i =
      ∑ j : ι, MvPolynomial.C (S.matrix i j) * S.graphVector j := by
  exact Matrix.mulVec_apply_eq_sum
    (S.matrix.map MvPolynomial.C) S.graphVector i

/-- Applying the inverse matrix to the equation vector recovers the graph
vector. -/
theorem inverse_mulVec_equationVector :
    (S.inverse.map MvPolynomial.C).mulVec S.equationVector =
      S.graphVector := by
  rw [equationVector, Matrix.mulVec_mulVec]
  have hmatrix :
      S.inverse.map MvPolynomial.C * S.matrix.map MvPolynomial.C = 1 := by
    simpa using congrArg
      (fun M : Matrix ι ι R => M.map MvPolynomial.C)
      S.rightInverse
  rw [hmatrix]
  simp

/-- Every graph equation is the explicit inverse-matrix combination of the
system equations. -/
theorem graph_reconstruct (i : ι) :
    S.graphVector i =
      ∑ j : ι, MvPolynomial.C (S.inverse i j) * S.equation j := by
  have h := congrFun S.inverse_mulVec_equationVector i
  simpa [equation, Matrix.mulVec_apply_eq_sum] using h.symm

/-- The equation as the familiar affine linear expression `MZ-b`. -/
theorem equation_eq_linear_expression (i : ι) :
    S.equation i =
      (∑ j : ι,
        MvPolynomial.C (S.matrix i j) * MvPolynomial.X j) -
        MvPolynomial.C (S.rhs i) := by
  rw [S.equation_reconstruct]
  simp_rw [graphVector, graphGenerator, mul_sub]
  rw [Finset.sum_sub_distrib]
  congr 1
  calc
    (∑ j : ι,
        MvPolynomial.C (S.matrix i j) *
          MvPolynomial.C (S.solution j)) =
        MvPolynomial.C
          (∑ j : ι, S.matrix i j * S.solution j) := by
      simp
    _ = MvPolynomial.C (S.rhs i) := by
      rw [← Matrix.mulVec_apply_eq_sum,
        S.matrix_mulVec_solution_apply]

/-- Main bridge: the actual linear-system ideal is exactly the actual graph
centre ideal of the computed solution. -/
theorem equationIdeal_eq_graphIdeal :
    S.equationIdeal = graphIdeal S.solution := by
  change ActualIdealGluing.generatedIdeal S.equation =
    ActualIdealGluing.generatedIdeal
      (graphGenerator S.solution)
  exact ActualIdealGluing.generatedIdeal_eq_of_mutual_combinations
    S.equation (graphGenerator S.solution)
    (fun i j => MvPolynomial.C (S.matrix i j))
    (fun i j => MvPolynomial.C (S.inverse i j))
    S.equation_reconstruct
    (fun i => by simpa [graphVector] using S.graph_reconstruct i)

/-- Exact quotient by the linear-system ideal. -/
noncomputable def quotientEquiv :
    (P (R := R) (ι := ι) ⧸ S.equationIdeal) ≃+* R := by
  rw [S.equationIdeal_eq_graphIdeal]
  exact PolynomialGraphCentreQuotient.quotientEquiv S.solution

end System

end

end InvertibleLinearSystemGraph
end Experimental
end PCRLean
