import Mathlib
import PCRLean.MarkedIdeal
import PCRLean.Experimental.LinearHybridSubspaceCentre

/-!
# Experimental minimal linear-hybrid centre compiler

A finite family of intrinsic components is represented by linear subspaces of a
finite-dimensional conormal vector space.  For every selected subfamily, take
their join and the actual degree-one ideal generated by that joined subspace.
The quotient is automatically regular and the ideal is automatically finitely
generated and proper.

If the full family is marked-permissible, this file selects a cardinality-
minimal permissible subfamily.  Every selected component is indispensable.
If its joined subspace is nonzero, the resulting ideal is also non-bottom, so
the certificate simultaneously closes the regularity, finite-type,
properness, strictness, and marked-power gates in the finite-dimensional linear
chamber.

The theorem does not prove singular-locus containment, joint passive safety,
boundary transversality, nonidentity of a Cartier centre, all-chart transport,
or globalization.
-/

namespace PCRLean
namespace Experimental
namespace LinearMinimalHybridCompiler

noncomputable section

universe u v w

variable {K : Type u} [Field K]
variable {V : Type v} [AddCommGroup V] [Module K V]
variable [FiniteDimensional K V]
variable {ι : Type w} [Fintype ι] [DecidableEq ι]

open LinearHybridSubspaceCentre

/-- Marked permissibility of the actual ideal generated by the selected joined
linear subspace. -/
def Acceptable
    (P : MarkedIdeal.Packet (SymmetricAlgebra K V))
    (component : ι → Submodule K V)
    (selected : Finset ι) : Prop :=
  MarkedIdeal.Permissible P
    (combinedCentreIdeal component selected)

/-- Cardinality-minimal marked-permissible linear hybrid. -/
structure MinimalCertificate
    (P : MarkedIdeal.Packet (SymmetricAlgebra K V))
    (component : ι → Submodule K V) where
  selected : Finset ι
  acceptable : Acceptable P component selected
  cardinalMinimal : ∀ candidate : Finset ι,
    Acceptable P component candidate →
      selected.card ≤ candidate.card

namespace MinimalCertificate

variable {P : MarkedIdeal.Packet (SymmetricAlgebra K V)}
variable {component : ι → Submodule K V}

/-- The actual ideal selected by the compiler. -/
def ideal (C : MinimalCertificate P component) :
    Ideal (SymmetricAlgebra K V) :=
  combinedCentreIdeal component C.selected

/-- The selected ideal has regular quotient. -/
theorem quotient_isRegularRing
    (C : MinimalCertificate P component) :
    IsRegularRing
      (SymmetricAlgebra K V ⧸ C.ideal) :=
  combined_quotient_isRegularRing component C.selected

/-- The selected ideal is proper. -/
theorem ideal_ne_top (C : MinimalCertificate P component) :
    C.ideal ≠ ⊤ :=
  LinearHybridSubspaceCentre.centreIdeal_ne_top
    (combinedSubspace component C.selected)

/-- The selected ideal is finitely generated. -/
theorem ideal_fg (C : MinimalCertificate P component) :
    C.ideal.FG :=
  LinearHybridSubspaceCentre.centreIdeal_fg
    (combinedSubspace component C.selected)

/-- Strictness is exactly nonvanishing of the joined component subspace. -/
theorem strict_iff_join_ne_bot
    (C : MinimalCertificate P component) :
    C.ideal ≠ ⊥ ∧ C.ideal ≠ ⊤ ↔
      combinedSubspace component C.selected ≠ ⊥ :=
  combined_strict_iff_join_ne_bot component C.selected

/-- No selected component can be deleted while retaining marked
permissibility. -/
theorem erase_not_acceptable
    (C : MinimalCertificate P component)
    {i : ι} (hi : i ∈ C.selected) :
    ¬ Acceptable P component (C.selected.erase i) := by
  intro herase
  have hle := C.cardinalMinimal (C.selected.erase i) herase
  have hlt : (C.selected.erase i).card < C.selected.card :=
    Finset.card_erase_lt_of_mem hi
  omega

/-- All selected linear components are marked-indispensable. -/
theorem all_components_indispensable
    (C : MinimalCertificate P component) :
    ∀ i ∈ C.selected,
      ¬ Acceptable P component (C.selected.erase i) := by
  intro i hi
  exact C.erase_not_acceptable hi

/-- Full restricted certificate, conditional only on the joined subspace being
nonzero. -/
structure StrictRegularCertificate
    (C : MinimalCertificate P component) where
  markedPermissible : MarkedIdeal.Permissible P C.ideal
  strict : C.ideal ≠ ⊥ ∧ C.ideal ≠ ⊤
  finiteType : C.ideal.FG
  quotientRegular : IsRegularRing
    (SymmetricAlgebra K V ⧸ C.ideal)
  indispensable : ∀ i ∈ C.selected,
    ¬ Acceptable P component (C.selected.erase i)

/-- Assemble every algebraic centre gate in the linear chamber. -/
noncomputable def strictRegularCertificate
    (C : MinimalCertificate P component)
    (hjoin : combinedSubspace component C.selected ≠ ⊥) :
    StrictRegularCertificate C where
  markedPermissible := C.acceptable
  strict := C.strict_iff_join_ne_bot.mpr hjoin
  finiteType := C.ideal_fg
  quotientRegular := C.quotient_isRegularRing
  indispensable := C.all_components_indispensable

end MinimalCertificate

/-- If the full linear component family is permissible, a cardinality-minimal
permissible linear hybrid exists. -/
theorem exists_minimalCertificate
    (P : MarkedIdeal.Packet (SymmetricAlgebra K V))
    (component : ι → Submodule K V)
    (hfull : Acceptable P component Finset.univ) :
    Nonempty (MinimalCertificate P component) := by
  classical
  let property : Nat → Prop := fun n =>
    ∃ selected : Finset ι,
      selected.card = n ∧ Acceptable P component selected
  have hex : ∃ n, property n :=
    ⟨Finset.univ.card, Finset.univ, rfl, hfull⟩
  obtain ⟨selected, hcard, hacceptable⟩ := Nat.find_spec hex
  refine ⟨{
    selected := selected
    acceptable := hacceptable
    cardinalMinimal := ?_
  }⟩
  intro candidate hcandidate
  have hproperty : property candidate.card :=
    ⟨candidate, rfl, hcandidate⟩
  have hmin : Nat.find hex ≤ candidate.card :=
    Nat.find_min' hex hproperty
  omega

/-- Expanded compiler theorem: the only remaining algebraic action boundary is
whether the selected joined subspace is zero. -/
theorem exists_minimal_regular_hybrid
    (P : MarkedIdeal.Packet (SymmetricAlgebra K V))
    (component : ι → Submodule K V)
    (hfull : Acceptable P component Finset.univ) :
    ∃ C : MinimalCertificate P component,
      MarkedIdeal.Permissible P C.ideal ∧
      C.ideal ≠ ⊤ ∧ C.ideal.FG ∧
      IsRegularRing (SymmetricAlgebra K V ⧸ C.ideal) ∧
      (C.ideal ≠ ⊥ ↔
        combinedSubspace component C.selected ≠ ⊥) := by
  obtain ⟨C⟩ := exists_minimalCertificate P component hfull
  refine ⟨C, C.acceptable, C.ideal_ne_top, C.ideal_fg,
    C.quotient_isRegularRing, ?_⟩
  have hstrict := C.strict_iff_join_ne_bot
  constructor
  · intro hbot hjoin
    exact hbot ((hstrict.mpr hjoin).1)
  · intro hjoin hbot
    exact hjoin ((hstrict.mp ⟨hbot, C.ideal_ne_top⟩))

end

end LinearMinimalHybridCompiler
end Experimental
end PCRLean
