import PCRLean.Experimental.LinearFrameSubspaceHeredity

#print axioms PCRLean.Experimental.LinearFrameSubspaceHeredity.map_centreIdeal_eq_frameCentreIdeal
#print axioms PCRLean.Experimental.LinearFrameSubspaceHeredity.map_frameCentreIdeal_eq_centreIdeal
#print axioms PCRLean.Experimental.LinearFrameSubspaceHeredity.mem_frameCentreIdeal_pow_iff
#print axioms PCRLean.Experimental.LinearFrameSubspaceHeredity.frameCentreIdeal_fg
#print axioms PCRLean.Experimental.LinearFrameSubspaceHeredity.frameCentreIdeal_ne_top
#print axioms PCRLean.Experimental.LinearFrameSubspaceHeredity.mem_frameCentreIdeal_pow_of_orderGE
#print axioms PCRLean.Experimental.LinearFrameSubspaceHeredity.frameCentreOrderGE_power_iff
#print axioms PCRLean.Experimental.LinearFrameSubspaceHeredity.frobeniusPower_mem_frameCentreIdeal_pow
