import PCRLean.Experimental.LinearSplitCentreBlowup

#print axioms PCRLean.Experimental.LinearSplitCentreBlowup.linearChartMap_forward
#print axioms PCRLean.Experimental.LinearSplitCentreBlowup.linearCentreSpan_eq_linearCentreIdeal
#print axioms PCRLean.Experimental.LinearSplitCentreBlowup.linearPassiveVar_fixed
#print axioms PCRLean.Experimental.LinearSplitCentreBlowup.linearCentreVar_factorization
#print axioms PCRLean.Experimental.LinearSplitCentreBlowup.linearCentreVar_pow_factorization
#print axioms PCRLean.Experimental.LinearSplitCentreBlowup.map_linearCentreSpan_le_linearPivotIdeal
#print axioms PCRLean.Experimental.LinearSplitCentreBlowup.map_linearCentreSpan_pow_le_linearPivotIdeal_pow
#print axioms PCRLean.Experimental.LinearSplitCentreBlowup.transformedLinearRootIdeal_eq_top
#print axioms PCRLean.Experimental.LinearSplitCentreBlowup.transformedLinearRootIdeal_eq
