import Mathlib
import PCRLean.Experimental.SurjectiveFiniteDimensionalRegularCentre
import PCRLean.Experimental.PacketCentreBoundary

/-!
# Experimental regularity of finite linear hybrid centres

A finite family of kernel, Frobenius-root, defect, or boundary components may
be represented by linear subspaces of one finite-dimensional conormal vector
space.  Their finite join is again a linear subspace.  The quotient map by this
join is surjective, and the intrinsic degree-one ideal generated by the join
has quotient equal to the symmetric algebra of the quotient vector space.

Thus, over a field, regularity and finite generation of a linear hybrid centre
are automatic after the component subspaces have been constructed.  The
separate finite minimal-hybrid compiler can therefore optimize marked
permissibility without re-proving regularity for every selected subfamily.

This theorem does not prove that the components are intrinsic, coherent on a
scheme, marked-permissible, owner-safe, boundary-transverse, or hereditary
under blowup.
-/

namespace PCRLean
namespace Experimental
namespace LinearHybridSubspaceCentre

noncomputable section

universe u v w

variable {K : Type u} [Field K]
variable {V : Type v} [AddCommGroup V] [Module K V]
variable [FiniteDimensional K V]

open IntrinsicKernelIdealFunctoriality
open SurjectiveFiniteDimensionalRegularCentre

/-- Intrinsic actual ideal attached to a linear subspace through the quotient
map `V -> V/N`. -/
def centreIdeal (N : Submodule K V) :
    Ideal (SymmetricAlgebra K V) :=
  SurjectiveFiniteDimensionalRegularCentre.centreIdeal N.mkQ

/-- The quotient projection is surjective. -/
theorem mkQ_surjective (N : Submodule K V) :
    Function.Surjective N.mkQ :=
  N.mkQ_surjective

/-- The intrinsic ideal is literally generated by the degree-one vectors of the
selected subspace. -/
theorem centreIdeal_eq_span_subspace (N : Submodule K V) :
    centreIdeal N =
      Ideal.span (Set.range fun x : N => SymmetricAlgebra.ι K V x.1) := by
  unfold centreIdeal SurjectiveFiniteDimensionalRegularCentre.centreIdeal
  unfold kernelIdealOf
  rw [Submodule.ker_mkQ]

/-- Exact quotient theorem for an arbitrary linear component sum. -/
noncomputable def quotientEquiv (N : Submodule K V) :
    (SymmetricAlgebra K V ⧸ centreIdeal N) ≃+*
      SymmetricAlgebra K (V ⧸ N) :=
  SurjectiveFiniteDimensionalRegularCentre.quotientEquiv
    N.mkQ (mkQ_surjective N)

/-- The subspace centre ideal is proper. -/
theorem centreIdeal_ne_top (N : Submodule K V) :
    centreIdeal N ≠ ⊤ :=
  SurjectiveFiniteDimensionalRegularCentre.centreIdeal_ne_top
    N.mkQ (mkQ_surjective N)

/-- The subspace centre ideal is finitely generated. -/
theorem centreIdeal_fg (N : Submodule K V) :
    (centreIdeal N).FG :=
  SurjectiveFiniteDimensionalRegularCentre.centreIdeal_fg
    N.mkQ (mkQ_surjective N)

/-- The quotient by any linear hybrid subspace centre is regular. -/
theorem quotient_isRegularRing (N : Submodule K V) :
    IsRegularRing (SymmetricAlgebra K V ⧸ centreIdeal N) :=
  SurjectiveFiniteDimensionalRegularCentre.quotient_isRegularRing
    N.mkQ (mkQ_surjective N)

/-- The centre is bottom exactly when the selected subspace is zero. -/
theorem centreIdeal_eq_bot_iff (N : Submodule K V) :
    centreIdeal N = ⊥ ↔ N = ⊥ := by
  calc
    centreIdeal N = ⊥ ↔ Function.Injective N.mkQ := by
      simpa [centreIdeal,
        SurjectiveFiniteDimensionalRegularCentre.centreIdeal,
        ArbitraryFiniteLinearPacketRegularCentre.centreIdeal] using
        (PacketCentreBoundary.centreIdeal_eq_bot_iff_injective N.mkQ)
    _ ↔ LinearMap.ker N.mkQ = ⊥ := LinearMap.ker_eq_bot.symm
    _ ↔ N = ⊥ := by rw [Submodule.ker_mkQ]

/-- A nonzero linear subspace gives a strict nonwhole centre ideal. -/
theorem strictCentre_iff_subspace_ne_bot (N : Submodule K V) :
    centreIdeal N ≠ ⊥ ∧ centreIdeal N ≠ ⊤ ↔ N ≠ ⊥ := by
  constructor
  · intro h hN
    exact h.1 ((centreIdeal_eq_bot_iff N).2 hN)
  · intro hN
    exact ⟨fun hbot => hN ((centreIdeal_eq_bot_iff N).1 hbot),
      centreIdeal_ne_top N⟩

section FiniteFamily

variable {ι : Type w} [Fintype ι] [DecidableEq ι]

/-- Linear subspace generated by a selected finite component family. -/
def combinedSubspace
    (component : ι → Submodule K V) (selected : Finset ι) :
    Submodule K V :=
  selected.sup component

/-- Actual ideal of a selected finite linear hybrid. -/
def combinedCentreIdeal
    (component : ι → Submodule K V) (selected : Finset ι) :
    Ideal (SymmetricAlgebra K V) :=
  centreIdeal (combinedSubspace component selected)

/-- Every finite selected linear hybrid has a regular quotient. -/
theorem combined_quotient_isRegularRing
    (component : ι → Submodule K V) (selected : Finset ι) :
    IsRegularRing
      (SymmetricAlgebra K V ⧸ combinedCentreIdeal component selected) :=
  quotient_isRegularRing (combinedSubspace component selected)

/-- The selected hybrid is nonwhole precisely when the joined component
subspace is nonzero. -/
theorem combined_strict_iff_join_ne_bot
    (component : ι → Submodule K V) (selected : Finset ι) :
    combinedCentreIdeal component selected ≠ ⊥ ∧
        combinedCentreIdeal component selected ≠ ⊤ ↔
      combinedSubspace component selected ≠ ⊥ :=
  strictCentre_iff_subspace_ne_bot (combinedSubspace component selected)

end FiniteFamily

end

end LinearHybridSubspaceCentre
end Experimental
end PCRLean
