import PCRLean.Experimental.MarkedPermissibilityFaithfullyFlatDescent

#print axioms PCRLean.Experimental.MarkedPermissibilityFaithfullyFlatDescent.mem_iff_map_mem_extend
#print axioms PCRLean.Experimental.MarkedPermissibilityFaithfullyFlatDescent.le_of_extend_le
#print axioms PCRLean.Experimental.MarkedPermissibilityFaithfullyFlatDescent.extend_eq_iff
#print axioms PCRLean.Experimental.MarkedPermissibilityFaithfullyFlatDescent.extend_eq_top_iff
#print axioms PCRLean.Experimental.MarkedPermissibilityFaithfullyFlatDescent.extend_eq_bot_iff
#print axioms PCRLean.Experimental.MarkedPermissibilityFaithfullyFlatDescent.extend_le_pow_iff
#print axioms PCRLean.Experimental.MarkedPermissibilityFaithfullyFlatDescent.permissible_extend_iff
