import PCRLean.Experimental.MaximalMinorResolutionKernelIndex

#print axioms PCRLean.Experimental.FittingMinorFaithfulCover.eq_of_chart_algebraMap_eq
#print axioms PCRLean.Experimental.FittingMinorFaithfulCover.funext_of_chart_algebraMap_eq
#print axioms PCRLean.Experimental.AugmentedMinorRangeNecessity.augmented_mul_eliminateLastColumn
#print axioms PCRLean.Experimental.AugmentedMinorRangeNecessity.det_augmented_eq_zero_of_solution
#print axioms PCRLean.Experimental.MaximalMinorRangeCriterion.packet_mulVec_injective
#print axioms PCRLean.Experimental.MaximalMinorRangeCriterion.globalGraph_solves
#print axioms PCRLean.Experimental.MaximalMinorRangeCriterion.solution_eq_globalGraph
#print axioms PCRLean.Experimental.MaximalMinorRangeCriterion.augmentedRankCondition_iff_exists_solution
#print axioms PCRLean.Experimental.MaximalMinorRangeCriterion.augmentedRankCondition_iff_existsUnique_solution
#print axioms PCRLean.Experimental.MaximalMinorGlobalResolutionMacro.certificate
#print axioms PCRLean.Experimental.MaximalMinorPresentationIndependence.EquationEquivalence.augmentedRankCondition_iff
#print axioms PCRLean.Experimental.MaximalMinorPresentationIndependence.EquationEquivalence.globalGraph_eq
#print axioms PCRLean.Experimental.PolynomialGraphSupportEquality.primePoint_contains_source_iff_contains_graph
#print axioms PCRLean.Experimental.PolynomialGraphActionBoundary.graphIdeal_eq_span_singleton
#print axioms PCRLean.Experimental.PolynomialGraphActionBoundary.actionClass
#print axioms PCRLean.Experimental.MaximalMinorResolutionKernelIndex.loaded
