import Mathlib
import Mathlib.LinearAlgebra.Matrix.Adjugate
import PCRLean.ActualIdealGluing
import PCRLean.Experimental.MaximalMinorAtlas
import PCRLean.Experimental.PolynomialGraphCentreHeredity

/-!
# The full rectangular packet ideal is the graph-centre ideal

Let `M : κ × ι → R`, let `b : κ → R`, and suppose the maximal row minors of
`M` generate the unit ideal.  If `h` is any solution of `M h = b`, define the
full affine equation ideal in `R[Z_i]` by all rows

`Σ_j M_{rj} Z_j - b_r`.

Then this full equation ideal is exactly the graph ideal

`(Z_i - h_i : i ∈ ι)`.

The easy inclusion writes every packet equation as a linear combination of the
graph equations.  For the reverse inclusion, on every maximal row selection
`s` the adjugate identity gives

`det(M_s) (Z-h) = adj(M_s) · (selected packet equations)`.

Thus every determinant multiple of every graph generator lies in the full
packet ideal.  Since the maximal minors generate `1`, these memberships patch
directly in the base ring, without localization or a separate ideal-descent
argument.

This theorem upgrades the current determinantal architecture: the actual
centre is already the ideal generated by the original finite packet equations,
not merely a graph ideal reconstructed after choosing local minors.
-/

namespace PCRLean
namespace Experimental
namespace MaximalMinorEquationIdeal

noncomputable section

universe u v w

variable {R : Type u} [CommRing R]
variable {κ : Type v} [Fintype κ]
variable {ι : Type w} [Fintype ι] [DecidableEq ι]

open MaximalMinorAtlas
open PolynomialGraphCentreHeredity

abbrev P := MvPolynomial ι R

/-- One affine equation of the full rectangular packet. -/
def equation
    (M : Matrix κ ι R) (b : κ → R) (r : κ) :
    P (R := R) (ι := ι) :=
  (∑ j : ι, MvPolynomial.C (M r j) * MvPolynomial.X j) -
    MvPolynomial.C (b r)

/-- Actual ideal generated by every row of the original packet. -/
def equationIdeal
    (M : Matrix κ ι R) (b : κ → R) :
    Ideal (P (R := R) (ι := ι)) :=
  ActualIdealGluing.generatedIdeal (equation M b)

/-- The same ideal viewed as an `R`-submodule, for patching determinant
multiples using the unit-ideal cover. -/
def equationRSubmodule
    (M : Matrix κ ι R) (b : κ → R) :
    Submodule R (P (R := R) (ι := ι)) where
  carrier := equationIdeal M b
  zero_mem' := (equationIdeal M b).zero_mem
  add_mem' := (equationIdeal M b).add_mem
  smul_mem' := by
    intro r f hf
    change MvPolynomial.C r * f ∈ equationIdeal M b
    exact (equationIdeal M b).mul_mem_left _ hf

/-- The graph-equation vector attached to a candidate solution. -/
def graphVector (h : ι → R) : ι → P (R := R) (ι := ι) :=
  fun i => graphGenerator h i

/-- Every full packet equation is the corresponding row combination of the
graph equations whenever `h` solves `M h = b`. -/
theorem equation_eq_graph_combination
    (M : Matrix κ ι R) (b : κ → R) (h : ι → R)
    (hsol : M.mulVec h = b) (r : κ) :
    equation M b r =
      ∑ j : ι, MvPolynomial.C (M r j) * graphGenerator h j := by
  rw [equation]
  simp_rw [graphGenerator, mul_sub]
  rw [Finset.sum_sub_distrib]
  congr 1
  calc
    (∑ j : ι,
      MvPolynomial.C (M r j) * MvPolynomial.C (h j)) =
        MvPolynomial.C (∑ j : ι, M r j * h j) := by simp
    _ = MvPolynomial.C (b r) := by
      rw [← Matrix.mulVec_apply_eq_sum, hsol]

/-- Hence the full packet ideal is contained in the graph ideal. -/
theorem equationIdeal_le_graphIdeal
    (M : Matrix κ ι R) (b : κ → R) (h : ι → R)
    (hsol : M.mulVec h = b) :
    equationIdeal M b ≤ graphIdeal h := by
  rw [equationIdeal, ActualIdealGluing.generatedIdeal, Ideal.span_le]
  rintro x ⟨r, rfl⟩
  rw [equation_eq_graph_combination M b h hsol r]
  exact (graphIdeal h).sum_mem fun j _ =>
    (graphIdeal h).mul_mem_left _ (graphGenerator_mem h j)

/-- Selected equation vector for one maximal row minor. -/
def selectedEquationVector
    (M : Matrix κ ι R) (b : κ → R)
    (s : Selection (κ := κ) (ι := ι)) :
    ι → P (R := R) (ι := ι) :=
  fun i => equation M b (s i)

/-- Selected coefficient matrix over the polynomial ring. -/
def selectedPolynomialMatrix
    (M : Matrix κ ι R)
    (s : Selection (κ := κ) (ι := ι)) :
    Matrix ι ι (P (R := R) (ι := ι)) :=
  (selectedMatrix M s).map MvPolynomial.C

/-- The selected packet equations are the selected matrix applied to the graph
vector. -/
theorem selectedEquationVector_eq_mulVec
    (M : Matrix κ ι R) (b : κ → R) (h : ι → R)
    (hsol : M.mulVec h = b)
    (s : Selection (κ := κ) (ι := ι)) :
    selectedEquationVector M b s =
      (selectedPolynomialMatrix M s).mulVec (graphVector h) := by
  funext i
  rw [selectedEquationVector,
    equation_eq_graph_combination M b h hsol (s i)]
  rfl

/-- The adjugate of one selected minor recovers the determinant multiple of
every graph equation. -/
theorem adjugate_mulVec_selectedEquationVector
    (M : Matrix κ ι R) (b : κ → R) (h : ι → R)
    (hsol : M.mulVec h = b)
    (s : Selection (κ := κ) (ι := ι)) :
    (selectedPolynomialMatrix M s).adjugate.mulVec
        (selectedEquationVector M b s) =
      fun i =>
        MvPolynomial.C (determinant M s) * graphGenerator h i := by
  rw [selectedEquationVector_eq_mulVec M b h hsol s,
    Matrix.mulVec_mulVec, Matrix.adjugate_mul]
  funext i
  simp [selectedPolynomialMatrix, determinant, graphVector]

/-- Every maximal-minor determinant multiple of every graph generator belongs
to the full packet ideal. -/
theorem determinant_mul_graphGenerator_mem
    (M : Matrix κ ι R) (b : κ → R) (h : ι → R)
    (hsol : M.mulVec h = b)
    (s : Selection (κ := κ) (ι := ι)) (i : ι) :
    MvPolynomial.C (determinant M s) * graphGenerator h i ∈
      equationIdeal M b := by
  have hcomponent :
      (selectedPolynomialMatrix M s).adjugate.mulVec
          (selectedEquationVector M b s) i ∈ equationIdeal M b := by
    rw [Matrix.mulVec_apply_eq_sum]
    exact (equationIdeal M b).sum_mem fun j _ =>
      (equationIdeal M b).mul_mem_left _
        (ActualIdealGluing.generator_mem (equation M b) (s j))
  rw [congrFun
    (adjugate_mulVec_selectedEquationVector M b h hsol s) i]
    at hcomponent
  exact hcomponent

/-- Unit generation by maximal minors patches the determinant multiples and
puts every graph generator in the original packet ideal. -/
theorem graphGenerator_mem_equationIdeal
    (M : Matrix κ ι R) (b : κ → R) (h : ι → R)
    (hsol : M.mulVec h = b)
    (Hrank : FullRankCover M)
    (i : ι) :
    graphGenerator h i ∈ equationIdeal M b := by
  change graphGenerator h i ∈ equationRSubmodule M b
  apply Submodule.mem_of_span_top_of_smul_mem
    (equationRSubmodule M b)
    (Set.range (determinant M)) Hrank.cover
    (graphGenerator h i)
  rintro ⟨d, ⟨s, rfl⟩⟩
  change MvPolynomial.C (determinant M s) * graphGenerator h i ∈
    equationIdeal M b
  exact determinant_mul_graphGenerator_mem M b h hsol s i

/-- Main theorem: on the full-rank locus, the ideal generated by all original
rectangular packet equations is exactly the graph centre of any solution. -/
theorem equationIdeal_eq_graphIdeal
    (M : Matrix κ ι R) (b : κ → R) (h : ι → R)
    (hsol : M.mulVec h = b)
    (Hrank : FullRankCover M) :
    equationIdeal M b = graphIdeal h := by
  apply le_antisymm
  · exact equationIdeal_le_graphIdeal M b h hsol
  · rw [graphIdeal, Ideal.span_le]
    rintro x ⟨i, rfl⟩
    exact graphGenerator_mem_equationIdeal M b h hsol Hrank i

end

end MaximalMinorEquationIdeal
end Experimental
end PCRLean
