import PCRLean.Experimental.MaximalMinorPresentationIndependence

#print axioms PCRLean.Experimental.MaximalMinorPresentationIndependence.EquationEquivalence.solution_iff
#print axioms PCRLean.Experimental.MaximalMinorPresentationIndependence.EquationEquivalence.exists_solution_iff
#print axioms PCRLean.Experimental.MaximalMinorPresentationIndependence.EquationEquivalence.existsUnique_solution_iff
#print axioms PCRLean.Experimental.MaximalMinorPresentationIndependence.EquationEquivalence.augmentedRankCondition_iff
#print axioms PCRLean.Experimental.MaximalMinorPresentationIndependence.EquationEquivalence.transportAugmented
#print axioms PCRLean.Experimental.MaximalMinorPresentationIndependence.EquationEquivalence.globalGraph_eq
