import PCRLean.Experimental.FittingMinorFaithfulCover
import PCRLean.Experimental.AugmentedMinorRangeNecessity
import PCRLean.Experimental.MaximalMinorRangeCriterion
import PCRLean.Experimental.MaximalMinorEquationIdeal
import PCRLean.Experimental.MaximalMinorGlobalResolutionMacro
import PCRLean.Experimental.MaximalMinorPresentationIndependence
import PCRLean.Experimental.MaximalMinorAffineEquivalence
import PCRLean.Experimental.MaximalMinorColumnChange
import PCRLean.Experimental.PolynomialGraphSupportEquality
import PCRLean.Experimental.PolynomialGraphActionBoundary

/-!
# Focused maximal-minor resolution index

This index isolates the new determinantal bridge of the current round:

* finite Fitting covers jointly reflect equality;
* every actual solution forces augmented-minor vanishing;
* full maximal-minor cover plus augmented-minor vanishing is equivalent to
  unique solvability;
* the ideal generated by all original rectangular packet equations is exactly
  the resulting graph-centre ideal, by an adjugate and unit-minor patching
  argument;
* the complete global affine graph-resolution macro is therefore defined by
  the original packet itself;
* the criterion and global graph are independent of equation frames and of
  arbitrary invertible normal-coordinate changes;
* the pure graph-root packet has exactly the graph support; and
* the one-normal-variable Cartier boundary is separated from higher-rank
  ordinary-centre candidates.

The index is experimental and does not assert general resolution.
-/

namespace PCRLean
namespace Experimental
namespace MaximalMinorResolutionKernelIndex

/-- Marker theorem confirming elaboration of the focused dependency graph. -/
theorem loaded : True := True.intro

end MaximalMinorResolutionKernelIndex
end Experimental
end PCRLean
