import Mathlib
import PCRLean.ActualIdealGluing
import PCRLean.Experimental.FittingGaugeCentreOverlap

/-!
# Global centres as images of finite module morphisms

A centre ideal should not be created by gluing coordinate tuples.  The more
intrinsic input is a global module morphism

`φ : M →ₗ[R] R`.

Its image is automatically an ideal of `R`.  A finite local frame of `M` merely
presents that already existing ideal by finitely many equations.  Changing the
frame by an invertible matrix changes the equation vector but not the image
ideal.

This separates construction from verification:

* the intrinsic Frobenius/Hasse/conormal theory must produce `M` and `φ`;
* finite generation gives local equation frames;
* Fitting minors prove that the image ideal is locally a regular graph centre;
* no global basis or global graph tuple is required.

The file proves the affine algebraic core and exact behavior under coefficient
extension for a chosen finite spanning frame.
-/

namespace PCRLean
namespace Experimental
namespace ModuleImageCentre

noncomputable section

universe u v w

variable {R : Type u} [CommRing R]
variable {M : Type v} [AddCommGroup M] [Module R M]

/-- The image of an `R`-linear functional, viewed as an actual ideal of `R`. -/
def imageIdeal (φ : M →ₗ[R] R) : Ideal R :=
  LinearMap.range φ

@[simp] theorem mem_imageIdeal_iff
    (φ : M →ₗ[R] R) (x : R) :
    x ∈ imageIdeal φ ↔ ∃ m : M, φ m = x := by
  rfl

/-- Every value of the morphism belongs to its image ideal. -/
theorem apply_mem_imageIdeal
    (φ : M →ₗ[R] R) (m : M) :
    φ m ∈ imageIdeal φ := by
  exact LinearMap.mem_range_self φ m

/-- Surjectively changing the source module does not change the image centre. -/
theorem imageIdeal_comp_of_surjective
    {N : Type w} [AddCommGroup N] [Module R N]
    (φ : M →ₗ[R] R) (e : N →ₗ[R] M)
    (he : Function.Surjective e) :
    imageIdeal (φ.comp e) = imageIdeal φ := by
  apply le_antisymm
  · rintro x ⟨n, rfl⟩
    exact apply_mem_imageIdeal φ (e n)
  · rintro x ⟨m, rfl⟩
    obtain ⟨n, rfl⟩ := he m
    exact ⟨n, rfl⟩

section FiniteFrame

variable {ι : Type w} [Fintype ι]

/-- A finite family spanning the source module. -/
structure SpanningFrame where
  vector : ι → M
  spans : Submodule.span R (Set.range vector) = ⊤

namespace SpanningFrame

variable (F : SpanningFrame (R := R) (M := M) (ι := ι))

/-- Equation vector of the image centre in the chosen frame. -/
def equation (φ : M →ₗ[R] R) : ι → R :=
  fun i => φ (F.vector i)

/-- Every morphism value belongs to the ideal generated by the frame equations. -/
theorem apply_mem_generatedIdeal
    (φ : M →ₗ[R] R) (m : M) :
    φ m ∈ ActualIdealGluing.generatedIdeal (F.equation φ) := by
  have hm : m ∈ Submodule.span R (Set.range F.vector) := by
    rw [F.spans]
    trivial
  induction hm using Submodule.span_induction with
  | mem x hx =>
      rcases hx with ⟨i, rfl⟩
      exact ActualIdealGluing.generator_mem (F.equation φ) i
  | zero => simpa using
      (ActualIdealGluing.generatedIdeal (F.equation φ)).zero_mem
  | add x y hx hy hxi hyi =>
      simpa using
        (ActualIdealGluing.generatedIdeal (F.equation φ)).add_mem hxi hyi
  | smul a x hx hxi =>
      simpa [equation] using
        (ActualIdealGluing.generatedIdeal (F.equation φ)).mul_mem_left a hxi

/-- A finite frame presents the intrinsic image ideal exactly. -/
theorem generatedIdeal_eq_imageIdeal
    (φ : M →ₗ[R] R) :
    ActualIdealGluing.generatedIdeal (F.equation φ) =
      imageIdeal φ := by
  apply le_antisymm
  · rw [ActualIdealGluing.generatedIdeal, Ideal.span_le]
    rintro x ⟨i, rfl⟩
    exact apply_mem_imageIdeal φ (F.vector i)
  · rintro x ⟨m, rfl⟩
    exact F.apply_mem_generatedIdeal φ m

/-- The image ideal is finitely generated whenever a finite spanning frame is
provided. -/
theorem imageIdeal_fg (φ : M →ₗ[R] R) : (imageIdeal φ).FG := by
  rw [← F.generatedIdeal_eq_imageIdeal φ]
  exact Ideal.fg_span_finset
    (Finset.univ.image (F.equation φ))

section BaseChange

variable {S : Type*} [CommRing S] [Algebra R S]

/-- The extension of the intrinsic image ideal is generated by the mapped frame
equations. -/
theorem map_imageIdeal_eq_generatedIdeal
    (φ : M →ₗ[R] R) :
    Ideal.map (algebraMap R S) (imageIdeal φ) =
      ActualIdealGluing.generatedIdeal
        (fun i => algebraMap R S (F.equation φ i)) := by
  rw [← F.generatedIdeal_eq_imageIdeal φ]
  exact FittingGaugeCentreOverlap.map_generatedIdeal
    (algebraMap R S) (F.equation φ)

end BaseChange

end SpanningFrame

end FiniteFrame

end

end ModuleImageCentre
end Experimental
end PCRLean
