import PCRLean.Experimental.MultivariateOrderIdealBridge

#print axioms PCRLean.Experimental.MultivariateOrderIdealBridge.exponentDegree_eq_degree
#print axioms PCRLean.Experimental.MultivariateOrderIdealBridge.X_mem_originIdeal
#print axioms PCRLean.Experimental.MultivariateOrderIdealBridge.mem_originIdeal_pow_iff_orderGE
#print axioms PCRLean.Experimental.MultivariateOrderIdealBridge.mem_originIdeal_pow_of_orderGE
#print axioms PCRLean.Experimental.MultivariateOrderIdealBridge.orderGE_of_mem_originIdeal_pow
#print axioms PCRLean.Experimental.MultivariateOrderIdealBridge.frobeniusPower_mem_originIdeal_pow
