import Mathlib
import PCRLean.Experimental.FrobeniusFiniteRootGeneration
import PCRLean.Experimental.MultiOwnerDualAffineFrobeniusChamber

/-!
# Experimental multi-owner chamber from finite Frobenius packet powers

In characteristic `p`, at mark `q = p^e`, the full row-span root package equals
the finite ideal generated by the `q`-th powers of the named packet rows.  Thus
the multi-owner root-realization hypothesis may be stated as one finite ideal
equality.  From that equality the actual affine row-span centre is permissible
for every active owner and their union, proper and finite type, with regular
quotient and the correct common tangent kernel.

This removes the infinite row-span object from the geometric hypothesis.  It
does not prove that arbitrary joint Hasse cores satisfy the finite packet-power
equality or that the resulting centre transports through all blowup charts.
-/

namespace PCRLean
namespace Experimental
namespace MultiOwnerFiniteFrobeniusPacketChamber

noncomputable section

universe u v w x y

variable {R : Type u} {K : Type v}
variable [CommRing R] [Field K]
variable {σ : Type w} [Fintype σ] [DecidableEq σ]
variable {κ : Type x} [Fintype κ]
variable {ω : Type y} [Fintype ω] [DecidableEq ω]
variable {spec : List (Nat × R)}
variable (p : Nat) [Fact p.Prime] [CharP K p]

abbrev Direction := σ → K
abbrev Dual := Module.Dual K (Direction (K := K) (σ := σ))
abbrev A := MvPolynomial σ K

variable [Algebra R (A (K := K) (σ := σ))]

open FrobeniusFiniteRootGeneration

/-- A finite packet-power realization gives the full row-span root realization. -/
theorem fullRootRealization_of_finite
    (F : MultiHasseOnlyDescent.RealizedFrame
      (R := R) (A := A (K := K) (σ := σ)) spec)
    (owners : ω → Ideal (A (K := K) (σ := σ)))
    (packet : κ → Dual (K := K) (σ := σ))
    (e : Nat)
    (hsource :
      (MultiOwnerHasseCore.jointCore F owners).map
          (algebraMap R (A (K := K) (σ := σ))) =
        packetPowerIdeal p packet e) :
    (MultiOwnerHasseCore.jointCore F owners).map
        (algebraMap R (A (K := K) (σ := σ))) =
      DualPacketAffineRootPackage.actualRootPowerIdeal packet (p ^ e) :=
  hsource.trans
    (actualRootPowerIdeal_eq_packetPowerIdeal p packet e).symm

/-- Every owner is permissible from the finite packet-power equality. -/
theorem every_owner_permissible
    (F : MultiHasseOnlyDescent.RealizedFrame
      (R := R) (A := A (K := K) (σ := σ)) spec)
    (owners : ω → Ideal (A (K := K) (σ := σ)))
    (hstable : ∀ i,
      DifferentialIdealSaturation.Stable F.hasseAddHom (owners i))
    (packet : κ → Dual (K := K) (σ := σ))
    (e : Nat)
    (hsource :
      (MultiOwnerHasseCore.jointCore F owners).map
          (algebraMap R (A (K := K) (σ := σ))) =
        packetPowerIdeal p packet e)
    (i : ω) :
    MarkedIdeal.Permissible
      (R := A (K := K) (σ := σ))
      ⟨owners i, p ^ e, pow_pos (Fact.out : p.Prime).pos e⟩
      (DualPacketAffineLinearRealization.actualIdeal packet) := by
  exact MultiOwnerDualAffineFrobeniusChamber.every_owner_permissible
    F owners hstable packet
    (pow_pos (Fact.out : p.Prime).pos e)
    (fullRootRealization_of_finite p F owners packet e hsource) i

/-- The finite union of active owners is permissible from the finite equality. -/
theorem jointOwnerIdeal_permissible
    (F : MultiHasseOnlyDescent.RealizedFrame
      (R := R) (A := A (K := K) (σ := σ)) spec)
    (owners : ω → Ideal (A (K := K) (σ := σ)))
    (hstable : ∀ i,
      DifferentialIdealSaturation.Stable F.hasseAddHom (owners i))
    (packet : κ → Dual (K := K) (σ := σ))
    (e : Nat)
    (hsource :
      (MultiOwnerHasseCore.jointCore F owners).map
          (algebraMap R (A (K := K) (σ := σ))) =
        packetPowerIdeal p packet e) :
    MarkedIdeal.Permissible
      (R := A (K := K) (σ := σ))
      ⟨MultiOwnerHasseCore.jointOwnerIdeal owners,
        p ^ e, pow_pos (Fact.out : p.Prime).pos e⟩
      (DualPacketAffineLinearRealization.actualIdeal packet) := by
  exact MultiOwnerDualAffineFrobeniusChamber.jointOwnerIdeal_permissible
    F owners hstable packet
    (pow_pos (Fact.out : p.Prime).pos e)
    (fullRootRealization_of_finite p F owners packet e hsource)

/-- Complete actual affine multi-owner certificate from the finite packet-power
realization equality. -/
noncomputable def certificate
    (F : MultiHasseOnlyDescent.RealizedFrame
      (R := R) (A := A (K := K) (σ := σ)) spec)
    (owners : ω → Ideal (A (K := K) (σ := σ)))
    (hstable : ∀ i,
      DifferentialIdealSaturation.Stable F.hasseAddHom (owners i))
    (packet : κ → Dual (K := K) (σ := σ))
    (e : Nat)
    (hsource :
      (MultiOwnerHasseCore.jointCore F owners).map
          (algebraMap R (A (K := K) (σ := σ))) =
        packetPowerIdeal p packet e) :
    MultiOwnerDualAffineFrobeniusChamber.Certificate
      owners packet (p ^ e) (pow_pos (Fact.out : p.Prime).pos e) :=
  MultiOwnerDualAffineFrobeniusChamber.certificate
    F owners hstable packet
    (pow_pos (Fact.out : p.Prime).pos e)
    (fullRootRealization_of_finite p F owners packet e hsource)

end

end MultiOwnerFiniteFrobeniusPacketChamber
end Experimental
end PCRLean
