import PCRLean.Experimental.MultivariatePointIdealBridge

#print axioms PCRLean.Experimental.MultivariatePointIdealBridge.translate_comp_neg
#print axioms PCRLean.Experimental.MultivariatePointIdealBridge.translate_neg_comp
#print axioms PCRLean.Experimental.MultivariatePointIdealBridge.translateEquiv
#print axioms PCRLean.Experimental.MultivariatePointIdealBridge.map_pointIdeal_eq_originIdeal
#print axioms PCRLean.Experimental.MultivariatePointIdealBridge.map_originIdeal_eq_pointIdeal
#print axioms PCRLean.Experimental.MultivariatePointIdealBridge.map_pointIdeal_pow_eq_originIdeal_pow
#print axioms PCRLean.Experimental.MultivariatePointIdealBridge.map_originIdeal_pow_eq_pointIdeal_pow
#print axioms PCRLean.Experimental.MultivariatePointIdealBridge.mem_pointIdeal_pow_iff
#print axioms PCRLean.Experimental.MultivariatePointIdealBridge.mem_pointIdeal_pow_of_atPointOrderGE
#print axioms PCRLean.Experimental.MultivariatePointIdealBridge.frobeniusPower_mem_pointIdeal_pow
