import PCRLean.Experimental.MultivariateFrobeniusOrderHeredity

#print axioms PCRLean.Experimental.MultivariateFrobeniusOrderHeredity.scaleExponent_injective
#print axioms PCRLean.Experimental.MultivariateFrobeniusOrderHeredity.exponentDegree_scale
#print axioms PCRLean.Experimental.MultivariateFrobeniusOrderHeredity.frobeniusPower_expansion
#print axioms PCRLean.Experimental.MultivariateFrobeniusOrderHeredity.scaled_mem_support
#print axioms PCRLean.Experimental.MultivariateFrobeniusOrderHeredity.mem_support_power_exists_scaled
#print axioms PCRLean.Experimental.MultivariateFrobeniusOrderHeredity.mem_support_power_iff
#print axioms PCRLean.Experimental.MultivariateFrobeniusOrderHeredity.orderGE_power_iff
#print axioms PCRLean.Experimental.MultivariateFrobeniusOrderHeredity.atPointOrderGE_power_iff
