import PCRLean.Experimental.NestedPolynomialGraphFlattening

#print axioms PCRLean.Experimental.NestedPolynomialGraphFlattening.flatten_X
#print axioms PCRLean.Experimental.NestedPolynomialGraphFlattening.flatten_C_X
#print axioms PCRLean.Experimental.NestedPolynomialGraphFlattening.flatten_C_C
#print axioms PCRLean.Experimental.NestedPolynomialGraphFlattening.flatten_reducedOuterGenerator
#print axioms PCRLean.Experimental.NestedPolynomialGraphFlattening.flatten_innerGenerator
#print axioms PCRLean.Experimental.NestedPolynomialGraphFlattening.map_reducedHybridIdeal_eq_graphIdeal
#print axioms PCRLean.Experimental.NestedPolynomialGraphFlattening.map_hybridIdeal_eq_graphIdeal
#print axioms PCRLean.Experimental.NestedPolynomialGraphFlattening.flattened_transformedRootIdeal_eq_top
#print axioms PCRLean.Experimental.NestedPolynomialGraphFlattening.flattened_transformedRootIdeal_eq
