import PCRLean.Experimental.NestedPolynomialGraphHybrid

#print axioms PCRLean.Experimental.NestedPolynomialGraphHybrid.coefficient_sub_reduced_mem_innerIdeal
#print axioms PCRLean.Experimental.NestedPolynomialGraphHybrid.graphGenerator_sub_reduced_mem_extendedInnerIdeal
#print axioms PCRLean.Experimental.NestedPolynomialGraphHybrid.original_generator_mem_reduced
#print axioms PCRLean.Experimental.NestedPolynomialGraphHybrid.reduced_generator_mem_original
#print axioms PCRLean.Experimental.NestedPolynomialGraphHybrid.hybridIdeal_eq_reducedHybridIdeal
#print axioms PCRLean.Experimental.NestedPolynomialGraphHybrid.quotientEquivInner
#print axioms PCRLean.Experimental.NestedPolynomialGraphHybrid.quotientEquiv
#print axioms PCRLean.Experimental.NestedPolynomialGraphHybrid.quotient_isRegularRing
