import PCRLean.Experimental.NoetherianOrbitMultiOwnerAffineChamber

#print axioms PCRLean.Experimental.NoetherianOrbitMultiOwnerAffineChamber.assemble
#print axioms PCRLean.Experimental.NoetherianOrbitMultiOwnerAffineChamber.exists_certificate
