import PCRLean.Experimental.NoetherianAffineOrbitPacket

#print axioms PCRLean.Experimental.NoetherianAffineOrbitPacket.Certificate.orbitSolution_of_finiteSolution
#print axioms PCRLean.Experimental.NoetherianAffineOrbitPacket.Certificate.finiteSolution_of_orbitSolution
#print axioms PCRLean.Experimental.NoetherianAffineOrbitPacket.Certificate.finiteSolution_iff_orbitSolution
#print axioms PCRLean.Experimental.NoetherianAffineOrbitPacket.Certificate.finitePacket_solution_iff_orbitSolution
#print axioms PCRLean.Experimental.NoetherianAffineOrbitPacket.finitePacket_choice_independent
#print axioms PCRLean.Experimental.NoetherianAffineOrbitPacket.intrinsicSolution_isOrbitSolution
#print axioms PCRLean.Experimental.NoetherianAffineOrbitPacket.existsUnique_orbitSolution
