import Mathlib
import PCRLean.Experimental.NoetherianOrbitDualRegularCentre
import PCRLean.Experimental.MultiOwnerFiniteFrobeniusPacketChamber
import PCRLean.Experimental.DualPacketAffineLinearRealization

/-!
# Experimental Noetherian-orbit finite Frobenius affine chamber

A represented Noetherian operator orbit supplies a finite raw covector packet.
In characteristic `p`, the full row-span root package at mark `p^e` is exactly
the finite ideal generated by the `p^e`-th powers of those named raw packet
rows.  Hence one finite ideal equality with the extended joint Hasse core
produces the actual affine regular centre, all active-owner permissibility and
the persistent tangent annihilator of the full infinite orbit.

This is the strongest current local algebraic U1--U3 certificate.  Its sole
root-effectivity input is finite and explicit.  Universal representation,
proof of that finite equality for arbitrary prepared singularities, passive and
boundary safety, nonlinear blowup-chart transport, immediate-defect escape and
globalization remain open.
-/

namespace PCRLean
namespace Experimental
namespace NoetherianOrbitFiniteFrobeniusAffineChamber

noncomputable section

universe u v w x y z

variable {R : Type u} {K : Type v}
variable [CommRing R] [Field K]
variable {D : Type w} [AddCommGroup D] [Module K D]
variable {σ : Type x} [Fintype σ] [DecidableEq σ]
variable {ι : Type y}
variable {ω : Type z} [Fintype ω] [DecidableEq ω]
variable [IsNoetherian K D]
variable {spec : List (Nat × R)}
variable (p : Nat) [Fact p.Prime] [CharP K p]

abbrev Direction := σ → K
abbrev Dual := Module.Dual K (Direction (K := K) (σ := σ))
abbrev A := MvPolynomial σ K

variable [Algebra R (A (K := K) (σ := σ))]

open NoetherianOrbitDualRegularCentre
open MultiOwnerFiniteFrobeniusPacketChamber

/-- Combined finite-Frobenius orbit and actual-affine owner certificate. -/
structure Certificate
    (F : MultiHasseOnlyDescent.RealizedFrame
      (R := R) (A := A (K := K) (σ := σ)) spec)
    (owners : ω → Ideal (A (K := K) (σ := σ)))
    (ops : ι → Module.End K D) (seed : D)
    (pair : D →ₗ[K] Dual (K := K) (σ := σ))
    (e : Nat) where
  orbit : NoetherianOrbitDualRegularCentre.Certificate ops seed pair
  finiteRootRealization :
    (MultiOwnerHasseCore.jointCore F owners).map
        (algebraMap R (A (K := K) (σ := σ))) =
      FrobeniusFiniteRootGeneration.packetPowerIdeal p
        (NoetherianOrbitDualRegularCentre.packetCovector pair orbit.packet) e
  ownerCentre : MultiOwnerDualAffineFrobeniusChamber.Certificate
    owners
    (NoetherianOrbitDualRegularCentre.packetCovector pair orbit.packet)
    (p ^ e) (pow_pos (Fact.out : p.Prime).pos e)
  abstractCentre_maps_to_actualCentre :
    Ideal.map
        (DualPacketAffineLinearRealization.symToPoly
          (K := K) (σ := σ))
        orbit.centreIdeal = ownerCentre.centreIdeal
  persistentTangent_eq_actualCentreTangent :
    NoetherianOperatorOrbit.annihilatorVia pair
        (NoetherianOperatorOrbit.orbitModule ops seed) =
      ownerCentre.tangentSpace

/-- Assemble the strongest current local certificate from one finite raw orbit
certificate and one finite packet-power realization equality. -/
noncomputable def assemble
    (F : MultiHasseOnlyDescent.RealizedFrame
      (R := R) (A := A (K := K) (σ := σ)) spec)
    (owners : ω → Ideal (A (K := K) (σ := σ)))
    (hstable : ∀ i,
      DifferentialIdealSaturation.Stable F.hasseAddHom (owners i))
    (ops : ι → Module.End K D) (seed : D)
    (pair : D →ₗ[K] Dual (K := K) (σ := σ))
    (C : NoetherianOrbitDualRegularCentre.Certificate ops seed pair)
    (e : Nat)
    (hroot :
      (MultiOwnerHasseCore.jointCore F owners).map
          (algebraMap R (A (K := K) (σ := σ))) =
        FrobeniusFiniteRootGeneration.packetPowerIdeal p
          (NoetherianOrbitDualRegularCentre.packetCovector pair C.packet) e) :
    Certificate p F owners ops seed pair e := by
  let OC := MultiOwnerFiniteFrobeniusPacketChamber.certificate
    p F owners hstable
    (NoetherianOrbitDualRegularCentre.packetCovector pair C.packet)
    e hroot
  refine {
    orbit := C
    finiteRootRealization := hroot
    ownerCentre := OC
    abstractCentre_maps_to_actualCentre := ?_
    persistentTangent_eq_actualCentreTangent := ?_
  }
  · rw [C.centreIdeal_eq]
    exact DualPacketAffineLinearRealization.map_centreIdeal_eq_actualIdeal
      (NoetherianOrbitDualRegularCentre.packetCovector pair C.packet)
  · calc
      NoetherianOperatorOrbit.annihilatorVia pair
          (NoetherianOperatorOrbit.orbitModule ops seed) =
          DualPacketRegularCentre.commonTangentKernel
            (NoetherianOrbitDualRegularCentre.packetCovector pair C.packet) :=
        C.persistentTangent_eq
      _ = OC.tangentSpace := OC.tangentSpace_eq_commonKernel.symm

/-- Existence of the strongest current local certificate, conditional only on
the finite packet-power realization for the automatically extracted raw orbit
packet. -/
theorem exists_certificate
    (F : MultiHasseOnlyDescent.RealizedFrame
      (R := R) (A := A (K := K) (σ := σ)) spec)
    (owners : ω → Ideal (A (K := K) (σ := σ)))
    (hstable : ∀ i,
      DifferentialIdealSaturation.Stable F.hasseAddHom (owners i))
    (ops : ι → Module.End K D) (seed : D)
    (pair : D →ₗ[K] Dual (K := K) (σ := σ))
    (e : Nat)
    (hroot : ∀ C : NoetherianOrbitDualRegularCentre.Certificate ops seed pair,
      (MultiOwnerHasseCore.jointCore F owners).map
          (algebraMap R (A (K := K) (σ := σ))) =
        FrobeniusFiniteRootGeneration.packetPowerIdeal p
          (NoetherianOrbitDualRegularCentre.packetCovector pair C.packet) e) :
    Nonempty (Certificate p F owners ops seed pair e) := by
  rcases NoetherianOrbitDualRegularCentre.exists_certificate
    ops seed pair with ⟨C⟩
  exact ⟨assemble p F owners hstable ops seed pair C e (hroot C)⟩

end

end NoetherianOrbitFiniteFrobeniusAffineChamber
end Experimental
end PCRLean
