import Mathlib
import Mathlib.LinearAlgebra.TensorProduct.Tower
import PCRLean.FunctionalPacketIdeal
import PCRLean.Experimental.ModuleImageCentre

/-!
# Operator-orbit integration as a global module-image centre

Let `D` be a finite-dimensional coordinate direction space and let a finite
operator family act on its dual. The full Noetherian operator orbit of one seed
is a `K`-submodule `O` of the dual space. Every covector in `O` integrates to an
actual linear polynomial.

Extend this integration `K[X]`-linearly:

`K[X] ⊗[K] O →ₗ[K[X]] K[X]`,

`a ⊗ λ ↦ a L_λ`.

Its image is an intrinsic actual ideal of the polynomial ambient ring. If a
finite packet spans the full orbit module, the image ideal is exactly the ideal
generated by the packet's linear polynomials. Finite-dimensionality supplies
such a packet automatically from raw operator descendants. Therefore the centre
is independent of the chosen finite Noetherian packet and does not require a
global basis of the orbit module.

This closes the finite-free coordinate version of

`intrinsic operator orbit → global finite actual centre`.

The universal scheme theorem must still construct these representations and
prove their compatibility under smooth localization and blowup transforms.
-/

namespace PCRLean
namespace Experimental
namespace OperatorOrbitImageCentre

noncomputable section

universe u v w

variable {K : Type u} [Field K]
variable {σ : Type v} [Fintype σ] [DecidableEq σ]
variable {κ : Type w}

abbrev P := MvPolynomial σ K
abbrev Direction := FunctionalPacketIdeal.Direction (K := K) (σ := σ)
abbrev Dual := FunctionalPacketIdeal.Dual (K := K) (σ := σ)

variable (ops : κ → Module.End K (Direction (K := K) (σ := σ)))
variable (seed : Dual (K := K) (σ := σ))

/-- Full operator-orbit module. -/
abbrev Orbit := DifferentialOrbitClosure.orbitModule ops seed

/-- Integration restricted to the orbit module. -/
def orbitIntegration :
    Orbit ops seed →ₗ[K] P (K := K) (σ := σ) :=
  (FunctionalPacketIdeal.integrationMap (K := K) (σ := σ)).comp
    (Orbit ops seed).subtype

/-- Bilinear multiplication of a polynomial coefficient with an integrated
orbit covector. -/
def multiplicationKernel :
    P (K := K) (σ := σ) →ₗ[P (K := K) (σ := σ)]
      Orbit ops seed →ₗ[K] P (K := K) (σ := σ) where
  toFun a :=
    { toFun := fun o => a * orbitIntegration ops seed o
      map_add' := by
        intro x y
        simp [orbitIntegration, mul_add]
      map_smul' := by
        intro c x
        simp [orbitIntegration, Algebra.smul_def, mul_assoc] }
  map_add' := by
    intro a b
    ext o
    simp [add_mul]
  map_smul' := by
    intro a b
    ext o
    simp [mul_assoc]

/-- `K[X]`-linear integration of the whole orbit module. -/
def extendedIntegration :
    (P (K := K) (σ := σ) ⊗[K] Orbit ops seed) →ₗ[P (K := K) (σ := σ)]
      P (K := K) (σ := σ) :=
  TensorProduct.AlgebraTensorModule.lift
    (multiplicationKernel ops seed)

@[simp] theorem extendedIntegration_tmul
    (a : P (K := K) (σ := σ))
    (o : Orbit ops seed) :
    extendedIntegration ops seed (a ⊗ₜ[K] o) =
      a * FunctionalPacketIdeal.functionalPolynomial o.1 := by
  rfl

/-- Intrinsic actual centre generated by the full operator orbit. -/
def orbitCentre : Ideal (P (K := K) (σ := σ)) :=
  ModuleImageCentre.imageIdeal (extendedIntegration ops seed)

/-- Every integrated orbit covector belongs to the intrinsic centre. -/
theorem functionalPolynomial_mem_orbitCentre
    (o : Orbit ops seed) :
    FunctionalPacketIdeal.functionalPolynomial o.1 ∈
      orbitCentre ops seed := by
  refine ⟨(1 : P (K := K) (σ := σ)) ⊗ₜ[K] o, ?_⟩
  simp [orbitCentre]

section FinitePacket

variable (s : Finset (Dual (K := K) (σ := σ)))
variable (hspan : DifferentialOrbitClosure.orbitModule ops seed =
  Submodule.span K (s : Set (Dual (K := K) (σ := σ))))

/-- The image of every extended orbit tensor belongs to the finite packet ideal. -/
theorem extendedIntegration_mem_packetIdeal
    (t : P (K := K) (σ := σ) ⊗[K] Orbit ops seed) :
    extendedIntegration ops seed t ∈
      FunctionalPacketIdeal.packetIdeal s := by
  induction t using TensorProduct.induction_on with
  | zero => simp
  | tmul a o =>
      rw [extendedIntegration_tmul]
      exact (FunctionalPacketIdeal.packetIdeal s).mul_mem_left a
        (FunctionalPacketIdeal.orbitModule_polynomial_mem_finite_packet_ideal
          ops seed s hspan o.2)
  | add x y hx hy =>
      rw [map_add]
      exact (FunctionalPacketIdeal.packetIdeal s).add_mem hx hy

/-- The intrinsic orbit centre is contained in the finite packet ideal. -/
theorem orbitCentre_le_packetIdeal :
    orbitCentre ops seed ≤ FunctionalPacketIdeal.packetIdeal s := by
  rintro x ⟨t, rfl⟩
  exact extendedIntegration_mem_packetIdeal ops seed s hspan t

/-- Every named finite packet generator belongs to the intrinsic orbit centre. -/
theorem packet_generator_mem_orbitCentre
    {f : Dual (K := K) (σ := σ)} (hf : f ∈ s) :
    FunctionalPacketIdeal.functionalPolynomial f ∈
      orbitCentre ops seed := by
  have hforbit : f ∈ DifferentialOrbitClosure.orbitModule ops seed := by
    rw [hspan]
    exact Submodule.subset_span hf
  exact functionalPolynomial_mem_orbitCentre ops seed ⟨f, hforbit⟩

/-- The finite packet ideal is contained in the intrinsic orbit centre. -/
theorem packetIdeal_le_orbitCentre :
    FunctionalPacketIdeal.packetIdeal s ≤ orbitCentre ops seed := by
  rw [FunctionalPacketIdeal.packetIdeal, Ideal.span_le]
  rintro x ⟨f, hf, rfl⟩
  exact packet_generator_mem_orbitCentre ops seed s hspan hf

/-- Main canonicity theorem: every finite spanning packet presents exactly the
same intrinsic module-image centre. -/
theorem orbitCentre_eq_packetIdeal :
    orbitCentre ops seed = FunctionalPacketIdeal.packetIdeal s := by
  exact le_antisymm
    (orbitCentre_le_packetIdeal ops seed s hspan)
    (packetIdeal_le_orbitCentre ops seed s hspan)

end FinitePacket

/-- Finite-dimensionality automatically supplies a raw finite packet that
presents the intrinsic orbit centre exactly. -/
theorem exists_finite_raw_packet_presentation :
    ∃ s : Finset (Dual (K := K) (σ := σ)),
      (s : Set (Dual (K := K) (σ := σ))) ⊆
        DifferentialOrbitClosure.orbitSet ops seed ∧
      orbitCentre ops seed = FunctionalPacketIdeal.packetIdeal s := by
  rcases DifferentialOrbitClosure.exists_finite_raw_orbit_generators
      ops seed with ⟨s, hs, hspan⟩
  exact ⟨s, hs, orbitCentre_eq_packetIdeal ops seed s hspan⟩

end

end OperatorOrbitImageCentre
end Experimental
end PCRLean
