import Mathlib
import PCRLean.Experimental.ArbitraryFiniteLinearPacketRegularCentre
import PCRLean.Experimental.FinitePacketAutomaticRegularCentre

/-!
# Experimental boundary of automatic finite-packet centres

Every finite linear packet on a finite-dimensional vector space has an
intrinsic degree-one ideal with regular quotient.  That algebraic regularity is
not yet a legal blowup-centre theorem: the ideal may be bottom, in which case
the corresponding closed subscheme is the whole ambient affine space.

This file isolates the missing `nonWhole` gate.  If the packet map is
injective, its intrinsic kernel ideal is exactly bottom.  Hence a non-bottom
packet centre forces a genuine common kernel.  The identity packet supplies a
minimal counterexample to the invalid implication

`regular quotient -> legal nontrivial centre`.

The statements below do not assert marked permissibility, singular-locus
containment, boundary compatibility, or hereditary blowup transport.
-/

namespace PCRLean
namespace Experimental
namespace PacketCentreBoundary

noncomputable section

universe u v w x

variable {K : Type u} [Field K]
variable {V : Type v} {W : Type w}
variable [AddCommGroup V] [Module K V]
variable [AddCommGroup W] [Module K W]

open IntrinsicKernelIdealFunctoriality
open ArbitraryFiniteLinearPacketRegularCentre

/-- A strict affine centre ideal is neither the whole ring nor the zero ideal.
The second condition is the missing gate in the earlier automatic-centre
certificate. -/
def StrictCentre (project : V →ₗ[K] W) : Prop :=
  centreIdeal project ≠ ⊥ ∧ centreIdeal project ≠ ⊤

/-- An injective packet map has zero kernel, so the intrinsic degree-one ideal
is bottom.  Algebraically regular quotient data alone therefore need not give a
usable centre. -/
theorem centreIdeal_eq_bot_of_injective
    (project : V →ₗ[K] W)
    (hinj : Function.Injective project) :
    centreIdeal project = ⊥ := by
  unfold centreIdeal kernelIdealOf
  apply le_antisymm
  · rw [Ideal.span_le]
    rintro z ⟨k, rfl⟩
    have hk : k.1 = 0 := hinj (LinearMap.mem_ker.mp k.2)
    rw [hk]
    simp
  · exact bot_le

/-- The identity packet is the minimal full-rank boundary example. -/
theorem identityCentreIdeal_eq_bot :
    centreIdeal (LinearMap.id : V →ₗ[K] V) = ⊥ := by
  apply centreIdeal_eq_bot_of_injective
  intro a b hab
  simpa using hab

/-- A non-bottom intrinsic packet ideal forces failure of injectivity.  Thus a
legal nonwhole packet centre requires an actual common-kernel direction. -/
theorem not_injective_of_centreIdeal_ne_bot
    (project : V →ₗ[K] W)
    (hcentre : centreIdeal project ≠ ⊥) :
    ¬ Function.Injective project := by
  intro hinj
  exact hcentre (centreIdeal_eq_bot_of_injective project hinj)

/-- At the opposite rank boundary, the zero packet cuts out the linear origin:
its ideal is generated by every degree-one element. -/
theorem zeroCentreIdeal_eq_span_iota :
    centreIdeal (0 : V →ₗ[K] W) =
      Ideal.span (Set.range fun v : V => SymmetricAlgebra.ι K V v) := by
  unfold centreIdeal kernelIdealOf
  apply congrArg Ideal.span
  ext z
  constructor
  · rintro ⟨k, rfl⟩
    exact ⟨k.1, rfl⟩
  · rintro ⟨v, rfl⟩
    exact ⟨⟨v, by simp⟩, rfl⟩

section FiniteDimensional

variable [FiniteDimensional K V] [FiniteDimensional K W]

/-- In finite dimension the earlier theorem supplies properness automatically,
so strictness is exactly the additional non-bottom condition. -/
theorem strictCentre_iff_ne_bot (project : V →ₗ[K] W) :
    StrictCentre project ↔ centreIdeal project ≠ ⊥ := by
  constructor
  · exact fun h => h.1
  · intro hbot
    exact ⟨hbot, centreIdeal_ne_top project⟩

/-- Minimal falsifier: the identity packet has a regular quotient but its
centre ideal is bottom.  Therefore regularity and properness of the quotient do
not imply a legal nonwhole blowup centre. -/
theorem identityPacket_regular_quotient_but_not_strict :
    IsRegularRing
        (SymmetricAlgebra K V ⧸
          centreIdeal (LinearMap.id : V →ₗ[K] V)) ∧
      ¬ StrictCentre (LinearMap.id : V →ₗ[K] V) := by
  constructor
  · exact quotient_isRegularRing
      (LinearMap.id : V →ₗ[K] V)
  · intro hstrict
    exact hstrict.1 identityCentreIdeal_eq_bot

end FiniteDimensional

section FinitePacket

variable {ι : Type x} [Fintype ι]

open FinitePacketAutomaticRegularCentre

/-- Packet form of the nonwhole-centre boundary. -/
theorem packetMap_not_injective_of_centreIdeal_ne_bot
    (packet : ι → Module.Dual K V)
    (hcentre : FinitePacketAutomaticRegularCentre.centreIdeal packet ≠ ⊥) :
    ¬ Function.Injective
      (FinitePacketAutomaticRegularCentre.packetMap packet) := by
  exact not_injective_of_centreIdeal_ne_bot
    (FinitePacketAutomaticRegularCentre.packetMap packet) hcentre

end FinitePacket

end

end PacketCentreBoundary
end Experimental
end PCRLean
