import Mathlib
import PCRLean.Experimental.PerfectFrobeniusRankZeroEscape
import PCRLean.Experimental.FrobeniusFiniteRootGeneration
import PCRLean.Experimental.DualPacketRankZeroNoGo

/-!
# Experimental finite pure Frobenius presentation

Over a perfect field, apply coefficientwise inverse Frobenius to every row of a
finite family of pure `p^e`-forms.  The finite packet-power ideal of the
recovered covector rows is exactly the ideal generated by the original pure
forms.  If at least one original row is nonzero, the recovered packet row span
has positive rank and therefore admits pivot blowup charts.

This closes a finite matrix version of the perfect-field rank-zero escape.  It
does not prove that every higher Hasse core has a finite pure Frobenius
presentation or handle mixed/non-pure terms and imperfect residue fields.
-/

namespace PCRLean
namespace Experimental
namespace PerfectFrobeniusFinitePresentation

noncomputable section

universe u v w

variable {K : Type u} [Field K]
variable {σ : Type v} [Fintype σ] [DecidableEq σ]
variable {κ : Type w} [Fintype κ]
variable (p : Nat) [Fact p.Prime] [CharP K p] [PerfectField K p]

abbrev Direction := σ → K
abbrev Dual := Module.Dual K (Direction (K := K) (σ := σ))

open PerfectFrobeniusRankZeroEscape

/-- Recovered finite covector packet. -/
def rootPacket
    (coeff : κ → σ → K) (e : Nat) :
    κ → Dual (K := K) (σ := σ) :=
  fun i => PerfectFrobeniusRankZeroEscape.rootFunctional p (coeff i) e

/-- Ideal generated by the finite family of pure higher-Frobenius forms. -/
def purePresentationIdeal
    (coeff : κ → σ → K) (e : Nat) : Ideal (MvPolynomial σ K) :=
  Ideal.span (Set.range fun i : κ =>
    pureFrobeniusPolynomial p (coeff i) e)

/-- Each recovered packet row has the corresponding pure form as its
`p^e`-power. -/
theorem packetRow_pow
    (coeff : κ → σ → K) (e : Nat) (i : κ) :
    (FunctionalPacketIdeal.functionalPolynomial
      (rootPacket p coeff e i)) ^ (p ^ e) =
        pureFrobeniusPolynomial p (coeff i) e := by
  rw [rootPacket,
    PerfectFrobeniusRankZeroEscape.functionalPolynomial_rootFunctional]
  exact PerfectFrobeniusRankZeroEscape.rootLinearPolynomial_pow
    p (coeff i) e

/-- Main finite-presentation theorem. -/
theorem packetPowerIdeal_eq_purePresentationIdeal
    (coeff : κ → σ → K) (e : Nat) :
    FrobeniusFiniteRootGeneration.packetPowerIdeal p
        (rootPacket p coeff e) e =
      purePresentationIdeal p coeff e := by
  apply le_antisymm
  · rw [FrobeniusFiniteRootGeneration.packetPowerIdeal, Ideal.span_le]
    rintro z ⟨i, rfl⟩
    rw [packetRow_pow]
    exact Ideal.subset_span ⟨i, rfl⟩
  · rw [purePresentationIdeal, Ideal.span_le]
    rintro z ⟨i, rfl⟩
    rw [← packetRow_pow]
    exact FrobeniusFiniteRootGeneration.packetPowerGenerator_mem
      p (rootPacket p coeff e) e i

/-- The full row-span root package is the same finite pure-presentation ideal. -/
theorem actualRootPowerIdeal_eq_purePresentationIdeal
    (coeff : κ → σ → K) (e : Nat) :
    DualPacketAffineRootPackage.actualRootPowerIdeal
        (rootPacket p coeff e) (p ^ e) =
      purePresentationIdeal p coeff e := by
  rw [FrobeniusFiniteRootGeneration.actualRootPowerIdeal_eq_packetPowerIdeal]
  exact packetPowerIdeal_eq_purePresentationIdeal p coeff e

/-- A nonzero pure row gives a nonzero recovered covector row. -/
theorem rootPacket_row_ne_zero
    (coeff : κ → σ → K) (e : Nat) (i : κ)
    (hi : pureFrobeniusPolynomial p (coeff i) e ≠ 0) :
    rootPacket p coeff e i ≠ 0 :=
  PerfectFrobeniusRankZeroEscape.rootFunctional_ne_zero_of_pure_ne_zero
    p (coeff i) e hi

/-- If at least one pure row is nonzero, the recovered packet has positive row
span rank. -/
theorem rootPacket_positive_finrank
    (coeff : κ → σ → K) (e : Nat)
    (hnonzero : ∃ i : κ,
      pureFrobeniusPolynomial p (coeff i) e ≠ 0) :
    0 < FiniteDimensional.finrank K
      (DualPacketRegularCentre.packetSpan (rootPacket p coeff e)) := by
  rcases hnonzero with ⟨i, hi⟩
  have hrow := rootPacket_row_ne_zero p coeff e i hi
  apply Nat.pos_of_ne_zero
  intro hzero
  have hz := DualPacketRankZeroNoGo.packet_eq_zero_of_finrank_eq_zero
    (rootPacket p coeff e) hzero i
  exact hrow hz

/-- A nonzero finite pure presentation supplies at least one pivot chart. -/
theorem rootPacket_hasPivot
    (coeff : κ → σ → K) (e : Nat)
    (hnonzero : ∃ i : κ,
      pureFrobeniusPolynomial p (coeff i) e ≠ 0) :
    Nonempty
      (DualPacketCoordinateNormalization.CentreIndex
        (rootPacket p coeff e)) :=
  DualPacketBlowupChart.nonempty_centreIndex_of_positive_finrank
    p (rootPacket p coeff e)
    (rootPacket_positive_finrank p coeff e hnonzero)

end

end PerfectFrobeniusFinitePresentation
end Experimental
end PCRLean
