import PCRLean.Experimental.PerfectFrobeniusFinitePresentation

#print axioms PCRLean.Experimental.PerfectFrobeniusFinitePresentation.packetRow_pow
#print axioms PCRLean.Experimental.PerfectFrobeniusFinitePresentation.packetPowerIdeal_eq_purePresentationIdeal
#print axioms PCRLean.Experimental.PerfectFrobeniusFinitePresentation.actualRootPowerIdeal_eq_purePresentationIdeal
#print axioms PCRLean.Experimental.PerfectFrobeniusFinitePresentation.rootPacket_row_ne_zero
#print axioms PCRLean.Experimental.PerfectFrobeniusFinitePresentation.rootPacket_positive_finrank
#print axioms PCRLean.Experimental.PerfectFrobeniusFinitePresentation.rootPacket_hasPivot
