import Mathlib
import PCRLean.Experimental.PerfectFrobeniusRankZeroEscape
import PCRLean.Experimental.FrobeniusFiniteRootGeneration

/-!
# Experimental pure Frobenius ideal escape

Over a perfect field, a pure `p^e`-Frobenius form is the `p^e`-th power of its
coefficientwise linear root.  The principal ideal generated by the pure form is
therefore exactly the finite Frobenius packet-power ideal of the recovered
singleton covector packet.

This converts a higher-Frobenius rank-zero diagnostic into the finite root
realization required by the positive-rank affine chamber.
-/

namespace PCRLean
namespace Experimental
namespace PerfectFrobeniusPureIdealEscape

noncomputable section

universe u v

variable {K : Type u} [Field K]
variable {σ : Type v} [Fintype σ] [DecidableEq σ]
variable (p : Nat) [Fact p.Prime] [CharP K p] [PerfectField K p]

abbrev Direction := σ → K
abbrev Dual := Module.Dual K (Direction (K := K) (σ := σ))

open PerfectFrobeniusRankZeroEscape

/-- Principal ideal generated by the pure higher-Frobenius form. -/
def pureFrobeniusIdeal
    (coeff : σ → K) (e : Nat) : Ideal (MvPolynomial σ K) :=
  Ideal.span ({pureFrobeniusPolynomial p coeff e} : Set (MvPolynomial σ K))

/-- The finite packet-power ideal of the recovered singleton packet is exactly
the pure Frobenius principal ideal. -/
theorem packetPowerIdeal_rootPacket_eq_pureFrobeniusIdeal
    (coeff : σ → K) (e : Nat) :
    FrobeniusFiniteRootGeneration.packetPowerIdeal p
        (rootPacket p coeff e) e =
      pureFrobeniusIdeal p coeff e := by
  apply le_antisymm
  · rw [FrobeniusFiniteRootGeneration.packetPowerIdeal, Ideal.span_le]
    rintro z ⟨i, rfl⟩
    apply Ideal.subset_span
    simp [rootPacket, functionalPolynomial_rootFunctional,
      rootLinearPolynomial_pow]
  · rw [pureFrobeniusIdeal, Ideal.span_le]
    intro z hz
    have hz' : z = pureFrobeniusPolynomial p coeff e := by
      simpa using hz
    rw [hz']
    rw [← rootLinearPolynomial_pow p coeff e]
    rw [← functionalPolynomial_rootFunctional p coeff e]
    exact FrobeniusFiniteRootGeneration.packetPowerGenerator_mem
      p (rootPacket p coeff e) e Unit.unit

/-- The full row-span root package of the recovered singleton packet is the
same pure Frobenius ideal. -/
theorem actualRootPowerIdeal_rootPacket_eq_pureFrobeniusIdeal
    (coeff : σ → K) (e : Nat) :
    DualPacketAffineRootPackage.actualRootPowerIdeal
        (rootPacket p coeff e) (p ^ e) =
      pureFrobeniusIdeal p coeff e := by
  rw [FrobeniusFiniteRootGeneration.actualRootPowerIdeal_eq_packetPowerIdeal]
  exact packetPowerIdeal_rootPacket_eq_pureFrobeniusIdeal p coeff e

/-- A nonzero pure form produces a proper nonzero recovered actual centre. -/
theorem recoveredActualIdeal_ne_bot
    (coeff : σ → K) (e : Nat)
    (hpure : pureFrobeniusPolynomial p coeff e ≠ 0) :
    DualPacketAffineLinearRealization.actualIdeal
      (rootPacket p coeff e) ≠ ⊥ := by
  intro hbot
  have hgen := Ideal.subset_span
    (show FunctionalPacketIdeal.functionalPolynomial
        (rootFunctional p coeff e) ∈
      Set.range (fun i : Unit =>
        FunctionalPacketIdeal.functionalPolynomial
          (rootPacket p coeff e i)) from ⟨Unit.unit, rfl⟩)
  rw [hbot] at hgen
  have hlin : FunctionalPacketIdeal.functionalPolynomial
      (rootFunctional p coeff e) = 0 := by
    simpa using hgen
  apply hpure
  rw [← rootLinearPolynomial_pow p coeff e]
  rw [← functionalPolynomial_rootFunctional p coeff e, hlin]
  simp [pow_pos (Fact.out : p.Prime).pos e]

end

end PerfectFrobeniusPureIdealEscape
end Experimental
end PCRLean
