import PCRLean.Experimental.PerfectFrobeniusRankZeroEscape

#print axioms PCRLean.Experimental.PerfectFrobeniusRankZeroEscape.frobeniusRootIter_pow
#print axioms PCRLean.Experimental.PerfectFrobeniusRankZeroEscape.finset_sum_pow_char_pow
#print axioms PCRLean.Experimental.PerfectFrobeniusRankZeroEscape.rootLinearPolynomial_pow
#print axioms PCRLean.Experimental.PerfectFrobeniusRankZeroEscape.coefficientRow_rootFunctional
#print axioms PCRLean.Experimental.PerfectFrobeniusRankZeroEscape.functionalPolynomial_rootFunctional
#print axioms PCRLean.Experimental.PerfectFrobeniusRankZeroEscape.rootFunctional_ne_zero_of_pure_ne_zero
#print axioms PCRLean.Experimental.PerfectFrobeniusRankZeroEscape.rootPacket_positive_finrank
#print axioms PCRLean.Experimental.PerfectFrobeniusRankZeroEscape.rootPacket_hasPivot
