import PCRLean.Experimental.PolynomialGraphJointResolutionChamber

#print axioms PCRLean.Experimental.PolynomialGraphJointResolutionChamber.certificate
#print axioms PCRLean.Experimental.PolynomialGraphJointResolutionChamber.cleanup_rank_decreases
