import Mathlib
import PCRLean.Experimental.PolynomialGraphBlowupHeredity
import PCRLean.Experimental.PolynomialGraphArbitraryMarkCertificate

/-!
# Exact prime support of polynomial graph-root packets

For a positive exponent `q`, the ideal generated by the powers

`(Z_i - h_i)^q`

and the graph ideal `(Z_i-h_i)` are contained in exactly the same prime ideals.
Thus the reduced support of the root packet is precisely the graph centre.

This is stronger than mere marked permissibility and supplies the local
set-theoretic singular-locus containment gate for the pure graph-root chamber.
It does not identify the full marked singular locus of an arbitrary differential
Rees algebra containing additional owners.
-/

namespace PCRLean
namespace Experimental
namespace PolynomialGraphSupportEquality

noncomputable section

universe u v

variable {R : Type u} [CommRing R] [IsDomain R]
variable {ι : Type v} [Fintype ι] [DecidableEq ι]

open PolynomialGraphCentreHeredity
open PolynomialGraphBlowupHeredity

abbrev P := MvPolynomial ι R

/-- A positive graph-root packet is contained in the underlying graph ideal. -/
theorem sourceIdeal_le_graphIdeal
    (h : ι → R) (q : Nat) (hq : 0 < q) :
    sourceIdeal h q ≤ graphIdeal h := by
  calc
    sourceIdeal h q ≤ (graphIdeal h) ^ q :=
      sourceIdeal_le_graphIdeal_pow h q
    _ ≤ (graphIdeal h) ^ 1 :=
      PolynomialGraphArbitraryMarkCertificate.pow_le_pow_of_le
        (graphIdeal h) hq
    _ = graphIdeal h := by simp

/-- Every graph generator has a positive power in the source packet. -/
theorem graphGenerator_pow_mem_sourceIdeal
    (h : ι → R) (q : Nat) (i : ι) :
    (graphGenerator h i) ^ q ∈ sourceIdeal h q := by
  apply Ideal.subset_span
  exact ⟨i, rfl⟩

/-- The graph ideal and the positive root packet have identical containment in
all prime ideals. -/
theorem sourceIdeal_le_prime_iff_graphIdeal_le_prime
    (h : ι → R) (q : Nat) (hq : 0 < q)
    (P : Ideal (P (R := R) (ι := ι)))
    (hP : P.IsPrime) :
    sourceIdeal h q ≤ P ↔ graphIdeal h ≤ P := by
  constructor
  · intro hsource
    rw [graphIdeal, Ideal.span_le]
    rintro x ⟨i, rfl⟩
    exact hP.mem_of_pow_mem q
      (hsource (graphGenerator_pow_mem_sourceIdeal h q i))
  · intro hgraph
    exact (sourceIdeal_le_graphIdeal h q hq).trans hgraph

/-- Prime-spectrum pointwise form: the reduced support of the source packet is
exactly the graph centre. -/
theorem primePoint_contains_source_iff_contains_graph
    (h : ι → R) (q : Nat) (hq : 0 < q)
    (x : PrimeSpectrum (P (R := R) (ι := ι))) :
    sourceIdeal h q ≤ x.asIdeal ↔ graphIdeal h ≤ x.asIdeal :=
  sourceIdeal_le_prime_iff_graphIdeal_le_prime
    h q hq x.asIdeal x.isPrime

end

end PolynomialGraphSupportEquality
end Experimental
end PCRLean
