import Mathlib
import PCRLean.Experimental.PolynomialGraphBlowupHeredity

/-!
# Marked graph-root transforms and pure exceptional debt

For a graph generator `r_i = Z_i - h_i`, every standard chart has

`φ_k(r_i^q) = E_k^q * u_{k,i}^q`.

If the source equation is assigned any positive mark `m ≤ q`, divide only by
`E_k^m`.  The controlled residual is then

`E_k^(q-m) * u_{k,i}^q`.

The ideal generated by all these residuals is exactly the principal exceptional
power `(E_k)^(q-m)`, because the pivot residual is `E_k^(q-m)`.  Thus:

* at the exact Frobenius mark `m=q`, the transformed packet is the unit ideal;
* at a smaller mark, the entire remaining packet is a pure bounded exceptional
  debt and contains no new nonmonomial root obstruction.

This gives an exact local implementation of the exceptional-debt bookkeeping
predicted by arbitrary-mark ceiling compression.
-/

namespace PCRLean
namespace Experimental
namespace PolynomialGraphMarkedTransformDebt

noncomputable section

universe u v

variable {R : Type u} [CommRing R] [IsDomain R]
variable {ι : Type v} [DecidableEq ι]

open PolynomialGraphCentreHeredity
open PolynomialGraphBlowupHeredity

abbrev P := MvPolynomial ι R

/-- Controlled residual after dividing a graph-generator `q`-th power by the
source mark `mark`. -/
def controlledResidual
    (k i : ι) (q mark : Nat) : P (R := R) (ι := ι) :=
  (exceptional (R := R) k) ^ (q - mark) *
    (explicitRootTransform (R := R) k i) ^ q

/-- Exact source-mark factorization. -/
theorem graphGenerator_power_factorization_at_mark
    (h : ι → R) (k i : ι) (q mark : Nat)
    (hmark : mark ≤ q) :
    graphChartMap h k ((graphGenerator h i) ^ q) =
      (exceptional (R := R) k) ^ mark *
        controlledResidual (R := R) k i q mark := by
  rw [graphGenerator_pow_factorization]
  unfold controlledResidual
  rw [← Nat.add_sub_of_le hmark, pow_add]
  ac_rfl

/-- The pivot controlled residual is exactly the exceptional debt. -/
theorem pivot_controlledResidual
    (k : ι) (q mark : Nat) :
    controlledResidual (R := R) k k q mark =
      (exceptional (R := R) k) ^ (q - mark) := by
  simp [controlledResidual, explicitRootTransform]

/-- Ideal generated by all controlled graph-root residuals. -/
def transformedMarkedRootIdeal
    (k : ι) (q mark : Nat) : Ideal (P (R := R) (ι := ι)) :=
  Ideal.span (Set.range fun i : ι =>
    controlledResidual (R := R) k i q mark)

/-- Every controlled residual belongs to the corresponding exceptional power. -/
theorem controlledResidual_mem_pivotPower
    (k i : ι) (q mark : Nat) :
    controlledResidual (R := R) k i q mark ∈
      (pivotIdeal (R := R) k) ^ (q - mark) := by
  unfold controlledResidual
  exact ((pivotIdeal (R := R) k) ^ (q - mark)).mul_mem_right _
    (Ideal.pow_mem_pow
      (exceptional_mem_pivotIdeal (R := R) k) (q - mark))

/-- The whole transformed packet is exactly one pure exceptional power. -/
theorem transformedMarkedRootIdeal_eq_pivotPower
    (k : ι) (q mark : Nat) :
    transformedMarkedRootIdeal (R := R) k q mark =
      (pivotIdeal (R := R) k) ^ (q - mark) := by
  apply le_antisymm
  · rw [transformedMarkedRootIdeal, Ideal.span_le]
    rintro x ⟨i, rfl⟩
    exact controlledResidual_mem_pivotPower
      (R := R) k i q mark
  · rw [pivotIdeal, Ideal.span_singleton_pow, Ideal.span_le]
    intro x hx
    have hx' : x = (exceptional (R := R) k) ^ (q - mark) := by
      simpa using hx
    rw [hx']
    apply Ideal.subset_span
    refine ⟨k, ?_⟩
    exact pivot_controlledResidual (R := R) k q mark

/-- At the exact Frobenius mark the transformed packet is terminal. -/
theorem transformedMarkedRootIdeal_eq_top_of_exactMark
    (k : ι) (q : Nat) :
    transformedMarkedRootIdeal (R := R) k q q = ⊤ := by
  rw [transformedMarkedRootIdeal_eq_pivotPower]
  simp

/-- At an arbitrary smaller mark, the transformed packet is completely
monomial: it is the exceptional ideal to the debt exponent `q-mark`. -/
theorem transformedMarkedRootIdeal_is_pureDebt
    (k : ι) (q mark : Nat) (_hmark : mark ≤ q) :
    transformedMarkedRootIdeal (R := R) k q mark =
      (pivotIdeal (R := R) k) ^ (q - mark) :=
  transformedMarkedRootIdeal_eq_pivotPower (R := R) k q mark

/-- The debt exponent is strictly positive when the mark is strictly below the
Frobenius block. -/
theorem debt_pos_of_mark_lt
    (q mark : Nat) (hmark : mark < q) :
    0 < q - mark :=
  Nat.sub_pos_of_lt hmark

end

end PolynomialGraphMarkedTransformDebt
end Experimental
end PCRLean
