import PCRLean.Experimental.PolynomialGraphBoundaryIntersection

#print axioms PCRLean.Experimental.PolynomialGraphBoundaryIntersection.coefficientIdeal_le_comap
#print axioms PCRLean.Experimental.PolynomialGraphBoundaryIntersection.graphIdeal_le_comap
#print axioms PCRLean.Experimental.PolynomialGraphBoundaryIntersection.combinedIdeal_eq_comap
#print axioms PCRLean.Experimental.PolynomialGraphBoundaryIntersection.ker_boundaryEval_eq_combinedIdeal
#print axioms PCRLean.Experimental.PolynomialGraphBoundaryIntersection.boundaryEval_surjective
#print axioms PCRLean.Experimental.PolynomialGraphBoundaryIntersection.quotientEquiv
#print axioms PCRLean.Experimental.PolynomialGraphBoundaryIntersection.quotient_isRegularRing
#print axioms PCRLean.Experimental.PolynomialGraphBoundaryIntersection.certificate
