import Mathlib
import Mathlib.RingTheory.Ideal.Quotient.Operations
import PCRLean.Experimental.ReducedPolynomialGraphCentreHeredity

/-!
# Exact quotient of a polynomial graph centre

For a commutative ring `R` and a tuple `h : ι → R`, evaluation at the graph

`Z_i ↦ h_i`

has kernel exactly the actual ideal generated by `Z_i - h_i`.  Hence the
coordinate ring of the graph centre is canonically isomorphic to `R`.

This theorem is independent of characteristic and reducedness.  Reducedness is
needed only for Frobenius reflection, while the quotient theorem supplies the
actual-centre, properness, finite-generation, and centre-coordinate-ring parts
of the geometric certificate.
-/

namespace PCRLean
namespace Experimental
namespace PolynomialGraphCentreQuotient

noncomputable section

universe u v

variable {R : Type u} [CommRing R]
variable {ι : Type v} [DecidableEq ι]

open ReducedPolynomialGraphCentreHeredity

abbrev P := MvPolynomial ι R

/-- Evaluation on the graph `Z_i = h_i`. -/
def graphEval (h : ι → R) : P (R := R) (ι := ι) →+* R :=
  MvPolynomial.eval₂Hom (RingHom.id R) h

@[simp] theorem graphEval_C (h : ι → R) (r : R) :
    graphEval h (MvPolynomial.C r) = r := by
  simp [graphEval]

@[simp] theorem graphEval_X (h : ι → R) (i : ι) :
    graphEval h (MvPolynomial.X i) = h i := by
  simp [graphEval]

@[simp] theorem graphEval_graphGenerator (h : ι → R) (i : ι) :
    graphEval h (graphGenerator h i) = 0 := by
  simp [graphGenerator]

/-- Re-embed the graph value as a constant polynomial. -/
def constantProjection (h : ι → R) :
    P (R := R) (ι := ι) →+* P :=
  MvPolynomial.C.comp (graphEval h)

@[simp] theorem constantProjection_apply
    (h : ι → R) (f : P (R := R) (ι := ι)) :
    constantProjection h f = MvPolynomial.C (graphEval h f) := rfl

/-- Every polynomial differs from its graph value by an element of the graph
ideal. -/
theorem sub_constantProjection_mem
    (h : ι → R) (f : P (R := R) (ι := ι)) :
    f - constantProjection h f ∈ graphIdeal h := by
  induction f using MvPolynomial.induction_on with
  | C r => simp [constantProjection]
  | add f g hf hg =>
      have hadd := (graphIdeal h).add_mem hf hg
      simpa [map_add, add_sub_add_comm] using hadd
  | mul_X f i hf =>
      have h₁ :
          (f - constantProjection h f) * MvPolynomial.X i ∈ graphIdeal h :=
        (graphIdeal h).mul_mem_right _ hf
      have h₂ :
          MvPolynomial.C (graphEval h f) * graphGenerator h i ∈ graphIdeal h :=
        (graphIdeal h).mul_mem_left _ (graphGenerator_mem h i)
      have hadd := (graphIdeal h).add_mem h₁ h₂
      have heq :
          f * MvPolynomial.X i -
              constantProjection h (f * MvPolynomial.X i) =
            (f - constantProjection h f) * MvPolynomial.X i +
              MvPolynomial.C (graphEval h f) * graphGenerator h i := by
        change
          f * MvPolynomial.X i -
              MvPolynomial.C (graphEval h (f * MvPolynomial.X i)) =
            (f - MvPolynomial.C (graphEval h f)) * MvPolynomial.X i +
              MvPolynomial.C (graphEval h f) *
                (MvPolynomial.X i - MvPolynomial.C (h i))
        rw [map_mul, graphEval_X]
        ring
      rw [heq]
      exact hadd

/-- The graph ideal is contained in the evaluation kernel. -/
theorem graphIdeal_le_ker (h : ι → R) :
    graphIdeal h ≤ RingHom.ker (graphEval h) := by
  rw [graphIdeal, Ideal.span_le]
  rintro x ⟨i, rfl⟩
  apply RingHom.mem_ker.mpr
  exact graphEval_graphGenerator h i

/-- Exact kernel theorem for the actual graph ideal. -/
theorem ker_graphEval_eq_graphIdeal (h : ι → R) :
    RingHom.ker (graphEval h) = graphIdeal h := by
  apply le_antisymm
  · intro f hf
    have hzero : graphEval h f = 0 := RingHom.mem_ker.mp hf
    have hmem := sub_constantProjection_mem h f
    simpa [constantProjection, hzero] using hmem
  · exact graphIdeal_le_ker h

/-- Evaluation on the graph is surjective. -/
theorem graphEval_surjective (h : ι → R) :
    Function.Surjective (graphEval h) := by
  intro r
  exact ⟨MvPolynomial.C r, by simp⟩

/-- The coordinate ring of the graph centre is exactly the coefficient ring. -/
noncomputable def quotientEquiv (h : ι → R) :
    (P (R := R) (ι := ι) ⧸ graphIdeal h) ≃+* R :=
  (Ideal.quotEquivOfEq (ker_graphEval_eq_graphIdeal h).symm).trans
    (RingHom.quotientKerEquivOfSurjective
      (f := graphEval h) (graphEval_surjective h))

@[simp] theorem quotientEquiv_mk
    (h : ι → R) (f : P (R := R) (ι := ι)) :
    quotientEquiv h (Ideal.Quotient.mk (graphIdeal h) f) =
      graphEval h f := by
  simp [quotientEquiv]

/-- A graph ideal is proper whenever the coefficient ring is nontrivial. -/
theorem graphIdeal_ne_top [Nontrivial R] (h : ι → R) :
    graphIdeal h ≠ ⊤ := by
  intro htop
  have hone : (1 : P (R := R) (ι := ι)) ∈ graphIdeal h := by
    rw [htop]
    trivial
  have hker := graphIdeal_le_ker h hone
  have hzero := RingHom.mem_ker.mp hker
  simpa using hzero

/-- A finite graph packet defines a finitely generated actual ideal without a
Noetherian hypothesis. -/
theorem graphIdeal_fg [Finite ι] (h : ι → R) :
    (graphIdeal h).FG :=
  Submodule.fg_span (Set.finite_range _)

/-- Reducedness of the centre coordinate ring follows from reducedness of the
coefficient ring. -/
theorem quotient_isReduced [IsReduced R] (h : ι → R) :
    IsReduced (P (R := R) (ι := ι) ⧸ graphIdeal h) :=
  isReduced_of_injective (quotientEquiv h).toRingHom (quotientEquiv h).injective

end

end PolynomialGraphCentreQuotient
end Experimental
end PCRLean
