import Mathlib
import PCRLean.Experimental.PolynomialGraphCentreHeredity
import PCRLean.Experimental.PolynomialGraphBlowupHeredity
import PCRLean.Experimental.PolynomialGraphArbitraryMarkCertificate

/-!
# Sharp upper-mark boundary for polynomial graph-root centres

A graph generator `r_i = Z_i-h_i` has normal order exactly one along the graph
centre.  Consequently `r_i^q` has normal order exactly `q` and does not belong
to the `(q+1)`-st power of the centre ideal.

Thus the packet generated by all `r_i^q` cannot be marked-permissible for any
mark strictly larger than `q`.  The hypothesis `0 < m ≤ q` in the arbitrary-mark
graph certificate is therefore sharp, not a technical limitation.

For marks above one Frobenius block, a correct algorithm must first extract a
root of higher centre order, enlarge the centre by additional defect
components, or enter a finite centre-word/escape branch.
-/

namespace PCRLean
namespace Experimental
namespace PolynomialGraphMarkBoundary

noncomputable section

universe u v

variable {R : Type u} [CommRing R] [IsDomain R]
variable {ι : Type v} [Fintype ι] [DecidableEq ι] [Nonempty ι]

open PolynomialGraphCentreHeredity
open PolynomialGraphBlowupHeredity

abbrev P := MvPolynomial ι R

/-- One graph generator has normal order exactly one. -/
theorem graphGenerator_not_mem_square
    (h : ι → R) (i : ι) :
    graphGenerator h i ∉ (graphIdeal h) ^ 2 := by
  intro hmem
  have horder : GraphOrderGE h (graphGenerator h i) 2 :=
    (mem_graphIdeal_pow_iff_graphOrderGE h (graphGenerator h i) 2).mp hmem
  unfold GraphOrderGE at horder
  rw [translate_graphGenerator] at horder
  unfold FrobeniusSupportDomain.OrderGE at horder
  have hsupp :
      Finsupp.single i 1 ∈
        (MvPolynomial.X i : P (R := R) (ι := ι)).support := by
    simp [MvPolynomial.X]
  have hb := horder (Finsupp.single i 1) hsupp
  simp [InitialFormFrobeniusCleaning.exponentDegree,
    Finsupp.degree_apply] at hb

/-- The `q`-th power of one graph generator has normal order exactly `q`. -/
theorem graphGenerator_pow_not_mem_succ
    (h : ι → R) (i : ι) (q : Nat) :
    (graphGenerator h i) ^ q ∉ (graphIdeal h) ^ (q + 1) := by
  intro hmem
  have horder : GraphOrderGE h ((graphGenerator h i) ^ q) (q + 1) :=
    (mem_graphIdeal_pow_iff_graphOrderGE
      h ((graphGenerator h i) ^ q) (q + 1)).mp hmem
  unfold GraphOrderGE at horder
  rw [map_pow, translate_graphGenerator] at horder
  unfold FrobeniusSupportDomain.OrderGE at horder
  have hsupp :
      Finsupp.single i q ∈
        ((MvPolynomial.X i : P (R := R) (ι := ι)) ^ q).support := by
    rw [MvPolynomial.X_pow_eq_monomial]
    simp
  have hb := horder (Finsupp.single i q) hsupp
  simp [InitialFormFrobeniusCleaning.exponentDegree,
    Finsupp.degree_apply] at hb

/-- The full graph-root packet cannot be permissible above its Frobenius block. -/
theorem sourceIdeal_not_le_graphIdeal_pow_of_block_lt_mark
    (h : ι → R) (q mark : Nat) (hqm : q < mark) :
    ¬ sourceIdeal h q ≤ (graphIdeal h) ^ mark := by
  intro hle
  obtain ⟨i⟩ := (inferInstance : Nonempty ι)
  have hsource : (graphGenerator h i) ^ q ∈ sourceIdeal h q := by
    apply Ideal.subset_span
    exact ⟨i, rfl⟩
  have hmark : (graphGenerator h i) ^ q ∈ (graphIdeal h) ^ mark :=
    hle hsource
  have hsucc : (graphGenerator h i) ^ q ∈ (graphIdeal h) ^ (q + 1) :=
    (PolynomialGraphArbitraryMarkCertificate.pow_le_pow_of_le
      (graphIdeal h) (Nat.succ_le_of_lt hqm)) hmark
  exact graphGenerator_pow_not_mem_succ h i q hsucc

/-- Packet-level no-go for a positive mark above `q`. -/
theorem sourcePacket_not_permissible_of_block_lt_mark
    (h : ι → R) (q mark : Nat)
    (hmark_pos : 0 < mark) (hqm : q < mark) :
    ¬ MarkedIdeal.Permissible
      (R := P (R := R) (ι := ι))
      ⟨sourceIdeal h q, mark, hmark_pos⟩
      (graphIdeal h) :=
  sourceIdeal_not_le_graphIdeal_pow_of_block_lt_mark h q mark hqm

end

end PolynomialGraphMarkBoundary
end Experimental
end PCRLean
