import Mathlib
import PCRLean.Experimental.PolynomialGraphCentreHeredity

/-!
# Principal Cartier boundary of polynomial graph centres

A graph centre with exactly one normal coordinate is generated by one equation
`Z-h`.  Such a centre is a principal Cartier-type chamber; blowing up an
already invertible principal ideal must not be counted as a genuine geometric
step.

This file proves the exact principal-ideal identity under the intrinsic type
condition `Subsingleton ι` and packages the finite dichotomy:

* `Subsingleton ι`: terminal/Cartier enrollment, no ordinary blowup action;
* `Nontrivial ι`: higher-rank graph centre, still requiring the separate
  scheme-level nonidentity theorem.

The result prevents the local graph macro from silently treating the
one-normal-variable case as a nonidentity resolution step.
-/

namespace PCRLean
namespace Experimental
namespace PolynomialGraphActionBoundary

noncomputable section

universe u v

variable {R : Type u} [CommRing R]
variable {ι : Type v} [Fintype ι] [DecidableEq ι]

open PolynomialGraphCentreHeredity

abbrev P := MvPolynomial ι R

/-- In a nonempty subsingleton normal direction type, the graph ideal is
principal. -/
theorem graphIdeal_eq_span_singleton
    [Nonempty ι] [Subsingleton ι]
    (h : ι → R) :
    graphIdeal h =
      Ideal.span ({graphGenerator h (default : ι)} : Set (P (R := R) (ι := ι))) := by
  rw [graphIdeal]
  congr 1
  ext x
  constructor
  · rintro ⟨i, rfl⟩
    simp [Subsingleton.elim i (default : ι)]
  · intro hx
    have hx' : x = graphGenerator h (default : ι) := by
      simpa using hx
    rw [hx']
    exact ⟨default, rfl⟩

/-- The one-normal-variable graph centre has an explicit principal generator. -/
theorem exists_principal_generator
    [Nonempty ι] [Subsingleton ι]
    (h : ι → R) :
    ∃ g : P (R := R) (ι := ι),
      graphIdeal h = Ideal.span ({g} : Set (P (R := R) (ι := ι))) :=
  ⟨graphGenerator h default, graphIdeal_eq_span_singleton h⟩

/-- Finite action classification for the graph-centre normal direction type. -/
inductive ActionClass (ι : Type v) : Prop
  | cartier (hsub : Subsingleton ι)
  | higherRank (hnontrivial : Nontrivial ι)

/-- Every finite normal direction type lies in exactly one of the two action
regimes used by the compiler. -/
theorem actionClass (ι : Type v) [Fintype ι] : ActionClass ι := by
  classical
  by_cases h : Subsingleton ι
  · exact ActionClass.cartier h
  · exact ActionClass.higherRank (not_subsingleton_iff_nontrivial.mp h)

/-- A nonempty Cartier-class graph centre is explicitly principal. -/
theorem principal_of_cartierClass
    [Nonempty ι]
    (h : ι → R)
    (hc : ActionClass ι)
    (hcartier : ∀ hnt : Nontrivial ι, False) :
    ∃ g : P (R := R) (ι := ι),
      graphIdeal h = Ideal.span ({g} : Set (P (R := R) (ι := ι))) := by
  cases hc with
  | cartier hsub =>
      letI : Subsingleton ι := hsub
      exact exists_principal_generator h
  | higherRank hnontrivial =>
      exact False.elim (hcartier hnontrivial)

end

end PolynomialGraphActionBoundary
end Experimental
end PCRLean
