import Mathlib
import PCRLean.CoordinateBoundarySNC
import PCRLean.Experimental.PolynomialGraphCentreHeredity
import PCRLean.Experimental.PolynomialGraphBlowupHeredity

/-!
# Boundary compatibility for polynomial graph centres

Let the coefficient ring be `K[X_a]`, with a finite or arbitrary family of old
boundary coordinates selected injectively among the passive variables.  In the
outer polynomial ring `K[X_a][Z_i]`, consider the graph centre

`Z_i - h_i(X) = 0`.

Graph translation is an algebra automorphism over the entire coefficient ring.
It therefore fixes every old boundary equation and sends each graph equation
to the separate coordinate `Z_i`.  The combined boundary/centre coordinate
family is injective, so no boundary direction collides with a centre direction.

Moreover every standard graph blowup chart fixes all coefficient-ring
polynomials.  Hence the old boundary ideal is carried to itself on every chart.
This is the exact algebraic SNC-frame gate for the graph-centre chamber.

The module records a coordinate-frame certificate, not the general theorem
that every regular boundary-compatible immersion admits such a graph atlas.
It also does not prove the next total boundary is globally SNC after overlap
gluing.
-/

namespace PCRLean
namespace Experimental
namespace PolynomialGraphBoundarySNC

noncomputable section

universe u v w x

variable {K : Type u} [Field K]
variable {β : Type v} {α : Type w} {ι : Type x}
variable [DecidableEq ι]

abbrev R := MvPolynomial α K
abbrev P := MvPolynomial ι (R (K := K) (α := α))

open PolynomialGraphCentreHeredity
open PolynomialGraphBlowupHeredity

/-- One old boundary equation, viewed in the outer graph polynomial ring. -/
def boundaryGenerator
    (F : CoordinateBoundarySNC.Frame (β := β) (α := α))
    (b : β) : P (K := K) (α := α) (ι := ι) :=
  MvPolynomial.C (MvPolynomial.X (F.boundary b))

/-- Actual ideal generated by all old boundary equations. -/
def boundaryIdeal
    (F : CoordinateBoundarySNC.Frame (β := β) (α := α)) :
    Ideal (P (K := K) (α := α) (ι := ι)) :=
  Ideal.span (Set.range (boundaryGenerator (K := K) (ι := ι) F))

/-- Combined old-boundary plus graph-centre ideal. -/
def combinedGraphIdeal
    (F : CoordinateBoundarySNC.Frame (β := β) (α := α))
    (h : ι → R (K := K) (α := α)) :
    Ideal (P (K := K) (α := α) (ι := ι)) :=
  boundaryIdeal (K := K) (ι := ι) F ⊔ graphIdeal h

/-- Combined old-boundary plus coordinate-centre ideal. -/
def combinedCoordinateIdeal
    (F : CoordinateBoundarySNC.Frame (β := β) (α := α)) :
    Ideal (P (K := K) (α := α) (ι := ι)) :=
  boundaryIdeal (K := K) (ι := ι) F ⊔
    originIdeal (R := R (K := K) (α := α)) (ι := ι)

/-- Every boundary equation belongs to the old boundary ideal. -/
theorem boundaryGenerator_mem
    (F : CoordinateBoundarySNC.Frame (β := β) (α := α))
    (b : β) :
    boundaryGenerator (K := K) (ι := ι) F b ∈
      boundaryIdeal (K := K) (ι := ι) F :=
  Ideal.subset_span ⟨b, rfl⟩

/-- Graph translation fixes every old boundary equation. -/
@[simp] theorem translate_boundaryGenerator
    (F : CoordinateBoundarySNC.Frame (β := β) (α := α))
    (h : ι → R (K := K) (α := α)) (b : β) :
    translate h (boundaryGenerator (K := K) (ι := ι) F b) =
      boundaryGenerator (K := K) (ι := ι) F b := by
  simp [boundaryGenerator, translate]

/-- Translation carries the old boundary ideal to itself. -/
theorem map_boundaryIdeal_eq
    (F : CoordinateBoundarySNC.Frame (β := β) (α := α))
    (h : ι → R (K := K) (α := α)) :
    Ideal.map (translate h) (boundaryIdeal (K := K) (ι := ι) F) =
      boundaryIdeal (K := K) (ι := ι) F := by
  apply le_antisymm
  · rw [Ideal.map_le_iff_le_comap, boundaryIdeal, Ideal.span_le]
    rintro x ⟨b, rfl⟩
    rw [Ideal.mem_comap]
    simpa using boundaryGenerator_mem (K := K) (ι := ι) F b
  · rw [boundaryIdeal, Ideal.span_le]
    rintro x ⟨b, rfl⟩
    have hm := Ideal.mem_map_of_mem (translate h)
      (boundaryGenerator_mem (K := K) (ι := ι) F b)
    simpa using hm

/-- Translation sends the combined graph/boundary ideal to the separated
coordinate model. -/
theorem map_combinedGraphIdeal_eq_coordinate
    (F : CoordinateBoundarySNC.Frame (β := β) (α := α))
    (h : ι → R (K := K) (α := α)) :
    Ideal.map (translate h) (combinedGraphIdeal (K := K) F h) =
      combinedCoordinateIdeal (K := K) (ι := ι) F := by
  rw [combinedGraphIdeal, combinedCoordinateIdeal, Ideal.map_sup,
    map_boundaryIdeal_eq, map_graphIdeal_eq_originIdeal]

/-- Every graph blowup chart fixes every old boundary equation. -/
@[simp] theorem graphChartMap_boundaryGenerator
    (F : CoordinateBoundarySNC.Frame (β := β) (α := α))
    (h : ι → R (K := K) (α := α))
    (k : ι) (b : β) :
    graphChartMap h k
        (boundaryGenerator (K := K) (ι := ι) F b) =
      boundaryGenerator (K := K) (ι := ι) F b := by
  simp [graphChartMap, coordinateChartMap, boundaryGenerator, translate]

/-- The old boundary ideal is exactly invariant in every standard graph chart. -/
theorem map_boundaryIdeal_chart_eq
    (F : CoordinateBoundarySNC.Frame (β := β) (α := α))
    (h : ι → R (K := K) (α := α))
    (k : ι) :
    Ideal.map (graphChartMap h k)
        (boundaryIdeal (K := K) (ι := ι) F) =
      boundaryIdeal (K := K) (ι := ι) F := by
  apply le_antisymm
  · rw [Ideal.map_le_iff_le_comap, boundaryIdeal, Ideal.span_le]
    rintro x ⟨b, rfl⟩
    rw [Ideal.mem_comap]
    simpa using boundaryGenerator_mem (K := K) (ι := ι) F b
  · rw [boundaryIdeal, Ideal.span_le]
    rintro x ⟨b, rfl⟩
    have hm := Ideal.mem_map_of_mem (graphChartMap h k)
      (boundaryGenerator_mem (K := K) (ι := ι) F b)
    simpa using hm

/-- Boundary and centre coordinate directions have no collisions. -/
theorem combined_directions_injective
    (F : CoordinateBoundarySNC.Frame (β := β) (α := α)) :
    Function.Injective (F.combined (ι := ι)) :=
  F.combined_injective (ι := ι)

/-- Typed local boundary/centre compatibility certificate. -/
structure Certificate
    (F : CoordinateBoundarySNC.Frame (β := β) (α := α))
    (h : ι → R (K := K) (α := α)) where
  directions_injective : Function.Injective (F.combined (ι := ι))
  translation_separates :
    Ideal.map (translate h) (combinedGraphIdeal (K := K) F h) =
      combinedCoordinateIdeal (K := K) (ι := ι) F
  allCharts_fix_boundary : ∀ k : ι,
    Ideal.map (graphChartMap h k)
        (boundaryIdeal (K := K) (ι := ι) F) =
      boundaryIdeal (K := K) (ι := ι) F

/-- Assemble the local SNC-frame certificate. -/
noncomputable def certificate
    (F : CoordinateBoundarySNC.Frame (β := β) (α := α))
    (h : ι → R (K := K) (α := α)) : Certificate (K := K) F h where
  directions_injective := combined_directions_injective (ι := ι) F
  translation_separates := map_combinedGraphIdeal_eq_coordinate F h
  allCharts_fix_boundary := fun k => map_boundaryIdeal_chart_eq F h k

end

end PolynomialGraphBoundarySNC
end Experimental
end PCRLean
