import Mathlib
import Mathlib.RingTheory.Ideal.Quotient.Operations
import Mathlib.RingTheory.RegularLocalRing.Defs
import PCRLean.Experimental.PolynomialGraphCentreQuotient

/-!
# Exact boundary intersections for polynomial graph centres

Let `P = R[Z_i]`, let `I_h = (Z_i-h_i)` be a polynomial graph centre, and let
`J ⊂ R` be an ideal describing a boundary stratum in the coefficient ring.
Write `J_P` for the ideal generated by the constant images of `J` in `P`.

This file proves

`I_h + J_P = graphEval_h ⁻¹(J)`

and consequently

`P / (I_h + J_P) ≃ R / J`.

Thus every boundary stratum restricts to the graph centre without acquiring
extra equations, nilpotents or hidden components.  If `R/J` is regular, the
intersection of that stratum with the graph centre is regular as well.

For an SNC boundary, applying the theorem to every finite boundary stratum is
the ring-theoretic core of centre--boundary compatibility.  The file does not
by itself package a scheme-level SNC divisor structure or prove transversality
outside this graph model.
-/

namespace PCRLean
namespace Experimental
namespace PolynomialGraphBoundaryIntersection

noncomputable section

universe u v

variable {R : Type u} [CommRing R] [IsDomain R]
variable {ι : Type v} [DecidableEq ι]

open PolynomialGraphCentreHeredity
open PolynomialGraphCentreQuotient

abbrev P := MvPolynomial ι R

/-- Extension of a coefficient-ring boundary ideal to the polynomial ambient
ring. -/
def coefficientIdeal (J : Ideal R) : Ideal (P (R := R) (ι := ι)) :=
  J.map MvPolynomial.C

/-- Scheme-theoretic intersection ideal of the graph centre and the extended
boundary stratum. -/
def combinedIdeal (h : ι → R) (J : Ideal R) :
    Ideal (P (R := R) (ι := ι)) :=
  graphIdeal h ⊔ coefficientIdeal (R := R) (ι := ι) J

/-- The extended boundary ideal maps back into the original boundary ideal. -/
theorem coefficientIdeal_le_comap
    (h : ι → R) (J : Ideal R) :
    coefficientIdeal (R := R) (ι := ι) J ≤
      J.comap (graphEval h) := by
  rw [coefficientIdeal, Ideal.map_le_iff_le_comap]
  intro r hr
  change graphEval h (MvPolynomial.C r) ∈ J
  simpa using hr

/-- The graph ideal maps to zero and hence lies over every coefficient ideal. -/
theorem graphIdeal_le_comap
    (h : ι → R) (J : Ideal R) :
    graphIdeal h ≤ J.comap (graphEval h) := by
  intro f hf
  change graphEval h f ∈ J
  have hz : graphEval h f = 0 :=
    RingHom.mem_ker.mp ((graphIdeal_le_ker h) hf)
  simpa [hz] using J.zero_mem

/-- Exact pullback formula for a boundary ideal. -/
theorem combinedIdeal_eq_comap
    (h : ι → R) (J : Ideal R) :
    combinedIdeal h J = J.comap (graphEval h) := by
  apply le_antisymm
  · exact sup_le (graphIdeal_le_comap h J)
      (coefficientIdeal_le_comap h J)
  · intro f hf
    have heval : graphEval h f ∈ J := hf
    have hdiff : f - constantProjection h f ∈ graphIdeal h :=
      sub_constantProjection_mem h f
    have hconst : constantProjection h f ∈
        coefficientIdeal (R := R) (ι := ι) J := by
      have hc : MvPolynomial.C (graphEval h f) ∈
          coefficientIdeal (R := R) (ι := ι) J := by
        exact Ideal.mem_map_of_mem MvPolynomial.C heval
      simpa [constantProjection] using hc
    have hdiff' : f - constantProjection h f ∈ combinedIdeal h J :=
      (show graphIdeal h ≤ combinedIdeal h J from le_sup_left) hdiff
    have hconst' : constantProjection h f ∈ combinedIdeal h J :=
      (show coefficientIdeal (R := R) (ι := ι) J ≤ combinedIdeal h J
        from le_sup_right) hconst
    have hadd := (combinedIdeal h J).add_mem hdiff' hconst'
    simpa using hadd

/-- Evaluation on the graph followed by reduction modulo the boundary. -/
def boundaryEval (h : ι → R) (J : Ideal R) :
    P (R := R) (ι := ι) →+* (R ⧸ J) :=
  (Ideal.Quotient.mk J).comp (graphEval h)

/-- The boundary evaluation kernel is exactly the combined intersection ideal. -/
theorem ker_boundaryEval_eq_combinedIdeal
    (h : ι → R) (J : Ideal R) :
    RingHom.ker (boundaryEval h J) = combinedIdeal h J := by
  rw [combinedIdeal_eq_comap]
  ext f
  constructor
  · intro hf
    have hz : boundaryEval h J f = 0 := RingHom.mem_ker.mp hf
    change Ideal.Quotient.mk J (graphEval h f) = 0 at hz
    exact (Ideal.Quotient.eq_zero_iff_mem).mp hz
  · intro hf
    apply RingHom.mem_ker.mpr
    change Ideal.Quotient.mk J (graphEval h f) = 0
    exact (Ideal.Quotient.eq_zero_iff_mem).mpr hf

/-- Boundary evaluation is surjective. -/
theorem boundaryEval_surjective
    (h : ι → R) (J : Ideal R) :
    Function.Surjective (boundaryEval h J) := by
  intro y
  obtain ⟨r, rfl⟩ := Ideal.Quotient.mk_surjective y
  refine ⟨MvPolynomial.C r, ?_⟩
  simp [boundaryEval]

/-- Exact quotient of the graph--boundary intersection. -/
noncomputable def quotientEquiv
    (h : ι → R) (J : Ideal R) :
    (P (R := R) (ι := ι) ⧸ combinedIdeal h J) ≃+* (R ⧸ J) :=
  (Ideal.quotEquivOfEq
      (ker_boundaryEval_eq_combinedIdeal h J).symm).trans
    (RingHom.quotientKerEquivOfSurjective
      (f := boundaryEval h J) (boundaryEval_surjective h J))

@[simp] theorem quotientEquiv_mk
    (h : ι → R) (J : Ideal R)
    (f : P (R := R) (ι := ι)) :
    quotientEquiv h J
        (Ideal.Quotient.mk (combinedIdeal h J) f) =
      Ideal.Quotient.mk J (graphEval h f) := by
  simp [quotientEquiv, boundaryEval]

/-- Regularity of a boundary stratum transfers exactly to its intersection
with the graph centre. -/
theorem quotient_isRegularRing
    (h : ι → R) (J : Ideal R)
    [IsRegularRing (R ⧸ J)] :
    IsRegularRing
      (P (R := R) (ι := ι) ⧸ combinedIdeal h J) := by
  exact IsRegularRing.of_ringEquiv (quotientEquiv h J).symm

/-- One exact boundary-intersection certificate. -/
structure Certificate (h : ι → R) (J : Ideal R) where
  intersection : Ideal (P (R := R) (ι := ι))
  intersection_eq : intersection = combinedIdeal h J
  pullback_eq : intersection = J.comap (graphEval h)
  quotient :
    (P (R := R) (ι := ι) ⧸ intersection) ≃+* (R ⧸ J)

/-- Assemble the exact intersection certificate. -/
noncomputable def certificate
    (h : ι → R) (J : Ideal R) : Certificate h J where
  intersection := combinedIdeal h J
  intersection_eq := rfl
  pullback_eq := combinedIdeal_eq_comap h J
  quotient := quotientEquiv h J

end

end PolynomialGraphBoundaryIntersection
end Experimental
end PCRLean
