import PCRLean.Experimental.PolynomialGraphBlowupHeredity

#print axioms PCRLean.Experimental.PolynomialGraphBlowupHeredity.graphGenerator_factorization
#print axioms PCRLean.Experimental.PolynomialGraphBlowupHeredity.graphGenerator_pow_factorization
#print axioms PCRLean.Experimental.PolynomialGraphBlowupHeredity.map_graphIdeal_le_pivotIdeal
#print axioms PCRLean.Experimental.PolynomialGraphBlowupHeredity.map_graphIdeal_pow_le_pivotIdeal_pow
#print axioms PCRLean.Experimental.PolynomialGraphBlowupHeredity.graphChartMap_mem_pivot_pow
#print axioms PCRLean.Experimental.PolynomialGraphBlowupHeredity.sourcePacket_permissible
#print axioms PCRLean.Experimental.PolynomialGraphBlowupHeredity.transformedRootIdeal_eq_top
#print axioms PCRLean.Experimental.PolynomialGraphBlowupHeredity.transformedRootIdeal_eq
