import Mathlib
import PCRLean.Experimental.PolynomialGraphFrobeniusCentreCertificate
import PCRLean.Experimental.PolynomialGraphMarkedTransformDebt

/-!
# Arbitrary-mark certificate for polynomial graph centres

Let `q = p^e` and let the graph-root source packet be generated by
`(Z_i-h_i)^q`.  For every positive mark `m ≤ q`:

* the same actual graph centre is marked-permissible;
* on every standard chart the controlled residual ideal is exactly
  `(E_k)^(q-m)`;
* if `m=q`, the packet is terminal;
* if `m<q`, the remaining obstruction is a positive pure exceptional debt; and
* the debt exponent is strictly smaller than the Frobenius block `q`.

Thus the arbitrary-mark local branch has a complete dichotomy with no hidden
residual equation.  The debt still has to be enrolled in the global boundary
and no-recharge ledgers.
-/

namespace PCRLean
namespace Experimental
namespace PolynomialGraphArbitraryMarkCertificate

noncomputable section

universe u v

variable {R : Type u} [CommRing R] [IsDomain R]
variable {ι : Type v} [Fintype ι] [DecidableEq ι] [Nonempty ι]

open PolynomialGraphCentreHeredity
open PolynomialGraphBlowupHeredity
open PolynomialGraphMarkedTransformDebt

abbrev P := MvPolynomial ι R

/-- Powers of an ideal form a decreasing filtration. -/
theorem pow_le_pow_of_le
    (I : Ideal (P (R := R) (ι := ι)))
    {m n : Nat} (hmn : m ≤ n) :
    I ^ n ≤ I ^ m := by
  obtain ⟨d, rfl⟩ := Nat.exists_eq_add_of_le hmn
  rw [pow_add]
  calc
    I ^ m * I ^ d ≤ I ^ m * ⊤ := mul_le_mul_left' le_top _
    _ = I ^ m := by simp

variable [IsNoetherianRing R] [IsRegularRing R]
variable (p : Nat) [Fact p.Prime] [CharP R p]

/-- Complete arbitrary-mark graph-centre certificate. -/
structure Certificate (h : ι → R) (e mark : Nat) where
  mark_pos : 0 < mark
  mark_le_block : mark ≤ p ^ e
  centreCertificate :
    PolynomialGraphFrobeniusCentreCertificate.Certificate p h e
  sourcePermissibleAtMark :
    MarkedIdeal.Permissible
      (R := P (R := R) (ι := ι))
      ⟨sourceIdeal h (p ^ e), mark, mark_pos⟩
      (graphIdeal h)
  chartFactorization : ∀ k i : ι,
    graphChartMap h k ((graphGenerator h i) ^ (p ^ e)) =
      (exceptional (R := R) k) ^ mark *
        controlledResidual (R := R) k i (p ^ e) mark
  chartResidualIdeal : ∀ k : ι,
    transformedMarkedRootIdeal (R := R) k (p ^ e) mark =
      (pivotIdeal (R := R) k) ^ (p ^ e - mark)
  debt_lt_block : p ^ e - mark < p ^ e
  terminal_or_positiveDebt :
    mark = p ^ e ∨ 0 < p ^ e - mark

/-- Assemble the arbitrary-mark graph-centre certificate. -/
noncomputable def certificate
    (h : ι → R) (e mark : Nat)
    (hmark_pos : 0 < mark)
    (hmark_le : mark ≤ p ^ e) :
    Certificate p h e mark where
  mark_pos := hmark_pos
  mark_le_block := hmark_le
  centreCertificate :=
    PolynomialGraphFrobeniusCentreCertificate.certificate p h e
  sourcePermissibleAtMark := by
    apply (sourceIdeal_le_graphIdeal_pow h (p ^ e)).trans
    exact pow_le_pow_of_le (graphIdeal h) hmark_le
  chartFactorization := fun k i =>
    graphGenerator_power_factorization_at_mark
      h k i (p ^ e) mark hmark_le
  chartResidualIdeal := fun k =>
    transformedMarkedRootIdeal_eq_pivotPower
      (R := R) k (p ^ e) mark
  debt_lt_block := by
    have hq : 0 < p ^ e := pow_pos (Fact.out : p.Prime).pos e
    omega
  terminal_or_positiveDebt := by
    omega

/-- At the exact mark every chart is terminal. -/
theorem exactMark_terminal
    (h : ι → R) (e : Nat) (k : ι) :
    transformedMarkedRootIdeal (R := R) k (p ^ e) (p ^ e) = ⊤ :=
  transformedMarkedRootIdeal_eq_top_of_exactMark
    (R := R) k (p ^ e)

/-- A strict submark produces a positive pure exceptional debt on every chart. -/
theorem strictSubmark_positiveDebt
    (e mark : Nat) (hmark : mark < p ^ e) :
    0 < p ^ e - mark :=
  debt_pos_of_mark_lt (p ^ e) mark hmark

end

end PolynomialGraphArbitraryMarkCertificate
end Experimental
end PCRLean
