import PCRLean.Experimental.PolynomialGraphMarkedTransformDebt

#print axioms PCRLean.Experimental.PolynomialGraphMarkedTransformDebt.graphGenerator_power_factorization_at_mark
#print axioms PCRLean.Experimental.PolynomialGraphMarkedTransformDebt.pivot_controlledResidual
#print axioms PCRLean.Experimental.PolynomialGraphMarkedTransformDebt.controlledResidual_mem_pivotPower
#print axioms PCRLean.Experimental.PolynomialGraphMarkedTransformDebt.transformedMarkedRootIdeal_eq_pivotPower
#print axioms PCRLean.Experimental.PolynomialGraphMarkedTransformDebt.transformedMarkedRootIdeal_eq_top_of_exactMark
#print axioms PCRLean.Experimental.PolynomialGraphMarkedTransformDebt.debt_pos_of_mark_lt
