import PCRLean.Experimental.PolynomialGraphBoundaryRegularSequence

#print axioms PCRLean.Experimental.PolynomialGraphBoundaryRegularSequence.quotientEquiv_smul_restrictEquation
#print axioms PCRLean.Experimental.PolynomialGraphBoundaryRegularSequence.sequence_forall₂
#print axioms PCRLean.Experimental.PolynomialGraphBoundaryRegularSequence.isWeaklyRegular_restrict_iff
#print axioms PCRLean.Experimental.PolynomialGraphBoundaryRegularSequence.isRegular_restrict_iff
#print axioms PCRLean.Experimental.PolynomialGraphBoundaryRegularSequence.isRegular_restrict
#print axioms PCRLean.Experimental.PolynomialGraphBoundaryRegularSequence.isRegular_of_restrict
