import Mathlib
import PCRLean.Experimental.ProjectiveMoritaDescent

/-!
# The intrinsic order ideal of a section of a finite-projective module

For a section `x : P`, its order ideal is generated by all values `f x` with
`f : P →ₗ[R] R`. If `P` is supplied with a finite dual frame, the finitely
many frame coefficients already generate the same ideal. The reconstruction
identity then shows

`x ∈ orderIdeal(x) • P`.

Thus the section vanishes after quotienting the base ring by its order ideal.
The ideal is independent of the chosen finite frame and is zero exactly when
the section is zero.
-/

namespace PCRLean
namespace Experimental
namespace ProjectiveSectionOrderIdeal

noncomputable section

universe u v w

variable {R : Type u} [CommRing R]
variable {P : Type v} [AddCommGroup P] [Module R P]
variable {ι : Type w} [Fintype ι] [DecidableEq ι]

open ProjectiveMoritaDescent

/-- Intrinsic order ideal of one module section. -/
def orderIdeal (x : P) : Ideal R :=
  Ideal.span (Set.range fun f : P →ₗ[R] R => f x)

/-- Finite coefficient ideal attached to one chosen dual frame. -/
def frameOrderIdeal
    (F : DualFrame (R := R) (P := P) (ι := ι))
    (x : P) : Ideal R :=
  Ideal.span (Set.range fun i : ι => F.functional i x)

/-- Frame coefficients are particular intrinsic functional values. -/
theorem frameOrderIdeal_le_orderIdeal
    (F : DualFrame (R := R) (P := P) (ι := ι))
    (x : P) :
    frameOrderIdeal F x ≤ orderIdeal x := by
  rw [frameOrderIdeal, orderIdeal, Ideal.span_le]
  rintro a ⟨i, rfl⟩
  exact Ideal.subset_span ⟨F.functional i, rfl⟩

/-- A finite dual frame generates every functional value of the section. -/
theorem orderIdeal_le_frameOrderIdeal
    (F : DualFrame (R := R) (P := P) (ι := ι))
    (x : P) :
    orderIdeal x ≤ frameOrderIdeal F x := by
  rw [orderIdeal, Ideal.span_le]
  rintro a ⟨f, rfl⟩
  rw [← F.reconstruct x, map_sum]
  exact (frameOrderIdeal F x).sum_mem fun i _ => by
    rw [map_smul, smul_eq_mul]
    exact (frameOrderIdeal F x).mul_mem_right (f (F.vector i))
      (Ideal.subset_span ⟨i, rfl⟩)

/-- The finite frame ideal is the intrinsic order ideal. -/
theorem frameOrderIdeal_eq_orderIdeal
    (F : DualFrame (R := R) (P := P) (ι := ι))
    (x : P) :
    frameOrderIdeal F x = orderIdeal x := by
  exact le_antisymm
    (frameOrderIdeal_le_orderIdeal F x)
    (orderIdeal_le_frameOrderIdeal F x)

/-- The section is generated by its own order ideal. -/
theorem section_mem_orderIdeal_smul_top
    (F : DualFrame (R := R) (P := P) (ι := ι))
    (x : P) :
    x ∈ orderIdeal x • (⊤ : Submodule R P) := by
  rw [← F.reconstruct x]
  exact Submodule.sum_mem _ fun i _ =>
    Submodule.smul_mem_smul
      (by
        rw [← F.frameOrderIdeal_eq_orderIdeal x]
        exact Ideal.subset_span ⟨i, rfl⟩)
      Submodule.mem_top

/-- The order ideal is zero exactly for the zero section. -/
theorem orderIdeal_eq_bot_iff
    (F : DualFrame (R := R) (P := P) (ι := ι))
    (x : P) :
    orderIdeal x = ⊥ ↔ x = 0 := by
  constructor
  · intro hbot
    rw [← F.reconstruct x]
    apply Finset.sum_eq_zero
    intro i hi
    have hmem : F.functional i x ∈ orderIdeal x :=
      Ideal.subset_span ⟨F.functional i, rfl⟩
    rw [hbot] at hmem
    have hz : F.functional i x = 0 := by simpa using hmem
    simp [hz]
  · rintro rfl
    simp [orderIdeal]

/-- Over a Noetherian base the intrinsic order ideal is finite type. -/
theorem orderIdeal_fg
    [IsNoetherianRing R]
    (x : P) : (orderIdeal x).FG :=
  IsNoetherian.noetherian _

end

end ProjectiveSectionOrderIdeal
end Experimental
end PCRLean
