import PCRLean.Experimental.ProjectiveSectionOrderIdealMinimality

#print axioms PCRLean.Experimental.ProjectiveSectionOrderIdealMinimality.coefficientsVanishMod_orderIdeal
#print axioms PCRLean.Experimental.ProjectiveSectionOrderIdealMinimality.coefficientsVanishMod_iff_orderIdeal_le
#print axioms PCRLean.Experimental.ProjectiveSectionOrderIdealMinimality.orderIdeal_isLeast
#print axioms PCRLean.Experimental.ProjectiveSectionOrderIdealMinimality.eq_top_of_orderIdeal_eq_top_of_coefficientsVanishMod
#print axioms PCRLean.Experimental.ProjectiveSectionOrderIdealMinimality.no_proper_ideal_absorbs_unit_obstruction
#print axioms PCRLean.Experimental.ProjectiveSectionOrderIdealMinimality.orderIdeal_eq_top_iff_no_proper_absorbing_ideal
