import PCRLean.Experimental.ProjectiveSectionOrderIdealBaseChange

#print axioms PCRLean.Experimental.ProjectiveSectionOrderIdealBaseChange.CompatibleFrames.map_frameOrderIdeal_eq
#print axioms PCRLean.Experimental.ProjectiveSectionOrderIdealBaseChange.CompatibleFrames.map_orderIdeal_eq
#print axioms PCRLean.Experimental.ProjectiveSectionOrderIdealBaseChange.CompatibleFrames.orderIdeal_eq_bot_of_source_eq_bot
#print axioms PCRLean.Experimental.ProjectiveSectionOrderIdealBaseChange.CompatibleFrames.source_orderIdeal_eq_bot_of_target_eq_bot
#print axioms PCRLean.Experimental.ProjectiveSectionOrderIdealBaseChange.CompatibleFrames.orderIdeal_eq_bot_iff
