import Mathlib
import PCRLean.Experimental.PDerivFrobeniusDescent
import PCRLean.Experimental.InitialFormFrobeniusCleaning
import PCRLean.Experimental.InitialFormCleaningTermination
import PCRLean.Experimental.ReesFrobeniusIntegralCompression
import PCRLean.Experimental.IntegralEquivalentReesPresentations

/-!
# Rank-zero Frobenius--Rees exit

This module packages the perfect-field rank-zero mechanism as one complete
non-geometric normalization macro.

For a nonconstant polynomial, either a first partial derivative is visible, or
there is a strict lower-degree `p`-th root.  The weighted root is integral over
the algebra generated by the original weighted equation and adjoining it does
not change the ambient integral class.

For a rank-zero lowest homogeneous initial form of positive degree, the degree
is divisible by `p`.  Cleaning by the canonical root removes the entire lowest
layer, strictly reduces monomial support, and the corresponding lower-weight
root is integral over the original weighted initial equation.

This does not select a blowup centre.  It normalizes the presentation before
centre synthesis.  The next geometric theorem must show that this integral
normalization preserves the singular locus and every legal transform.
-/

namespace PCRLean
namespace Experimental
namespace RankZeroFrobeniusReesExit

noncomputable section

universe u v

variable {K : Type u} [Field K]
variable {σ : Type v} [DecidableEq σ]
variable (p : Nat) [Fact p.Prime] [CharP K p] [PerfectField K p]

abbrev A := MvPolynomial σ K

open PDerivFrobeniusDescent
open InitialFormFrobeniusCleaning
open InitialFormCleaningTermination
open ReesFrobeniusIntegralCompression
open IntegralEquivalentReesPresentations

/-- Every nonconstant polynomial either has a visible derivative or a strict
lower-degree root whose weighted adjoining is integral. -/
theorem visible_or_integral_strict_root
    (f : A (K := K) (σ := σ))
    (hf : 0 < f.totalDegree) (m : Nat) :
    DerivativeVisible f ∨
      ∃ g : A (K := K) (σ := σ),
        f = g ^ p ∧
        0 < g.totalDegree ∧
        g.totalDegree < f.totalDegree ∧
        IsIntegral
          (Algebra.adjoin (A (K := K) (σ := σ))
            {weightedTerm (m * p) f})
          (weightedTerm m g) := by
  rcases visible_or_strict_root p f hf with hvis | hroot
  · exact Or.inl hvis
  · rcases hroot with ⟨g, hfg, hgpos, hglt⟩
    refine Or.inr ⟨g, hfg, hgpos, hglt, ?_⟩
    exact weightedRoot_isIntegral_over_adjoin p m f g hfg.symm

/-- The strict-root branch produces an integrally equivalent lower-weight
presentation. -/
theorem strictRoot_integralEquivalent
    (f g : A (K := K) (σ := σ))
    (m : Nat) (hroot : g ^ p = f) :
    IntegralEquivalent
      (Algebra.adjoin (A (K := K) (σ := σ))
        {weightedTerm (m * p) f})
      (Algebra.adjoin
        (Algebra.adjoin (A (K := K) (σ := σ))
          {weightedTerm (m * p) f})
        {weightedTerm m g}) :=
  singleRoot_integralEquivalent p
    (Algebra.adjoin (A (K := K) (σ := σ))
      {weightedTerm (m * p) f})
    m f g hroot (Algebra.subset_adjoin rfl)

namespace InitialDecomposition

variable {f : A (K := K) (σ := σ)} {n : Nat}
variable (D : InitialDecomposition f n)

/-- Complete initial-form cleaning certificate: divisible degree, higher
remainder, strict support decrease, and integral lower-weight root. -/
theorem integral_cleaning_exit
    (hrank : D.RankZero)
    (hinitial : D.initial ≠ 0)
    (hdegree : 0 < n) :
    ∃ m : Nat,
      n = m * p ∧ 0 < m ∧
      HigherThan n (f - (D.root p) ^ p) ∧
      (f - (D.root p) ^ p).support.card < f.support.card ∧
      IsIntegral
        (Algebra.adjoin (A (K := K) (σ := σ))
          {weightedTerm n D.initial})
        (weightedTerm m (D.root p)) := by
  have hdiv : p ∣ n := D.prime_dvd_initial_degree p hrank hinitial
  rcases hdiv with ⟨m, hm⟩
  have hnm : n = m * p := by
    rw [hm]
    ring
  have hmpos : 0 < m := by
    have hp : 0 < p := Fact.out.pos
    omega
  refine ⟨m, hnm, hmpos, D.cleaned_higher p hrank,
    cleaned_support_card_lt p D hrank hinitial, ?_⟩
  rw [hnm]
  exact weightedRoot_isIntegral_over_adjoin p m D.initial (D.root p)
    (D.root_pow p hrank)

/-- The initial root-adjoin presentation is integrally equivalent to the
original weighted initial equation. -/
theorem integral_cleaning_equivalent
    (hrank : D.RankZero)
    (hinitial : D.initial ≠ 0)
    (hdegree : 0 < n) :
    ∃ m : Nat, n = m * p ∧
      IntegralEquivalent
        (Algebra.adjoin (A (K := K) (σ := σ))
          {weightedTerm n D.initial})
        (Algebra.adjoin
          (Algebra.adjoin (A (K := K) (σ := σ))
            {weightedTerm n D.initial})
          {weightedTerm m (D.root p)}) := by
  rcases D.integral_cleaning_exit p hrank hinitial hdegree with
    ⟨m, hnm, hmpos, hhigher, hcard, hint⟩
  refine ⟨m, hnm, ?_⟩
  rw [hnm]
  exact singleRoot_integralEquivalent p
    (Algebra.adjoin (A (K := K) (σ := σ))
      {weightedTerm (m * p) D.initial})
    m D.initial (D.root p) (D.root_pow p hrank)
    (Algebra.subset_adjoin rfl)

end InitialDecomposition

end

end RankZeroFrobeniusReesExit
end Experimental
end PCRLean
