import PCRLean.Experimental.ReducedCoordinateCentreExactFrobeniusHeredity

#print axioms PCRLean.Experimental.ReducedCoordinateCentreExactFrobeniusHeredity.map_centreIdeal_eq_normalIdeal
#print axioms PCRLean.Experimental.ReducedCoordinateCentreExactFrobeniusHeredity.map_normalIdeal_eq_centreIdeal
#print axioms PCRLean.Experimental.ReducedCoordinateCentreExactFrobeniusHeredity.mem_centreIdeal_pow_iff_normalIdeal_pow
#print axioms PCRLean.Experimental.ReducedCoordinateCentreExactFrobeniusHeredity.mem_centreIdeal_pow_iff_normalOrderGE
#print axioms PCRLean.Experimental.ReducedCoordinateCentreExactFrobeniusHeredity.normalOrderGE_power_iff
#print axioms PCRLean.Experimental.ReducedCoordinateCentreExactFrobeniusHeredity.frobeniusPower_mem_centreIdeal_pow_iff
#print axioms PCRLean.Experimental.ReducedCoordinateCentreExactFrobeniusHeredity.coordinateCentre_reflects
#print axioms PCRLean.Experimental.ReducedCoordinateCentreExactFrobeniusHeredity.isReduced_of_coordinateCentre_reflects
#print axioms PCRLean.Experimental.ReducedCoordinateCentreExactFrobeniusHeredity.coordinateCentre_reflects_iff_isReduced
