import PCRLean.Experimental.ReducedPolynomialGraphCentreHeredity

#print axioms PCRLean.Experimental.ReducedPolynomialGraphCentreHeredity.translate_comp_neg
#print axioms PCRLean.Experimental.ReducedPolynomialGraphCentreHeredity.map_graphIdeal_eq_originIdeal
#print axioms PCRLean.Experimental.ReducedPolynomialGraphCentreHeredity.mem_graphIdeal_pow_iff
#print axioms PCRLean.Experimental.ReducedPolynomialGraphCentreHeredity.mem_graphIdeal_pow_iff_graphOrderGE
#print axioms PCRLean.Experimental.ReducedPolynomialGraphCentreHeredity.graphOrderGE_power_iff
#print axioms PCRLean.Experimental.ReducedPolynomialGraphCentreHeredity.frobeniusPower_mem_graphIdeal_pow_iff
#print axioms PCRLean.Experimental.ReducedPolynomialGraphCentreHeredity.graphIdeal_reflectsFrobeniusPowers
#print axioms PCRLean.Experimental.ReducedPolynomialGraphCentreHeredity.isReduced_of_graphIdeal_reflects
#print axioms PCRLean.Experimental.ReducedPolynomialGraphCentreHeredity.graphIdeal_reflects_iff_isReduced
