import PCRLean.Experimental.ReducedFrobeniusNormalLocalModel

#print axioms PCRLean.Experimental.ReducedFrobeniusNormalLocalModel.reflects_of_reducedCoordinateModel
#print axioms PCRLean.Experimental.ReducedFrobeniusNormalLocalModel.power_mem_scaled_iff_of_reducedCoordinateModel
#print axioms PCRLean.Experimental.ReducedFrobeniusNormalLocalModel.reflects_of_reducedGraphModel
#print axioms PCRLean.Experimental.ReducedFrobeniusNormalLocalModel.power_mem_scaled_iff_of_reducedGraphModel
