import PCRLean.Experimental.ReducedNormalConeKernelIndex

#print axioms PCRLean.Experimental.FrobeniusSupportReduced.pow_ne_zero_of_isReduced
#print axioms PCRLean.Experimental.FrobeniusSupportReduced.orderGE_power_iff
#print axioms PCRLean.Experimental.ReducedCoordinateCentreExactFrobeniusHeredity.frobeniusPower_mem_centreIdeal_pow_iff
#print axioms PCRLean.Experimental.ReducedCoordinateCentreExactFrobeniusHeredity.coordinateCentre_reflects_iff_isReduced
#print axioms PCRLean.Experimental.ReducedPolynomialGraphCentreHeredity.frobeniusPower_mem_graphIdeal_pow_iff
#print axioms PCRLean.Experimental.ReducedPolynomialGraphCentreHeredity.graphIdeal_reflects_iff_isReduced
#print axioms PCRLean.Experimental.ReducedGraphCentreQuotient.ker_graphEval_eq_graphIdeal
#print axioms PCRLean.Experimental.ReducedGraphCentreQuotient.quotientEquiv
#print axioms PCRLean.Experimental.ReducedGraphCentreQuotient.quotient_isReduced
#print axioms PCRLean.Experimental.ReducedGraphCentreQuotient.quotient_isRegularRing
#print axioms PCRLean.Experimental.ReducedFrobeniusNormalLocalModel.reflects_of_reducedCoordinateModel
#print axioms PCRLean.Experimental.ReducedFrobeniusNormalLocalModel.reflects_of_reducedGraphModel
#print axioms PCRLean.Experimental.ReducedNormalConePowerModel.PowerModel.initialPowerNonvanishing
#print axioms PCRLean.Experimental.ReducedNormalConePowerModel.reflectsFrobeniusPowers_of_models
#print axioms PCRLean.Experimental.ReducedNormalConeKernelIndex.loaded
