import Mathlib
import PCRLean.ReesFoundation

/-!
# Frobenius roots as integral Rees-algebra compression

If a weighted equation is a prime-power Frobenius power, its lower-weight root
should not be interpreted as a blowup centre by itself.  The correct structural
statement is that adjoining the root to the graded algebra is integral.

Let `x = g W^m` in the polynomial ring `A[W]`.  If `x^p` already belongs to a
subalgebra `S`, then `x` is integral over `S`, since an integral element remains
integral after taking a positive root.  When `g^p = f`, the identity

`(g W^m)^p = f W^(mp)`

shows that a weighted Frobenius root is integral over every graded algebra
containing the original weighted equation.  Thus Frobenius mark compression is
naturally an integral-closure operation rather than an identity blowup.

A full resolution proof still needs the geometric theorem that integral
equivalence of differential Rees algebras preserves singular loci, permissible
centres, controlled transforms and hereditary reentry.
-/

namespace PCRLean
namespace Experimental
namespace ReesFrobeniusIntegralCompression

noncomputable section

universe u

variable {A : Type u} [CommRing A]
variable (p : Nat) [Fact p.Prime]

/-- Weighted element `a W^m`. -/
def weightedTerm (m : Nat) (a : A) : Polynomial A :=
  Polynomial.monomial m a

/-- Exact power identity for weighted terms. -/
theorem weightedTerm_pow (m : Nat) (a : A) :
    (weightedTerm m a) ^ p = weightedTerm (m * p) (a ^ p) := by
  exact Polynomial.monomial_pow m a p

/-- Any positive root of an element already lying in a subalgebra is integral
over that subalgebra. -/
theorem isIntegral_of_pow_mem
    (S : Subalgebra A (Polynomial A))
    (x : Polynomial A) (hx : x ^ p ∈ S) :
    IsIntegral S x := by
  have hpow : IsIntegral S (x ^ p) := by
    simpa using
      (isIntegral_algebraMap (R := S) (A := Polynomial A)
        (⟨x ^ p, hx⟩ : S))
  exact hpow.of_pow Fact.out.pos

/-- A weighted Frobenius root is integral over a graded algebra containing the
original weighted equation. -/
theorem weightedRoot_isIntegral
    (S : Subalgebra A (Polynomial A))
    (m : Nat) (f g : A)
    (hroot : g ^ p = f)
    (hsource : weightedTerm (m * p) f ∈ S) :
    IsIntegral S (weightedTerm m g) := by
  apply isIntegral_of_pow_mem p S (weightedTerm m g)
  rw [weightedTerm_pow, hroot]
  exact hsource

/-- The root is integral over the algebra generated by the original weighted
Frobenius equation. -/
theorem weightedRoot_isIntegral_over_adjoin
    (m : Nat) (f g : A) (hroot : g ^ p = f) :
    IsIntegral
      (Algebra.adjoin A {weightedTerm (m * p) f})
      (weightedTerm m g) := by
  apply weightedRoot_isIntegral p
  exact Algebra.subset_adjoin rfl

/-- The same statement for an iterated prime-power root. -/
theorem weightedIteratedRoot_isIntegral
    (e m : Nat) (f g : A)
    (hroot : g ^ (p ^ e) = f)
    (he : 0 < e) :
    IsIntegral
      (Algebra.adjoin A {weightedTerm (m * (p ^ e)) f})
      (weightedTerm m g) := by
  have hpowmem :
      (weightedTerm m g) ^ (p ^ e) ∈
        Algebra.adjoin A {weightedTerm (m * (p ^ e)) f} := by
    rw [Polynomial.monomial_pow, hroot]
    exact Algebra.subset_adjoin rfl
  have hint : IsIntegral
      (Algebra.adjoin A {weightedTerm (m * (p ^ e)) f})
      ((weightedTerm m g) ^ (p ^ e)) := by
    simpa using
      (isIntegral_algebraMap
        (R := Algebra.adjoin A {weightedTerm (m * (p ^ e)) f})
        (A := Polynomial A)
        (⟨(weightedTerm m g) ^ (p ^ e), hpowmem⟩ :
          Algebra.adjoin A {weightedTerm (m * (p ^ e)) f}))
  exact hint.of_pow (pow_pos Fact.out.pos e)

end

end ReesFrobeniusIntegralCompression
end Experimental
end PCRLean
