import PCRLean.Experimental.SplitSurjectionTensorKernelExact

#print axioms PCRLean.Experimental.SplitSurjectionTensorKernelExact.project_residualLinear
#print axioms PCRLean.Experimental.SplitSurjectionTensorKernelExact.project_comp_kernelSubtype
#print axioms PCRLean.Experimental.SplitSurjectionTensorKernelExact.tensorProject_comp_tensorKernelInclusion
#print axioms PCRLean.Experimental.SplitSurjectionTensorKernelExact.tensorKernelInclusion_comp_tensorKernelProjection
#print axioms PCRLean.Experimental.SplitSurjectionTensorKernelExact.tensorResidual_eq_id_sub
#print axioms PCRLean.Experimental.SplitSurjectionTensorKernelExact.tensorResidual_eq_self_of_mem_ker
#print axioms PCRLean.Experimental.SplitSurjectionTensorKernelExact.range_tensorKernelInclusion_eq_ker
#print axioms PCRLean.Experimental.SplitSurjectionTensorKernelExact.tensorExtendedKernelIdeal_eq_tensorKernelIdeal
#print axioms PCRLean.Experimental.SplitSurjectionTensorKernelExact.tensorExtendedQuotientEquiv
