import Mathlib
import Mathlib.LinearAlgebra.SymmetricAlgebra.Basic
import Mathlib.RingTheory.Ideal.Quotient.Operations

/-!
# Experimental split-conormal symmetric quotient

Let `Kmod` be the persistent tangent directions and `Tmod` the transverse
conormal directions. On the split module `Kmod × Tmod`, the symmetric-algebra
map which keeps `Kmod` and kills `Tmod` has kernel exactly the ideal generated
by the transverse degree-one elements `ι (0,t)`.

Thus the quotient by the actual transverse ideal is the symmetric algebra of
the persistent factor. This is the coordinate-free algebraic shadow of an
actual regular linear centre. The theorem does not construct a split frame
from an arbitrary singular Frobenius/Fitting core and does not prove gluing.
-/

namespace PCRLean
namespace Experimental
namespace SplitConormalSymmetricQuotient

noncomputable section

universe u v w

variable {R : Type u} [CommRing R]
variable {Kmod : Type v} {Tmod : Type w}
variable [AddCommGroup Kmod] [Module R Kmod]
variable [AddCommGroup Tmod] [Module R Tmod]

abbrev V := Kmod × Tmod
abbrev SymV := SymmetricAlgebra R (V (Kmod := Kmod) (Tmod := Tmod))
abbrev SymK := SymmetricAlgebra R Kmod

/-- Linear generator map which keeps persistent directions and kills the
transverse factor. -/
def keepLinear :
    V (Kmod := Kmod) (Tmod := Tmod) →ₗ[R] SymK (R := R) (Kmod := Kmod) where
  toFun x := SymmetricAlgebra.ι R Kmod x.1
  map_add' := by
    intro x y
    simp
  map_smul' := by
    intro a x
    simp

/-- Symmetric-algebra elimination map. -/
def keep :
    SymV (R := R) (Kmod := Kmod) (Tmod := Tmod) →ₐ[R]
      SymK (R := R) (Kmod := Kmod) :=
  SymmetricAlgebra.lift (keepLinear (R := R) (Kmod := Kmod) (Tmod := Tmod))

/-- Degree-one embedding of the persistent factor. -/
def embedLinear :
    Kmod →ₗ[R] SymV (R := R) (Kmod := Kmod) (Tmod := Tmod) where
  toFun k := SymmetricAlgebra.ι R
    (V (Kmod := Kmod) (Tmod := Tmod)) (k, 0)
  map_add' := by
    intro x y
    change (SymmetricAlgebra.ι R
      (V (Kmod := Kmod) (Tmod := Tmod))) (x + y, 0) = _
    have hpair :
        (x + y, (0 : Tmod)) =
          (x, (0 : Tmod)) + (y, (0 : Tmod)) := by
      ext <;> simp
    rw [hpair]
    exact (SymmetricAlgebra.ι R
      (V (Kmod := Kmod) (Tmod := Tmod))).map_add _ _
  map_smul' := by
    intro a x
    change (SymmetricAlgebra.ι R
      (V (Kmod := Kmod) (Tmod := Tmod))) (a • x, 0) = _
    have hpair :
        (a • x, (0 : Tmod)) = a • (x, (0 : Tmod)) := by
      ext <;> simp
    rw [hpair]
    exact (SymmetricAlgebra.ι R
      (V (Kmod := Kmod) (Tmod := Tmod))).map_smul a _

/-- Symmetric-algebra embedding of the persistent factor. -/
def embedK :
    SymK (R := R) (Kmod := Kmod) →ₐ[R]
      SymV (R := R) (Kmod := Kmod) (Tmod := Tmod) :=
  SymmetricAlgebra.lift
    (embedLinear (R := R) (Kmod := Kmod) (Tmod := Tmod))

@[simp] theorem keep_ι (k : Kmod) (t : Tmod) :
    keep (R := R) (Kmod := Kmod) (Tmod := Tmod)
        (SymmetricAlgebra.ι R
          (V (Kmod := Kmod) (Tmod := Tmod)) (k, t)) =
      SymmetricAlgebra.ι R Kmod k := by
  simp [keep, keepLinear]

@[simp] theorem embedK_ι (k : Kmod) :
    embedK (R := R) (Kmod := Kmod) (Tmod := Tmod)
        (SymmetricAlgebra.ι R Kmod k) =
      SymmetricAlgebra.ι R
        (V (Kmod := Kmod) (Tmod := Tmod)) (k, 0) := by
  simp [embedK, embedLinear]

/-- Elimination after the persistent embedding is the identity. -/
theorem keep_comp_embedK :
    (keep (R := R) (Kmod := Kmod) (Tmod := Tmod)).comp
        (embedK (R := R) (Kmod := Kmod) (Tmod := Tmod)) =
      AlgHom.id R (SymK (R := R) (Kmod := Kmod)) := by
  apply SymmetricAlgebra.algHom_ext
  ext k
  simp

/-- Algebraic projection onto the persistent symmetric algebra, re-embedded in
the split symmetric algebra. -/
def projection :
    SymV (R := R) (Kmod := Kmod) (Tmod := Tmod) →ₐ[R]
      SymV (R := R) (Kmod := Kmod) (Tmod := Tmod) :=
  (embedK (R := R) (Kmod := Kmod) (Tmod := Tmod)).comp
    (keep (R := R) (Kmod := Kmod) (Tmod := Tmod))

/-- Actual ideal generated by all transverse degree-one elements. -/
def transverseIdeal :
    Ideal (SymV (R := R) (Kmod := Kmod) (Tmod := Tmod)) :=
  Ideal.span (Set.range fun t : Tmod =>
    SymmetricAlgebra.ι R
      (V (Kmod := Kmod) (Tmod := Tmod)) (0, t))

/-- Every transverse generator belongs to the actual transverse ideal. -/
theorem transverseGenerator_mem (t : Tmod) :
    SymmetricAlgebra.ι R
        (V (Kmod := Kmod) (Tmod := Tmod)) (0, t) ∈
      transverseIdeal (R := R) (Kmod := Kmod) (Tmod := Tmod) :=
  Ideal.subset_span ⟨t, rfl⟩

/-- A degree-one element differs from its persistent projection by precisely
its transverse degree-one part. -/
theorem ι_sub_projection_ι (k : Kmod) (t : Tmod) :
    SymmetricAlgebra.ι R
        (V (Kmod := Kmod) (Tmod := Tmod)) (k, t) -
      projection (R := R) (Kmod := Kmod) (Tmod := Tmod)
        (SymmetricAlgebra.ι R
          (V (Kmod := Kmod) (Tmod := Tmod)) (k, t)) =
      SymmetricAlgebra.ι R
        (V (Kmod := Kmod) (Tmod := Tmod)) (0, t) := by
  rw [projection]
  simp only [AlgHom.comp_apply, keep_ι, embedK_ι]
  rw [← (SymmetricAlgebra.ι R
    (V (Kmod := Kmod) (Tmod := Tmod))).map_sub]
  congr 1
  ext <;> simp

/-- Every symmetric polynomial differs from its persistent projection by an
element of the transverse ideal. -/
theorem sub_projection_mem
    (p : SymV (R := R) (Kmod := Kmod) (Tmod := Tmod)) :
    p - projection (R := R) (Kmod := Kmod) (Tmod := Tmod) p ∈
      transverseIdeal (R := R) (Kmod := Kmod) (Tmod := Tmod) := by
  induction p using SymmetricAlgebra.induction with
  | algebraMap r => simp [projection]
  | ι x =>
      rcases x with ⟨k, t⟩
      rw [ι_sub_projection_ι]
      exact transverseGenerator_mem (R := R) (Kmod := Kmod) t
  | mul a b ha hb =>
      have h1 :
          (a - projection (R := R) (Kmod := Kmod) (Tmod := Tmod) a) * b ∈
            transverseIdeal (R := R) (Kmod := Kmod) (Tmod := Tmod) :=
        (transverseIdeal (R := R) (Kmod := Kmod) (Tmod := Tmod)).mul_mem_right b ha
      have h2 :
          projection (R := R) (Kmod := Kmod) (Tmod := Tmod) a *
              (b - projection (R := R) (Kmod := Kmod) (Tmod := Tmod) b) ∈
            transverseIdeal (R := R) (Kmod := Kmod) (Tmod := Tmod) :=
        (transverseIdeal (R := R) (Kmod := Kmod) (Tmod := Tmod)).mul_mem_left
          (projection (R := R) (Kmod := Kmod) (Tmod := Tmod) a) hb
      have hadd :=
        (transverseIdeal (R := R) (Kmod := Kmod) (Tmod := Tmod)).add_mem h1 h2
      have heq :
          a * b - projection (R := R) (Kmod := Kmod) (Tmod := Tmod) (a * b) =
            (a - projection (R := R) (Kmod := Kmod) (Tmod := Tmod) a) * b +
              projection (R := R) (Kmod := Kmod) (Tmod := Tmod) a *
                (b - projection (R := R) (Kmod := Kmod) (Tmod := Tmod) b) := by
        rw [map_mul]
        ring
      rw [heq]
      exact hadd
  | add a b ha hb =>
      have hadd :=
        (transverseIdeal (R := R) (Kmod := Kmod) (Tmod := Tmod)).add_mem ha hb
      have heq :
          a + b - projection (R := R) (Kmod := Kmod) (Tmod := Tmod) (a + b) =
            (a - projection (R := R) (Kmod := Kmod) (Tmod := Tmod) a) +
              (b - projection (R := R) (Kmod := Kmod) (Tmod := Tmod) b) := by
        rw [map_add]
        abel
      rw [heq]
      exact hadd

/-- The actual transverse ideal is contained in the elimination kernel. -/
theorem transverseIdeal_le_ker :
    transverseIdeal (R := R) (Kmod := Kmod) (Tmod := Tmod) ≤
      RingHom.ker
        (keep (R := R) (Kmod := Kmod) (Tmod := Tmod)).toRingHom := by
  rw [transverseIdeal, Ideal.span_le]
  rintro x ⟨t, rfl⟩
  apply RingHom.mem_ker.mpr
  simp

/-- Coordinate-free kernel theorem for a split conormal module. -/
theorem ker_keep_eq_transverseIdeal :
    RingHom.ker
        (keep (R := R) (Kmod := Kmod) (Tmod := Tmod)).toRingHom =
      transverseIdeal (R := R) (Kmod := Kmod) (Tmod := Tmod) := by
  apply le_antisymm
  · intro p hp
    have hzero : keep (R := R) (Kmod := Kmod) (Tmod := Tmod) p = 0 :=
      RingHom.mem_ker.mp hp
    have hmem := sub_projection_mem
      (R := R) (Kmod := Kmod) (Tmod := Tmod) p
    simpa [projection, hzero] using hmem
  · exact transverseIdeal_le_ker (R := R) (Kmod := Kmod) (Tmod := Tmod)

/-- Elimination is surjective because it has the symmetric-algebra embedding. -/
theorem keep_surjective :
    Function.Surjective
      (keep (R := R) (Kmod := Kmod) (Tmod := Tmod)) := by
  intro y
  refine ⟨embedK (R := R) (Kmod := Kmod) (Tmod := Tmod) y, ?_⟩
  have h := congrArg
    (fun f : SymK (R := R) (Kmod := Kmod) →ₐ[R]
        SymK (R := R) (Kmod := Kmod) => f y)
    (keep_comp_embedK (R := R) (Kmod := Kmod) (Tmod := Tmod))
  simpa using h

/-- Exact coordinate-free quotient by the split transverse centre. -/
noncomputable def quotientEquiv :
    (SymV (R := R) (Kmod := Kmod) (Tmod := Tmod) ⧸
        transverseIdeal (R := R) (Kmod := Kmod) (Tmod := Tmod)) ≃+*
      SymK (R := R) (Kmod := Kmod) :=
  (Ideal.quotEquivOfEq
      (ker_keep_eq_transverseIdeal
        (R := R) (Kmod := Kmod) (Tmod := Tmod)).symm).trans
    (RingHom.quotientKerEquivOfSurjective
      (f := (keep (R := R) (Kmod := Kmod) (Tmod := Tmod)).toRingHom)
      (keep_surjective (R := R) (Kmod := Kmod) (Tmod := Tmod)))

end

end SplitConormalSymmetricQuotient
end Experimental
end PCRLean