import PCRLean.Experimental.SplitSurjectionSymmetricQuotient

#print axioms PCRLean.Experimental.SplitSurjectionSymmetricQuotient.SplitSurjection.project_liftBack
#print axioms PCRLean.Experimental.SplitSurjectionSymmetricQuotient.SplitSurjection.projectAlg_comp_liftBackAlg
#print axioms PCRLean.Experimental.SplitSurjectionSymmetricQuotient.SplitSurjection.residual_mem_ker
#print axioms PCRLean.Experimental.SplitSurjectionSymmetricQuotient.SplitSurjection.ι_sub_algebraProjection_ι
#print axioms PCRLean.Experimental.SplitSurjectionSymmetricQuotient.SplitSurjection.sub_algebraProjection_mem
#print axioms PCRLean.Experimental.SplitSurjectionSymmetricQuotient.SplitSurjection.kernelIdeal_le_ker_projectAlg
#print axioms PCRLean.Experimental.SplitSurjectionSymmetricQuotient.SplitSurjection.ker_projectAlg_eq_kernelIdeal
#print axioms PCRLean.Experimental.SplitSurjectionSymmetricQuotient.SplitSurjection.projectAlg_surjective
#print axioms PCRLean.Experimental.SplitSurjectionSymmetricQuotient.SplitSurjection.quotientEquiv
