import Mathlib
import Mathlib.RingTheory.Noetherian.Basic
import PCRLean.Experimental.SplitSurjectionSymmetricQuotient

/-!
# Experimental actual centre from a split surjection

For a split linear projection, the intrinsic kernel ideal in the symmetric
algebra is an actual ideal independent of the chosen complement.  If the
ambient symmetric algebra is Noetherian, that ideal is finitely generated.  If
the target symmetric algebra is nontrivial, the ideal is proper.  Together with
the exact quotient theorem, these data form an affine finite-type centre
certificate.

This does not prove regular immersion over an arbitrary base, construct the
split projection from Frobenius/Fitting data, or provide hereditary blowup
transport.
-/

namespace PCRLean
namespace Experimental
namespace SplitSurjectionActualCentre

noncomputable section

universe u v w

variable {R : Type u} [CommRing R]
variable {V : Type v} {Kmod : Type w}
variable [AddCommGroup V] [Module R V]
variable [AddCommGroup Kmod] [Module R Kmod]

open SplitSurjectionSymmetricQuotient

variable (S : SplitSurjection (R := R) (V := V) (Kmod := Kmod))

/-- Properness follows from the nontrivial quotient target. -/
theorem kernelIdeal_ne_top
    [Nontrivial (SymmetricAlgebra R Kmod)] :
    S.kernelIdeal ≠ ⊤ := by
  intro htop
  have hmem : (1 : SymmetricAlgebra R V) ∈ S.kernelIdeal := by
    rw [htop]
    trivial
  rw [← S.ker_projectAlg_eq_kernelIdeal] at hmem
  have hzero := RingHom.mem_ker.mp hmem
  simpa using hzero

/-- Noetherianity turns the intrinsic actual ideal into a finite-type ideal. -/
theorem kernelIdeal_fg
    [IsNoetherianRing (SymmetricAlgebra R V)] :
    S.kernelIdeal.FG :=
  IsNoetherian.noetherian _

/-- One affine actual-centre certificate generated by a split conormal
projection. -/
structure Certificate where
  ideal : Ideal (SymmetricAlgebra R V)
  ideal_eq : ideal = S.kernelIdeal
  proper : ideal ≠ ⊤
  finiteType : ideal.FG
  quotient :
    (SymmetricAlgebra R V ⧸ ideal) ≃+* SymmetricAlgebra R Kmod

/-- Assemble the finite-type certificate from the kernel theorem and
Noetherianity. -/
noncomputable def certificate
    [Nontrivial (SymmetricAlgebra R Kmod)]
    [IsNoetherianRing (SymmetricAlgebra R V)] :
    Certificate S where
  ideal := S.kernelIdeal
  ideal_eq := rfl
  proper := kernelIdeal_ne_top S
  finiteType := kernelIdeal_fg S
  quotient := S.quotientEquiv

end

end SplitSurjectionActualCentre
end Experimental
end PCRLean
