import Mathlib
import Mathlib.LinearAlgebra.TensorProduct.Map
import PCRLean.Experimental.SplitSurjectionTensorHeredity

/-!
# Experimental exact tensor kernel for split-surjection centres

For a split projection `project : V → Kmod`, tensoring by an arbitrary module
preserves not only surjectivity but the kernel itself.  The kernel of
`project ⊗ 1` is exactly the range of the natural map
`ker(project) ⊗ M → V ⊗ M`.  This requires no flatness because the chosen
splitting gives an explicit residual projection onto the kernel.

Consequently the intrinsic centre ideal after tensor transport is exactly the
ideal generated by the tensor extension of the old linear kernel.  This is a
module-level hereditary identity.  A later scalar-base-change theorem must
still compare symmetric algebras over different base rings and identify this
ideal with ordinary ideal extension under that algebra equivalence.
-/

namespace PCRLean
namespace Experimental
namespace SplitSurjectionTensorKernelExact

noncomputable section

universe u v w x

variable {R : Type u} [CommRing R]
variable {V : Type v} {Kmod : Type w} {M : Type x}
variable [AddCommGroup V] [Module R V]
variable [AddCommGroup Kmod] [Module R Kmod]
variable [AddCommGroup M] [Module R M]

open scoped TensorProduct
open SplitSurjectionSymmetricQuotient
open SplitSurjectionTensorHeredity

variable (S : SplitSurjection (R := R) (V := V) (Kmod := Kmod))

/-- Linear residual projection associated to the chosen splitting. -/
def residualLinear : V →ₗ[R] V :=
  LinearMap.id - S.liftBack.comp S.project

@[simp] theorem residualLinear_apply (v : V) :
    S.residualLinear v = v - S.liftBack (S.project v) := rfl

/-- The residual projection lands in the original linear kernel. -/
theorem project_residualLinear (v : V) :
    S.project (S.residualLinear v) = 0 := by
  simp [residualLinear, S.project_liftBack]

/-- Residual projection with codomain restricted to the kernel subtype. -/
def kernelProjection : V →ₗ[R] LinearMap.ker S.project where
  toFun v := ⟨S.residualLinear v, S.project_residualLinear v⟩
  map_add' x y := by
    apply Subtype.ext
    exact (S.residualLinear).map_add x y
  map_smul' a x := by
    apply Subtype.ext
    exact (S.residualLinear).map_smul a x

/-- Including the kernel after residual projection recovers the residual linear
endomorphism. -/
theorem kernelSubtype_comp_kernelProjection :
    (LinearMap.ker S.project).subtype.comp S.kernelProjection =
      S.residualLinear := by
  ext v
  rfl

/-- Projecting a vector already in the kernel gives zero. -/
theorem project_comp_kernelSubtype :
    S.project.comp (LinearMap.ker S.project).subtype = 0 := by
  ext k
  exact LinearMap.mem_ker.mp k.2

/-- Natural tensor extension of the original kernel inclusion. -/
def tensorKernelInclusion :
    TensorProduct R (LinearMap.ker S.project) M →ₗ[R]
      TensorProduct R V M :=
  (LinearMap.ker S.project).subtype.rTensor M

/-- Tensor extension of the residual projection onto the old kernel. -/
def tensorKernelProjection :
    TensorProduct R V M →ₗ[R]
      TensorProduct R (LinearMap.ker S.project) M :=
  S.kernelProjection.rTensor M

/-- Tensor extension of the residual endomorphism. -/
def tensorResidual :
    TensorProduct R V M →ₗ[R] TensorProduct R V M :=
  S.residualLinear.rTensor M

/-- The transported projection vanishes on the tensor-extended old kernel. -/
theorem tensorProject_comp_tensorKernelInclusion :
    S.tensorProject.comp S.tensorKernelInclusion = 0 := by
  change (S.project.rTensor M).comp
      ((LinearMap.ker S.project).subtype.rTensor M) = 0
  rw [← LinearMap.rTensor_comp]
  rw [S.project_comp_kernelSubtype]
  simp

/-- Tensor inclusion after tensor residual projection is the transported
residual endomorphism. -/
theorem tensorKernelInclusion_comp_tensorKernelProjection :
    S.tensorKernelInclusion.comp S.tensorKernelProjection =
      S.tensorResidual := by
  change ((LinearMap.ker S.project).subtype.rTensor M).comp
      (S.kernelProjection.rTensor M) = S.residualLinear.rTensor M
  rw [← LinearMap.rTensor_comp]
  rw [S.kernelSubtype_comp_kernelProjection]

/-- The transported residual is identity minus the transported split
projection. -/
theorem tensorResidual_eq_id_sub :
    S.tensorResidual =
      LinearMap.id - S.tensorLiftBack.comp S.tensorProject := by
  change ((LinearMap.id - S.liftBack.comp S.project).rTensor M) =
    LinearMap.id -
      (S.liftBack.rTensor M).comp (S.project.rTensor M)
  rw [LinearMap.rTensor_sub, LinearMap.rTensor_comp]
  simp

/-- On the kernel of the transported projection, the transported residual is
the identity. -/
theorem tensorResidual_eq_self_of_mem_ker
    {y : TensorProduct R V M}
    (hy : y ∈ LinearMap.ker S.tensorProject) :
    S.tensorResidual y = y := by
  have hy0 : S.tensorProject y = 0 := LinearMap.mem_ker.mp hy
  rw [S.tensorResidual_eq_id_sub]
  simp [LinearMap.comp_apply, hy0]

/-- Every tensor-extended old-kernel element lies in the new kernel. -/
theorem range_tensorKernelInclusion_le_ker :
    LinearMap.range S.tensorKernelInclusion ≤
      LinearMap.ker S.tensorProject := by
  intro y hy
  rcases hy with ⟨x, rfl⟩
  apply LinearMap.mem_ker.mpr
  have h := congrArg
    (fun f : TensorProduct R (LinearMap.ker S.project) M →ₗ[R]
        TensorProduct R Kmod M => f x)
    S.tensorProject_comp_tensorKernelInclusion
  simpa [LinearMap.comp_apply] using h

/-- Every element of the new kernel comes from the tensor extension of the old
kernel. -/
theorem ker_le_range_tensorKernelInclusion :
    LinearMap.ker S.tensorProject ≤
      LinearMap.range S.tensorKernelInclusion := by
  intro y hy
  refine ⟨S.tensorKernelProjection y, ?_⟩
  have h := congrArg
    (fun f : TensorProduct R V M →ₗ[R] TensorProduct R V M => f y)
    S.tensorKernelInclusion_comp_tensorKernelProjection
  calc
    S.tensorKernelInclusion (S.tensorKernelProjection y) =
        S.tensorResidual y := by
      simpa [LinearMap.comp_apply] using h
    _ = y := S.tensorResidual_eq_self_of_mem_ker hy

/-- Exact kernel transport for a split projection, with no flatness
hypothesis. -/
theorem range_tensorKernelInclusion_eq_ker :
    LinearMap.range S.tensorKernelInclusion =
      LinearMap.ker S.tensorProject := by
  apply le_antisymm
  · exact S.range_tensorKernelInclusion_le_ker
  · exact S.ker_le_range_tensorKernelInclusion

/-- Ideal generated in the transported symmetric algebra by the tensor
extension of the old kernel. -/
def tensorExtendedKernelIdeal :
    Ideal (SymmetricAlgebra R (TensorProduct R V M)) :=
  Ideal.span (Set.range fun
    x : TensorProduct R (LinearMap.ker S.project) M =>
      SymmetricAlgebra.ι R (TensorProduct R V M)
        (S.tensorKernelInclusion x))

/-- The tensor-extended old-kernel ideal is contained in the intrinsic new
kernel ideal. -/
theorem tensorExtendedKernelIdeal_le_tensorKernelIdeal :
    S.tensorExtendedKernelIdeal ≤
      (S.tensorSplit (M := M)).kernelIdeal := by
  rw [tensorExtendedKernelIdeal, Ideal.span_le]
  rintro z ⟨x, rfl⟩
  apply Ideal.subset_span
  have hx : S.tensorKernelInclusion x ∈
      LinearMap.ker (S.tensorSplit (M := M)).project := by
    have hx' : S.tensorKernelInclusion x ∈
        LinearMap.ker S.tensorProject :=
      S.range_tensorKernelInclusion_le_ker ⟨x, rfl⟩
    simpa using hx'
  exact ⟨⟨S.tensorKernelInclusion x, hx⟩, rfl⟩

/-- Every intrinsic new-kernel generator is generated by the tensor extension
of the old kernel. -/
theorem tensorKernelIdeal_le_tensorExtendedKernelIdeal :
    (S.tensorSplit (M := M)).kernelIdeal ≤
      S.tensorExtendedKernelIdeal := by
  rw [SplitSurjectionSymmetricQuotient.SplitSurjection.kernelIdeal,
    Ideal.span_le]
  rintro z ⟨k, rfl⟩
  have hk : k.1 ∈ LinearMap.ker S.tensorProject := by
    simpa using k.2
  rcases S.ker_le_range_tensorKernelInclusion hk with ⟨x, hx⟩
  rw [← hx]
  exact Ideal.subset_span ⟨x, rfl⟩

/-- Exact hereditary identity for the intrinsic centre ideal after tensor
transport. -/
theorem tensorExtendedKernelIdeal_eq_tensorKernelIdeal :
    S.tensorExtendedKernelIdeal =
      (S.tensorSplit (M := M)).kernelIdeal := by
  apply le_antisymm
  · exact S.tensorExtendedKernelIdeal_le_tensorKernelIdeal
  · exact S.tensorKernelIdeal_le_tensorExtendedKernelIdeal

/-- Exact quotient theorem stated using the tensor-extension presentation of
the old kernel. -/
noncomputable def tensorExtendedQuotientEquiv :
    (SymmetricAlgebra R (TensorProduct R V M) ⧸
        S.tensorExtendedKernelIdeal) ≃+*
      SymmetricAlgebra R (TensorProduct R Kmod M) := by
  rw [S.tensorExtendedKernelIdeal_eq_tensorKernelIdeal]
  exact S.tensorQuotientEquiv

end

end SplitSurjectionTensorKernelExact
end Experimental
end PCRLean
