import Mathlib
import Mathlib.LinearAlgebra.SymmetricAlgebra.Basic
import Mathlib.RingTheory.Ideal.Quotient.Operations

/-!
# Experimental split-surjection symmetric quotient

Let `project : V →ₗ[R] Kmod` admit a linear right inverse. The induced map
`SymmetricAlgebra R V → SymmetricAlgebra R Kmod` has kernel exactly the actual
ideal generated by degree-one elements coming from `LinearMap.ker project`.
Consequently the quotient by that intrinsic kernel ideal is the symmetric
algebra of `Kmod`.

The ideal depends only on `project`; the chosen right inverse is used only to
prove the quotient theorem. This is therefore stronger than a coordinate or
chosen-complement statement. It still assumes a split linear projection and
does not construct such a projection from an arbitrary Frobenius/Fitting core.
-/

namespace PCRLean
namespace Experimental
namespace SplitSurjectionSymmetricQuotient

noncomputable section

universe u v w

variable {R : Type u} [CommRing R]
variable {V : Type v} {Kmod : Type w}
variable [AddCommGroup V] [Module R V]
variable [AddCommGroup Kmod] [Module R Kmod]

structure SplitSurjection where
  project : V →ₗ[R] Kmod
  liftBack : Kmod →ₗ[R] V
  rightInverse : project.comp liftBack = LinearMap.id

namespace SplitSurjection

variable (S : SplitSurjection (R := R) (V := V) (Kmod := Kmod))

@[simp] theorem project_liftBack (k : Kmod) :
    S.project (S.liftBack k) = k := by
  have h := congrArg (fun L : Kmod →ₗ[R] Kmod => L k) S.rightInverse
  simpa [LinearMap.comp_apply] using h

def projectAlg : SymmetricAlgebra R V →ₐ[R] SymmetricAlgebra R Kmod :=
  SymmetricAlgebra.lift ((SymmetricAlgebra.ι R Kmod).comp S.project)

def liftBackAlg : SymmetricAlgebra R Kmod →ₐ[R] SymmetricAlgebra R V :=
  SymmetricAlgebra.lift ((SymmetricAlgebra.ι R V).comp S.liftBack)

@[simp] theorem projectAlg_ι (v : V) :
    S.projectAlg (SymmetricAlgebra.ι R V v) =
      SymmetricAlgebra.ι R Kmod (S.project v) := by
  simp [projectAlg]

@[simp] theorem liftBackAlg_ι (k : Kmod) :
    S.liftBackAlg (SymmetricAlgebra.ι R Kmod k) =
      SymmetricAlgebra.ι R V (S.liftBack k) := by
  simp [liftBackAlg]

theorem projectAlg_comp_liftBackAlg :
    S.projectAlg.comp S.liftBackAlg = AlgHom.id R (SymmetricAlgebra R Kmod) := by
  apply SymmetricAlgebra.algHom_ext
  ext k
  simp

def algebraProjection : SymmetricAlgebra R V →ₐ[R] SymmetricAlgebra R V :=
  S.liftBackAlg.comp S.projectAlg

def kernelIdeal : Ideal (SymmetricAlgebra R V) :=
  Ideal.span (Set.range fun x : S.project.ker => SymmetricAlgebra.ι R V x.1)

def residual (v : V) : V := v - S.liftBack (S.project v)

theorem residual_mem_ker (v : V) : S.residual v ∈ S.project.ker := by
  change S.project (v - S.liftBack (S.project v)) = 0
  simp [S.project_liftBack]

theorem residualGenerator_mem (v : V) :
    SymmetricAlgebra.ι R V (S.residual v) ∈ S.kernelIdeal := by
  apply Ideal.subset_span
  exact ⟨⟨S.residual v, S.residual_mem_ker v⟩, rfl⟩

theorem ι_sub_algebraProjection_ι (v : V) :
    SymmetricAlgebra.ι R V v -
        S.algebraProjection (SymmetricAlgebra.ι R V v) =
      SymmetricAlgebra.ι R V (S.residual v) := by
  rw [algebraProjection]
  simp only [AlgHom.comp_apply, projectAlg_ι, liftBackAlg_ι]
  rw [← (SymmetricAlgebra.ι R V).map_sub]
  rfl

theorem sub_algebraProjection_mem (p : SymmetricAlgebra R V) :
    p - S.algebraProjection p ∈ S.kernelIdeal := by
  induction p using SymmetricAlgebra.induction with
  | algebraMap r => simp [algebraProjection]
  | ι v =>
      rw [S.ι_sub_algebraProjection_ι]
      exact S.residualGenerator_mem v
  | mul a b ha hb =>
      have h1 : (a - S.algebraProjection a) * b ∈ S.kernelIdeal :=
        S.kernelIdeal.mul_mem_right b ha
      have h2 : S.algebraProjection a * (b - S.algebraProjection b) ∈
          S.kernelIdeal :=
        S.kernelIdeal.mul_mem_left (S.algebraProjection a) hb
      have hadd := S.kernelIdeal.add_mem h1 h2
      have heq :
          a * b - S.algebraProjection (a * b) =
            (a - S.algebraProjection a) * b +
              S.algebraProjection a * (b - S.algebraProjection b) := by
        rw [map_mul]
        ring
      rw [heq]
      exact hadd
  | add a b ha hb =>
      have hadd := S.kernelIdeal.add_mem ha hb
      have heq :
          a + b - S.algebraProjection (a + b) =
            (a - S.algebraProjection a) + (b - S.algebraProjection b) := by
        rw [map_add]
        abel
      rw [heq]
      exact hadd

theorem kernelIdeal_le_ker_projectAlg :
    S.kernelIdeal ≤ RingHom.ker S.projectAlg.toRingHom := by
  rw [kernelIdeal, Ideal.span_le]
  rintro x ⟨k, rfl⟩
  apply RingHom.mem_ker.mpr
  change S.projectAlg (SymmetricAlgebra.ι R V k.1) = 0
  rw [projectAlg_ι]
  have hk : S.project k.1 = 0 := LinearMap.mem_ker.mp k.2
  simp [hk]

theorem ker_projectAlg_eq_kernelIdeal :
    RingHom.ker S.projectAlg.toRingHom = S.kernelIdeal := by
  apply le_antisymm
  · intro p hp
    have hzero : S.projectAlg p = 0 := RingHom.mem_ker.mp hp
    have hmem := S.sub_algebraProjection_mem p
    simpa [algebraProjection, hzero] using hmem
  · exact S.kernelIdeal_le_ker_projectAlg

theorem projectAlg_surjective : Function.Surjective S.projectAlg := by
  intro y
  refine ⟨S.liftBackAlg y, ?_⟩
  have h := congrArg
    (fun f : SymmetricAlgebra R Kmod →ₐ[R] SymmetricAlgebra R Kmod => f y)
    S.projectAlg_comp_liftBackAlg
  simpa using h

noncomputable def quotientEquiv :
    (SymmetricAlgebra R V ⧸ S.kernelIdeal) ≃+* SymmetricAlgebra R Kmod :=
  (Ideal.quotEquivOfEq S.ker_projectAlg_eq_kernelIdeal.symm).trans
    (RingHom.quotientKerEquivOfSurjective
      (f := S.projectAlg.toRingHom) S.projectAlg_surjective)

end SplitSurjection

end

end SplitSurjectionSymmetricQuotient
end Experimental
end PCRLean
