import PCRLean.Experimental.SplitMatrixOrderIdealHybrid

#print axioms PCRLean.Experimental.SplitMatrixOrderIdealHybrid.targetFrame
#print axioms PCRLean.Experimental.SplitMatrixOrderIdealHybrid.matrixMap
#print axioms PCRLean.Experimental.SplitMatrixOrderIdealHybrid.SplitPacket.residual_eq_splitResidual
#print axioms PCRLean.Experimental.SplitMatrixOrderIdealHybrid.SplitPacket.residual_coordinate_mem
#print axioms PCRLean.Experimental.SplitMatrixOrderIdealHybrid.SplitPacket.graph_residual_mem_defectIdeal
#print axioms PCRLean.Experimental.SplitMatrixOrderIdealHybrid.SplitPacket.equationIdeal_le_hybridIdeal
#print axioms PCRLean.Experimental.SplitMatrixOrderIdealHybrid.SplitPacket.poweredEquationIdeal_le_hybridIdeal_pow
#print axioms PCRLean.Experimental.SplitMatrixOrderIdealHybrid.SplitPacket.defectIdeal_eq_bot_iff_exists_solution
#print axioms PCRLean.Experimental.SplitMatrixOrderIdealHybrid.SplitPacket.no_proper_ideal_absorbs_residual
