import PCRLean.Experimental.SplitMatrixMarkedHybridCompiler

#print axioms PCRLean.Experimental.SplitMatrixMarkedHybridCompiler.closureCertificate
#print axioms PCRLean.Experimental.SplitMatrixMarkedHybridCompiler.rawDefect_le_coefficientClosure
#print axioms PCRLean.Experimental.SplitMatrixMarkedHybridCompiler.graph_residual_mem_closure
#print axioms PCRLean.Experimental.SplitMatrixMarkedHybridCompiler.equationIdeal_le_centreIdeal
#print axioms PCRLean.Experimental.SplitMatrixMarkedHybridCompiler.poweredEquationIdeal_le_centreIdeal_pow
#print axioms PCRLean.Experimental.SplitMatrixMarkedHybridCompiler.extended_ownerIdeal_le_centreIdeal_pow
#print axioms PCRLean.Experimental.SplitMatrixMarkedHybridCompiler.selected_component_le
#print axioms PCRLean.Experimental.SplitMatrixMarkedHybridCompiler.selected_component_essential
#print axioms PCRLean.Experimental.SplitMatrixMarkedHybridCompiler.centreIdeal_fg
