import PCRLean.Experimental.SplitSurjectionRegularCentre

#print axioms PCRLean.Experimental.SplitSurjectionRegularCentre.quotient_isRegularRing
#print axioms PCRLean.Experimental.SplitSurjectionRegularCentre.certificate
