import PCRLean.Experimental.SurjectiveFiniteDimensionalRegularCentre

#print axioms PCRLean.Experimental.SurjectiveFiniteDimensionalRegularCentre.rightInvOfSurjective_spec
#print axioms PCRLean.Experimental.SurjectiveFiniteDimensionalRegularCentre.split_kernelIdeal_eq_centreIdeal
#print axioms PCRLean.Experimental.SurjectiveFiniteDimensionalRegularCentre.quotientEquiv
#print axioms PCRLean.Experimental.SurjectiveFiniteDimensionalRegularCentre.regularCentreCertificate
#print axioms PCRLean.Experimental.SurjectiveFiniteDimensionalRegularCentre.centreIdeal_ne_top
#print axioms PCRLean.Experimental.SurjectiveFiniteDimensionalRegularCentre.centreIdeal_fg
#print axioms PCRLean.Experimental.SurjectiveFiniteDimensionalRegularCentre.quotient_isRegularRing
