import PCRLean.Experimental.SurjectiveFreeRegularCentre

#print axioms PCRLean.Experimental.SurjectiveFreeRegularCentre.quotient_isRegularRing
#print axioms PCRLean.Experimental.SurjectiveFreeRegularCentre.certificate
