import Mathlib
import Mathlib.LinearAlgebra.SymmetricAlgebra.Basis
import Mathlib.LinearAlgebra.FreeModule.Finite.Basic
import Mathlib.RingTheory.RegularLocalRing.Polynomial
import PCRLean.Experimental.SplitSurjectionRegularCentre

/-!
# Experimental regular centre from a surjective linear map

Over a field, every surjective linear map admits a linear right inverse.  The
split-surjection kernel theorem can therefore be applied without taking a
splitting as input.  The resulting ideal is intrinsic: it is generated by the
degree-one image of the kernel of the original map and contains no choice of
basis or right inverse.

For finite-dimensional source and target, their symmetric algebras are
polynomial rings in finitely many variables.  Hence the intrinsic kernel ideal
is proper and finitely generated, and its quotient is regular.

This closes the affine finite-dimensional linear realization chamber.  It does
not construct the surjective conormal map from an arbitrary Frobenius/Fitting
core, prove owner permissibility, boundary transversality, hereditary blowup
transport, or global gluing.
-/

namespace PCRLean
namespace Experimental
namespace SurjectiveLinearMapRegularCentre

noncomputable section

universe u v w

variable {K : Type u} [Field K]
variable {V : Type v} {W : Type w}
variable [AddCommGroup V] [Module K V]
variable [AddCommGroup W] [Module K W]

open SplitSurjectionSymmetricQuotient
open SplitSurjectionActualCentre
open SplitSurjectionRegularCentre

/-- The intrinsic actual ideal attached to a linear map.  Its definition does
not contain a splitting. -/
def kernelIdeal (project : V →ₗ[K] W) :
    Ideal (SymmetricAlgebra K V) :=
  Ideal.span (Set.range fun x : project.ker =>
    SymmetricAlgebra.ι K V x.1)

/-- A surjective linear map of vector spaces has a chosen linear right inverse. -/
noncomputable def splitOfSurjective
    (project : V →ₗ[K] W)
    (hproject : Function.Surjective project) :
    SplitSurjection (R := K) (V := V) (Kmod := W) := by
  have hrange : LinearMap.range project = ⊤ :=
    LinearMap.range_eq_top.mpr hproject
  rcases project.exists_rightInverse_of_surjective hrange with
    ⟨liftBack, hrightInverse⟩
  exact
    { project := project
      liftBack := liftBack
      rightInverse := hrightInverse }

/-- The split package uses exactly the intrinsic ideal of the original map. -/
theorem split_kernelIdeal_eq
    (project : V →ₗ[K] W)
    (hproject : Function.Surjective project) :
    (splitOfSurjective project hproject).kernelIdeal =
      kernelIdeal project := by
  rfl

/-- The induced symmetric-algebra map has exactly the intrinsic linear kernel
ideal. -/
theorem ker_projectAlg_eq_kernelIdeal
    (project : V →ₗ[K] W)
    (hproject : Function.Surjective project) :
    RingHom.ker
        (splitOfSurjective project hproject).projectAlg.toRingHom =
      kernelIdeal project := by
  calc
    RingHom.ker
        (splitOfSurjective project hproject).projectAlg.toRingHom =
        (splitOfSurjective project hproject).kernelIdeal :=
      (splitOfSurjective project hproject).ker_projectAlg_eq_kernelIdeal
    _ = kernelIdeal project := split_kernelIdeal_eq project hproject

/-- Exact quotient by the intrinsic kernel ideal. -/
noncomputable def quotientEquiv
    (project : V →ₗ[K] W)
    (hproject : Function.Surjective project) :
    (SymmetricAlgebra K V ⧸ kernelIdeal project) ≃+*
      SymmetricAlgebra K W :=
  (Ideal.quotEquivOfEq
      (split_kernelIdeal_eq project hproject).symm).trans
    (splitOfSurjective project hproject).quotientEquiv

/-- The intrinsic ideal is proper whenever the target symmetric algebra is
nontrivial. -/
theorem kernelIdeal_ne_top
    [Nontrivial (SymmetricAlgebra K W)]
    (project : V →ₗ[K] W)
    (hproject : Function.Surjective project) :
    kernelIdeal project ≠ ⊤ := by
  rw [← split_kernelIdeal_eq project hproject]
  exact SplitSurjectionActualCentre.kernelIdeal_ne_top
    (splitOfSurjective project hproject)

/-- Noetherianity of the ambient symmetric algebra makes the intrinsic centre
finite type. -/
theorem kernelIdeal_fg
    [IsNoetherianRing (SymmetricAlgebra K V)]
    (project : V →ₗ[K] W) :
    (kernelIdeal project).FG := by
  exact IsNoetherian.noetherian _

/-- Regularity transfers from the target symmetric algebra to the quotient by
the intrinsic centre. -/
theorem quotient_isRegularRing
    [IsRegularRing (SymmetricAlgebra K W)]
    (project : V →ₗ[K] W)
    (hproject : Function.Surjective project) :
    IsRegularRing (SymmetricAlgebra K V ⧸ kernelIdeal project) := by
  exact IsRegularRing.of_ringEquiv (quotientEquiv project hproject).symm

/-- Actual regular affine-centre certificate attached only to the original
surjective map. -/
structure Certificate (project : V →ₗ[K] W) where
  ideal : Ideal (SymmetricAlgebra K V)
  ideal_eq : ideal = kernelIdeal project
  proper : ideal ≠ ⊤
  finiteType : ideal.FG
  quotient :
    (SymmetricAlgebra K V ⧸ ideal) ≃+* SymmetricAlgebra K W
  quotientRegular : IsRegularRing (SymmetricAlgebra K V ⧸ ideal)

/-- Assemble the intrinsic regular-centre certificate under ring-theoretic
finiteness and regularity hypotheses. -/
noncomputable def certificate
    [Nontrivial (SymmetricAlgebra K W)]
    [IsNoetherianRing (SymmetricAlgebra K V)]
    [IsRegularRing (SymmetricAlgebra K W)]
    (project : V →ₗ[K] W)
    (hproject : Function.Surjective project) :
    Certificate project where
  ideal := kernelIdeal project
  ideal_eq := rfl
  proper := kernelIdeal_ne_top project hproject
  finiteType := kernelIdeal_fg project
  quotient := quotientEquiv project hproject
  quotientRegular := quotient_isRegularRing project hproject

/-- A symmetric algebra on a finite free vector space is a regular ring. -/
theorem symmetricAlgebra_isRegularRing
    (M : Type*) [AddCommGroup M] [Module K M]
    [Module.Free K M] [Module.Finite K M] :
    IsRegularRing (SymmetricAlgebra K M) := by
  let b := Module.Free.chooseBasis K M
  letI : Fintype (Module.Free.ChooseBasisIndex K M) :=
    Module.Free.ChooseBasisIndex.fintype K M
  haveI : IsRegularRing
      (MvPolynomial (Module.Free.ChooseBasisIndex K M) K) := by
    infer_instance
  exact IsRegularRing.of_ringEquiv
    (SymmetricAlgebra.equivMvPolynomial b).symm.toRingEquiv

/-- Finite-dimensional source and target make every hypothesis of the regular
centre certificate automatic. -/
noncomputable def finiteDimensionalCertificate
    [Module.Free K V] [Module.Finite K V]
    [Module.Free K W] [Module.Finite K W]
    (project : V →ₗ[K] W)
    (hproject : Function.Surjective project) :
    Certificate project := by
  letI : IsRegularRing (SymmetricAlgebra K V) :=
    symmetricAlgebra_isRegularRing V
  letI : IsRegularRing (SymmetricAlgebra K W) :=
    symmetricAlgebra_isRegularRing W
  exact certificate project hproject

end

end SurjectiveLinearMapRegularCentre
end Experimental
end PCRLean
