import Mathlib
import Mathlib.LinearAlgebra.FreeModule.Basic
import PCRLean.Experimental.SplitSurjectionSymmetricQuotient

/-!
# Experimental symmetric quotient from a surjection onto a free module

A surjective linear map onto a free module admits a linear right inverse: choose
one preimage of each basis vector and extend linearly. Feeding this split into
the intrinsic split-surjection theorem yields a quotient theorem whose centre
ideal depends only on the original map.

This is a sharper U2 interface. Geometry now has to construct a finite locally
free quotient of conormal data and prove the relevant map surjective. The
present theorem does not establish constant rank, regular immersion, gluing, or
compatibility with blowup transforms.
-/

namespace PCRLean
namespace Experimental
namespace SurjectiveLinearMapSymmetricQuotient

noncomputable section

universe u v w

variable {R : Type u} [CommRing R]
variable {V : Type v} {Kmod : Type w}
variable [AddCommGroup V] [Module R V]
variable [AddCommGroup Kmod] [Module R Kmod]
variable [Module.Free R Kmod]

/-- Choose one preimage for every vector in a fixed free basis of the target and
extend linearly. -/
noncomputable def liftBackOfSurjective
    (project : V →ₗ[R] Kmod)
    (hproject : Function.Surjective project) : Kmod →ₗ[R] V :=
  let b := Module.Free.chooseBasis R Kmod
  (b.constr R) (fun i => Classical.choose (hproject (b i)))

/-- The constructed linear map is a genuine right inverse. -/
theorem project_comp_liftBackOfSurjective
    (project : V →ₗ[R] Kmod)
    (hproject : Function.Surjective project) :
    project.comp (liftBackOfSurjective project hproject) = LinearMap.id := by
  let b := Module.Free.chooseBasis R Kmod
  apply b.ext
  intro i
  change project
      ((b.constr R) (fun j => Classical.choose (hproject (b j))) (b i)) = b i
  rw [b.constr_basis]
  exact Classical.choose_spec (hproject (b i))

/-- Canonical split-surjection package extracted from the surjectivity proof. -/
noncomputable def splitOfSurjective
    (project : V →ₗ[R] Kmod)
    (hproject : Function.Surjective project) :
    SplitSurjectionSymmetricQuotient.SplitSurjection
      (R := R) (V := V) (Kmod := Kmod) where
  project := project
  liftBack := liftBackOfSurjective project hproject
  rightInverse := project_comp_liftBackOfSurjective project hproject

/-- The actual centre ideal generated by the linear kernel. Its definition
contains no basis and no chosen right inverse. -/
def kernelIdeal (project : V →ₗ[R] Kmod) :
    Ideal (SymmetricAlgebra R V) :=
  Ideal.span (Set.range fun x : project.ker =>
    SymmetricAlgebra.ι R V x.1)

/-- The split package uses exactly the intrinsic ideal determined by the
original surjection. -/
theorem split_kernelIdeal_eq
    (project : V →ₗ[R] Kmod)
    (hproject : Function.Surjective project) :
    (splitOfSurjective project hproject).kernelIdeal =
      kernelIdeal project := by
  rfl

/-- Main intrinsic kernel theorem for a surjection onto a free module. -/
theorem ker_projectAlg_eq_kernelIdeal
    (project : V →ₗ[R] Kmod)
    (hproject : Function.Surjective project) :
    RingHom.ker (splitOfSurjective project hproject).projectAlg.toRingHom =
      kernelIdeal project := by
  simpa [split_kernelIdeal_eq] using
    (splitOfSurjective project hproject).ker_projectAlg_eq_kernelIdeal

/-- Exact quotient theorem for a surjection onto a free module. -/
noncomputable def quotientEquiv
    (project : V →ₗ[R] Kmod)
    (hproject : Function.Surjective project) :
    (SymmetricAlgebra R V ⧸ kernelIdeal project) ≃+*
      SymmetricAlgebra R Kmod := by
  simpa [split_kernelIdeal_eq] using
    (splitOfSurjective project hproject).quotientEquiv

/-- The intrinsic centre ideal is proper whenever the target symmetric algebra
is nontrivial. -/
theorem kernelIdeal_ne_top
    [Nontrivial (SymmetricAlgebra R Kmod)]
    (project : V →ₗ[R] Kmod)
    (hproject : Function.Surjective project) :
    kernelIdeal project ≠ ⊤ := by
  intro htop
  have hmem : (1 : SymmetricAlgebra R V) ∈ kernelIdeal project := by
    rw [htop]
    trivial
  rw [← ker_projectAlg_eq_kernelIdeal project hproject] at hmem
  have hzero := RingHom.mem_ker.mp hmem
  simpa using hzero

end

end SurjectiveLinearMapSymmetricQuotient
end Experimental
end PCRLean
