import Mathlib
import PCRLean.Experimental.PolynomialHasseFrobenius
import PCRLean.Experimental.FiniteHasseIntegralCompression
import PCRLean.Experimental.IntegralEquivalentReesPresentations

/-!
# Univariate Hasse--Frobenius integral compression

Fix a finite family of polynomial roots `g_j` and a finite Hasse order range
`0 ≤ d < q`.  The source packet consists of the `p*d`-th Hasse derivatives of
`g_j^p`; the root packet consists of the `d`-th Hasse derivatives of `g_j`.
The polynomial Hasse--Frobenius identity supplies

`(D^[d] g_j)^p = D^[p*d] (g_j^p)`.

Consequently any algebra containing the finite source-Hasse packet admits the
entire finite root-Hasse packet by a finite integral extension, with unchanged
ambient integral class.

This is the first concrete differential-Rees compression theorem.  Higher
variables require commuting coordinate Hasse operators and multiindex weight
bookkeeping, but no new integrality argument.
-/

namespace PCRLean
namespace Experimental
namespace UnivariateHasseIntegralCompression

noncomputable section

universe u v

variable {K : Type u} [Field K]
variable {κ : Type v} [Fintype κ]
variable (p : Nat) [Fact p.Prime] [CharP K p]
variable (q : Nat)

open PolynomialHasseFrobenius
open FiniteHasseIntegralCompression
open IntegralEquivalentReesPresentations

/-- Concrete finite Hasse packet attached to a finite family of roots. -/
def packet (root : κ → Polynomial K) :
    Packet (B := Polynomial K) (κ := κ) (δ := Fin q) p where
  root := root
  source j := (root j) ^ p
  root_pow j := rfl
  rootOp d g := Polynomial.hasseDeriv d.1 g
  sourceOp d f := Polynomial.hasseDeriv (d.1 * p) f
  operator_pow d j :=
    (hasseDeriv_pow_prime p (root j) d.1).symm

/-- Finite set of low-order Hasse derivatives of the roots. -/
def rootHasseSet (root : κ → Polynomial K) : Set (Polynomial K) :=
  (packet p q root).rootOperatorSet

/-- Algebra generated by the corresponding high-order Hasse derivatives of the
source `p`-th powers. -/
def sourceHasseAlgebra (root : κ → Polynomial K) :
    Subalgebra K (Polynomial K) :=
  (packet p q root).sourceOperatorAlgebra

/-- Every low-order root Hasse derivative is integral over the finite
source-Hasse algebra. -/
theorem rootHasse_isIntegral
    (root : κ → Polynomial K) (d : Fin q) (j : κ) :
    IsIntegral (sourceHasseAlgebra p q root)
      (Polynomial.hasseDeriv d.1 (root j)) := by
  exact (packet p q root).rootOperator_isIntegral p
    (sourceHasseAlgebra p q root)
    (packet p q root).sourceOperator_mem d j

/-- Adjoining all finite root-Hasse derivatives is a finite module extension. -/
theorem rootHasseAdjoin_moduleFinite
    (root : κ → Polynomial K) :
    Module.Finite (sourceHasseAlgebra p q root)
      (Algebra.adjoin (sourceHasseAlgebra p q root)
        (rootHasseSet p q root)) := by
  exact (packet p q root).rootOperatorAdjoin_over_source_moduleFinite p

/-- Source- and root-Hasse presentations have the same ambient integral
class. -/
theorem source_root_integralEquivalent
    (root : κ → Polynomial K) :
    IntegralEquivalent (sourceHasseAlgebra p q root)
      (Algebra.adjoin (sourceHasseAlgebra p q root)
        (rootHasseSet p q root)) :=
  finiteHasseSource_integralEquivalent p (packet p q root)

/-- Elementwise form of the common integral closure. -/
theorem isIntegral_source_iff_rootHasseAdjoin
    (root : κ → Polynomial K) (y : Polynomial K) :
    IsIntegral (sourceHasseAlgebra p q root) y ↔
      IsIntegral
        (Algebra.adjoin (sourceHasseAlgebra p q root)
          (rootHasseSet p q root)) y :=
  source_root_integralEquivalent p q root y

end

end UnivariateHasseIntegralCompression
end Experimental
end PCRLean
