import PCRLean.Experimental.UnivariateFrobeniusOrderHeredity

#print axioms PCRLean.Experimental.UnivariateFrobeniusOrderHeredity.natTrailingDegree_pow
#print axioms PCRLean.Experimental.UnivariateFrobeniusOrderHeredity.atOriginSingular_pow_iff
#print axioms PCRLean.Experimental.UnivariateFrobeniusOrderHeredity.root_compression_atOrigin_iff
#print axioms PCRLean.Experimental.UnivariateFrobeniusOrderHeredity.atPointSingular_pow_iff
#print axioms PCRLean.Experimental.UnivariateFrobeniusOrderHeredity.root_compression_atPoint_iff
#print axioms PCRLean.Experimental.UnivariateFrobeniusOrderHeredity.derivativeZero_root_preserves_atPoint
#print axioms PCRLean.Experimental.UnivariateFrobeniusOrderHeredity.derivativeZero_root_preserves_atOrigin
