import PCRLean.Experimental.X032SplitFreeOrderIdealKernelIndex

#print axioms PCRLean.Experimental.IntrinsicOrderIdealMinimality.functionalsVanishMod_iff_orderIdeal_le
#print axioms PCRLean.Experimental.IntrinsicOrderIdealMinimality.orderIdeal_isLeast_intrinsic
#print axioms PCRLean.Experimental.IntrinsicOrderIdealMinimality.no_proper_ideal_absorbs_unit_intrinsic
#print axioms PCRLean.Experimental.IntrinsicOrderIdealMinimality.zeroDetection_requires_dual_separation
#print axioms PCRLean.Experimental.SplitFreePresentationDualFrame.SplitFreePresentation.reconstruct
#print axioms PCRLean.Experimental.SplitFreePresentationDualFrame.SplitFreePresentation.orderIdeal_eq_bot_iff
#print axioms PCRLean.Experimental.SplitFreePresentationDualFrame.CompatibleSplitPresentations.map_orderIdeal_eq
#print axioms PCRLean.Experimental.SplitFreePresentationDualFrame.CompatibleSplitPresentations.properNonzero_iff
#print axioms PCRLean.Experimental.SplitCokernelOrderIdealCompiler.ideal_trichotomy
#print axioms PCRLean.Experimental.SplitCokernelOrderIdealCompiler.obstructionIdeal_eq_bot_iff_exists
#print axioms PCRLean.Experimental.X032SplitFreeOrderIdealKernelIndex.loaded
