import PCRLean.Experimental.X032CanonicalMinimizerSymmetryIndex

#print axioms PCRLean.Experimental.CanonicalMarkedMinimizerSpace.erase_not_acceptable
#print axioms PCRLean.Experimental.CanonicalMarkedMinimizerSpace.no_fixed_minimizer_of_two_point_swap
#print axioms PCRLean.Experimental.CanonicalMarkedMinimizerSpace.exists_markedMinimizer
#print axioms PCRLean.Experimental.CanonicalMarkedMinimizerSpace.UniqueMarkedClosureCertificate.ofExistsUnique
#print axioms PCRLean.Experimental.CanonicalMarkedMinimizerSpace.UniqueMarkedClosureCertificate.owner_le_power
#print axioms PCRLean.Experimental.CanonicalMarkedMinimizerSpace.UniqueMarkedClosureCertificate.selected_essential
#print axioms PCRLean.Experimental.TwoChoiceMarkedMinimizerNoGo.minimizer_iff
#print axioms PCRLean.Experimental.TwoChoiceMarkedMinimizerNoGo.no_equivariant_single_minimizer
#print axioms PCRLean.Experimental.TwoChoiceMarkedMinimizerNoGo.intersection_not_acceptable
#print axioms PCRLean.Experimental.TwoChoiceMarkedMinimizerNoGo.union_eq_univ
