import PCRLean.Experimental.X032FiniteProjectiveAutomaticIndex

#print axioms PCRLean.Experimental.FiniteProjectiveAutomaticDualFrame.exists_surjective_fin_fun
#print axioms PCRLean.Experimental.FiniteProjectiveAutomaticDualFrame.exists_splitFiniteFreePresentation
#print axioms PCRLean.Experimental.FiniteProjectiveAutomaticDualFrame.exists_finite_dualFrame
#print axioms PCRLean.Experimental.FiniteProjectiveAutomaticDualFrame.exists_finite_dualFrame_reconstruct
#print axioms PCRLean.Experimental.FiniteProjectiveAutomaticDualFrame.automaticFrameCertificate
#print axioms PCRLean.Experimental.FiniteProjectiveCokernelOrderIdealCompiler.compile
#print axioms PCRLean.Experimental.FiniteProjectiveCokernelOrderIdealCompiler.branch_coverage
#print axioms PCRLean.Experimental.FiniteProjectiveCokernelOrderIdealCompiler.automatic_status_nonempty
#print axioms PCRLean.Experimental.X032FiniteProjectiveAutomaticIndex.loaded
