import PCRLean.Experimental.X032FiniteProjectivePresentationIndex

#print axioms PCRLean.Experimental.FiniteProjectivePresentationDualFrame.SplitFiniteFreePresentation.project_section
#print axioms PCRLean.Experimental.FiniteProjectivePresentationDualFrame.SplitFiniteFreePresentation.project_surjective
#print axioms PCRLean.Experimental.FiniteProjectivePresentationDualFrame.SplitFiniteFreePresentation.projective
#print axioms PCRLean.Experimental.FiniteProjectivePresentationDualFrame.SplitFiniteFreePresentation.toDualFrame_reconstruct
#print axioms PCRLean.Experimental.FiniteProjectivePresentationDualFrame.exists_dualFrame_of_projective_surjection
#print axioms PCRLean.Experimental.FiniteProjectiveOrderIdealCompiler.coefficientsVanishMod_iff_orderIdeal_le
#print axioms PCRLean.Experimental.FiniteProjectiveOrderIdealCompiler.orderIdeal_isLeast
#print axioms PCRLean.Experimental.FiniteProjectiveOrderIdealCompiler.orderIdeal_eq_bot_iff
#print axioms PCRLean.Experimental.FiniteProjectiveOrderIdealCompiler.CompatibleSplitPresentations.map_orderIdeal_eq
#print axioms PCRLean.Experimental.FiniteProjectiveOrderIdealCompiler.CompatibleSplitPresentations.properNonzero_iff
#print axioms PCRLean.Experimental.SplitCokernelOrderIdealCompiler.status_coverage
#print axioms PCRLean.Experimental.SplitCokernelOrderIdealCompiler.splitPresentation_edge_sound
#print axioms PCRLean.Experimental.X032FiniteProjectivePresentationIndex.loaded
