import Mathlib
import Mathlib.RingTheory.MvPolynomial.EulerIdentity

/-!
# Radicial differential packets in characteristic two

This file formalizes invariant algebraic facts used by the nonprincipal
radicial branch of the PCR program:

* partial derivatives are unchanged by square cleaning;
* an odd homogeneous polynomial belongs to the ideal generated by its partial
  derivatives, by Euler's identity in characteristic two;
* a unit partial derivative makes the differential ideal the unit ideal.

No regularity or scheme-level centre theorem is inferred from a proper
Jacobian ideal.
-/

noncomputable section

namespace PCRLean.Chambers.RadicialDifferential

open MvPolynomial

variable {R σ : Type*} [CommRing R] [CharP R 2]

/-- Every partial derivative of a square vanishes in characteristic two. -/
theorem pderiv_sq_zero (i : σ) (G : MvPolynomial σ R) :
    pderiv i (G ^ 2) = 0 := by
  rw [pow_two, pderiv_mul]
  rw [mul_comm (pderiv i G) G]
  exact CharTwo.add_self_eq_zero _

/-- Square cleaning does not change the radicial differential packet. -/
theorem pderiv_add_sq (i : σ) (H G : MvPolynomial σ R) :
    pderiv i (H + G ^ 2) = pderiv i H := by
  rw [map_add, pderiv_sq_zero, add_zero]

variable [Fintype σ]

/-- Euler's identity for odd homogeneous polynomials in characteristic two. -/
theorem euler_odd {H : MvPolynomial σ R} {N : ℕ}
    (hH : H.IsHomogeneous (2 * N + 1)) :
    (∑ i : σ, X i * pderiv i H) = H := by
  calc
    (∑ i : σ, X i * pderiv i H) = (2 * N + 1) • H :=
      hH.sum_X_mul_pderiv
    _ = (2 * N) • H + 1 • H := by rw [add_nsmul]
    _ = N • (2 • H) + H := by rw [mul_nsmul, one_nsmul]
    _ = H := by rw [CharTwo.two_nsmul, nsmul_zero, zero_add]

/-- The ideal generated by all partial derivatives. -/
def jacobianIdeal (H : MvPolynomial σ R) : Ideal (MvPolynomial σ R) :=
  Ideal.span (Set.range fun i : σ => pderiv i H)

/-- Each partial derivative is a member of the Jacobian ideal. -/
theorem pderiv_mem_jacobianIdeal (H : MvPolynomial σ R) (i : σ) :
    pderiv i H ∈ jacobianIdeal H :=
  Ideal.subset_span (Set.mem_range_self i)

/-- A unit partial derivative makes the differential packet transverse: its
Jacobian ideal is the unit ideal. -/
theorem jacobianIdeal_eq_top_of_isUnit_pderiv (H : MvPolynomial σ R) (i : σ)
    (hunit : IsUnit (pderiv i H)) :
    jacobianIdeal H = ⊤ := by
  apply (Ideal.eq_top_iff_one).2
  rcases hunit with ⟨u, hu⟩
  have hmem : (u : MvPolynomial σ R) ∈ jacobianIdeal H := by
    rw [hu]
    exact pderiv_mem_jacobianIdeal H i
  have hinv := (jacobianIdeal H).mul_mem_left
    (↑(u⁻¹) : MvPolynomial σ R) hmem
  simpa using hinv

/-- An odd homogeneous form lies in its Jacobian ideal.  This is the formal
Euler step underlying the exact differential-core identity; it does not imply
that the radical of the Jacobian ideal is regular. -/
theorem odd_homogeneous_mem_jacobianIdeal {H : MvPolynomial σ R} {N : ℕ}
    (hH : H.IsHomogeneous (2 * N + 1)) :
    H ∈ jacobianIdeal H := by
  have hsum : (∑ i : σ, X i * pderiv i H) ∈ jacobianIdeal H := by
    exact (jacobianIdeal H).sum_mem fun i _ =>
      (jacobianIdeal H).mul_mem_left (X i) (pderiv_mem_jacobianIdeal H i)
  rw [euler_odd hH] at hsum
  exact hsum

end PCRLean.Chambers.RadicialDifferential
