import Mathlib
import Mathlib.Algebra.CharP.Two
import Mathlib.Algebra.Polynomial.Derivative

/-!
# Odd-contact differential depth in characteristic two

For the critical coefficient `X^(2n+1)`, the formal derivative is exactly
`X^(2n)`.  Even powers have zero derivative.  These identities are the
kernel-checked algebraic origin of the odd-contact differential debt used in
the radicial cusp chambers.
-/

namespace PCRLean.Algebra.OddContactDerivative

open Polynomial
open scoped Polynomial

variable {R : Type*} [CommRing R] [CharP R 2]

/-- The derivative of an odd monomial in characteristic two. -/
@[simp] theorem derivative_odd_power (n : ℕ) :
    derivative (X ^ (2 * n + 1) : R[X]) = X ^ (2 * n) := by
  rw [show 2 * n + 1 = (2 * n) + 1 by omega]
  rw [derivative_X_pow_succ]
  simp [CharTwo.natCast_eq_mod]

/-- The derivative of an even monomial vanishes in characteristic two. -/
@[simp] theorem derivative_even_power (n : ℕ) :
    derivative (X ^ (2 * n) : R[X]) = 0 := by
  rw [derivative_X_pow]
  simp [CharTwo.natCast_eq_mod]

/-- Adding a constant does not change the odd-contact differential. -/
@[simp] theorem derivative_odd_power_add_const (n : ℕ) (u : R) :
    derivative (X ^ (2 * n + 1) + C u : R[X]) = X ^ (2 * n) := by
  simp

/-- The principal differential ideal of an odd-contact coefficient. -/
def criticalIdeal (n : ℕ) : Ideal R[X] :=
  Ideal.span ({derivative (X ^ (2 * n + 1) : R[X])} : Set R[X])

/-- The critical ideal is exactly generated by the even power `X^(2n)`. -/
theorem criticalIdeal_eq (n : ℕ) :
    criticalIdeal (R := R) n = Ideal.span ({X ^ (2 * n)} : Set R[X]) := by
  simp [criticalIdeal]

/-- The differential order is twice the odd-contact debt at the exponent
level. -/
theorem differential_exponent_eq_twice_debt (n : ℕ) :
    2 * n = n + n := by
  omega

end PCRLean.Algebra.OddContactDerivative
