import Mathlib

/-!
# Actual ideals glued by finite generator changes

A geometric centre is an actual coherent ideal, not merely a locally named
subspace or a direction scheme. This file proves the affine algebraic core of
higher-rank gluing: two finite generator families related by mutually inverse
finite linear-combination certificates generate the same ideal.

A scheme-level application still has to provide localization maps and verify
these certificates on every overlap.
-/

namespace PCRLean
namespace ActualIdealGluing

noncomputable section

universe u v

variable {R : Type u} [CommRing R]
variable {ι : Type v} [Fintype ι]

/-- The actual ideal generated by a finite family. -/
def generatedIdeal (g : ι → R) : Ideal R :=
  Ideal.span (Set.range g)

/-- Each named generator belongs to the generated ideal. -/
theorem generator_mem (g : ι → R) (i : ι) :
    g i ∈ generatedIdeal g := by
  exact Ideal.subset_span ⟨i, rfl⟩

/-- If every generator of `g` is an explicit finite linear combination of the
generators of `h`, then the ideal of `g` is contained in the ideal of `h`. -/
theorem generatedIdeal_le_of_combinations
    (g h : ι → R) (coeff : ι → ι → R)
    (hcomb : ∀ i, g i = ∑ j, coeff i j * h j) :
    generatedIdeal g ≤ generatedIdeal h := by
  rw [generatedIdeal, generatedIdeal, Ideal.span_le]
  rintro x ⟨i, rfl⟩
  rw [hcomb i]
  exact (Ideal.span (Set.range h)).sum_mem fun j _ =>
    (Ideal.span (Set.range h)).mul_mem_left (coeff i j)
      (Ideal.subset_span ⟨j, rfl⟩)

/-- Mutual finite linear-combination certificates give equality of the actual
ideals. -/
theorem generatedIdeal_eq_of_mutual_combinations
    (g h : ι → R)
    (forward backward : ι → ι → R)
    (hforward : ∀ i, g i = ∑ j, forward i j * h j)
    (hbackward : ∀ i, h i = ∑ j, backward i j * g j) :
    generatedIdeal g = generatedIdeal h := by
  apply le_antisymm
  · exact generatedIdeal_le_of_combinations g h forward hforward
  · exact generatedIdeal_le_of_combinations h g backward hbackward

/-- A finite overlap certificate for two local generator frames. The two
coefficient systems need not be declared matrix inverses: the explicit
reconstruction equations are exactly what ideal gluing uses. -/
structure GeneratorFrameEquivalence (g h : ι → R) where
  forward : ι → ι → R
  backward : ι → ι → R
  reconstruct_g : ∀ i, g i = ∑ j, forward i j * h j
  reconstruct_h : ∀ i, h i = ∑ j, backward i j * g j

namespace GeneratorFrameEquivalence

variable {g h : ι → R}

/-- Equivalent finite generator frames define the same actual ideal. -/
theorem ideal_eq (E : GeneratorFrameEquivalence g h) :
    generatedIdeal g = generatedIdeal h :=
  generatedIdeal_eq_of_mutual_combinations
    g h E.forward E.backward E.reconstruct_g E.reconstruct_h

end GeneratorFrameEquivalence

/-- Multiplying a principal generator by a unit preserves its actual ideal. -/
theorem principal_unit_change (u : Rˣ) (g : R) :
    Ideal.span ({(u : R) * g} : Set R) = Ideal.span ({g} : Set R) := by
  apply le_antisymm
  · rw [Ideal.span_le]
    intro x hx
    have hx' : x = (u : R) * g := by simpa using hx
    rw [hx']
    exact (Ideal.span ({g} : Set R)).mul_mem_left _
      (Ideal.subset_span (by simp))
  · rw [Ideal.span_le]
    intro x hx
    have hx' : x = g := by simpa using hx
    rw [hx']
    have hgen : (u : R) * g ∈ Ideal.span ({(u : R) * g} : Set R) :=
      Ideal.subset_span (by simp)
    have hinv := (Ideal.span ({(u : R) * g} : Set R)).mul_mem_left
      ((u⁻¹ : Rˣ) : R) hgen
    simpa using hinv

/-- A finite atlas of generator frames with explicit pairwise overlap
certificates. -/
structure FiniteGeneratorAtlas (Chart : Type*) [Fintype Chart] where
  generator : Chart → ι → R
  overlap : ∀ i j, GeneratorFrameEquivalence (generator i) (generator j)

namespace FiniteGeneratorAtlas

variable {Chart : Type*} [Fintype Chart]
    (A : FiniteGeneratorAtlas (R := R) (ι := ι) Chart)

/-- Every chart frame generates the same actual ideal. -/
theorem ideal_eq (i j : Chart) :
    generatedIdeal (A.generator i) = generatedIdeal (A.generator j) :=
  GeneratorFrameEquivalence.ideal_eq (A.overlap i j)

/-- Choosing a reference chart defines an ideal independent of the reference. -/
def gluedIdeal (i : Chart) : Ideal R :=
  generatedIdeal (A.generator i)

/-- Reference independence of the glued ideal. -/
theorem gluedIdeal_eq (i j : Chart) : A.gluedIdeal i = A.gluedIdeal j :=
  A.ideal_eq i j

end FiniteGeneratorAtlas

end

end ActualIdealGluing
end PCRLean
