import Mathlib
import PCRLean.FinitePacketEvaluation
import PCRLean.FunctionalPacketIdeal
import PCRLean.ActualIdealGluing

/-!
# Affine linear-core certificate

This file packages the finite Hasse--Cartier packet, its actual linear ideal,
and the split persistent kernel on one finite free affine chart.  It proves
presentation independence under equality of packet spans and exposes the
explicit direct-summand decomposition of the direction module.

The remaining geometric bridge is to prove that arbitrary prepared packets
admit these constant-rank charts and that the local actual ideals glue as a
coherent regular centre compatible with all marked owners and boundaries.
-/

namespace PCRLean
namespace AffineLinearCore

noncomputable section

universe u v w

variable {K : Type u} [Field K]
variable {σ : Type v} [Fintype σ] [DecidableEq σ]
variable {ι : Type w} [Fintype ι]

abbrev Direction := σ → K
abbrev Dual := Module.Dual K Direction

/-- One finite free chart carrying a trace packet and a splitting of its
evaluation map. -/
structure Chart where
  packet : ι → Dual (K := K) (σ := σ)
  section : (ι → K) →ₗ[K] Direction
  rightInverse :
    (FinitePacketEvaluation.evalMap packet).comp section = LinearMap.id

namespace Chart

variable (C : Chart (K := K) (σ := σ) (ι := ι))

/-- Persistent direction kernel of the chart packet. -/
def persistentKernel : Submodule K Direction :=
  FinitePacketEvaluation.persistentKernel C.packet

/-- The actual affine ideal generated by all packet functionals. -/
def actualIdeal : Ideal (MvPolynomial σ K) :=
  Ideal.span
    (Set.range fun i : ι =>
      FunctionalPacketIdeal.functionalPolynomial (C.packet i))

/-- Every chart functional contributes an actual ideal generator. -/
theorem generator_mem_actualIdeal (i : ι) :
    FunctionalPacketIdeal.functionalPolynomial (C.packet i) ∈ C.actualIdeal := by
  exact Ideal.subset_span ⟨i, rfl⟩

/-- The persistent kernel is an explicit direct summand of the direction
module on the split chart. -/
theorem kernel_complemented :
    ∃ e : Direction ≃ₗ[K] C.persistentKernel × (ι → K),
      ∀ x, (e x).1.1 =
        x - C.section (FinitePacketEvaluation.evalMap C.packet x) := by
  exact FinitePacketEvaluation.kernel_complemented_of_section
    C.packet C.section C.rightInverse

/-- The chart evaluation map is surjective. -/
theorem evaluation_surjective :
    Function.Surjective (FinitePacketEvaluation.evalMap C.packet) := by
  intro y
  refine ⟨C.section y, ?_⟩
  have h := congrArg
    (fun F : (ι → K) →ₗ[K] (ι → K) => F y) C.rightInverse
  simpa using h

/-- The persistent kernel is exactly simultaneous annihilation by the packet. -/
theorem mem_kernel_iff (x : Direction) :
    x ∈ C.persistentKernel ↔ ∀ i, C.packet i x = 0 :=
  FinitePacketEvaluation.mem_persistentKernel_iff C.packet x

end Chart

/-- Two finite packets on the same coordinate chart that span the same dual
submodule define the same actual ideal. -/
theorem actualIdeal_eq_of_span_eq
    (p q : ι → Dual (K := K) (σ := σ))
    (hspan : Submodule.span K (Set.range p) =
      Submodule.span K (Set.range q)) :
    Ideal.span
      (Set.range fun i : ι =>
        FunctionalPacketIdeal.functionalPolynomial (p i)) =
    Ideal.span
      (Set.range fun i : ι =>
        FunctionalPacketIdeal.functionalPolynomial (q i)) := by
  let sp : Finset (Dual (K := K) (σ := σ)) := Finset.univ.image p
  let sq : Finset (Dual (K := K) (σ := σ)) := Finset.univ.image q
  have hsp : (sp : Set (Dual (K := K) (σ := σ))) = Set.range p := by
    ext f
    simp [sp]
  have hsq : (sq : Set (Dual (K := K) (σ := σ))) = Set.range q := by
    ext f
    simp [sq]
  have hspan' :
      Submodule.span K (sp : Set (Dual (K := K) (σ := σ))) =
      Submodule.span K (sq : Set (Dual (K := K) (σ := σ))) := by
    simpa [hsp, hsq] using hspan
  have hideal := FunctionalPacketIdeal.packetIdeal_eq_of_span_eq sp sq hspan'
  simpa [FunctionalPacketIdeal.packetIdeal, hsp, hsq] using hideal

/-- Presentation independence for two split charts with the same trace
submodule. -/
theorem Chart.actualIdeal_eq
    (C D : Chart (K := K) (σ := σ) (ι := ι))
    (hspan : Submodule.span K (Set.range C.packet) =
      Submodule.span K (Set.range D.packet)) :
    C.actualIdeal = D.actualIdeal := by
  exact actualIdeal_eq_of_span_eq C.packet D.packet hspan

/-- Their persistent kernels also agree when packet spans agree. -/
theorem Chart.persistentKernel_eq
    (C D : Chart (K := K) (σ := σ) (ι := ι))
    (hspan : Submodule.span K (Set.range C.packet) =
      Submodule.span K (Set.range D.packet)) :
    C.persistentKernel = D.persistentKernel := by
  apply le_antisymm
  · intro x hx
    rw [C.mem_kernel_iff] at hx
    rw [D.mem_kernel_iff]
    intro d
    have hd : d ∈ Submodule.span K (Set.range D.packet) :=
      Submodule.subset_span ⟨_, rfl⟩
    rw [← hspan] at hd
    induction hd using Submodule.span_induction with
    | mem f hf =>
        rcases hf with ⟨i, rfl⟩
        exact hx i
    | zero => simp
    | add f g hf hg hfx hgx =>
        simpa using congrArg₂ (fun a b : K => a + b) hfx hgx
    | smul a f hf hfx =>
        simpa using congrArg (fun b : K => a * b) hfx
  · intro x hx
    rw [D.mem_kernel_iff] at hx
    rw [C.mem_kernel_iff]
    intro c
    have hc : c ∈ Submodule.span K (Set.range C.packet) :=
      Submodule.subset_span ⟨_, rfl⟩
    rw [hspan] at hc
    induction hc using Submodule.span_induction with
    | mem f hf =>
        rcases hf with ⟨i, rfl⟩
        exact hx i
    | zero => simp
    | add f g hf hg hfx hgx =>
        simpa using congrArg₂ (fun a b : K => a + b) hfx hgx
    | smul a f hf hfx =>
        simpa using congrArg (fun b : K => a * b) hfx

end

end AffineLinearCore
end PCRLean
