import PCRLean.OperatorSpanFullness
import PCRLean.EndomorphismGeneration
import PCRLean.BiorthogonalEndomorphismBasis

#print axioms PCRLean.FiniteFreeEndomorphismDescent.map_fullyInvariant
#print axioms PCRLean.FiniteFreeEndomorphismDescent.mem_iff_coefficients_mem
#print axioms PCRLean.IdealEndomorphismDescent.UnitFrame.coefficientIdeal_eq_comap
#print axioms PCRLean.IdealEndomorphismDescent.UnitFrame.ideal_eq_map_comap_of_fullyInvariant
#print axioms PCRLean.OperatorSpanFullness.fullyInvariant_of_spansEnd
#print axioms PCRLean.OperatorSpanFullness.ideal_eq_map_comap_of_spanning_packet
#print axioms PCRLean.EndomorphismGeneration.stable_of_generated
#print axioms PCRLean.EndomorphismGeneration.fullyInvariant_of_generatesMatrixUnits
#print axioms PCRLean.EndomorphismGeneration.fullyInvariant_of_conjugate_generatesMatrixUnits
#print axioms PCRLean.EndomorphismGeneration.ideal_eq_map_comap_of_generated_matrixUnits
#print axioms PCRLean.BiorthogonalEndomorphismBasis.Frame.conjugate_rankOne_eq_matrixUnit
#print axioms PCRLean.BiorthogonalEndomorphismBasis.Frame.conjugated_rankOnePacket_generatesMatrixUnits
#print axioms PCRLean.BiorthogonalEndomorphismBasis.Frame.ideal_eq_map_comap_of_rankOne_stable
