import PCRLean.OperatorSpanFullness
import PCRLean.EndomorphismGeneration
import PCRLean.BiorthogonalEndomorphismBasis
import PCRLean.FiniteHasseModel
import PCRLean.CoordinatePacketDescent
import PCRLean.ProductMatrixUnitGeneration
import PCRLean.IteratedHasseProduct
import PCRLean.IdealOperatorPacketDescent
import PCRLean.MonogenicFrobeniusFrame
import PCRLean.AdjoinRootFrobeniusFrame
import PCRLean.HasseSaturationDescent
import PCRLean.DifferentialIdealIteration

#print axioms PCRLean.FiniteFreeEndomorphismDescent.map_fullyInvariant
#print axioms PCRLean.FiniteFreeEndomorphismDescent.mem_iff_coefficients_mem
#print axioms PCRLean.IdealEndomorphismDescent.UnitFrame.coefficientIdeal_eq_comap
#print axioms PCRLean.IdealEndomorphismDescent.UnitFrame.ideal_eq_map_comap_of_fullyInvariant
#print axioms PCRLean.OperatorSpanFullness.fullyInvariant_of_spansEnd
#print axioms PCRLean.OperatorSpanFullness.ideal_eq_map_comap_of_spanning_packet
#print axioms PCRLean.EndomorphismGeneration.stable_of_generated
#print axioms PCRLean.EndomorphismGeneration.fullyInvariant_of_generatesMatrixUnits
#print axioms PCRLean.EndomorphismGeneration.fullyInvariant_of_conjugate_generatesMatrixUnits
#print axioms PCRLean.EndomorphismGeneration.ideal_eq_map_comap_of_generated_matrixUnits
#print axioms PCRLean.BiorthogonalEndomorphismBasis.Frame.conjugate_rankOne_eq_matrixUnit
#print axioms PCRLean.BiorthogonalEndomorphismBasis.Frame.conjugated_rankOnePacket_generatesMatrixUnits
#print axioms PCRLean.BiorthogonalEndomorphismBasis.Frame.ideal_eq_map_comap_of_rankOne_stable
#print axioms PCRLean.FiniteHasseModel.primitivePacket_generatesMatrixUnits
#print axioms PCRLean.FiniteHasseModel.fullyInvariant_of_primitive_stable
#print axioms PCRLean.CoordinatePacketDescent.ideal_eq_map_comap_of_pullbackPacket_stable
#print axioms PCRLean.ProductMatrixUnitGeneration.productPacket_generatesMatrixUnits
#print axioms PCRLean.ProductMatrixUnitGeneration.twoVariablePrimitivePacket_generatesMatrixUnits
#print axioms PCRLean.ProductMatrixUnitGeneration.ideal_eq_map_comap_of_twoVariablePacket_stable
#print axioms PCRLean.IteratedHasseProduct.multiPrimitivePacket_generatesMatrixUnits
#print axioms PCRLean.IteratedHasseProduct.fullyInvariant_of_multiPrimitive_stable
#print axioms PCRLean.IteratedHasseProduct.ideal_eq_map_comap_of_multiPrimitive_stable
#print axioms PCRLean.IdealOperatorPacketDescent.ideal_eq_map_comap_of_partitionedPacket
#print axioms PCRLean.IdealOperatorPacketDescent.ideal_eq_map_comap_of_hasse_stable
#print axioms PCRLean.MonogenicFrobeniusFrame.Frame.ideal_eq_map_comap_of_hasse_stable
#print axioms PCRLean.MonogenicFrobeniusFrame.ideal_eq_map_comap_of_powerBasis_hasse_stable
#print axioms PCRLean.AdjoinRootFrobeniusFrame.ideal_eq_map_comap_of_hasse_stable
#print axioms PCRLean.HasseSaturationDescent.hasseSaturation_eq_map_core
#print axioms PCRLean.HasseSaturationDescent.hasseSaturation_dichotomy
#print axioms PCRLean.DifferentialIdealIteration.saturation_closureStep
#print axioms PCRLean.DifferentialIdealIteration.reaches_saturation
#print axioms PCRLean.DifferentialIdealIteration.no_infinite_closure_execution
