import Mathlib

namespace PCRLean
namespace CechEffectivity

universe u v

variable {A : Type u} [AddCommGroup A]
variable {ι : Type v}

/-- The transition difference attached to local root representatives. -/
def transition (root : ι → A) (i j : ι) : A := root j - root i

/-- Every transition family coming from actual local representatives satisfies
the Čech cocycle identity. -/
theorem transition_cocycle (root : ι → A) (i j k : ι) :
    transition root i j + transition root j k = transition root i k := by
  simp [transition]
  abel

/-- A transition family is a coboundary when it is generated by a zero-cochain. -/
def IsCoboundary (c : ι → ι → A) : Prop :=
  ∃ gauge : ι → A, ∀ i j, c i j = gauge j - gauge i

/-- Correct local roots by a gauge. -/
def correctedRoot (root gauge : ι → A) (i : ι) : A :=
  root i - gauge i

/-- If the root-transition cocycle is the coboundary of `gauge`, all corrected
local roots agree on every overlap. -/
theorem correctedRoot_eq_of_coboundary
    (root gauge : ι → A)
    (h : ∀ i j, transition root i j = gauge j - gauge i)
    (i j : ι) :
    correctedRoot root gauge i = correctedRoot root gauge j := by
  have hij := h i j
  change root j - root i = gauge j - gauge i at hij
  change root i - gauge i = root j - gauge j
  calc
    root i - gauge i = root i + (gauge j - gauge i) - gauge j := by abel
    _ = root i + (root j - root i) - gauge j := by rw [← hij]
    _ = root j - gauge j := by abel

/-- Given one chosen patch, a vanishing Čech obstruction produces a single
global value represented by every corrected local root. -/
def globalRoot [Inhabited ι] (root gauge : ι → A) : A :=
  correctedRoot root gauge default

/-- Every corrected local root equals the global value. -/
theorem correctedRoot_eq_global [Inhabited ι]
    (root gauge : ι → A)
    (h : ∀ i j, transition root i j = gauge j - gauge i)
    (i : ι) :
    correctedRoot root gauge i = globalRoot root gauge := by
  exact correctedRoot_eq_of_coboundary root gauge h i default

/-- The obstruction-free global value is independent of the chosen base
patch. -/
theorem globalRoot_independent
    (root gauge : ι → A)
    (h : ∀ i j, transition root i j = gauge j - gauge i)
    (i j : ι) :
    correctedRoot root gauge i = correctedRoot root gauge j :=
  correctedRoot_eq_of_coboundary root gauge h i j

/-- A nonzero cycle sum refutes coboundary effectivity. This is the finite
algebraic no-go certificate used by the torsor layer. -/
theorem not_coboundary_of_triangle_defect
    (c : ι → ι → A) {i j k : ι}
    (hdefect : c i j + c j k ≠ c i k) :
    ¬ IsCoboundary c := by
  rintro ⟨gauge, hgauge⟩
  apply hdefect
  rw [hgauge i j, hgauge j k, hgauge i k]
  abel

/-- Gauge-equivalent root atlases have the same corrected global class. -/
theorem gauge_shift_invariant [Inhabited ι]
    (root gauge : ι → A) (a : A) :
    globalRoot (fun i => root i + a) (fun i => gauge i + a) =
      globalRoot root gauge := by
  simp [globalRoot, correctedRoot]
  abel

end CechEffectivity
end PCRLean
