import PCRLean.FiniteRootPacketTransform
import PCRLean.CoordinateCentrePrincipalization

#print axioms PCRLean.FiniteRootPacketTransform.sourceIdeal_le_centre_pow
#print axioms PCRLean.FiniteRootPacketTransform.sourcePacket_permissible
#print axioms PCRLean.FiniteRootPacketTransform.generator_reentry
#print axioms PCRLean.FiniteRootPacketTransform.map_sourceIdeal_le_exceptional_mul_transformed
#print axioms PCRLean.CoordinateCentrePrincipalization.centreVar_factorization
#print axioms PCRLean.CoordinateCentrePrincipalization.centreVar_pow_factorization
#print axioms PCRLean.CoordinateCentrePrincipalization.sourceIdeal_le_centre_pow
#print axioms PCRLean.CoordinateCentrePrincipalization.transformedRootIdeal_eq_top
#print axioms PCRLean.CoordinateCentrePrincipalization.map_sourceIdeal_le_exceptional_mul_transformed
#print axioms PCRLean.CoordinateCentrePrincipalization.one_step_terminal_on_every_chart
