import Mathlib
import PCRLean.CoordinateBlowupChart

/-!
# Controlled transforms on coordinate blowup charts

The all-chart ideal containment theorem implies actual divisibility by the
exceptional pivot.  This file extracts a quotient polynomial and records the
controlled-transform factorization.  For a pure `q`-th-power equation, the
controlled transform at mark `q` is again a `q`-th power of the transformed
root on every standard chart.

The quotient is chosen noncomputably from principal divisibility.  Its
existence and factorization are kernel-checked; no completion or formal power
series is used.
-/

namespace PCRLean
namespace CoordinateControlledTransform

noncomputable section

universe u v w

variable {R : Type u} [CommRing R]
variable {α : Type v} {ι : Type w}
variable [DecidableEq ι]

abbrev P := CoordinateBlowupChart.P (R := R) (α := α) (ι := ι)

/-- A power of the principal exceptional ideal is generated by the
corresponding power of the pivot coordinate. -/
theorem pivotIdeal_pow_eq_span_pow (k : ι) (b : Nat) :
    (CoordinateBlowupChart.pivotIdeal
      (R := R) (α := α) k) ^ b =
      Ideal.span
        {(CoordinateBlowupChart.centreVar
          (R := R) (α := α) k) ^ b} := by
  induction b with
  | zero => simp [CoordinateBlowupChart.pivotIdeal]
  | succ b ih =>
      rw [pow_succ, ih]
      simp [CoordinateBlowupChart.pivotIdeal, pow_succ]

/-- Every marked-permissible equation has an actual controlled-transform
quotient on each standard coordinate chart. -/
theorem exists_controlledTransform
    (k : ι) {b : Nat} {f : P (R := R) (α := α) (ι := ι)}
    (hf : f ∈
      (CoordinateBlowupChart.centreIdeal
        (R := R) (α := α) (ι := ι)) ^ b) :
    ∃ g : P (R := R) (α := α) (ι := ι),
      CoordinateBlowupChart.chartMap (R := R) (α := α) k f =
        (CoordinateBlowupChart.centreVar
          (R := R) (α := α) k) ^ b * g := by
  have hmem := CoordinateBlowupChart.chartMap_mem_pivot_pow
    (R := R) (α := α) k hf
  rw [pivotIdeal_pow_eq_span_pow (R := R) (α := α) k b,
    Ideal.mem_span_singleton] at hmem
  exact hmem

/-- Chosen controlled transform. -/
noncomputable def controlledTransform
    (k : ι) (b : Nat) (f : P (R := R) (α := α) (ι := ι))
    (hf : f ∈
      (CoordinateBlowupChart.centreIdeal
        (R := R) (α := α) (ι := ι)) ^ b) :
    P (R := R) (α := α) (ι := ι) :=
  Classical.choose (exists_controlledTransform
    (R := R) (α := α) k hf)

/-- Exact exceptional-factor identity for the chosen controlled transform. -/
theorem controlledTransform_factorization
    (k : ι) (b : Nat) (f : P (R := R) (α := α) (ι := ι))
    (hf : f ∈
      (CoordinateBlowupChart.centreIdeal
        (R := R) (α := α) (ι := ι)) ^ b) :
    CoordinateBlowupChart.chartMap (R := R) (α := α) k f =
      (CoordinateBlowupChart.centreVar
        (R := R) (α := α) k) ^ b *
        controlledTransform (R := R) (α := α) k b f hf :=
  Classical.choose_spec (exists_controlledTransform
    (R := R) (α := α) k hf)

/-- Root transform obtained by removing one exceptional pivot from a root that
vanishes on the centre. -/
noncomputable def rootTransform
    (k : ι) (g : P (R := R) (α := α) (ι := ι))
    (hg : g ∈ CoordinateBlowupChart.centreIdeal
      (R := R) (α := α) (ι := ι)) :
    P (R := R) (α := α) (ι := ι) :=
  controlledTransform (R := R) (α := α) k 1 g (by simpa using hg)

/-- Exact factorization of a transformed root. -/
theorem rootTransform_factorization
    (k : ι) (g : P (R := R) (α := α) (ι := ι))
    (hg : g ∈ CoordinateBlowupChart.centreIdeal
      (R := R) (α := α) (ι := ι)) :
    CoordinateBlowupChart.chartMap (R := R) (α := α) k g =
      CoordinateBlowupChart.centreVar (R := R) (α := α) k *
        rootTransform (R := R) (α := α) k g hg := by
  simpa [rootTransform] using
    controlledTransform_factorization
      (R := R) (α := α) k 1 g (by simpa using hg)

/-- Pure Frobenius powers reenter the same class after controlled transform on
every standard chart. -/
theorem rootPower_reentry
    (k : ι) (q : Nat)
    (g : P (R := R) (α := α) (ι := ι))
    (hg : g ∈ CoordinateBlowupChart.centreIdeal
      (R := R) (α := α) (ι := ι)) :
    CoordinateBlowupChart.chartMap (R := R) (α := α) k (g ^ q) =
      (CoordinateBlowupChart.centreVar
        (R := R) (α := α) k) ^ q *
        (rootTransform (R := R) (α := α) k g hg) ^ q := by
  rw [map_pow, rootTransform_factorization
    (R := R) (α := α) k g hg, mul_pow]

/-- The controlled transform of a pure `q`-th power may be chosen to be the
`q`-th power of the transformed root. -/
theorem exists_rootPower_controlledTransform
    (k : ι) (q : Nat)
    (g : P (R := R) (α := α) (ι := ι))
    (hg : g ∈ CoordinateBlowupChart.centreIdeal
      (R := R) (α := α) (ι := ι)) :
    ∃ h : P (R := R) (α := α) (ι := ι),
      CoordinateBlowupChart.chartMap (R := R) (α := α) k (g ^ q) =
        (CoordinateBlowupChart.centreVar
          (R := R) (α := α) k) ^ q * h ^ q :=
  ⟨rootTransform (R := R) (α := α) k g hg,
    rootPower_reentry (R := R) (α := α) k q g hg⟩

end

end CoordinateControlledTransform
end PCRLean
