import Mathlib
import PCRLean.CoordinateBlowupChart
import PCRLean.MarkedIdeal

/-!
# One-step principalization of a coordinate Frobenius packet

Take the root packet to be the full set of coordinate generators of the centre.
In the chart with pivot `k`, the pivot root has controlled transform `1`, while
every nonpivot root has controlled transform equal to its ratio coordinate.
Therefore the transformed root ideal is the unit ideal on every standard chart.
The `q`-th-power packet is exactly an exceptional `q`-th power times a unit
controlled packet.

This is a complete local terminal theorem for the pure split Frobenius chamber:
blowing up the actual coordinate root ideal principalizes its `q`-th-power
packet in one step on all charts.
-/

namespace PCRLean
namespace CoordinateCentrePrincipalization

noncomputable section

universe u v w

variable {R : Type u} [CommRing R]
variable {α : Type v} {ι : Type w}
variable [DecidableEq ι]

abbrev P := CoordinateBlowupChart.P (R := R) (α := α) (ι := ι)

/-- Explicit controlled transform of one coordinate root in the chart with
pivot `k`. -/
def explicitRootTransform (k i : ι) :
    P (R := R) (α := α) (ι := ι) :=
  if i = k then 1 else CoordinateBlowupChart.centreVar
    (R := R) (α := α) i

/-- Exact root factorization for every coordinate generator. -/
theorem centreVar_factorization (k i : ι) :
    CoordinateBlowupChart.chartMap (R := R) (α := α) k
        (CoordinateBlowupChart.centreVar
          (R := R) (α := α) i) =
      CoordinateBlowupChart.centreVar (R := R) (α := α) k *
        explicitRootTransform (R := R) (α := α) k i := by
  by_cases h : i = k
  · subst i
    simp [explicitRootTransform]
  · simp [explicitRootTransform, h,
      CoordinateBlowupChart.chartMap_nonpivot]

/-- Exact `q`-th-power factorization. -/
theorem centreVar_pow_factorization (k i : ι) (q : Nat) :
    CoordinateBlowupChart.chartMap (R := R) (α := α) k
        ((CoordinateBlowupChart.centreVar
          (R := R) (α := α) i) ^ q) =
      (CoordinateBlowupChart.centreVar
        (R := R) (α := α) k) ^ q *
        (explicitRootTransform (R := R) (α := α) k i) ^ q := by
  rw [map_pow, centreVar_factorization
    (R := R) (α := α) k i, mul_pow]

/-- Source ideal generated by all coordinate `q`-th powers. -/
noncomputable def sourceIdeal (q : Nat) :
    Ideal (P (R := R) (α := α) (ι := ι)) :=
  Ideal.span (Set.range fun i : ι =>
    (CoordinateBlowupChart.centreVar
      (R := R) (α := α) i) ^ q)

/-- Explicit controlled root ideal in one chart. -/
noncomputable def transformedRootIdeal (k : ι) (q : Nat) :
    Ideal (P (R := R) (α := α) (ι := ι)) :=
  Ideal.span (Set.range fun i : ι =>
    (explicitRootTransform (R := R) (α := α) k i) ^ q)

/-- The source coordinate Frobenius packet is permissible at mark `q`. -/
theorem sourceIdeal_le_centre_pow (q : Nat) :
    sourceIdeal (R := R) (α := α) (ι := ι) q ≤
      (CoordinateBlowupChart.centreIdeal
        (R := R) (α := α) (ι := ι)) ^ q := by
  rw [sourceIdeal, Ideal.span_le]
  rintro x ⟨i, rfl⟩
  exact Ideal.pow_mem_pow
    (Ideal.subset_span ⟨i, rfl⟩) q

/-- The transformed root packet contains `1` because the pivot root transforms
to `1`. -/
theorem one_mem_transformedRootIdeal (k : ι) (q : Nat) :
    (1 : P (R := R) (α := α) (ι := ι)) ∈
      transformedRootIdeal (R := R) (α := α) k q := by
  apply Ideal.subset_span
  refine ⟨k, ?_⟩
  simp [explicitRootTransform]

/-- Hence the controlled root packet is the unit ideal on every standard
chart. -/
theorem transformedRootIdeal_eq_top (k : ι) (q : Nat) :
    transformedRootIdeal (R := R) (α := α) k q = ⊤ := by
  exact Ideal.eq_top_iff_one.mpr
    (one_mem_transformedRootIdeal (R := R) (α := α) k q)

/-- Image of the full source packet factors through the exceptional `q`-th
power and the explicit transformed packet. -/
theorem map_sourceIdeal_le_exceptional_mul_transformed
    (k : ι) (q : Nat) :
    (sourceIdeal (R := R) (α := α) (ι := ι) q).map
        (CoordinateBlowupChart.chartMap (R := R) (α := α) k) ≤
      (CoordinateBlowupChart.pivotIdeal
        (R := R) (α := α) k) ^ q *
        transformedRootIdeal (R := R) (α := α) k q := by
  rw [Ideal.map_le_iff_le_comap, sourceIdeal, Ideal.span_le]
  rintro x ⟨i, rfl⟩
  change CoordinateBlowupChart.chartMap (R := R) (α := α) k
      ((CoordinateBlowupChart.centreVar
        (R := R) (α := α) i) ^ q) ∈ _
  rw [centreVar_pow_factorization
    (R := R) (α := α) k i q]
  exact Ideal.mul_mem_mul
    (Ideal.pow_mem_pow
      (CoordinateBlowupChart.pivot_mem
        (R := R) (α := α) k) q)
    (Ideal.subset_span ⟨i, rfl⟩)

/-- After removing the exceptional factor, the pure coordinate Frobenius
packet is terminal on every standard chart. -/
theorem one_step_terminal_on_every_chart (k : ι) (q : Nat) :
    transformedRootIdeal (R := R) (α := α) k q = ⊤ :=
  transformedRootIdeal_eq_top (R := R) (α := α) k q

end

end CoordinateCentrePrincipalization
end PCRLean
