import Mathlib
import PCRLean.CoordinateBlowupChart
import PCRLean.MarkedIdeal

/-!
# Coordinate Frobenius-root packets

The ideal generated by the `q`-th powers of all coordinate-centre generators
is permissible at mark `q`.  In the chart with pivot `k`, the pivot root has
controlled transform `1`, while a nonpivot root has controlled transform equal
to its ratio coordinate.  Hence the transformed full root packet is the unit
ideal on every standard chart.

This module is self-contained and does not use strict-transform saturation or
scheme-level overlap localization.
-/

namespace PCRLean
namespace CoordinateRootPacket

noncomputable section

universe u v w

variable {R : Type u} [CommRing R]
variable {α : Type v} {ι : Type w}
variable [DecidableEq ι]

abbrev P := CoordinateBlowupChart.P (R := R) (α := α) (ι := ι)

/-- Explicit controlled transform of one coordinate root in the pivot chart. -/
def explicitRootTransform (k i : ι) :
    P (R := R) (α := α) (ι := ι) :=
  if i = k then 1 else
    CoordinateBlowupChart.centreVar (R := R) (α := α) i

/-- Exact root factorization in every standard chart. -/
theorem centreVar_factorization (k i : ι) :
    CoordinateBlowupChart.chartMap (R := R) (α := α) k
        (CoordinateBlowupChart.centreVar (R := R) (α := α) i) =
      CoordinateBlowupChart.centreVar (R := R) (α := α) k *
        explicitRootTransform (R := R) (α := α) k i := by
  by_cases h : i = k
  · subst i
    simp [explicitRootTransform]
  · simp [explicitRootTransform, h,
      CoordinateBlowupChart.chartMap_nonpivot]

/-- Exact factorization of a coordinate `q`-th power. -/
theorem centreVar_pow_factorization (k i : ι) (q : Nat) :
    CoordinateBlowupChart.chartMap (R := R) (α := α) k
        ((CoordinateBlowupChart.centreVar
          (R := R) (α := α) i) ^ q) =
      (CoordinateBlowupChart.centreVar
        (R := R) (α := α) k) ^ q *
        (explicitRootTransform (R := R) (α := α) k i) ^ q := by
  rw [map_pow, centreVar_factorization
    (R := R) (α := α) k i, mul_pow]

/-- Source ideal generated by all coordinate `q`-th powers. -/
noncomputable def sourceIdeal (q : Nat) :
    Ideal (P (R := R) (α := α) (ι := ι)) :=
  Ideal.span (Set.range fun i : ι =>
    (CoordinateBlowupChart.centreVar
      (R := R) (α := α) i) ^ q)

/-- The source coordinate packet is contained in the marked centre power. -/
theorem sourceIdeal_le_centre_pow (q : Nat) :
    sourceIdeal (R := R) (α := α) (ι := ι) q ≤
      (CoordinateBlowupChart.centreIdeal
        (R := R) (α := α) (ι := ι)) ^ q := by
  rw [sourceIdeal, Ideal.span_le]
  rintro x ⟨i, rfl⟩
  exact Ideal.pow_mem_pow
    (Ideal.subset_span ⟨i, rfl⟩) q

/-- Marked formulation of source permissibility. -/
theorem sourcePacket_permissible
    {q : Nat} (hq : 0 < q) :
    MarkedIdeal.Permissible
      (R := P (R := R) (α := α) (ι := ι))
      ⟨sourceIdeal (R := R) (α := α) (ι := ι) q, q, hq⟩
      (CoordinateBlowupChart.centreIdeal
        (R := R) (α := α) (ι := ι)) :=
  sourceIdeal_le_centre_pow (R := R) (α := α) (ι := ι) q

/-- Controlled root ideal on one standard chart. -/
noncomputable def transformedRootIdeal (k : ι) (q : Nat) :
    Ideal (P (R := R) (α := α) (ι := ι)) :=
  Ideal.span (Set.range fun i : ι =>
    (explicitRootTransform (R := R) (α := α) k i) ^ q)

/-- The transformed packet contains the unit because the pivot root transforms
to `1`. -/
theorem one_mem_transformedRootIdeal (k : ι) (q : Nat) :
    (1 : P (R := R) (α := α) (ι := ι)) ∈
      transformedRootIdeal (R := R) (α := α) k q := by
  apply Ideal.subset_span
  refine ⟨k, ?_⟩
  simp [explicitRootTransform]

/-- The full coordinate root packet is terminal on every standard chart. -/
theorem transformedRootIdeal_eq_top (k : ι) (q : Nat) :
    transformedRootIdeal (R := R) (α := α) k q = ⊤ := by
  apply top_unique
  intro x hx
  have h1 := one_mem_transformedRootIdeal
    (R := R) (α := α) k q
  simpa using
    (transformedRootIdeal (R := R) (α := α) k q).mul_mem_left x h1

/-- Terminal chart packets agree pairwise. -/
theorem transformedRootIdeal_eq (i j : ι) (q : Nat) :
    transformedRootIdeal (R := R) (α := α) i q =
      transformedRootIdeal (R := R) (α := α) j q := by
  rw [transformedRootIdeal_eq_top, transformedRootIdeal_eq_top]

end

end CoordinateRootPacket
end PCRLean
