import Mathlib
import PCRLean.DifferentialOrbitKernel

/-!
# Differential-operator orbit closure

Starting from one leading functional and a family of Hasse/Cartier operators,
this file constructs the submodule generated by every finite operator word.
The orbit module is stable under all operators, so its common annihilator is an
invariant persistent kernel.

The construction is purely linear algebra. A geometric application must still
identify the correct finite bundle, prove local freeness and descend the kernel
to an actual regular centre.
-/

namespace PCRLean
namespace DifferentialOrbitClosure

noncomputable section

universe u v w

variable {K : Type u} {V : Type v} {ι : Type w}
variable [Field K] [AddCommGroup V] [Module K V]

abbrev Dual := Module.Dual K V

/-- Apply a finite word of operators to a dual functional. -/
def applyWord (ops : ι → Module.End K V) :
    List ι → Dual (K := K) (V := V) → Dual (K := K) (V := V)
  | [], f => f
  | i :: word, f => (ops i).dualMap (applyWord ops word f)

@[simp] theorem applyWord_nil (ops : ι → Module.End K V)
    (f : Dual (K := K) (V := V)) :
    applyWord ops [] f = f := rfl

@[simp] theorem applyWord_cons (ops : ι → Module.End K V)
    (i : ι) (word : List ι) (f : Dual (K := K) (V := V)) :
    applyWord ops (i :: word) f = (ops i).dualMap (applyWord ops word f) := rfl

/-- All finite differential descendants of one seed. -/
def orbitSet (ops : ι → Module.End K V)
    (seed : Dual (K := K) (V := V)) : Set (Dual (K := K) (V := V)) :=
  {f | ∃ word : List ι, f = applyWord ops word seed}

/-- The linear differential orbit generated by the seed. -/
def orbitModule (ops : ι → Module.End K V)
    (seed : Dual (K := K) (V := V)) :
    Submodule K (Dual (K := K) (V := V)) :=
  Submodule.span K (orbitSet ops seed)

/-- The seed belongs to its orbit module. -/
theorem seed_mem_orbitModule (ops : ι → Module.End K V)
    (seed : Dual (K := K) (V := V)) :
    seed ∈ orbitModule ops seed := by
  apply Submodule.subset_span
  exact ⟨[], rfl⟩

/-- An operator sends each raw orbit element to another raw orbit element. -/
theorem dualMap_mem_orbitSet (ops : ι → Module.End K V)
    (seed : Dual (K := K) (V := V)) (i : ι)
    {f : Dual (K := K) (V := V)} (hf : f ∈ orbitSet ops seed) :
    (ops i).dualMap f ∈ orbitSet ops seed := by
  rcases hf with ⟨word, rfl⟩
  exact ⟨i :: word, rfl⟩

/-- The full span of the orbit is stable under every operator. -/
theorem orbitModule_stable (ops : ι → Module.End K V)
    (seed : Dual (K := K) (V := V)) (i : ι) :
    DifferentialOrbitKernel.DualStable (ops i) (orbitModule ops seed) := by
  intro f hf
  induction hf using Submodule.span_induction with
  | mem f hf =>
      exact Submodule.subset_span (dualMap_mem_orbitSet ops seed i hf)
  | zero =>
      simpa using (orbitModule ops seed).zero_mem
  | add x y hx hy hx' hy' =>
      rw [map_add]
      exact (orbitModule ops seed).add_mem hx' hy'
  | smul a x hx hx' =>
      rw [map_smul]
      exact (orbitModule ops seed).smul_mem a hx'

/-- The operator family stabilizes the full orbit module. -/
theorem orbitModule_familyStable (ops : ι → Module.End K V)
    (seed : Dual (K := K) (V := V)) :
    DifferentialOrbitKernel.FamilyStable ops (orbitModule ops seed) := by
  intro i
  exact orbitModule_stable ops seed i

/-- The persistent annihilator of the full differential orbit is invariant
under every original operator. -/
theorem orbitAnnihilator_invariant (ops : ι → Module.End K V)
    (seed : Dual (K := K) (V := V)) :
    ∀ i x,
      x ∈ DifferentialOrbitKernel.annihilator (orbitModule ops seed) →
      ops i x ∈ DifferentialOrbitKernel.annihilator (orbitModule ops seed) := by
  exact DifferentialOrbitKernel.annihilator_family_invariant
    ops (orbitModule ops seed) (orbitModule_familyStable ops seed)

/-- The persistent orbit kernel lies inside the kernel of the original seed. -/
theorem orbitAnnihilator_le_seedKernel
    (ops : ι → Module.End K V)
    (seed : Dual (K := K) (V := V)) :
    DifferentialOrbitKernel.annihilator (orbitModule ops seed) ≤
      LinearMap.ker seed := by
  exact DifferentialOrbitKernel.annihilator_le_ker_of_mem
    (seed_mem_orbitModule ops seed)

/-- If a finite family spans the orbit module, membership in the persistent
kernel is checked by that finite family alone. -/
theorem mem_orbitAnnihilator_iff_of_span_eq
    (ops : ι → Module.End K V)
    (seed : Dual (K := K) (V := V))
    (s : Finset (Dual (K := K) (V := V)))
    (hspan : orbitModule ops seed =
      Submodule.span K (s : Set (Dual (K := K) (V := V))))
    (x : V) :
    x ∈ DifferentialOrbitKernel.annihilator (orbitModule ops seed) ↔
      ∀ f ∈ s, f x = 0 := by
  constructor
  · intro hx f hf
    apply hx f
    rw [hspan]
    exact Submodule.subset_span hf
  · intro hgen
    rw [DifferentialOrbitKernel.mem_annihilator_iff]
    intro f hf
    rw [hspan] at hf
    induction hf using Submodule.span_induction with
    | mem f hf => exact hgen f hf
    | zero => simp
    | add f g hf hg hff hgg =>
        rw [map_add, hff, hgg, add_zero]
    | smul a f hf hff =>
        rw [map_smul, hff, smul_zero]

section FiniteDimensional

variable [FiniteDimensional K V]

/-- Although the raw operator orbit contains words of arbitrary length, in a
finite-dimensional conormal fibre its span is generated by finitely many raw
orbit elements. This is the exact finite-packet theorem for the linearized
operator orbit. -/
theorem exists_finite_raw_orbit_generators
    (ops : ι → Module.End K V)
    (seed : Dual (K := K) (V := V)) :
    ∃ s : Finset (Dual (K := K) (V := V)),
      (s : Set (Dual (K := K) (V := V))) ⊆ orbitSet ops seed ∧
      orbitModule ops seed = Submodule.span K (s : Set (Dual (K := K) (V := V))) := by
  have hfg : (Submodule.span K (orbitSet ops seed)).FG :=
    IsNoetherian.noetherian _
  rcases (Submodule.fg_span_iff_fg_span_finset_subset
    (R := K) (orbitSet ops seed)).mp hfg with ⟨s, hs, heq⟩
  exact ⟨s, hs, by simpa [orbitModule] using heq⟩

/-- The entire infinite operator orbit therefore has a finite raw subpacket
that both spans it and cuts out exactly the same persistent kernel. -/
theorem exists_finite_kernel_packet
    (ops : ι → Module.End K V)
    (seed : Dual (K := K) (V := V)) :
    ∃ s : Finset (Dual (K := K) (V := V)),
      (s : Set (Dual (K := K) (V := V))) ⊆ orbitSet ops seed ∧
      orbitModule ops seed = Submodule.span K (s : Set (Dual (K := K) (V := V))) ∧
      ∀ x : V,
        x ∈ DifferentialOrbitKernel.annihilator (orbitModule ops seed) ↔
          ∀ f ∈ s, f x = 0 := by
  rcases exists_finite_raw_orbit_generators ops seed with ⟨s, hs, hspan⟩
  exact ⟨s, hs, hspan, fun x =>
    mem_orbitAnnihilator_iff_of_span_eq ops seed s hspan x⟩

end FiniteDimensional

end

end DifferentialOrbitClosure
end PCRLean
