import Mathlib
import PCRLean.DifferentialIdealSaturation
import PCRLean.ResolutionCompiler

/-!
# Finite Noetherian realization of operator saturation

The least ideal stable under a family of additive operators is defined in
`DifferentialIdealSaturation` by an intersection.  This file gives a finite
constructive realization on a Noetherian ring.

Starting from an ideal `I`, one closure step adjoins the ideal generated by all
operator images of elements of `I`.  If `I` is not already saturated, this
strictly enlarges `I`; the full saturation is unchanged by the step.  Since the
ideal lattice of a Noetherian ring has no infinite strictly increasing chain,
finitely many actual closure steps reach the canonical saturation exactly.

This is the Hilbert-basis compiler behind canonical Hasse saturation: the
impredicative intersection can be replaced by a finite certificate consisting
of explicit operator-closure steps.
-/

namespace PCRLean
namespace DifferentialIdealIteration

noncomputable section

universe u v

variable {A : Type u} [CommRing A]
variable {ι : Type v}

/-- All one-step operator images of elements of an ideal. -/
def operatorImageSet (ops : ι → A →+ A) (I : Ideal A) : Set A :=
  {y | ∃ i x, x ∈ I ∧ y = ops i x}

/-- The actual ideal generated by all one-step operator images. -/
def operatorImageIdeal (ops : ι → A →+ A) (I : Ideal A) : Ideal A :=
  Ideal.span (operatorImageSet ops I)

/-- One constructive closure step. -/
def closureStep (ops : ι → A →+ A) (I : Ideal A) : Ideal A :=
  I ⊔ operatorImageIdeal ops I

/-- The old ideal is contained in its next closure step. -/
theorem le_closureStep (ops : ι → A →+ A) (I : Ideal A) :
    I ≤ closureStep ops I :=
  le_sup_left

/-- Every declared operator image is a generator of the image ideal. -/
theorem operator_mem_imageIdeal
    (ops : ι → A →+ A) (I : Ideal A)
    (i : ι) {x : A} (hx : x ∈ I) :
    ops i x ∈ operatorImageIdeal ops I := by
  exact Ideal.subset_span ⟨i, x, hx, rfl⟩

/-- Every declared operator image belongs to the next closure step. -/
theorem operator_mem_closureStep
    (ops : ι → A →+ A) (I : Ideal A)
    (i : ι) {x : A} (hx : x ∈ I) :
    ops i x ∈ closureStep ops I :=
  le_sup_right (operator_mem_imageIdeal ops I i hx)

/-- The operator-image ideal is monotone in its seed. -/
theorem operatorImageIdeal_mono
    (ops : ι → A →+ A) {I J : Ideal A} (hIJ : I ≤ J) :
    operatorImageIdeal ops I ≤ operatorImageIdeal ops J := by
  rw [operatorImageIdeal, Ideal.span_le]
  rintro y ⟨i, x, hx, rfl⟩
  exact operator_mem_imageIdeal ops J i (hIJ hx)

/-- One-step closure is monotone. -/
theorem closureStep_mono
    (ops : ι → A →+ A) {I J : Ideal A} (hIJ : I ≤ J) :
    closureStep ops I ≤ closureStep ops J := by
  exact sup_le_sup hIJ (operatorImageIdeal_mono ops hIJ)

/-- Any stable over-ideal contains the next closure step. -/
theorem closureStep_le_of_le_of_stable
    (ops : ι → A →+ A) {I J : Ideal A}
    (hIJ : I ≤ J) (hJ : DifferentialIdealSaturation.Stable ops J) :
    closureStep ops I ≤ J := by
  apply sup_le hIJ
  rw [operatorImageIdeal, Ideal.span_le]
  rintro y ⟨i, x, hx, rfl⟩
  exact hJ i x (hIJ hx)

/-- If the next closure step is already contained in the seed, the seed is
operator-stable. -/
theorem stable_of_closureStep_le
    (ops : ι → A →+ A) (I : Ideal A)
    (h : closureStep ops I ≤ I) :
    DifferentialIdealSaturation.Stable ops I := by
  intro i x hx
  exact h (operator_mem_closureStep ops I i hx)

/-- Fixed points of the constructive closure operation are exactly the stable
ideals. -/
theorem closureStep_eq_self_iff_stable
    (ops : ι → A →+ A) (I : Ideal A) :
    closureStep ops I = I ↔ DifferentialIdealSaturation.Stable ops I := by
  constructor
  · intro h
    exact stable_of_closureStep_le ops I h.le
  · intro h
    apply le_antisymm
    · exact closureStep_le_of_le_of_stable ops le_rfl h
    · exact le_closureStep ops I

/-- One constructive closure step is contained in the canonical saturation. -/
theorem closureStep_le_saturation
    (ops : ι → A →+ A) (I : Ideal A) :
    closureStep ops I ≤ DifferentialIdealSaturation.saturation ops I := by
  exact closureStep_le_of_le_of_stable ops
    (DifferentialIdealSaturation.le_saturation ops I)
    (DifferentialIdealSaturation.saturation_stable ops I)

/-- A closure step does not change the final canonical saturation. -/
theorem saturation_closureStep
    (ops : ι → A →+ A) (I : Ideal A) :
    DifferentialIdealSaturation.saturation ops (closureStep ops I) =
      DifferentialIdealSaturation.saturation ops I := by
  apply le_antisymm
  · exact DifferentialIdealSaturation.saturation_le_of_le_of_stable ops
      (closureStep_le_saturation ops I)
      (DifferentialIdealSaturation.saturation_stable ops I)
  · exact DifferentialIdealSaturation.saturation_mono ops
      (le_closureStep ops I)

/-- If the seed is not saturated, one constructive closure step is a strict
ideal enlargement. -/
theorem closureStep_strict_of_ne_saturation
    (ops : ι → A →+ A) {I : Ideal A}
    (hI : I ≠ DifferentialIdealSaturation.saturation ops I) :
    I < closureStep ops I := by
  refine lt_of_le_of_ne (le_closureStep ops I) ?_
  intro hEq
  have hStable : DifferentialIdealSaturation.Stable ops I :=
    (closureStep_eq_self_iff_stable ops I).mp hEq.symm
  have hSat : DifferentialIdealSaturation.saturation ops I = I :=
    DifferentialIdealSaturation.saturation_eq_self_of_stable ops I hStable
  exact hI hSat.symm

/-- One accepted strict closure step. -/
def Step (ops : ι → A →+ A) (I J : Ideal A) : Prop :=
  I ≠ DifferentialIdealSaturation.saturation ops I ∧
    J = closureStep ops I

/-- Terminal ideals are exactly their own canonical saturations. -/
def Terminal (ops : ι → A →+ A) (I : Ideal A) : Prop :=
  I = DifferentialIdealSaturation.saturation ops I

/-- Every accepted closure step strictly enlarges the current ideal. -/
theorem step_strict
    (ops : ι → A →+ A) {I J : Ideal A} (h : Step ops I J) :
    I < J := by
  rcases h with ⟨hI, rfl⟩
  exact closureStep_strict_of_ne_saturation ops hI

/-- Every accepted closure step preserves the final saturation. -/
theorem step_preserves_saturation
    (ops : ι → A →+ A) {I J : Ideal A} (h : Step ops I J) :
    DifferentialIdealSaturation.saturation ops J =
      DifferentialIdealSaturation.saturation ops I := by
  rcases h with ⟨hI, rfl⟩
  exact saturation_closureStep ops I

/-- Saturation is invariant along a finite chain of accepted closure steps. -/
theorem reaches_preserves_saturation
    (ops : ι → A →+ A) {I J : Ideal A}
    (h : ResolutionCompiler.Reaches (Step ops) I J) :
    DifferentialIdealSaturation.saturation ops J =
      DifferentialIdealSaturation.saturation ops I := by
  induction h with
  | refl s => rfl
  | @cons s t u hst htu ih =>
      exact ih.trans (step_preserves_saturation ops hst)

section Noetherian

variable [IsNoetherianRing A]

/-- The constructive operator-closure program.  Its rank is the ideal itself,
ordered by reverse inclusion; Noetherianity supplies well-foundedness. -/
def program (ops : ι → A →+ A) : ResolutionCompiler.Program where
  State := Ideal A
  Rank := Ideal A
  step := Step ops
  terminal := Terminal ops
  rank := id
  lt := (· > ·)
  wf := IsNoetherian.wf (R := A) (M := A) inferInstance
  decreases := by
    intro I J h
    exact step_strict ops h
  progress := by
    intro I hI
    change I ≠ DifferentialIdealSaturation.saturation ops I at hI
    exact ⟨closureStep ops I, hI, rfl⟩

/-- The canonical saturation is reached after finitely many explicit closure
steps. -/
theorem reaches_saturation
    (ops : ι → A →+ A) (I : Ideal A) :
    ∃ J, ResolutionCompiler.Reaches (Step ops) I J ∧
      J = DifferentialIdealSaturation.saturation ops I := by
  obtain ⟨J, hreach, hterminal⟩ :=
    (program ops).terminal_reachable I
  refine ⟨J, hreach, ?_⟩
  change J = DifferentialIdealSaturation.saturation ops J at hterminal
  exact hterminal.trans (reaches_preserves_saturation ops hreach)

/-- No infinite chain of strict operator-closure steps exists on a Noetherian
ring. -/
theorem no_infinite_closure_execution
    (ops : ι → A →+ A) :
    ¬ ∃ f : Nat → Ideal A,
      ∀ n, Step ops (f n) (f (n + 1)) :=
  (program ops).no_infinite_execution

end Noetherian

end

end DifferentialIdealIteration
end PCRLean
