import Mathlib
import PCRLean.MatrixStableSubmodule
import PCRLean.FiniteFreeEndomorphismDescent
import PCRLean.IdealEndomorphismDescent

/-!
# Endomorphism generation and ideal descent

A finite family of Hasse--Cartier operators need not be declared equal to the
full endomorphism algebra.  It is enough to exhibit expressions for the matrix
units in the algebra generated by the family.  This file formalizes that
reduction.

The predicate `Generated` is the unital `R`-algebra closure of a family of
endomorphisms, presented inductively by zero, identity, addition, scalar
multiplication and composition.  Stability under the original operators then
propagates to every generated operator.  On a finite free coordinate module,
generation of all matrix units forces full endomorphism invariance.  After a
change of finite free frame this combines with `IdealEndomorphismDescent` to
show that an operator-stable ideal is extended from the base ring.

For the positive-characteristic program, the remaining concrete task is to
write every coordinate matrix unit as a finite Hasse--Cartier expression on a
local Frobenius frame.
-/

namespace PCRLean
namespace EndomorphismGeneration

noncomputable section

universe u v w x

variable {R : Type u} {M : Type v} {κ : Type w}
variable [CommSemiring R] [AddCommMonoid M] [Module R M]

/-- The unital algebraic closure of a family of endomorphisms, written without
choosing a generating word normal form. -/
inductive Generated (ops : κ → Module.End R M) : Module.End R M → Prop
  | zero : Generated ops 0
  | identity : Generated ops (LinearMap.id : Module.End R M)
  | generator (i : κ) : Generated ops (ops i)
  | add {S T : Module.End R M} :
      Generated ops S → Generated ops T → Generated ops (S + T)
  | smul (r : R) {T : Module.End R M} :
      Generated ops T → Generated ops (r • T)
  | comp {S T : Module.End R M} :
      Generated ops S → Generated ops T → Generated ops (S.comp T)

/-- A submodule is preserved by one endomorphism. -/
def StableUnder (N : Submodule R M) (T : Module.End R M) : Prop :=
  ∀ y, y ∈ N → T y ∈ N

/-- Zero preserves every submodule. -/
theorem stable_zero (N : Submodule R M) : StableUnder N 0 := by
  intro y hy
  simpa using N.zero_mem

/-- Identity preserves every submodule. -/
theorem stable_identity (N : Submodule R M) :
    StableUnder N (LinearMap.id : Module.End R M) := by
  intro y hy
  simpa using hy

/-- Stability is closed under addition of operators. -/
theorem stable_add (N : Submodule R M) {S T : Module.End R M}
    (hS : StableUnder N S) (hT : StableUnder N T) :
    StableUnder N (S + T) := by
  intro y hy
  simpa using N.add_mem (hS y hy) (hT y hy)

/-- Stability is closed under scalar multiplication of operators. -/
theorem stable_smul (N : Submodule R M) (r : R)
    {T : Module.End R M} (hT : StableUnder N T) :
    StableUnder N (r • T) := by
  intro y hy
  simpa using N.smul_mem r (hT y hy)

/-- Stability is closed under operator composition. -/
theorem stable_comp (N : Submodule R M) {S T : Module.End R M}
    (hS : StableUnder N S) (hT : StableUnder N T) :
    StableUnder N (S.comp T) := by
  intro y hy
  exact hS (T y) (hT y hy)

/-- Stability under the declared generators propagates to every generated
endomorphism. -/
theorem stable_of_generated
    (ops : κ → Module.End R M) (N : Submodule R M)
    (hops : ∀ i, StableUnder N (ops i))
    {T : Module.End R M} (hT : Generated ops T) :
    StableUnder N T := by
  induction hT with
  | zero => exact stable_zero N
  | identity => exact stable_identity N
  | generator i => exact hops i
  | add hS hT ihS ihT => exact stable_add N ihS ihT
  | smul r hT ihT => exact stable_smul N r ihT
  | comp hS hT ihS ihT => exact stable_comp N ihS ihT

/-- The family generates every endomorphism. -/
def GeneratesAll (ops : κ → Module.End R M) : Prop :=
  ∀ T : Module.End R M, Generated ops T

/-- Generation of the full endomorphism algebra turns generator stability into
full invariance. -/
theorem fullyInvariant_of_generatesAll
    (ops : κ → Module.End R M) (N : Submodule R M)
    (hgen : GeneratesAll ops) (hops : ∀ i, StableUnder N (ops i)) :
    FiniteFreeEndomorphismDescent.FullyInvariant N := by
  intro T y hy
  exact stable_of_generated ops N hops (hgen T) y hy

section Coordinates

variable {ι : Type x} [Fintype ι] [DecidableEq ι]

abbrev Coordinates := ι → R

/-- It is enough that the generated operator algebra contain every coordinate
matrix unit. -/
def GeneratesMatrixUnits
    (ops : κ → Module.End R (Coordinates (R := R) (ι := ι))) : Prop :=
  ∀ i j,
    Generated ops (MatrixStableSubmodule.matrixUnit (R := R) i j)

/-- Matrix-unit generation gives the coordinate-ideal membership implication
used in the Morita classification. -/
theorem coordinate_mem_of_generatesMatrixUnits
    (ops : κ → Module.End R (Coordinates (R := R) (ι := ι)))
    (N : Submodule R (Coordinates (R := R) (ι := ι)))
    (hgen : GeneratesMatrixUnits ops)
    (hops : ∀ k, StableUnder N (ops k))
    {y : Coordinates (R := R) (ι := ι)} (hy : y ∈ N) (j : ι) :
    y j ∈ MatrixStableSubmodule.coordinateIdeal N := by
  intro i
  have hunit := stable_of_generated ops N hops (hgen i j) y hy
  simpa using hunit

/-- A submodule stable under generators which produce all matrix units is
coordinatewise extension of one base ideal. -/
theorem eq_fromIdeal_of_generatesMatrixUnits
    (ops : κ → Module.End R (Coordinates (R := R) (ι := ι)))
    (N : Submodule R (Coordinates (R := R) (ι := ι)))
    (hgen : GeneratesMatrixUnits ops)
    (hops : ∀ k, StableUnder N (ops k)) :
    N = MatrixStableSubmodule.fromIdeal
      (ι := ι) (MatrixStableSubmodule.coordinateIdeal N) := by
  ext y
  constructor
  · intro hy
    exact fun i => coordinate_mem_of_generatesMatrixUnits
      ops N hgen hops hy i
  · intro hy
    exact MatrixStableSubmodule.mem_of_forall_coordinate_mem hy

/-- Matrix-unit generation is already sufficient for full endomorphism
invariance; equality with the full operator algebra need not be assumed. -/
theorem fullyInvariant_of_generatesMatrixUnits
    (ops : κ → Module.End R (Coordinates (R := R) (ι := ι)))
    (N : Submodule R (Coordinates (R := R) (ι := ι)))
    (hgen : GeneratesMatrixUnits ops)
    (hops : ∀ k, StableUnder N (ops k)) :
    MatrixStableSubmodule.FullyInvariant N := by
  rw [eq_fromIdeal_of_generatesMatrixUnits ops N hgen hops]
  exact MatrixStableSubmodule.fromIdeal_fullyInvariant
    (MatrixStableSubmodule.coordinateIdeal N)

end Coordinates

section Transport

variable {ι : Type x} [Fintype ι] [DecidableEq ι]

/-- Transport an endomorphism into a finite free coordinate frame. -/
def conjugateToCoordinates
    (e : M ≃ₗ[R] (ι → R)) (T : Module.End R M) :
    Module.End R (ι → R) :=
  e.toLinearMap.comp (T.comp e.symm.toLinearMap)

@[simp] theorem conjugateToCoordinates_apply
    (e : M ≃ₗ[R] (ι → R)) (T : Module.End R M) (y : M) :
    conjugateToCoordinates e T (e y) = e (T y) := by
  simp [conjugateToCoordinates]

/-- Stability of a submodule transports to stability of its coordinate image. -/
theorem mapped_stable
    (e : M ≃ₗ[R] (ι → R)) (ops : κ → Module.End R M)
    {N : Submodule R M} (hops : ∀ k, StableUnder N (ops k)) (k : κ) :
    StableUnder (N.map e.toLinearMap)
      (conjugateToCoordinates e (ops k)) := by
  intro y hy
  rcases hy with ⟨x, hx, rfl⟩
  refine ⟨ops k x, hops k x hx, ?_⟩
  simpa using (conjugateToCoordinates_apply e (ops k) x).symm

/-- If the transported operators generate all coordinate matrix units, then the
original submodule is invariant under every endomorphism. -/
theorem fullyInvariant_of_conjugate_generatesMatrixUnits
    (e : M ≃ₗ[R] (ι → R)) (ops : κ → Module.End R M)
    (N : Submodule R M)
    (hgen : GeneratesMatrixUnits
      (fun k => conjugateToCoordinates e (ops k)))
    (hops : ∀ k, StableUnder N (ops k)) :
    FiniteFreeEndomorphismDescent.FullyInvariant N := by
  have hcoord : MatrixStableSubmodule.FullyInvariant
      (N.map e.toLinearMap) :=
    fullyInvariant_of_generatesMatrixUnits
      (fun k => conjugateToCoordinates e (ops k))
      (N.map e.toLinearMap) hgen (mapped_stable e ops hops)
  intro T x hx
  have hxcoord : e x ∈ N.map e.toLinearMap := ⟨x, hx, rfl⟩
  have hout := hcoord (conjugateToCoordinates e T) (e x) hxcoord
  rcases hout with ⟨y, hy, hey⟩
  have hxy : y = T x := by
    apply e.injective
    calc
      e y = conjugateToCoordinates e T (e x) := hey
      _ = e (T x) := conjugateToCoordinates_apply e T x
  simpa [hxy] using hy

end Transport

section IdealDescent

variable {A : Type v} {ι : Type x}
variable [CommRing R] [CommRing A] [Algebra R A]
variable [Fintype ι] [DecidableEq ι]

/-- Finite operator criterion for Frobenius-base ideal descent.  It suffices to
produce every matrix unit after conjugating the operators into a unit-normalized
finite free frame. -/
theorem ideal_eq_map_comap_of_generated_matrixUnits
    (F : IdealEndomorphismDescent.UnitFrame
      (R := R) (A := A) (ι := ι))
    (ops : κ → Module.End R A)
    (I : Ideal A)
    (hgen : GeneratesMatrixUnits
      (fun k => conjugateToCoordinates F.coord (ops k)))
    (hstable : ∀ k, StableUnder
      (IdealEndomorphismDescent.idealSubmodule (R := R) I) (ops k)) :
    I = (I.comap (algebraMap R A)).map (algebraMap R A) := by
  apply IdealEndomorphismDescent.UnitFrame.ideal_eq_map_comap_of_fullyInvariant
    F I
  exact fullyInvariant_of_conjugate_generatesMatrixUnits
    F.coord ops (IdealEndomorphismDescent.idealSubmodule (R := R) I)
      hgen hstable

end IdealDescent

end

end EndomorphismGeneration
end PCRLean
