import Mathlib
import PCRLean.MatrixStableSubmodule
import PCRLean.FiniteFreeEndomorphismDescent
import PCRLean.IdealEndomorphismDescent

/-!
# Endomorphism generation and ideal descent

A finite family of Hasse--Cartier operators need not be declared equal to the
full endomorphism algebra. It is enough to exhibit expressions for the matrix
units in the algebra generated by the family.

The predicate `Generated` is the unital algebraic closure of a family of
endomorphisms under zero, identity, addition, scalar multiplication and
composition. Stability under the original operators propagates to every
generated operator. On a finite free coordinate module, generation of all
matrix units forces full endomorphism invariance. After transport through a
finite free frame, this combines with `IdealEndomorphismDescent` to show that
an operator-stable ideal is extended from the base ring.

The semiring-level closure lemmas are deliberately separated from the
ring-level Morita descent lemmas. This avoids imposing subtraction where it is
not needed while keeping the finite-free ideal classification definitionally
aligned with its `CommRing` hypotheses.
-/

namespace PCRLean
namespace EndomorphismGeneration

noncomputable section

universe u v w x y

variable {R : Type u} {M : Type v} {κ : Type w}

section Basic

variable [CommSemiring R] [AddCommMonoid M] [Module R M]

/-- The unital algebraic closure of a family of endomorphisms, written without
choosing a generating-word normal form. -/
inductive Generated (ops : κ → Module.End R M) : Module.End R M → Prop
  | zero : Generated ops 0
  | identity : Generated ops (LinearMap.id : Module.End R M)
  | generator (i : κ) : Generated ops (ops i)
  | add {S T : Module.End R M} :
      Generated ops S → Generated ops T → Generated ops (S + T)
  | smul (r : R) {T : Module.End R M} :
      Generated ops T → Generated ops (r • T)
  | comp {S T : Module.End R M} :
      Generated ops S → Generated ops T → Generated ops (S.comp T)

/-- A submodule is preserved by one endomorphism. -/
def StableUnder (N : Submodule R M) (T : Module.End R M) : Prop :=
  ∀ z, z ∈ N → T z ∈ N

/-- Zero preserves every submodule. -/
theorem stable_zero (N : Submodule R M) : StableUnder N 0 := by
  intro z hz
  simpa using N.zero_mem

/-- Identity preserves every submodule. -/
theorem stable_identity (N : Submodule R M) :
    StableUnder N (LinearMap.id : Module.End R M) := by
  intro z hz
  simpa using hz

/-- Stability is closed under addition of operators. -/
theorem stable_add (N : Submodule R M) {S T : Module.End R M}
    (hS : StableUnder N S) (hT : StableUnder N T) :
    StableUnder N (S + T) := by
  intro z hz
  simpa using N.add_mem (hS z hz) (hT z hz)

/-- Stability is closed under scalar multiplication of operators. -/
theorem stable_smul (N : Submodule R M) (r : R)
    {T : Module.End R M} (hT : StableUnder N T) :
    StableUnder N (r • T) := by
  intro z hz
  simpa using N.smul_mem r (hT z hz)

/-- Stability is closed under operator composition. -/
theorem stable_comp (N : Submodule R M) {S T : Module.End R M}
    (hS : StableUnder N S) (hT : StableUnder N T) :
    StableUnder N (S.comp T) := by
  intro z hz
  exact hS (T z) (hT z hz)

/-- Stability under the declared generators propagates to every generated
endomorphism. -/
theorem stable_of_generated
    (ops : κ → Module.End R M) (N : Submodule R M)
    (hops : ∀ i, StableUnder N (ops i))
    {T : Module.End R M} (hT : Generated ops T) :
    StableUnder N T := by
  induction hT with
  | zero => exact stable_zero N
  | identity => exact stable_identity N
  | generator i => exact hops i
  | add hS hT ihS ihT => exact stable_add N ihS ihT
  | smul r hT ihT => exact stable_smul N r ihT
  | comp hS hT ihS ihT => exact stable_comp N ihS ihT

/-- The family generates every endomorphism. -/
def GeneratesAll (ops : κ → Module.End R M) : Prop :=
  ∀ T : Module.End R M, Generated ops T

end Basic

section FullRing

variable [CommRing R] [AddCommGroup M] [Module R M]

/-- Generation of the full endomorphism algebra turns generator stability into
full invariance. -/
theorem fullyInvariant_of_generatesAll
    (ops : κ → Module.End R M) (N : Submodule R M)
    (hgen : GeneratesAll ops) (hops : ∀ i, StableUnder N (ops i)) :
    FiniteFreeEndomorphismDescent.FullyInvariant N := by
  intro T z hz
  exact stable_of_generated ops N hops (hgen T) z hz

end FullRing

section Coordinates

variable [CommRing R]
variable {ι : Type x} [Fintype ι] [DecidableEq ι]

abbrev Coordinates := ι → R

/-- It is enough that the generated operator algebra contain every coordinate
matrix unit. -/
def GeneratesMatrixUnits
    (ops : κ → Module.End R (Coordinates (R := R) (ι := ι))) : Prop :=
  ∀ i j,
    Generated ops (MatrixStableSubmodule.matrixUnit (R := R) i j)

/-- Matrix-unit generation gives the coordinate-ideal membership implication
used in the Morita classification. -/
theorem coordinate_mem_of_generatesMatrixUnits
    (ops : κ → Module.End R (Coordinates (R := R) (ι := ι)))
    (N : Submodule R (Coordinates (R := R) (ι := ι)))
    (hgen : GeneratesMatrixUnits ops)
    (hops : ∀ k, StableUnder N (ops k))
    {z : Coordinates (R := R) (ι := ι)} (hz : z ∈ N) (j : ι) :
    z j ∈ MatrixStableSubmodule.coordinateIdeal N := by
  intro i
  have hunit := stable_of_generated ops N hops (hgen i j) z hz
  simpa using hunit

/-- A submodule stable under generators producing all matrix units is the
coordinatewise extension of one base ideal. -/
theorem eq_fromIdeal_of_generatesMatrixUnits
    (ops : κ → Module.End R (Coordinates (R := R) (ι := ι)))
    (N : Submodule R (Coordinates (R := R) (ι := ι)))
    (hgen : GeneratesMatrixUnits ops)
    (hops : ∀ k, StableUnder N (ops k)) :
    N = MatrixStableSubmodule.fromIdeal
      (ι := ι) (MatrixStableSubmodule.coordinateIdeal N) := by
  ext z
  constructor
  · intro hz i
    exact coordinate_mem_of_generatesMatrixUnits ops N hgen hops hz i
  · intro hz
    exact MatrixStableSubmodule.mem_of_forall_coordinate_mem hz

/-- Matrix-unit generation is sufficient for full endomorphism invariance;
equality with a pre-existing operator algebra need not be assumed. -/
theorem fullyInvariant_of_generatesMatrixUnits
    (ops : κ → Module.End R (Coordinates (R := R) (ι := ι)))
    (N : Submodule R (Coordinates (R := R) (ι := ι)))
    (hgen : GeneratesMatrixUnits ops)
    (hops : ∀ k, StableUnder N (ops k)) :
    MatrixStableSubmodule.FullyInvariant N := by
  rw [eq_fromIdeal_of_generatesMatrixUnits ops N hgen hops]
  exact MatrixStableSubmodule.fromIdeal_fullyInvariant
    (MatrixStableSubmodule.coordinateIdeal N)

end Coordinates

section Transport

variable [CommRing R] [AddCommGroup M] [Module R M]
variable {ι : Type x} [Fintype ι] [DecidableEq ι]

/-- Transport an endomorphism into a finite free coordinate frame. -/
def conjugateToCoordinates
    (e : M ≃ₗ[R] (ι → R)) (T : Module.End R M) :
    Module.End R (ι → R) :=
  e.toLinearMap.comp (T.comp e.symm.toLinearMap)

@[simp] theorem conjugateToCoordinates_apply
    (e : M ≃ₗ[R] (ι → R)) (T : Module.End R M) (z : M) :
    conjugateToCoordinates e T (e z) = e (T z) := by
  simp [conjugateToCoordinates]

/-- Stability of a submodule transports to stability of its coordinate image. -/
theorem mapped_stable
    (e : M ≃ₗ[R] (ι → R)) (ops : κ → Module.End R M)
    {N : Submodule R M} (hops : ∀ k, StableUnder N (ops k)) (k : κ) :
    StableUnder (N.map e.toLinearMap)
      (conjugateToCoordinates e (ops k)) := by
  intro z hz
  rcases hz with ⟨x, hx, rfl⟩
  refine ⟨ops k x, hops k x hx, ?_⟩
  exact (conjugateToCoordinates_apply e (ops k) x).symm

/-- If transported operators generate all coordinate matrix units, the original
submodule is invariant under every endomorphism. -/
theorem fullyInvariant_of_conjugate_generatesMatrixUnits
    (e : M ≃ₗ[R] (ι → R)) (ops : κ → Module.End R M)
    (N : Submodule R M)
    (hgen : GeneratesMatrixUnits
      (fun k => conjugateToCoordinates e (ops k)))
    (hops : ∀ k, StableUnder N (ops k)) :
    FiniteFreeEndomorphismDescent.FullyInvariant N := by
  have hcoord : MatrixStableSubmodule.FullyInvariant
      (N.map e.toLinearMap) :=
    fullyInvariant_of_generatesMatrixUnits
      (fun k => conjugateToCoordinates e (ops k))
      (N.map e.toLinearMap) hgen (mapped_stable e ops hops)
  intro T x hx
  have hxcoord : e x ∈ N.map e.toLinearMap := ⟨x, hx, rfl⟩
  have hout := hcoord (conjugateToCoordinates e T) (e x) hxcoord
  rcases hout with ⟨z, hz, hzeq⟩
  have hzx : z = T x := by
    apply e.injective
    calc
      e z = conjugateToCoordinates e T (e x) := hzeq
      _ = e (T x) := conjugateToCoordinates_apply e T x
  simpa [hzx] using hz

end Transport

section IdealDescent

variable [CommRing R]
variable {A : Type y} [CommRing A] [Algebra R A]
variable {ι : Type x} [Fintype ι] [DecidableEq ι]

/-- Finite operator criterion for Frobenius-base ideal descent. It suffices to
produce every matrix unit after conjugating the operators into a unit-normalized
finite free frame. -/
theorem ideal_eq_map_comap_of_generated_matrixUnits
    (F : IdealEndomorphismDescent.UnitFrame
      (R := R) (A := A) (ι := ι))
    (ops : κ → Module.End R A)
    (I : Ideal A)
    (hgen : GeneratesMatrixUnits
      (fun k => conjugateToCoordinates F.coord (ops k)))
    (hstable : ∀ k, StableUnder
      (IdealEndomorphismDescent.idealSubmodule (R := R) I) (ops k)) :
    I = (I.comap (algebraMap R A)).map (algebraMap R A) := by
  have hfull : FiniteFreeEndomorphismDescent.FullyInvariant
      (IdealEndomorphismDescent.idealSubmodule (R := R) I) :=
    fullyInvariant_of_conjugate_generatesMatrixUnits
      (R := R) (M := A) (κ := κ) (ι := ι)
      F.coord ops (IdealEndomorphismDescent.idealSubmodule (R := R) I)
      hgen hstable
  exact IdealEndomorphismDescent.UnitFrame.ideal_eq_map_comap_of_fullyInvariant
    F I hfull

end IdealDescent

end

end EndomorphismGeneration
end PCRLean
