import Mathlib
import PCRLean.WeightedOperatorLedger

/-!
# Finite weighted closure of a marked ideal

Given a marked ideal `(I,b)` and a finite family of positive-cost operators,
this file constructs every differential descendant visible below mark `b`.
For a word `w`, the image ideal is generated by all `D_w(f)` with `f ∈ I`, and
is enrolled at residual mark `b-cost(w)`.  Positive costs imply that only
finitely many words occur.

The resulting level ideals are actual ideals, contain the source at level `b`,
and preserve marked permissibility: if `I ⊆ C^b`, then every residual level
`m` is contained in `C^m`.  Over a Noetherian ring all levels are finitely
generated.

This is a finite, generator-independent local packetization theorem.  The
geometric program must still identify the intrinsic Hasse operators and prove
presentation/base-change compatibility.
-/

namespace PCRLean
namespace FiniteWeightedMarkedClosure

noncomputable section

universe u v

variable {R : Type u} [CommRing R]
variable {κ : Type v} [Fintype κ] [DecidableEq κ]

/-- Ideal generated by the image of one source ideal under one operator word. -/
def wordImageIdeal
    (ops : κ → WeightedOperatorLedger.Operator (R := R))
    (I : Ideal R) (word : List κ) : Ideal R :=
  Ideal.span
    (WeightedOperatorLedger.applyWord ops word '' (I : Set R))

/-- Words enrolled at exactly residual mark `m`. -/
def wordsAtResidual
    (ops : κ → WeightedOperatorLedger.Operator (R := R))
    (b m : Nat) : Finset (List κ) :=
  (WeightedOperatorLedger.boundedWords ops b).filter
    (fun word => b - WeightedOperatorLedger.wordCost ops word = m)

/-- Actual ideal at residual mark `m` in the finite weighted closure. -/
def levelIdeal
    (ops : κ → WeightedOperatorLedger.Operator (R := R))
    (I : Ideal R) (b m : Nat) : Ideal R :=
  (wordsAtResidual ops b m).sup
    (wordImageIdeal ops I)

/-- Membership characterization for the finite residual-word set. -/
@[simp] theorem mem_wordsAtResidual_iff
    (ops : κ → WeightedOperatorLedger.Operator (R := R))
    (b m : Nat) (word : List κ) :
    word ∈ wordsAtResidual ops b m ↔
      WeightedOperatorLedger.wordCost ops word ≤ b ∧
      b - WeightedOperatorLedger.wordCost ops word = m := by
  simp [wordsAtResidual,
    WeightedOperatorLedger.mem_boundedWords_iff]

/-- An operator-word image ideal preserves the corresponding residual centre
power. -/
theorem wordImageIdeal_le_power
    (ops : κ → WeightedOperatorLedger.Operator (R := R))
    (I C : Ideal R) {b : Nat} (hI : I ≤ C ^ b)
    (word : List κ) :
    wordImageIdeal ops I word ≤
      C ^ (b - WeightedOperatorLedger.wordCost ops word) := by
  rw [wordImageIdeal, Ideal.span_le]
  rintro y ⟨x, hx, rfl⟩
  exact WeightedOperatorLedger.applyWord_mem_power
    ops C (hI hx) word

/-- Every residual level of the finite weighted closure is permissible for the
same centre at its residual mark. -/
theorem levelIdeal_le_power
    (ops : κ → WeightedOperatorLedger.Operator (R := R))
    (I C : Ideal R) {b m : Nat} (hI : I ≤ C ^ b) :
    levelIdeal ops I b m ≤ C ^ m := by
  rw [levelIdeal]
  apply Finset.sup_le
  intro word hword
  have hm := (mem_wordsAtResidual_iff ops b m word).1 hword |>.2
  rw [← hm]
  exact wordImageIdeal_le_power ops I C hI word

/-- The empty word contributes the source ideal itself. -/
theorem le_wordImageIdeal_nil
    (ops : κ → WeightedOperatorLedger.Operator (R := R))
    (I : Ideal R) :
    I ≤ wordImageIdeal ops I [] := by
  intro x hx
  apply Ideal.subset_span
  exact ⟨x, hx, rfl⟩

/-- The original ideal is enrolled at its original mark. -/
theorem source_le_topLevel
    (ops : κ → WeightedOperatorLedger.Operator (R := R))
    (I : Ideal R) (b : Nat) :
    I ≤ levelIdeal ops I b b := by
  apply (le_wordImageIdeal_nil ops I).trans
  rw [levelIdeal]
  apply Finset.le_sup
  exact (mem_wordsAtResidual_iff ops b b []).2
    ⟨by simp, by simp⟩

/-- Every declared operator word of cost at most `b` contributes to the level
with the expected residual mark. -/
theorem wordImageIdeal_le_levelIdeal
    (ops : κ → WeightedOperatorLedger.Operator (R := R))
    (I : Ideal R) (b : Nat) (word : List κ)
    (hcost : WeightedOperatorLedger.wordCost ops word ≤ b) :
    wordImageIdeal ops I word ≤
      levelIdeal ops I b
        (b - WeightedOperatorLedger.wordCost ops word) := by
  rw [levelIdeal]
  apply Finset.le_sup
  exact (mem_wordsAtResidual_iff ops b
    (b - WeightedOperatorLedger.wordCost ops word) word).2
    ⟨hcost, rfl⟩

/-- Complete marked permissibility of the finite closure. -/
theorem all_levels_permissible
    (ops : κ → WeightedOperatorLedger.Operator (R := R))
    (I C : Ideal R) (b : Nat) (hI : I ≤ C ^ b) :
    ∀ m : Nat, levelIdeal ops I b m ≤ C ^ m :=
  fun m => levelIdeal_le_power ops I C hI

/-- The closure contains no nonzero residual levels above the source mark. -/
theorem levelIdeal_eq_bot_of_mark_lt
    (ops : κ → WeightedOperatorLedger.Operator (R := R))
    (I : Ideal R) {b m : Nat} (hbm : b < m) :
    levelIdeal ops I b m = ⊥ := by
  rw [levelIdeal]
  apply Finset.sup_eq_bot.mpr
  intro word hword
  have hm := (mem_wordsAtResidual_iff ops b m word).1 hword |>.2
  have hle : b - WeightedOperatorLedger.wordCost ops word ≤ b :=
    Nat.sub_le _ _
  omega

section Noetherian

variable [IsNoetherianRing R]

/-- Every residual level is a finitely generated actual ideal. -/
theorem levelIdeal_fg
    (ops : κ → WeightedOperatorLedger.Operator (R := R))
    (I : Ideal R) (b m : Nat) :
    (levelIdeal ops I b m).FG :=
  IsNoetherian.noetherian _

/-- Each residual level has a finite set of actual ring generators. -/
theorem exists_finite_level_generators
    (ops : κ → WeightedOperatorLedger.Operator (R := R))
    (I : Ideal R) (b m : Nat) :
    ∃ s : Finset R,
      levelIdeal ops I b m = Ideal.span (s : Set R) := by
  rcases levelIdeal_fg ops I b m with ⟨s, hs⟩
  exact ⟨s, hs.symm⟩

end Noetherian

end

end FiniteWeightedMarkedClosure
end PCRLean
