import Mathlib
import PCRLean.CoordinateControlledTransform
import PCRLean.MarkedIdeal

/-!
# Finite Frobenius-root packets under coordinate blowup

A finite family of roots vanishing on a coordinate centre determines the
marked ideal generated by their `q`-th powers.  It is permissible at mark `q`.
On every standard blowup chart, each generator factors as the exceptional
pivot to the `q`-th power times the `q`-th power of the transformed root.
Thus the finite controlled packet reenters the same Frobenius-root class on all
charts.

The theorem is ideal-valued and treats all generators simultaneously.  It does
not yet identify overlap localizations or perform strict-transform saturation.
-/

namespace PCRLean
namespace FiniteRootPacketTransform

noncomputable section

universe u v w x

variable {R : Type u} [CommRing R]
variable {α : Type v} {ι : Type w} {β : Type x}
variable [DecidableEq ι] [Fintype β]

abbrev P := CoordinateBlowupChart.P (R := R) (α := α) (ι := ι)

/-- Ideal generated by the `q`-th powers of a finite root packet. -/
noncomputable def sourceIdeal
    (q : Nat) (roots : β → P (R := R) (α := α) (ι := ι)) :
    Ideal (P (R := R) (α := α) (ι := ι)) :=
  Ideal.span (Set.range fun i => (roots i) ^ q)

/-- Transformed root in one standard chart. -/
noncomputable def transformedRoot
    (k : ι)
    (roots : β → P (R := R) (α := α) (ι := ι))
    (hroots : ∀ i, roots i ∈
      CoordinateBlowupChart.centreIdeal
        (R := R) (α := α) (ι := ι))
    (i : β) : P (R := R) (α := α) (ι := ι) :=
  CoordinateControlledTransform.rootTransform
    (R := R) (α := α) k (roots i) (hroots i)

/-- Controlled finite root packet in one chart. -/
noncomputable def transformedIdeal
    (k : ι) (q : Nat)
    (roots : β → P (R := R) (α := α) (ι := ι))
    (hroots : ∀ i, roots i ∈
      CoordinateBlowupChart.centreIdeal
        (R := R) (α := α) (ι := ι)) :
    Ideal (P (R := R) (α := α) (ι := ι)) :=
  Ideal.span (Set.range fun i =>
    (transformedRoot (R := R) (α := α) k roots hroots i) ^ q)

/-- The source packet is permissible for the coordinate centre at mark `q`. -/
theorem sourceIdeal_le_centre_pow
    (q : Nat)
    (roots : β → P (R := R) (α := α) (ι := ι))
    (hroots : ∀ i, roots i ∈
      CoordinateBlowupChart.centreIdeal
        (R := R) (α := α) (ι := ι)) :
    sourceIdeal q roots ≤
      (CoordinateBlowupChart.centreIdeal
        (R := R) (α := α) (ι := ι)) ^ q := by
  rw [sourceIdeal, Ideal.span_le]
  rintro x ⟨i, rfl⟩
  exact Ideal.pow_mem_pow (hroots i) q

/-- Marked-ideal form of finite root-packet permissibility. -/
theorem sourcePacket_permissible
    {q : Nat} (hq : 0 < q)
    (roots : β → P (R := R) (α := α) (ι := ι))
    (hroots : ∀ i, roots i ∈
      CoordinateBlowupChart.centreIdeal
        (R := R) (α := α) (ι := ι)) :
    MarkedIdeal.Permissible
      (R := P (R := R) (α := α) (ι := ι))
      ⟨sourceIdeal q roots, q, hq⟩
      (CoordinateBlowupChart.centreIdeal
        (R := R) (α := α) (ι := ι)) :=
  sourceIdeal_le_centre_pow q roots hroots

/-- Exact chart factorization for every generator in the finite root packet. -/
theorem generator_reentry
    (k : ι) (q : Nat)
    (roots : β → P (R := R) (α := α) (ι := ι))
    (hroots : ∀ i, roots i ∈
      CoordinateBlowupChart.centreIdeal
        (R := R) (α := α) (ι := ι))
    (i : β) :
    CoordinateBlowupChart.chartMap (R := R) (α := α) k
        ((roots i) ^ q) =
      (CoordinateBlowupChart.centreVar
        (R := R) (α := α) k) ^ q *
        (transformedRoot (R := R) (α := α) k roots hroots i) ^ q := by
  exact CoordinateControlledTransform.rootPower_reentry
    (R := R) (α := α) k q (roots i) (hroots i)

/-- The image of the full source packet lies in the exceptional `q`-th power
times the transformed Frobenius-root packet. -/
theorem map_sourceIdeal_le_exceptional_mul_transformed
    (k : ι) (q : Nat)
    (roots : β → P (R := R) (α := α) (ι := ι))
    (hroots : ∀ i, roots i ∈
      CoordinateBlowupChart.centreIdeal
        (R := R) (α := α) (ι := ι)) :
    (sourceIdeal q roots).map
        (CoordinateBlowupChart.chartMap (R := R) (α := α) k) ≤
      (CoordinateBlowupChart.pivotIdeal
          (R := R) (α := α) k) ^ q *
        transformedIdeal (R := R) (α := α) k q roots hroots := by
  rw [Ideal.map_le_iff_le_comap, sourceIdeal, Ideal.span_le]
  rintro x ⟨i, rfl⟩
  change CoordinateBlowupChart.chartMap (R := R) (α := α) k
      ((roots i) ^ q) ∈ _
  rw [generator_reentry (R := R) (α := α) k q roots hroots i]
  have hpivot :
      (CoordinateBlowupChart.centreVar
        (R := R) (α := α) k) ^ q ∈
      (CoordinateBlowupChart.pivotIdeal
        (R := R) (α := α) k) ^ q :=
    Ideal.pow_mem_pow
      (CoordinateBlowupChart.pivot_mem
        (R := R) (α := α) k) q
  have hroot :
      (transformedRoot (R := R) (α := α) k roots hroots i) ^ q ∈
        transformedIdeal (R := R) (α := α) k q roots hroots :=
    Ideal.subset_span ⟨i, rfl⟩
  exact Ideal.mul_mem_mul hpivot hroot

end

end FiniteRootPacketTransform
end PCRLean
