import Mathlib
import PCRLean.MarkedIdeal

/-!
# Actual Frobenius root centres

A descended ideal on a Frobenius base is useful for resolution only after it
produces an actual centre in the ambient algebra.  The required algebraic
bridge is a root section: a ring map `root : R → A` whose `q`-th powers recover
the chosen base map `R → A`.

For every base ideal `J`, the extension of `J` along the base map is contained
in the `q`-th power of the actual ideal generated by the roots of `J`.  Thus a
Frobenius-descended marked ideal of mark `q` is automatically permissible for
the actual root ideal.  No completion or formal centre occurs in this
construction.

Regularity and SNC compatibility of the root ideal require a separate
geometric frame theorem; the present file proves the marked-power bridge.
-/

namespace PCRLean
namespace FrobeniusRootCentre

noncomputable section

universe u v

variable {R : Type u} {A : Type v}
variable [CommRing R] [CommRing A] [Algebra R A]

/-- A chosen algebraic `q`-th-root section of the base map. -/
structure RootSection (q : Nat) where
  root : R →+* A
  pow_eq_algebraMap : ∀ r : R,
    (root r) ^ q = algebraMap R A r

namespace RootSection

variable {q : Nat}
variable (S : RootSection (R := R) (A := A) q)

/-- The actual ambient ideal generated by roots of a base ideal. -/
def rootIdeal (J : Ideal R) : Ideal A :=
  J.map S.root

/-- Every base extension is contained in the `q`-th power of its actual root
ideal. -/
theorem baseExtension_le_rootIdeal_pow (J : Ideal R) :
    J.map (algebraMap R A) ≤ (S.rootIdeal J) ^ q := by
  rw [Ideal.map_le_iff_le_comap]
  intro r hr
  change algebraMap R A r ∈ (S.rootIdeal J) ^ q
  rw [← S.pow_eq_algebraMap r]
  exact Ideal.pow_mem_pow
    (Ideal.mem_map_of_mem S.root hr) q

/-- Any ideal contained in the descended base extension is therefore contained
in the marked power of the root centre. -/
theorem le_rootIdeal_pow_of_le_baseExtension
    {I : Ideal A} {J : Ideal R}
    (hI : I ≤ J.map (algebraMap R A)) :
    I ≤ (S.rootIdeal J) ^ q :=
  hI.trans (S.baseExtension_le_rootIdeal_pow J)

/-- Exact Frobenius descent gives the same marked-power conclusion. -/
theorem le_rootIdeal_pow_of_eq_baseExtension
    {I : Ideal A} {J : Ideal R}
    (hI : I = J.map (algebraMap R A)) :
    I ≤ (S.rootIdeal J) ^ q := by
  rw [hI]
  exact S.baseExtension_le_rootIdeal_pow J

/-- A positive-mark Frobenius-descended packet is permissible for the actual
root ideal. -/
theorem markedPacket_permissible
    {I : Ideal A} {J : Ideal R} (hq : 0 < q)
    (hI : I ≤ J.map (algebraMap R A)) :
    MarkedIdeal.Permissible
      (R := A) ⟨I, q, hq⟩ (S.rootIdeal J) :=
  S.le_rootIdeal_pow_of_le_baseExtension hI

/-- In particular, equality with a descended extension supplies an actual
marked-permissible root centre. -/
theorem markedPacket_permissible_of_eq
    {I : Ideal A} {J : Ideal R} (hq : 0 < q)
    (hI : I = J.map (algebraMap R A)) :
    MarkedIdeal.Permissible
      (R := A) ⟨I, q, hq⟩ (S.rootIdeal J) := by
  exact S.markedPacket_permissible hq (by simpa [hI])

/-- Taking powers of a descended extension multiplies the marked order of the
root centre. -/
theorem baseExtension_pow_le_rootIdeal_pow_mul
    (J : Ideal R) (b : Nat) :
    (J.map (algebraMap R A)) ^ b ≤ (S.rootIdeal J) ^ (q * b) := by
  calc
    (J.map (algebraMap R A)) ^ b ≤
        ((S.rootIdeal J) ^ q) ^ b := by
      gcongr
      exact S.baseExtension_le_rootIdeal_pow J
    _ = (S.rootIdeal J) ^ (q * b) := by
      rw [pow_mul]

/-- A packet controlled by the `b`-th power of a descended ideal is
permissible at the multiplied mark `q*b`. -/
theorem markedPacket_permissible_of_le_baseExtension_pow
    {I : Ideal A} {J : Ideal R} {b : Nat}
    (hqb : 0 < q * b)
    (hI : I ≤ (J.map (algebraMap R A)) ^ b) :
    MarkedIdeal.Permissible
      (R := A) ⟨I, q * b, hqb⟩ (S.rootIdeal J) :=
  hI.trans (S.baseExtension_pow_le_rootIdeal_pow_mul J b)

end RootSection

end

end FrobeniusRootCentre
end PCRLean
