import Mathlib
import PCRLean.CoordinateBlowupChart
import PCRLean.CoordinateCentrePrincipalization

/-!
# Frobenius powers of ideals and root equivalences

On a characteristic-`p` ring the `e`-fold Frobenius is a ring homomorphism.
The Frobenius power of an ideal is therefore its ideal-theoretic image under
this homomorphism.

If a Frobenius base ring is identified with the ambient ring by a root
isomorphism and the structural base map is `F^e` after that identification,
then extension of every base ideal is exactly the Frobenius power of its root
ideal.  For a coordinate centre, this Frobenius power is precisely the ideal
generated by the `p^e`-th powers of the centre coordinates.

This is the missing equality behind one-step principalization of the pure
split Frobenius chamber; it strengthens marked-power containment to exact
identification of the transformed packet.
-/

namespace PCRLean
namespace FrobeniusPowerIdeal

noncomputable section

universe u v w x

variable {A : Type u} [CommRing A]
variable (p e : Nat) [ExpChar A p]

/-- Ideal-theoretic image under the `e`-fold Frobenius. -/
def powerIdeal (I : Ideal A) : Ideal A :=
  I.map (iterateFrobenius A p e)

/-- A Frobenius image of an ideal element belongs to its Frobenius power. -/
theorem map_mem_powerIdeal {I : Ideal A} {a : A} (ha : a ∈ I) :
    iterateFrobenius A p e a ∈ powerIdeal (A := A) p e I :=
  Ideal.mem_map_of_mem (iterateFrobenius A p e) ha

/-- Elementwise power form of the previous theorem. -/
theorem pow_mem_powerIdeal {I : Ideal A} {a : A} (ha : a ∈ I) :
    a ^ p ^ e ∈ powerIdeal (A := A) p e I := by
  simpa [iterateFrobenius_def] using
    map_mem_powerIdeal (A := A) p e ha

/-- Frobenius powers are monotone in the source ideal. -/
theorem mono {I J : Ideal A} (hIJ : I ≤ J) :
    powerIdeal (A := A) p e I ≤ powerIdeal (A := A) p e J :=
  Ideal.map_mono hIJ

section RootEquiv

variable {R : Type v} [CommRing R] [Algebra R A]

/-- An abstract identification of the Frobenius base with the ambient ring.
The algebra structure map is required to be the iterated Frobenius after the
root equivalence. -/
structure RootEquiv where
  rootEquiv : R ≃+* A
  algebraMap_eq :
    algebraMap R A =
      (iterateFrobenius A p e).comp rootEquiv.toRingHom

namespace RootEquiv

variable (S : RootEquiv (A := A) p e (R := R))

/-- Actual root ideal transported into the ambient ring. -/
def rootIdeal (J : Ideal R) : Ideal A :=
  J.map S.rootEquiv.toRingHom

/-- Extension from the Frobenius base is exactly the Frobenius power of the
actual root ideal. -/
theorem baseExtension_eq_powerIdeal (J : Ideal R) :
    J.map (algebraMap R A) =
      powerIdeal (A := A) p e (S.rootIdeal J) := by
  calc
    J.map (algebraMap R A) =
        J.map ((iterateFrobenius A p e).comp
          S.rootEquiv.toRingHom) := by
      rw [S.algebraMap_eq]
    _ = (J.map S.rootEquiv.toRingHom).map
        (iterateFrobenius A p e) := by
      rw [Ideal.map_map]
    _ = powerIdeal (A := A) p e (S.rootIdeal J) := rfl

/-- Properness of root ideals follows from the ring equivalence. -/
theorem rootIdeal_ne_top_iff (J : Ideal R) :
    S.rootIdeal J ≠ ⊤ ↔ J ≠ ⊤ := by
  constructor
  · intro hroot hJ
    apply hroot
    simp [rootIdeal, hJ]
  · intro hJ hroot
    have hmap := congrArg
      (fun I : Ideal A => I.map S.rootEquiv.symm.toRingHom) hroot
    apply hJ
    calc
      J = (S.rootIdeal J).map S.rootEquiv.symm.toRingHom := by
        rw [rootIdeal, Ideal.map_map]
        convert (Ideal.map_id J).symm using 1
        ext r
        simp
      _ = (⊤ : Ideal A).map S.rootEquiv.symm.toRingHom := by
        rw [hroot]
      _ = ⊤ := by simp

end RootEquiv
end RootEquiv

section CoordinateCentre

variable {K : Type w} [CommRing K] [ExpChar K p]
variable {α : Type x} {ι : Type*}
variable [DecidableEq ι]

abbrev P := CoordinateBlowupChart.P (R := K) (α := α) (ι := ι)

/-- Explicit ideal generated by the `p^e`-th powers of all centre coordinates. -/
noncomputable def coordinatePowerIdeal :
    Ideal (P (K := K) (α := α) (ι := ι)) :=
  Ideal.span (Set.range fun i : ι =>
    (CoordinateBlowupChart.centreVar
      (R := K) (α := α) i) ^ p ^ e)

/-- Frobenius power of a coordinate centre is exactly the coordinate-power
ideal. -/
theorem coordinateCentre_powerIdeal_eq :
    powerIdeal (A := P (K := K) (α := α) (ι := ι)) p e
        (CoordinateBlowupChart.centreIdeal
          (R := K) (α := α) (ι := ι)) =
      coordinatePowerIdeal (K := K) (α := α) (ι := ι) p e := by
  apply le_antisymm
  · rw [powerIdeal, Ideal.map_le_iff_le_comap,
      CoordinateBlowupChart.centreIdeal, Ideal.span_le]
    rintro x ⟨i, rfl⟩
    change iterateFrobenius
      (P (K := K) (α := α) (ι := ι)) p e
      (CoordinateBlowupChart.centreVar
        (R := K) (α := α) i) ∈
      coordinatePowerIdeal (K := K) (α := α) (ι := ι) p e
    simpa [iterateFrobenius_def, coordinatePowerIdeal] using
      (Ideal.subset_span
        (s := Set.range fun j : ι =>
          (CoordinateBlowupChart.centreVar
            (R := K) (α := α) j) ^ p ^ e)
        ⟨i, rfl⟩)
  · rw [coordinatePowerIdeal, Ideal.span_le]
    rintro x ⟨i, rfl⟩
    have hmem := Ideal.mem_map_of_mem
      (iterateFrobenius
        (P (K := K) (α := α) (ι := ι)) p e)
      (Ideal.subset_span
        (s := Set.range
          (CoordinateBlowupChart.centreVar
            (R := K) (α := α) (ι := ι)))
        ⟨i, rfl⟩)
    simpa [powerIdeal, iterateFrobenius_def] using hmem

/-- The explicit coordinate power ideal is the source packet used by the
one-step coordinate principalization theorem. -/
theorem coordinatePowerIdeal_eq_sourceIdeal :
    coordinatePowerIdeal (K := K) (α := α) (ι := ι) p e =
      CoordinateCentrePrincipalization.sourceIdeal
        (R := K) (α := α) (ι := ι) (p ^ e) := by
  rfl

end CoordinateCentre

end

end FrobeniusPowerIdeal
end PCRLean
