import Mathlib
import PCRLean.LinearPacketIdeal
import PCRLean.DifferentialOrbitClosure

/-!
# Actual linear ideals from functional packets

After choosing a finite free coordinate chart, each trace functional has one
actual linear polynomial.  A functional lying in the span of a finite packet
produces a polynomial lying in the actual ideal generated by that packet.
Consequently the actual linear ideal depends only on the spanned trace
submodule, not on the chosen finite generating packet.

This is a local integration theorem for the Hasse--Cartier orbit.  Coordinate
change and scheme-level descent are handled by separate overlap certificates.
-/

namespace PCRLean
namespace FunctionalPacketIdeal

noncomputable section

universe u v

variable {K : Type u} [Field K]
variable {σ : Type v} [Fintype σ] [DecidableEq σ]

abbrev Direction := σ → K
abbrev Dual := Module.Dual K Direction

/-- Standard basis vector of the coordinate direction space. -/
def basisVector (i : σ) : Direction (K := K) (σ := σ) :=
  fun j => if j = i then 1 else 0

/-- Coordinate row of a functional. -/
def coefficientRow (f : Dual (K := K) (σ := σ)) : σ → K :=
  fun i => f (basisVector (K := K) i)

/-- The actual linear polynomial attached to a trace functional. -/
def functionalPolynomial (f : Dual (K := K) (σ := σ)) : MvPolynomial σ K :=
  LinearPacketIdeal.linearPolynomial (coefficientRow f)

/-- Functional-to-polynomial integration is additive. -/
theorem functionalPolynomial_add
    (f g : Dual (K := K) (σ := σ)) :
    functionalPolynomial (f + g) =
      functionalPolynomial f + functionalPolynomial g := by
  apply LinearPacketIdeal.linearPolynomial_add

/-- Functional-to-polynomial integration is scalar linear. -/
theorem functionalPolynomial_smul
    (a : K) (f : Dual (K := K) (σ := σ)) :
    functionalPolynomial (a • f) =
      MvPolynomial.C a * functionalPolynomial f := by
  apply LinearPacketIdeal.linearPolynomial_smul

/-- Functional-to-polynomial integration as a linear map. -/
def integrationMap :
    Dual (K := K) (σ := σ) →ₗ[K] MvPolynomial σ K where
  toFun := functionalPolynomial
  map_add' := functionalPolynomial_add
  map_smul' := by
    intro a f
    simpa [Algebra.smul_def] using functionalPolynomial_smul a f

/-- The actual ideal generated by a finite functional packet. -/
def packetIdeal (s : Finset (Dual (K := K) (σ := σ))) :
    Ideal (MvPolynomial σ K) :=
  Ideal.span (functionalPolynomial '' (s : Set (Dual (K := K) (σ := σ))))

/-- Every named packet functional contributes a generator. -/
theorem generator_mem_packetIdeal
    (s : Finset (Dual (K := K) (σ := σ))) {f : Dual (K := K) (σ := σ)}
    (hf : f ∈ s) : functionalPolynomial f ∈ packetIdeal s := by
  exact Ideal.subset_span ⟨f, hf, rfl⟩

/-- Every functional in the linear span of the packet integrates to an element
of the same actual ideal. -/
theorem functionalPolynomial_mem_of_mem_span
    (s : Finset (Dual (K := K) (σ := σ)))
    {f : Dual (K := K) (σ := σ)}
    (hf : f ∈ Submodule.span K (s : Set (Dual (K := K) (σ := σ)))) :
    functionalPolynomial f ∈ packetIdeal s := by
  induction hf using Submodule.span_induction with
  | mem f hf => exact generator_mem_packetIdeal s hf
  | zero =>
      simp [functionalPolynomial, coefficientRow,
        LinearPacketIdeal.linearPolynomial, packetIdeal]
  | add f g hf hg hfi hgi =>
      rw [functionalPolynomial_add]
      exact (packetIdeal s).add_mem hfi hgi
  | smul a f hf hfi =>
      rw [functionalPolynomial_smul]
      exact (packetIdeal s).mul_mem_left _ hfi

/-- Finite packets spanning the same trace submodule define the same actual
linear ideal. -/
theorem packetIdeal_eq_of_span_eq
    (s t : Finset (Dual (K := K) (σ := σ)))
    (hspan : Submodule.span K (s : Set (Dual (K := K) (σ := σ))) =
      Submodule.span K (t : Set (Dual (K := K) (σ := σ)))) :
    packetIdeal s = packetIdeal t := by
  apply le_antisymm
  · rw [packetIdeal, Ideal.span_le]
    rintro x ⟨f, hf, rfl⟩
    apply functionalPolynomial_mem_of_mem_span t
    rw [← hspan]
    exact Submodule.subset_span hf
  · rw [packetIdeal, Ideal.span_le]
    rintro x ⟨f, hf, rfl⟩
    apply functionalPolynomial_mem_of_mem_span s
    rw [hspan]
    exact Submodule.subset_span hf

/-- A finite generator packet extracted from the full operator orbit integrates
to an actual ideal containing the polynomial of every raw future trace. -/
theorem raw_orbit_polynomial_mem_finite_packet_ideal
    {ι : Type*}
    (ops : ι → Module.End K Direction)
    (seed : Dual (K := K) (σ := σ))
    (s : Finset (Dual (K := K) (σ := σ)))
    (hspan : DifferentialOrbitClosure.orbitModule ops seed =
      Submodule.span K (s : Set (Dual (K := K) (σ := σ))))
    {f : Dual (K := K) (σ := σ)}
    (hf : f ∈ DifferentialOrbitClosure.orbitSet ops seed) :
    functionalPolynomial f ∈ packetIdeal s := by
  apply functionalPolynomial_mem_of_mem_span s
  rw [← hspan]
  exact Submodule.subset_span hf

/-- More generally every element of the full operator-orbit module integrates
into the finite packet ideal. -/
theorem orbitModule_polynomial_mem_finite_packet_ideal
    {ι : Type*}
    (ops : ι → Module.End K Direction)
    (seed : Dual (K := K) (σ := σ))
    (s : Finset (Dual (K := K) (σ := σ)))
    (hspan : DifferentialOrbitClosure.orbitModule ops seed =
      Submodule.span K (s : Set (Dual (K := K) (σ := σ))))
    {f : Dual (K := K) (σ := σ)}
    (hf : f ∈ DifferentialOrbitClosure.orbitModule ops seed) :
    functionalPolynomial f ∈ packetIdeal s := by
  apply functionalPolynomial_mem_of_mem_span s
  rw [← hspan]
  exact hf

end

end FunctionalPacketIdeal
end PCRLean
