import Mathlib
import PCRLean.LinearCoordinateChange

/-!
# Packet ideals as coordinate ideals under a linear automorphism

A full dual frame turns the ideal generated by any selected packet rows into
the image of the corresponding coordinate ideal.  Thus all local regularity
questions for independent linear packets reduce to the standard coordinate
ideal in a polynomial ring.
-/

namespace PCRLean
namespace LinearCoordinateIdeal

noncomputable section

universe u v

variable {K : Type u} [Field K]
variable {σ : Type v} [Fintype σ] [DecidableEq σ]

/-- Coordinate ideal generated by variables indexed by `s`. -/
def coordinateIdeal (s : Finset σ) : Ideal (MvPolynomial σ K) :=
  Ideal.span (MvPolynomial.X '' (s : Set σ))

/-- Packet ideal generated by the corresponding rows of a full frame. -/
def frameIdeal
    (F : LinearCoordinateChange.FullFrame (K := K) (σ := σ))
    (s : Finset σ) : Ideal (MvPolynomial σ K) :=
  Ideal.span (F.forwardVariable '' (s : Set σ))

/-- The forward polynomial automorphism carries the coordinate ideal onto the
selected packet ideal. -/
theorem map_coordinateIdeal_eq_frameIdeal
    (F : LinearCoordinateChange.FullFrame (K := K) (σ := σ))
    (s : Finset σ) :
    Ideal.map F.forward (coordinateIdeal s) = frameIdeal F s := by
  apply le_antisymm
  · rw [coordinateIdeal, frameIdeal, Ideal.map_le_iff_le_comap,
      Ideal.span_le]
    intro x hx
    rcases hx with ⟨i, hi, rfl⟩
    change F.forward (MvPolynomial.X i) ∈
      Ideal.comap F.forward (Ideal.span (F.forwardVariable '' (s : Set σ)))
    rw [Ideal.mem_comap, F.forward_X]
    exact Ideal.subset_span ⟨i, hi, rfl⟩
  · rw [frameIdeal, Ideal.span_le]
    intro x hx
    rcases hx with ⟨i, hi, rfl⟩
    rw [← F.forward_X]
    exact Ideal.mem_map_of_mem F.forward
      (Ideal.subset_span ⟨i, hi, rfl⟩)

/-- The inverse automorphism carries the packet ideal back to the coordinate
ideal. -/
theorem map_frameIdeal_eq_coordinateIdeal
    (F : LinearCoordinateChange.FullFrame (K := K) (σ := σ))
    (s : Finset σ) :
    Ideal.map F.inverse (frameIdeal F s) = coordinateIdeal s := by
  apply le_antisymm
  · rw [frameIdeal, coordinateIdeal, Ideal.map_le_iff_le_comap,
      Ideal.span_le]
    intro x hx
    rcases hx with ⟨i, hi, rfl⟩
    change F.inverse (F.forwardVariable i) ∈
      Ideal.comap F.inverse (Ideal.span (MvPolynomial.X '' (s : Set σ)))
    rw [Ideal.mem_comap, F.inverse_forwardVariable]
    exact Ideal.subset_span ⟨i, hi, rfl⟩
  · rw [coordinateIdeal, Ideal.span_le]
    intro x hx
    rcases hx with ⟨i, hi, rfl⟩
    rw [← F.inverse_forwardVariable]
    exact Ideal.mem_map_of_mem F.inverse
      (Ideal.subset_span ⟨i, hi, rfl⟩)

/-- Membership in a packet ideal is equivalent to membership in the coordinate
ideal after applying the inverse automorphism. -/
theorem mem_frameIdeal_iff
    (F : LinearCoordinateChange.FullFrame (K := K) (σ := σ))
    (s : Finset σ) (p : MvPolynomial σ K) :
    p ∈ frameIdeal F s ↔ F.inverse p ∈ coordinateIdeal s := by
  constructor
  · intro hp
    have hm : F.inverse p ∈ Ideal.map F.inverse (frameIdeal F s) :=
      Ideal.mem_map_of_mem F.inverse hp
    rw [map_frameIdeal_eq_coordinateIdeal] at hm
    exact hm
  · intro hp
    have hm : F.forward (F.inverse p) ∈
        Ideal.map F.forward (coordinateIdeal s) :=
      Ideal.mem_map_of_mem F.forward hp
    rw [map_coordinateIdeal_eq_frameIdeal] at hm
    have hcomp := congrArg
      (fun H : MvPolynomial σ K →ₐ[K] MvPolynomial σ K => H p)
      F.forward_comp_inverse
    simpa using hcomp ▸ hm

end

end LinearCoordinateIdeal
end PCRLean
