import Mathlib
import PCRLean.MultiOwnerHasseCore
import PCRLean.CoordinateRootPacket
import PCRLean.CoordinateCentreProper
import PCRLean.CoordinateBoundarySNC
import PCRLean.CoordinateTerminalOverlap
import PCRLean.FreePassiveOwnerSafety
import PCRLean.CoordinatePassiveSafety

/-!
# Multi-owner split Frobenius chamber

Let a finite family of active owners be Hasse-stable on one realized finite
product Frobenius frame.  Assume that the extension of their joint contracted
core is identified with the ideal generated by the `q`-th powers of a full
coordinate centre.  Then the same actual proper coordinate centre is
permissible for every owner and for their finite union, and the controlled full
root packet is terminal on every standard chart.

This is the first nontrivial MLEL-002 geometric chamber.  The coordinate
realization hypothesis is explicit; the module does not assert universal
regularization of arbitrary Frobenius cores.
-/

namespace PCRLean
namespace MultiOwnerSplitFrobeniusChamber

noncomputable section

universe u v w x y

variable {R : Type u} {K : Type v}
variable [CommRing R] [CommRing K] [Nontrivial K]
variable {α : Type w} {ι : Type x} {ω : Type y}
variable [DecidableEq ι]
variable [Fintype ω] [DecidableEq ω]
variable {spec : List (Nat × R)}

abbrev A := CoordinateBlowupChart.P (R := K) (α := α) (ι := ι)

variable [Algebra R (A (K := K) (α := α) (ι := ι))]

/-- Every owner is contained in the coordinate `q`-power source once the joint
core extension has been identified with that source. -/
theorem owner_le_coordinateSource
    (F : MultiHasseOnlyDescent.RealizedFrame
      (R := R) (A := A (K := K) (α := α) (ι := ι)) spec)
    (owners : ω → Ideal (A (K := K) (α := α) (ι := ι)))
    (hstable : ∀ i,
      DifferentialIdealSaturation.Stable F.hasseAddHom (owners i))
    (q : Nat)
    (hsource :
      (MultiOwnerHasseCore.jointCore F owners).map
          (algebraMap R (A (K := K) (α := α) (ι := ι))) =
        CoordinateRootPacket.sourceIdeal
          (R := K) (α := α) (ι := ι) q)
    (i : ω) :
    owners i ≤ CoordinateRootPacket.sourceIdeal
      (R := K) (α := α) (ι := ι) q := by
  calc
    owners i ≤
        (MultiOwnerHasseCore.jointCore F owners).map
          (algebraMap R (A (K := K) (α := α) (ι := ι))) :=
      MultiOwnerHasseCore.owner_le_jointCoreExtension
        F owners hstable i
    _ = CoordinateRootPacket.sourceIdeal
          (R := K) (α := α) (ι := ι) q := hsource

/-- Every active owner is permissible for the same coordinate centre. -/
theorem every_owner_permissible
    (F : MultiHasseOnlyDescent.RealizedFrame
      (R := R) (A := A (K := K) (α := α) (ι := ι)) spec)
    (owners : ω → Ideal (A (K := K) (α := α) (ι := ι)))
    (hstable : ∀ i,
      DifferentialIdealSaturation.Stable F.hasseAddHom (owners i))
    {q : Nat} (hq : 0 < q)
    (hsource :
      (MultiOwnerHasseCore.jointCore F owners).map
          (algebraMap R (A (K := K) (α := α) (ι := ι))) =
        CoordinateRootPacket.sourceIdeal
          (R := K) (α := α) (ι := ι) q)
    (i : ω) :
    MarkedIdeal.Permissible
      (R := A (K := K) (α := α) (ι := ι))
      ⟨owners i, q, hq⟩
      (CoordinateBlowupChart.centreIdeal
        (R := K) (α := α) (ι := ι)) := by
  exact (owner_le_coordinateSource F owners hstable q hsource i).trans
    (CoordinateRootPacket.sourceIdeal_le_centre_pow
      (R := K) (α := α) (ι := ι) q)

/-- The finite union of all active owners is permissible for the same centre. -/
theorem jointOwnerIdeal_permissible
    (F : MultiHasseOnlyDescent.RealizedFrame
      (R := R) (A := A (K := K) (α := α) (ι := ι)) spec)
    (owners : ω → Ideal (A (K := K) (α := α) (ι := ι)))
    (hstable : ∀ i,
      DifferentialIdealSaturation.Stable F.hasseAddHom (owners i))
    {q : Nat} (hq : 0 < q)
    (hsource :
      (MultiOwnerHasseCore.jointCore F owners).map
          (algebraMap R (A (K := K) (α := α) (ι := ι))) =
        CoordinateRootPacket.sourceIdeal
          (R := K) (α := α) (ι := ι) q) :
    MarkedIdeal.Permissible
      (R := A (K := K) (α := α) (ι := ι))
      ⟨MultiOwnerHasseCore.jointOwnerIdeal owners, q, hq⟩
      (CoordinateBlowupChart.centreIdeal
        (R := K) (α := α) (ι := ι)) := by
  have hjoint : MultiOwnerHasseCore.jointOwnerIdeal owners ≤
      CoordinateRootPacket.sourceIdeal
        (R := K) (α := α) (ι := ι) q := by
    calc
      MultiOwnerHasseCore.jointOwnerIdeal owners ≤
          (MultiOwnerHasseCore.jointCore F owners).map
            (algebraMap R (A (K := K) (α := α) (ι := ι))) :=
        MultiOwnerHasseCore.jointOwnerIdeal_le_jointCoreExtension
          F owners hstable
      _ = CoordinateRootPacket.sourceIdeal
            (R := K) (α := α) (ι := ι) q := hsource
  exact hjoint.trans
    (CoordinateRootPacket.sourceIdeal_le_centre_pow
      (R := K) (α := α) (ι := ι) q)

/-- Complete restricted MLEL-002 certificate. -/
theorem certificate
    (F : MultiHasseOnlyDescent.RealizedFrame
      (R := R) (A := A (K := K) (α := α) (ι := ι)) spec)
    (owners : ω → Ideal (A (K := K) (α := α) (ι := ι)))
    (hstable : ∀ i,
      DifferentialIdealSaturation.Stable F.hasseAddHom (owners i))
    {q : Nat} (hq : 0 < q)
    (hsource :
      (MultiOwnerHasseCore.jointCore F owners).map
          (algebraMap R (A (K := K) (α := α) (ι := ι))) =
        CoordinateRootPacket.sourceIdeal
          (R := K) (α := α) (ι := ι) q) :
    (∀ i : ω,
        MarkedIdeal.Permissible
          (R := A (K := K) (α := α) (ι := ι))
          ⟨owners i, q, hq⟩
          (CoordinateBlowupChart.centreIdeal
            (R := K) (α := α) (ι := ι))) ∧
      MarkedIdeal.Permissible
        (R := A (K := K) (α := α) (ι := ι))
        ⟨MultiOwnerHasseCore.jointOwnerIdeal owners, q, hq⟩
        (CoordinateBlowupChart.centreIdeal
          (R := K) (α := α) (ι := ι)) ∧
      CoordinateBlowupChart.centreIdeal
        (R := K) (α := α) (ι := ι) ≠ ⊤ ∧
      (∀ k : ι,
        CoordinateRootPacket.transformedRootIdeal
          (R := K) (α := α) k q = ⊤) ∧
      (∀ i j : ι,
        CoordinateRootPacket.transformedRootIdeal
            (R := K) (α := α) i q =
          CoordinateRootPacket.transformedRootIdeal
            (R := K) (α := α) j q) := by
  refine ⟨?_,
    jointOwnerIdeal_permissible F owners hstable hq hsource,
    CoordinateCentreProper.centreIdeal_ne_top
      (K := K) (α := α) (ι := ι), ?_, ?_⟩
  · intro i
    exact every_owner_permissible
      F owners hstable hq hsource i
  · intro k
    exact CoordinateRootPacket.transformedRootIdeal_eq_top
      (R := K) (α := α) k q
  · intro i j
    exact CoordinateTerminalOverlap.transformedRootIdeal_eq
      (R := K) (α := α) i j q

/-- A boundary frame remains disjoint from the coordinate centre variables. -/
theorem boundary_coordinate_certificate
    {β : Type*}
    (B : CoordinateBoundarySNC.Frame (β := β) (α := α)) :
    Function.Injective (B.combined (ι := ι)) :=
  B.combined_injective (ι := ι)

end

end MultiOwnerSplitFrobeniusChamber
end PCRLean
