import Mathlib
import PCRLean.CoordinateBlowupChart
import PCRLean.CoordinateCentrePrincipalization
import PCRLean.MarkedIdeal

/-!
# MLEL-002: multi-owner coordinate Frobenius support chamber

This experimental module isolates the finite-support version of the
coordinate-realized joint-core theorem. Each owner is generated by `q`-th
powers of a finite set of centre coordinates. The full coordinate centre is
simultaneously permissible. An owner containing a chart pivot has unit
controlled transform, and a charged joint packet is terminal on every pivot
chart.

Universal core regularization is not asserted here.
-/

namespace PCRLean
namespace MultiOwnerCoordinateFrobenius

noncomputable section

universe u v w x

variable {R : Type u} [CommRing R]
variable {α : Type v} {ι : Type w} {ω : Type x}
variable [DecidableEq ι]
variable [Fintype ω] [DecidableEq ω]

abbrev P := CoordinateBlowupChart.P (R := R) (α := α) (ι := ι)

/-- Coordinate `q`-power ideal attached to one finite owner support. -/
noncomputable def ownerIdeal (support : Finset ι) (q : Nat) :
    Ideal (P (R := R) (α := α) (ι := ι)) :=
  Ideal.span (Set.range fun i : support =>
    (CoordinateBlowupChart.centreVar
      (R := R) (α := α) (ι := ι) i.1) ^ q)

/-- Finite supremum of all active owner ideals. -/
noncomputable def jointIdeal
    (support : ω → Finset ι) (q : Nat) :
    Ideal (P (R := R) (α := α) (ι := ι)) :=
  Finset.univ.sup (fun o => ownerIdeal (R := R) (α := α) (support o) q)

/-- Union of all charged coordinate roots. -/
def jointSupport (support : ω → Finset ι) : Finset ι :=
  Finset.univ.biUnion support

/-- Every coordinate owner is permissible for the full coordinate centre at
mark `q`. -/
theorem ownerIdeal_le_centre_pow
    (support : Finset ι) (q : Nat) :
    ownerIdeal (R := R) (α := α) support q ≤
      (CoordinateBlowupChart.centreIdeal
        (R := R) (α := α) (ι := ι)) ^ q := by
  rw [ownerIdeal, Ideal.span_le]
  rintro z ⟨i, rfl⟩
  exact Ideal.pow_mem_pow
    (Ideal.subset_span ⟨i.1, rfl⟩) q

/-- All owners are simultaneously permissible for the same coordinate centre. -/
theorem jointIdeal_le_centre_pow
    (support : ω → Finset ι) (q : Nat) :
    jointIdeal (R := R) (α := α) support q ≤
      (CoordinateBlowupChart.centreIdeal
        (R := R) (α := α) (ι := ι)) ^ q := by
  rw [jointIdeal]
  exact Finset.sup_le fun o ho =>
    ownerIdeal_le_centre_pow (R := R) (α := α) (support o) q

/-- Marked form of simultaneous active-owner permissibility. -/
theorem jointPacket_permissible
    (support : ω → Finset ι) {q : Nat} (hq : 0 < q) :
    MarkedIdeal.Permissible
      (R := P (R := R) (α := α) (ι := ι))
      ⟨jointIdeal (R := R) (α := α) support q, q, hq⟩
      (CoordinateBlowupChart.centreIdeal
        (R := R) (α := α) (ι := ι)) :=
  jointIdeal_le_centre_pow (R := R) (α := α) support q

/-- Controlled root ideal of one owner in a pivot chart. -/
noncomputable def transformedOwnerIdeal
    (k : ι) (support : Finset ι) (q : Nat) :
    Ideal (P (R := R) (α := α) (ι := ι)) :=
  Ideal.span (Set.range fun i : support =>
    (CoordinateCentrePrincipalization.explicitRootTransform
      (R := R) (α := α) k i.1) ^ q)

/-- Exact generatorwise exceptional-factor containment for one owner. -/
theorem map_ownerIdeal_le_exceptional_mul_transformed
    (k : ι) (support : Finset ι) (q : Nat) :
    (ownerIdeal (R := R) (α := α) support q).map
        (CoordinateBlowupChart.chartMap (R := R) (α := α) k) ≤
      (CoordinateBlowupChart.pivotIdeal
        (R := R) (α := α) k) ^ q *
        transformedOwnerIdeal (R := R) (α := α) k support q := by
  rw [Ideal.map_le_iff_le_comap, ownerIdeal, Ideal.span_le]
  rintro z ⟨i, rfl⟩
  change CoordinateBlowupChart.chartMap (R := R) (α := α) k
      ((CoordinateBlowupChart.centreVar
        (R := R) (α := α) i.1) ^ q) ∈ _
  rw [CoordinateCentrePrincipalization.centreVar_pow_factorization
    (R := R) (α := α) k i.1 q]
  exact Ideal.mul_mem_mul
    (Ideal.pow_mem_pow
      (CoordinateBlowupChart.pivot_mem
        (R := R) (α := α) k) q)
    (Ideal.subset_span ⟨i, rfl⟩)

/-- An owner containing the pivot becomes terminal on that chart. -/
theorem transformedOwnerIdeal_eq_top_of_mem
    (k : ι) (support : Finset ι) (q : Nat)
    (hk : k ∈ support) :
    transformedOwnerIdeal (R := R) (α := α) k support q = ⊤ := by
  apply Ideal.eq_top_iff_one.mpr
  apply Ideal.subset_span
  refine ⟨⟨k, hk⟩, ?_⟩
  simp [CoordinateCentrePrincipalization.explicitRootTransform]

/-- Joint controlled packet in one pivot chart. -/
noncomputable def transformedJointIdeal
    (k : ι) (support : ω → Finset ι) (q : Nat) :
    Ideal (P (R := R) (α := α) (ι := ι)) :=
  Finset.univ.sup fun o =>
    transformedOwnerIdeal (R := R) (α := α) k (support o) q

/-- A pivot charged to some owner makes the joint controlled packet top. -/
theorem transformedJointIdeal_eq_top_of_mem_jointSupport
    (k : ι) (support : ω → Finset ι) (q : Nat)
    (hk : k ∈ jointSupport support) :
    transformedJointIdeal (R := R) (α := α) k support q = ⊤ := by
  have hex : ∃ o ∈ (Finset.univ : Finset ω), k ∈ support o := by
    simpa [jointSupport] using hk
  rcases hex with ⟨o, ho, hko⟩
  apply top_unique
  rw [← transformedOwnerIdeal_eq_top_of_mem
    (R := R) (α := α) k (support o) q hko]
  exact Finset.le_sup (f := fun a =>
    transformedOwnerIdeal (R := R) (α := α) k (support a) q) ho

end

end MultiOwnerCoordinateFrobenius
end PCRLean
