import Mathlib

/-!
# Noetherian operator orbits and finite kernel packets

This file upgrades the finite-dimensional Hasse--Cartier orbit construction to
one fixed Noetherian ancestor module.  Arbitrarily long words in a family of
operators generate a submodule, but Noetherianity extracts finitely many raw
orbit elements that generate the whole orbit.  Any linear pairing with an
ambient direction module is therefore cut out by finitely many actual
functionals.

This is the Hilbert-basis part of the proposed causal-envelope construction.
It does not identify the geometric ancestor module, prove presentation
independence, or prove that the resulting kernel integrates to a regular
permissible centre.
-/

namespace PCRLean
namespace NoetherianOperatorOrbit

noncomputable section

universe u v w z

variable {R : Type u} {D : Type v} {ι : Type w}
variable [CommSemiring R] [AddCommMonoid D] [Module R D]

/-- Apply a finite operator word to a seed element. -/
def applyWord (ops : ι → Module.End R D) : List ι → D → D
  | [], x => x
  | i :: word, x => ops i (applyWord ops word x)

@[simp] theorem applyWord_nil (ops : ι → Module.End R D) (x : D) :
    applyWord ops [] x = x := rfl

@[simp] theorem applyWord_cons (ops : ι → Module.End R D)
    (i : ι) (word : List ι) (x : D) :
    applyWord ops (i :: word) x = ops i (applyWord ops word x) := rfl

/-- The raw orbit under all finite words. -/
def orbitSet (ops : ι → Module.End R D) (seed : D) : Set D :=
  {x | ∃ word : List ι, x = applyWord ops word seed}

/-- The submodule generated by the full raw orbit. -/
def orbitModule (ops : ι → Module.End R D) (seed : D) : Submodule R D :=
  Submodule.span R (orbitSet ops seed)

/-- The seed is contained in its operator orbit. -/
theorem seed_mem_orbitModule (ops : ι → Module.End R D) (seed : D) :
    seed ∈ orbitModule ops seed := by
  apply Submodule.subset_span
  exact ⟨[], rfl⟩

/-- One more operator sends a raw orbit element to a raw orbit element. -/
theorem map_mem_orbitSet (ops : ι → Module.End R D) (seed : D)
    (i : ι) {x : D} (hx : x ∈ orbitSet ops seed) :
    ops i x ∈ orbitSet ops seed := by
  rcases hx with ⟨word, rfl⟩
  exact ⟨i :: word, rfl⟩

/-- The generated orbit module is stable under every operator. -/
theorem orbitModule_stable (ops : ι → Module.End R D) (seed : D) (i : ι) :
    ∀ x ∈ orbitModule ops seed, ops i x ∈ orbitModule ops seed := by
  intro x hx
  induction hx using Submodule.span_induction with
  | mem x hx =>
      exact Submodule.subset_span (map_mem_orbitSet ops seed i hx)
  | zero => simpa using (orbitModule ops seed).zero_mem
  | add x y hx hy hxi hyi =>
      rw [map_add]
      exact (orbitModule ops seed).add_mem hxi hyi
  | smul a x hx hxi =>
      rw [map_smul]
      exact (orbitModule ops seed).smul_mem a hxi

section Noetherian

variable [IsNoetherian R D]

/-- Although the raw orbit contains words of arbitrary length, its span has a
finite generating packet consisting of raw orbit elements. -/
theorem exists_finite_raw_orbit_generators
    (ops : ι → Module.End R D) (seed : D) :
    ∃ s : Finset D,
      (s : Set D) ⊆ orbitSet ops seed ∧
      orbitModule ops seed = Submodule.span R (s : Set D) := by
  have hfg : (Submodule.span R (orbitSet ops seed)).FG :=
    IsNoetherian.noetherian _
  rcases (Submodule.fg_span_iff_fg_span_finset_subset
    (R := R) (orbitSet ops seed)).mp hfg with ⟨s, hs, heq⟩
  exact ⟨s, hs, by simpa [orbitModule] using heq⟩

end Noetherian

section Pairing

variable {V : Type z} [AddCommMonoid V] [Module R V]

abbrev DualV := Module.Dual R V

/-- The common kernel in `V` of an operator-orbit submodule paired into
`V*`. -/
def annihilatorVia (pair : D →ₗ[R] DualV (R := R) (V := V))
    (N : Submodule R D) : Submodule R V where
  carrier := {x | ∀ d, d ∈ N → pair d x = 0}
  zero_mem' := by
    intro d hd
    simp
  add_mem' := by
    intro x y hx hy d hd
    rw [map_add, hx d hd, hy d hd, add_zero]
  smul_mem' := by
    intro a x hx d hd
    rw [map_smul, hx d hd, smul_zero]

@[simp] theorem mem_annihilatorVia_iff
    {pair : D →ₗ[R] DualV (R := R) (V := V)}
    {N : Submodule R D} {x : V} :
    x ∈ annihilatorVia pair N ↔ ∀ d, d ∈ N → pair d x = 0 :=
  Iff.rfl

/-- Enlarging the orbit module can only shrink its common kernel. -/
theorem annihilatorVia_antitone
    (pair : D →ₗ[R] DualV (R := R) (V := V))
    {N P : Submodule R D} (hNP : N ≤ P) :
    annihilatorVia pair P ≤ annihilatorVia pair N := by
  intro x hx
  intro d hd
  exact hx d (hNP hd)

/-- If a finite family spans an orbit module, its common kernel is tested by
that finite family alone. -/
theorem mem_annihilatorVia_iff_of_span_eq
    (pair : D →ₗ[R] DualV (R := R) (V := V))
    (N : Submodule R D) (s : Finset D)
    (hspan : N = Submodule.span R (s : Set D)) (x : V) :
    x ∈ annihilatorVia pair N ↔ ∀ d ∈ s, pair d x = 0 := by
  constructor
  · intro hx d hd
    apply hx d
    rw [hspan]
    exact Submodule.subset_span hd
  · intro hgen
    rw [mem_annihilatorVia_iff]
    intro d hd
    rw [hspan] at hd
    induction hd using Submodule.span_induction with
    | mem d hd => exact hgen d hd
    | zero => simp
    | add a b ha hb hza hzb =>
        have hadd := congrArg₂ (fun x y : R => x + y) hza hzb
        simpa using hadd
    | smul a d hd hzd =>
        have hsmul := congrArg (fun y : R => a * y) hzd
        simpa using hsmul

variable [IsNoetherian R D]

/-- The infinite operator orbit admits a finite raw packet cutting out exactly
its paired persistent kernel. -/
theorem exists_finite_kernel_packet
    (ops : ι → Module.End R D) (seed : D)
    (pair : D →ₗ[R] DualV (R := R) (V := V)) :
    ∃ s : Finset D,
      (s : Set D) ⊆ orbitSet ops seed ∧
      orbitModule ops seed = Submodule.span R (s : Set D) ∧
      ∀ x : V,
        x ∈ annihilatorVia pair (orbitModule ops seed) ↔
          ∀ d ∈ s, pair d x = 0 := by
  rcases exists_finite_raw_orbit_generators ops seed with ⟨s, hs, hspan⟩
  exact ⟨s, hs, hspan, fun x =>
    mem_annihilatorVia_iff_of_span_eq pair (orbitModule ops seed) s hspan x⟩

end Pairing

end

end NoetherianOperatorOrbit
end PCRLean
