import Mathlib
import PCRLean.NoetherianOperatorOrbit

/-!
# Canonical operator saturation

A presentation-independent differential packet should depend on the submodule
of seed data, not on a chosen list of generators.  This file closes the
linear-algebraic part of that requirement.  Given a family of operators and a
seed submodule, `saturation` is the least operator-stable submodule containing
the seed.  It is monotone, idempotent, and finitely generated on a Noetherian
ambient module.

The geometric use still requires a functorial finite ancestor module and proof
that blowup transforms act through the declared operator family.
-/

namespace PCRLean
namespace OperatorSaturation

noncomputable section

universe u v w

variable {R : Type u} {D : Type v} {ι : Type w}
variable [CommSemiring R] [AddCommMonoid D] [Module R D]

open NoetherianOperatorOrbit

/-- A submodule is stable under every operator in the family. -/
def Stable (ops : ι → Module.End R D) (P : Submodule R D) : Prop :=
  ∀ i x, x ∈ P → ops i x ∈ P

/-- Raw descendants of every element of a seed submodule. -/
def saturationSet (ops : ι → Module.End R D) (N : Submodule R D) : Set D :=
  {y | ∃ x, x ∈ N ∧ ∃ word : List ι,
    y = NoetherianOperatorOrbit.applyWord ops word x}

/-- The least candidate stable packet generated by a seed submodule. -/
def saturation (ops : ι → Module.End R D) (N : Submodule R D) :
    Submodule R D :=
  Submodule.span R (saturationSet ops N)

/-- Every seed element is a raw descendant of itself. -/
theorem seed_mem_saturationSet (ops : ι → Module.End R D)
    (N : Submodule R D) {x : D} (hx : x ∈ N) :
    x ∈ saturationSet ops N := by
  exact ⟨x, hx, [], rfl⟩

/-- The seed submodule is contained in its saturation. -/
theorem le_saturation (ops : ι → Module.End R D) (N : Submodule R D) :
    N ≤ saturation ops N := by
  intro x hx
  exact Submodule.subset_span (seed_mem_saturationSet ops N hx)

/-- One more operator sends a raw saturated descendant to another raw
descendant. -/
theorem map_mem_saturationSet (ops : ι → Module.End R D)
    (N : Submodule R D) (i : ι) {x : D}
    (hx : x ∈ saturationSet ops N) :
    ops i x ∈ saturationSet ops N := by
  rcases hx with ⟨seed, hseed, word, rfl⟩
  exact ⟨seed, hseed, i :: word, rfl⟩

/-- The saturation is stable under every operator. -/
theorem saturation_stable (ops : ι → Module.End R D)
    (N : Submodule R D) : Stable ops (saturation ops N) := by
  intro i x hx
  induction hx using Submodule.span_induction with
  | mem x hx =>
      exact Submodule.subset_span (map_mem_saturationSet ops N i hx)
  | zero =>
      simpa using (saturation ops N).zero_mem
  | add x y hx hy hxi hyi =>
      rw [map_add]
      exact (saturation ops N).add_mem hxi hyi
  | smul a x hx hxi =>
      rw [map_smul]
      exact (saturation ops N).smul_mem a hxi

/-- Every finite operator word preserves a stable submodule. -/
theorem applyWord_mem_of_stable
    (ops : ι → Module.End R D) (P : Submodule R D)
    (hP : Stable ops P) (word : List ι) {x : D} (hx : x ∈ P) :
    NoetherianOperatorOrbit.applyWord ops word x ∈ P := by
  induction word with
  | nil => simpa
  | cons i word ih =>
      exact hP i _ (ih hx)

/-- Minimality: every stable submodule containing the seed contains its
saturation. -/
theorem saturation_le_of_le_of_stable
    (ops : ι → Module.End R D) {N P : Submodule R D}
    (hNP : N ≤ P) (hP : Stable ops P) :
    saturation ops N ≤ P := by
  rw [saturation, Submodule.span_le]
  intro y hy
  rcases hy with ⟨x, hxN, word, rfl⟩
  exact applyWord_mem_of_stable ops P hP word (hNP hxN)

/-- The saturation is the least stable submodule containing the seed. -/
theorem saturation_le_iff
    (ops : ι → Module.End R D) {N P : Submodule R D}
    (hP : Stable ops P) :
    saturation ops N ≤ P ↔ N ≤ P := by
  constructor
  · exact fun h => (le_saturation ops N).trans h
  · exact fun h => saturation_le_of_le_of_stable ops h hP

/-- Saturation is monotone in the seed submodule. -/
theorem saturation_mono (ops : ι → Module.End R D)
    {N P : Submodule R D} (hNP : N ≤ P) :
    saturation ops N ≤ saturation ops P := by
  exact saturation_le_of_le_of_stable ops
    (hNP.trans (le_saturation ops P)) (saturation_stable ops P)

/-- A stable submodule is already saturated. -/
theorem saturation_eq_self_of_stable
    (ops : ι → Module.End R D) (N : Submodule R D)
    (hN : Stable ops N) :
    saturation ops N = N := by
  apply le_antisymm
  · exact saturation_le_of_le_of_stable ops le_rfl hN
  · exact le_saturation ops N

/-- Saturation is idempotent. -/
theorem saturation_idempotent
    (ops : ι → Module.End R D) (N : Submodule R D) :
    saturation ops (saturation ops N) = saturation ops N := by
  exact saturation_eq_self_of_stable ops (saturation ops N)
    (saturation_stable ops N)

/-- Equal seed submodules have equal canonical saturations; no generator list
is retained in the construction. -/
theorem saturation_congr (ops : ι → Module.End R D)
    {N P : Submodule R D} (h : N = P) :
    saturation ops N = saturation ops P := by
  simpa [h]

section Noetherian

variable [IsNoetherian R D]

/-- The canonical saturation is finitely generated in a Noetherian ancestor
module. -/
theorem saturation_fg (ops : ι → Module.End R D)
    (N : Submodule R D) : (saturation ops N).FG :=
  IsNoetherian.noetherian _

/-- The canonical saturation can be generated by finitely many raw operator
descendants of seed elements. -/
theorem exists_finite_raw_saturation_generators
    (ops : ι → Module.End R D) (N : Submodule R D) :
    ∃ s : Finset D,
      (s : Set D) ⊆ saturationSet ops N ∧
      saturation ops N = Submodule.span R (s : Set D) := by
  have hfg : (Submodule.span R (saturationSet ops N)).FG :=
    IsNoetherian.noetherian _
  rcases (Submodule.fg_span_iff_fg_span_finset_subset
    (R := R) (saturationSet ops N)).mp hfg with ⟨s, hs, heq⟩
  exact ⟨s, hs, by simpa [saturation] using heq⟩

end Noetherian

end

end OperatorSaturation
end PCRLean
