import Mathlib
import Mathlib.LinearAlgebra.Matrix.Block
import Mathlib.LinearAlgebra.Matrix.NonsingularInverse
import PCRLean.DiagonalMatrixUnitFactory

/-!
# Finite Pascal separation

For the Frobenius monomial frame `1,x,...,x^(q-1)`, the composite `x^b H_b`
is diagonal with eigenvalue `choose(c,b)` on `x^c`.  The resulting finite
Pascal matrix is upper triangular with diagonal entries one, hence has
determinant one over every commutative ring.  Its nonsingular inverse supplies
canonical coefficients separating each monomial coordinate.

This proves the finite linear-algebra identity required by
`DiagonalMatrixUnitFactory` without assuming an inverse matrix or using a
characteristic-zero division formula.
-/

namespace PCRLean
namespace PascalSeparation

noncomputable section

universe u

variable {R : Type u} [CommRing R]
variable (q : ℕ)

/-- The finite Pascal weight matrix, with Hasse order in the row and monomial
exponent in the column. -/
def pascalMatrix : Matrix (Fin q) (Fin q) R :=
  fun b c => (Nat.choose c.1 b.1 : R)

/-- The Pascal matrix is upper triangular in the natural order. -/
theorem pascal_blockTriangular :
    (pascalMatrix (R := R) q).BlockTriangular id := by
  intro i j hji
  have hlt : j.1 < i.1 := by
    simpa using hji
  have hzero : Nat.choose j.1 i.1 = 0 :=
    Nat.choose_eq_zero_of_lt hlt
  simp [pascalMatrix, hzero]

/-- Every diagonal entry of the finite Pascal matrix is one. -/
@[simp] theorem pascal_diagonal (i : Fin q) :
    pascalMatrix (R := R) q i i = 1 := by
  simp [pascalMatrix]

/-- The finite Pascal matrix has determinant one over every commutative ring. -/
theorem pascal_det : (pascalMatrix (R := R) q).det = 1 := by
  rw [Matrix.det_of_upperTriangular
    (pascal_blockTriangular (R := R) q)]
  simp

/-- In particular its determinant is a unit. -/
theorem pascal_det_isUnit :
    IsUnit (pascalMatrix (R := R) q).det := by
  rw [pascal_det (R := R) q]
  exact isUnit_one

/-- The canonical inverse-Pascal coefficients. -/
def inverseCoeff (d b : Fin q) : R :=
  (pascalMatrix (R := R) q)⁻¹ d b

/-- The inverse coefficients separate the Hasse/Pascal weights into Kronecker
delta functions. -/
theorem inverseCoeff_separates (d c : Fin q) :
    ∑ b : Fin q,
        inverseCoeff (R := R) q d b * (Nat.choose c.1 b.1 : R) =
      if c = d then 1 else 0 := by
  have hmul := Matrix.nonsing_inv_mul
    (pascalMatrix (R := R) q) (pascal_det_isUnit (R := R) q)
  have hentry := congrFun (congrFun hmul d) c
  simpa [inverseCoeff, pascalMatrix, Matrix.mul_apply, eq_comm] using hentry

/-- The concrete Pascal weight family used by the diagonal factory. -/
def pascalWeight (b c : Fin q) : R :=
  (Nat.choose c.1 b.1 : R)

/-- The concrete Pascal coefficients satisfy the abstract separation
certificate. -/
theorem pascalWeight_separates :
    ∀ d c,
      ∑ b : Fin q,
          inverseCoeff (R := R) q d b * pascalWeight (R := R) q b c =
        if c = d then 1 else 0 := by
  intro d c
  exact inverseCoeff_separates (R := R) q d c

/-- Consequently, for any transfer family, all diagonal coordinate projectors
are generated by the finite Pascal diagonal packet. -/
theorem generated_pascal_projector
    (transfer : Fin q → Fin q →
      Module.End R (DiagonalMatrixUnitFactory.Coordinates
        (R := R) (ι := Fin q)))
    (d : Fin q) :
    EndomorphismGeneration.Generated
      (DiagonalMatrixUnitFactory.packet
        (pascalWeight (R := R) q) transfer)
      (MatrixStableSubmodule.matrixUnit (R := R) d d) := by
  exact DiagonalMatrixUnitFactory.generated_projector
    (pascalWeight (R := R) q)
    (inverseCoeff (R := R) q)
    transfer
    (pascalWeight_separates (R := R) q) d

end

end PascalSeparation
end PCRLean
