import Mathlib.RingTheory.ReesAlgebra

namespace PCRLean
namespace ReesFoundation

universe u

variable {R : Type u} [CommRing R]

/-- The coefficientwise membership criterion for the Rees algebra. -/
theorem mem_rees_iff (I : Ideal R) (f : Polynomial R) :
    f ∈ reesAlgebra I ↔ ∀ n : Nat, f.coeff n ∈ I ^ n := by
  exact mem_reesAlgebra_iff I f

/-- A degree-`n` monomial belongs to the Rees algebra exactly when its
coefficient belongs to the `n`th power of the ideal. -/
theorem monomial_mem_iff {I : Ideal R} {n : Nat} {r : R} :
    Polynomial.monomial n r ∈ reesAlgebra I ↔ r ∈ I ^ n := by
  exact reesAlgebra.monomial_mem

/-- The Rees algebra is generated by degree-one ideal elements. -/
theorem generated_in_degree_one (I : Ideal R) :
    Algebra.adjoin R
      (Submodule.map (Polynomial.monomial 1) I : Set (Polynomial R)) =
      reesAlgebra I := by
  exact adjoin_monomial_eq_reesAlgebra I

/-- A finitely generated centre ideal has a finitely generated Rees algebra. -/
theorem rees_fg_of_ideal_fg {I : Ideal R} (hI : I.FG) :
    (reesAlgebra I).FG := by
  exact reesAlgebra.fg hI

/-- Over a Noetherian base, the Rees algebra is a finite-type algebra. -/
theorem rees_finiteType_of_noetherian (I : Ideal R) [IsNoetherianRing R] :
    Algebra.FiniteType R (reesAlgebra I) := by
  infer_instance

/-- The degree-zero coefficient of a Rees element is unconstrained beyond
belonging to the unit ideal. -/
theorem coeff_zero_mem (I : Ideal R) (f : reesAlgebra I) :
    (f : Polynomial R).coeff 0 ∈ I ^ 0 := by
  exact (mem_reesAlgebra_iff I (f : Polynomial R)).mp f.property 0

end ReesFoundation
end PCRLean
