import Mathlib
import PCRLean.FrobeniusPowerIdeal
import PCRLean.CoordinateCentrePrincipalization
import PCRLean.MarkedIdeal

/-!
# The pure split Frobenius chamber

Suppose a Frobenius base is identified with a polynomial ambient ring through
a root equivalence, and the root of a descended base ideal is exactly a
coordinate centre.  Then the descended ambient ideal is exactly the ideal
generated by the `p^e`-th powers of those coordinate generators.

Blowing up the coordinate root centre is therefore permissible at mark `p^e`,
and on every standard chart the controlled root packet is the unit ideal.  This
file gives a complete, actual, all-chart, one-step terminal theorem for the pure
split Frobenius chamber.

The universal resolution problem is reduced to proving that every fully
Frobenius-stable prepared chamber either admits this split coordinate form or
has an earlier strict invariant drop.
-/

namespace PCRLean
namespace SplitFrobeniusChamber

noncomputable section

universe u v w x

variable {R : Type u} {K : Type v}
variable [CommRing R] [CommRing K]
variable (p e : Nat) [ExpChar K p]
variable {α : Type w} {ι : Type x}
variable [DecidableEq ι]

abbrev A := CoordinateBlowupChart.P (R := K) (α := α) (ι := ι)

variable [Algebra R (A (K := K) (α := α) (ι := ι))]

/-- A coordinate root identification turns base extension into the explicit
coordinate Frobenius-power packet. -/
theorem baseExtension_eq_coordinateSource
    (S : FrobeniusPowerIdeal.RootEquiv
      (A := A (K := K) (α := α) (ι := ι)) p e (R := R))
    (J : Ideal R)
    (hcoord : S.rootIdeal J =
      CoordinateBlowupChart.centreIdeal
        (R := K) (α := α) (ι := ι)) :
    J.map (algebraMap R (A (K := K) (α := α) (ι := ι))) =
      CoordinateCentrePrincipalization.sourceIdeal
        (R := K) (α := α) (ι := ι) (p ^ e) := by
  calc
    J.map (algebraMap R (A (K := K) (α := α) (ι := ι))) =
        FrobeniusPowerIdeal.powerIdeal
          (A := A (K := K) (α := α) (ι := ι)) p e
          (S.rootIdeal J) :=
      S.baseExtension_eq_powerIdeal J
    _ = FrobeniusPowerIdeal.powerIdeal
          (A := A (K := K) (α := α) (ι := ι)) p e
          (CoordinateBlowupChart.centreIdeal
            (R := K) (α := α) (ι := ι)) := by rw [hcoord]
    _ = FrobeniusPowerIdeal.coordinatePowerIdeal
          (K := K) (α := α) (ι := ι) p e :=
      FrobeniusPowerIdeal.coordinateCentre_powerIdeal_eq
        (K := K) (α := α) (ι := ι) p e
    _ = CoordinateCentrePrincipalization.sourceIdeal
          (R := K) (α := α) (ι := ι) (p ^ e) :=
      FrobeniusPowerIdeal.coordinatePowerIdeal_eq_sourceIdeal
        (K := K) (α := α) (ι := ι) p e

/-- The descended coordinate Frobenius packet is permissible for its actual
coordinate root centre. -/
theorem baseExtension_permissible
    (hp : 0 < p)
    (S : FrobeniusPowerIdeal.RootEquiv
      (A := A (K := K) (α := α) (ι := ι)) p e (R := R))
    (J : Ideal R)
    (hcoord : S.rootIdeal J =
      CoordinateBlowupChart.centreIdeal
        (R := K) (α := α) (ι := ι)) :
    MarkedIdeal.Permissible
      (R := A (K := K) (α := α) (ι := ι))
      ⟨J.map (algebraMap R (A (K := K) (α := α) (ι := ι))),
        p ^ e, pow_pos hp e⟩
      (CoordinateBlowupChart.centreIdeal
        (R := K) (α := α) (ι := ι)) := by
  rw [baseExtension_eq_coordinateSource
    (K := K) (α := α) (ι := ι) p e S J hcoord]
  exact CoordinateCentrePrincipalization.sourceIdeal_le_centre_pow
    (R := K) (α := α) (ι := ι) (p ^ e)

/-- Complete one-step resolution certificate for a split descended ideal. -/
theorem oneStep_certificate
    (hp : 0 < p)
    (S : FrobeniusPowerIdeal.RootEquiv
      (A := A (K := K) (α := α) (ι := ι)) p e (R := R))
    {I : Ideal (A (K := K) (α := α) (ι := ι))}
    {J : Ideal R}
    (hdesc : I = J.map
      (algebraMap R (A (K := K) (α := α) (ι := ι))))
    (hcoord : S.rootIdeal J =
      CoordinateBlowupChart.centreIdeal
        (R := K) (α := α) (ι := ι)) :
    I = CoordinateCentrePrincipalization.sourceIdeal
          (R := K) (α := α) (ι := ι) (p ^ e) ∧
      MarkedIdeal.Permissible
        (R := A (K := K) (α := α) (ι := ι))
        ⟨I, p ^ e, pow_pos hp e⟩
        (CoordinateBlowupChart.centreIdeal
          (R := K) (α := α) (ι := ι)) ∧
      ∀ k : ι,
        CoordinateCentrePrincipalization.transformedRootIdeal
          (R := K) (α := α) k (p ^ e) = ⊤ := by
  have hsource : I =
      CoordinateCentrePrincipalization.sourceIdeal
        (R := K) (α := α) (ι := ι) (p ^ e) := by
    rw [hdesc]
    exact baseExtension_eq_coordinateSource
      (K := K) (α := α) (ι := ι) p e S J hcoord
  refine ⟨hsource, ?_, ?_⟩
  · rw [hsource]
    exact CoordinateCentrePrincipalization.sourceIdeal_le_centre_pow
      (R := K) (α := α) (ι := ι) (p ^ e)
  · intro k
    exact CoordinateCentrePrincipalization.one_step_terminal_on_every_chart
      (R := K) (α := α) k (p ^ e)

end

end SplitFrobeniusChamber
end PCRLean
